return  {
	Typography = {
		Title = {
			FontFamily = "Gotham SSm",
			FontWeight = "Black",
			FontSize = 34,
			LineHeight = "120%",
			LetterSpacing = "0%",
		},
		Header = {
			FontFamily = "Gotham SSm",
			FontWeight = "Bold",
			FontSize = 20,
			LineHeight = "140%",
			LetterSpacing = "0%",
		},
		Subheader = {
			FontFamily = "Gotham SSm",
			FontWeight = "Medium",
			FontSize = 16,
			LineHeight = "125%",
			LetterSpacing = "0%",
		},
		Body = {
			FontFamily = "Gotham SSm",
			FontWeight = "Book",
			FontSize = 16,
			LineHeight = "125%",
			LetterSpacing = "0%",
		},
		CaptionHeader = {
			FontFamily = "Gotham SSm",
			FontWeight = "Medium",
			FontSize = 12,
			LineHeight = "115%",
			LetterSpacing = "0%",
		},
		CaptionBody = {
			FontFamily = "Gotham SSm",
			FontWeight = "Book",
			FontSize = 12,
			LineHeight = "115%",
			LetterSpacing = "0%",
		},
		Footer = {
			FontFamily = "Gotham SSm",
			FontWeight = "Medium",
			FontSize = 10,
			LineHeight = "120%",
			LetterSpacing = "0%",
		},
	},
	Color = {
		Background = {
			Default = Color3.fromHex("#232527"),
			Contrast = Color3.fromHex("#191b1d"),
			Muted = Color3.fromHex("#111214"),
			OnHover = Color3.fromHex("#ffffff"),
			OnPress = Color3.fromHex("#000000"),
		},
		BackgroundUi = {
			Default = Color3.fromHex("#393b3d"),
			Contrast = Color3.fromHex("#000000"),
		},
		Ui = {
			Default = Color3.fromHex("#656668"),
			Muted = Color3.fromHex("#111214"),
			Emphasis = Color3.fromHex("#ffffff"),
		},
		Text = {
			Default = Color3.fromHex("#bdbebe"),
			Muted = Color3.fromHex("#ffffff"),
			Emphasis = Color3.fromHex("#ffffff"),
			Link = Color3.fromHex("#52adf4"),
		},
		Icon = {
			Default = Color3.fromHex("#ffffff"),
			Emphasis = Color3.fromHex("#ffffff"),
			OnHover = Color3.fromHex("#ffffff"),
		},
		Button = {
			ContextualPrimary = {
				Default = Color3.fromHex("#00b46d"),
				OnHover = Color3.fromHex("#00b46d"),
				Content = Color3.fromHex("#ffffff"),
			},
			SystemPrimary = {
				Default = Color3.fromHex("#ffffff"),
				OnHover = Color3.fromHex("#ffffff"),
				Content = Color3.fromHex("#393b3d"),
			},
			Secondary = {
				Default = Color3.fromHex("#ffffff"),
				OnHover = Color3.fromHex("#ffffff"),
				Content = Color3.fromHex("#ffffff"),
			},
		},
		Common = {
			Divider = Color3.fromHex("#ffffff"),
			Overlay = Color3.fromHex("#000000"),
			DropShadow = Color3.fromHex("#000000"),
			NavigationBar = Color3.fromHex("#191b1d"),
			Badge = Color3.fromHex("#ffffff"),
			BadgeContent = Color3.fromHex("#393b3d"),
			Placeholder = Color3.fromHex("#393b3d"),
			Online = Color3.fromHex("#00b46d"),
			Offline = Color3.fromHex("#ffffff"),
			Alert = Color3.fromHex("#f74b52"),
			Success = Color3.fromHex("#00b46d"),
		},
	},
	BorderRadius = {
		None = 0,
		Small = 4,
		Medium = 8,
		Large = 12,
		XLarge = 16,
		Circle = "50%",
	},
	Icon = {
		Size = {
			Small = 16,
			Medium = 28,
			Large = 48,
			XLarge = 96,
		},
	},
}
