return {
	FFlagRemoveSettingsReorderFirstVariantIXPSetup = require(script.FFlagRemoveSettingsReorderFirstVariantIXPSetup),
	FFlagIEMButtonsResponsiveLayout = require(script.FFlagIEMButtonsResponsiveLayout),
	FFlagIEMSettingsLogExposureIXPFlags = require(script.FFlagIEMSettingsLogExposureIXPFlags),
	FFlagCreateInExperienceMenuReact = require(script.FFlagCreateInExperienceMenuReact),
	FFlagMenuButtonsCheckVisibilityBeforeMount = require(script.FFlagMenuButtonsCheckVisibilityBeforeMount),
	FFlagAddTraversalHistoryReactMenuButtons = require(script.FFlagAddTraversalHistoryReactMenuButtons),
}
