-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("StreamingServiceDispatcherRegistry")
local var1 = require(var0.Src.Types)
local var2 = var0.Src.Commands
local var3 = var2.DisplayRichText
local var4 = var2.DisplaySuggestions
local var5 = var2.DisplayError
local var6 = var2.QueueRichText
local var7 = var2.BuilderCommands
local var8 = var7.Instantiate
local var9 = var7.InsertAsset
local var10 = var7.SetProperty
local var11 = var7.CreateMaterial
local var12 = var7.SetMaterial
local var13 = var7.RemoveInstance
local var14 = var7.CloneInstance
local var15 = var7.DisplayRegionAdornments
local var16 = var7.DebugBulkPublishToInventory
local var17 = var7.SetDraftMode
local var18 = var7.RunDraftCommand
local var19 = var7.DebugSleep
local var20 = var7.RunCode
local var21 = {}
local var430 = {}
var3.Name = require(var3)
var5.Name = require(var5)
local var442 = require(var15)
var15.Name = var442
var442 = var9
var430.InsertAssetInstant = require(var442)
var430.SetPropertyInstant = require(var10)
var430.InstantiateInstant = require(var8)
var21.parallel = var430
local var451 = {}
var8.Name = require(var8)
var9.Name = require(var9)
var10.Name = require(var10)
var6.Name = require(var6)
var11.Name = require(var11)
var12.Name = require(var12)
var16.Name = require(var16)
var4.Name = require(var4)
var13.Name = require(var13)
var14.Name = require(var14)
var17.Name = require(var17)
var18.Name = require(var18)
var19.Name = require(var19)
var21.sequential = var451
var451 = require(var0.Src.Flags.getFFlagConvAICodeRunner)
if var451() then
   local var0 = var21.sequential
   var20.Name = require(var20)
end
return var21
