-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.BrickColor = require(script.BrickColorRenderer)
var0.Color = require(script.ColorRenderer)
var0.ColorSequence = require(script.SequenceRenderers.ColorSequenceRenderer)
var0.Derive = require(script.DeriveRenderer)
var0.FontFamily = require(script.FontRenderers.FontFamilyRenderer)
var0.FontStyle = require(script.FontRenderers.FontStyleRenderer)
var0.FontWeight = require(script.FontRenderers.FontWeightRenderer)
var0.NumberSequence = require(script.SequenceRenderers.NumberSequenceRenderer)
var0.PropertyName = require(script.PropertyNameRenderer)
var0.StaticText = require(script.StaticTextRenderer)
var0.Theme = require(script.BreadcrumbRadioRenderer)
var0.TokenReference = require(script.TokenReferenceRenderer)
return var0
