-- ROBLOX upstream: https://github.com/ardatan/graphql-tools/blob/release-1666533990323/packages/utils/src/declarations.d.ts
-- ROBLOX deviation START: defining global module is not supported
-- error("not implemented") --[[ ROBLOX TODO: Unhandled node for type: TSModuleDeclaration ]] --[[ declare global {
--   type Reducer<T, R> = (prev: Partial<R>, curr: T) => R;
--   interface ReadonlyArray<T> {
--     reduce<R>(reducer: Reducer<T, R>, target: Partial<R>): R;
--   }
--   interface Array<T> {
--     reduce<R>(reducer: Reducer<T, R>, target: Partial<R>): R;
--   }
-- } ]]
-- error("not implemented") --[[ ROBLOX TODO: Unhandled node for type: TSModuleDeclaration ]] --[[ declare module 'graphql-upload/*.mjs'; ]]
return {}
-- ROBLOX deviation END
