-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent
local var1 = require(var0.Packages.Roact)
local var2 = require(var0.Packages.Framework)
local var3 = var2.ContextServices
local var4 = var2.Style.Colors
local var5 = var2.UI
local var6 = var5.Pane
local var7 = var5.TextLabel
local var8 = var1.PureComponent:extend("CGEAlert")
function var8.render(arg1)
   local var0 = arg1.props
   local var1 = var0.Stylizer.CGEAlert
   local var32 = {}
   var32.LayoutOrder = 1
   var32.AutomaticSize = Enum.AutomaticSize.Y
   var32.Padding = var1.Padding
   var32.BackgroundColor3 = var4.darker(var1.BackgroundColor, var1.BackgroundColorHoverDarkerMultiplier)
   var32.Size = UDim2.fromScale(1, 0)
   var32.OnClick = var0.OnClick
   local var46 = {}
   local var50 = {}
   var50.CornerRadius = var1.CornerRadius
   var46.UICorner = var1.createElement("UICorner", var50)
   local var56 = {}
   var56.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
   var56.Color = var1.BorderColor
   var46.UIStroke = var1.createElement("UIStroke", var56)
   local var63 = {}
   var63.AutomaticSize = Enum.AutomaticSize.Y
   var63.Padding = var1.LinePadding
   var63.Spacing = var1.LineSpacing
   var63.Layout = Enum.FillDirection.Vertical
   var63.HorizontalAlignment = Enum.HorizontalAlignment.Left
   var63.Size = UDim2.fromScale(1, 0)
   local var73 = {}
   local var77 = {}
   var77.AutomaticSize = Enum.AutomaticSize.Y
   var77.LayoutOrder = 1
   var77.Size = UDim2.fromScale(1, 0)
   local var84 = {}
   local var88 = {}
   local var89 = Enum.AutomaticSize.XY
   var88.AutomaticSize = var89
   var89 = `<b>%*</b>`
   var88.Text = var89
   var88.TextXAlignment = Enum.TextXAlignment.Left
   var88.RichText = true
   var88.LayoutOrder = 1
   var84.Title = var1.createElement(var7, var88)
   local var101 = {}
   var101.AnchorPoint = Vector2.new(1, 0)
   var101.AutomaticSize = Enum.AutomaticSize.X
   var101.Position = UDim2.fromScale(1, 0)
   var101.Size = UDim2.fromOffset(0, 18)
   var101.LayoutOrder = 2
   local var116 = {}
   local var120 = {}
   var120.AutomaticSize = Enum.AutomaticSize.XY
   var120.Font = var1.PrimaryActionFont
   local var123 = true
   var120.RichText = var123
   var123 = `<u>%*</u>`
   var120.Text = var123
   var120.TextColor = var1.TextColor
   var116.PrimaryAction = var1.createElement(var7, var120)
   var84.RightSide = var1.createElement(var6, var101, var116)
   var73.TopBar = var1.createElement(var6, var77, var84)
   local var138 = {}
   var138.LayoutOrder = 2
   var138.AutomaticSize = Enum.AutomaticSize.XY
   var138.Text = var0.Body
   var138.TextWrapped = true
   var138.TextXAlignment = Enum.TextXAlignment.Left
   var138.RichText = true
   var73.Body = var1.createElement(var7, var138)
   var46.Inner = var1.createElement(var6, var63, var73)
   return var1.createElement(var6, var32, var46)
end

local var148 = {}
var148.Stylizer = var3.Stylizer
var148.Localization = var3.Localization
var8 = var3.withContext(var148)(var8)
return var8
