local OptionSelectorGroupItem = require(script.OptionSelectorGroupItem)

export type OptionSelectorGroupItemProps = OptionSelectorGroupItem.OptionSelectorGroupItemProps

return OptionSelectorGroupItem
