-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.RemoveMetaBreakpoint = "Debugger.MetaBreakpoint.User.Remove"
var0.RemoveAllMetaBreakpoints = "Debugger.MetaBreakpoint.User.RemoveAll"
var0.EnableMetaBreakpoint = "Debugger.MetaBreakpoint.User.Enable"
var0.DisableMetaBreakpoint = "Debugger.MetaBreakpoint.User.Disable"
var0.EnableBreakpoint = "Debugger.Breakpoint.User.Enable"
var0.DisableBreakpoint = "Debugger.Breakpoint.User.Disable"
var0.EnableAllMetaBreakpoints = "Debugger.MetaBreakpoint.User.EnableAll"
var0.DisableAllMetaBreakpoints = "Debugger.MetaBreakpoint.User.DisableAll"
var0.MetaBreakpointConditionChanged = "Debugger.MetaBreakpoint.User.Edit.Condition"
var0.MetaBreakpointLogMessageChanged = "Debugger.MetaBreakpoint.User.Edit.LogMessage"
var0.MetaBreakpointContinueExecutionChanged = "Debugger.MetaBreakpoint.User.Edit.ContinueExecution"
var0.MetaBreakpointRemoveOnHitChanged = "Debugger.MetaBreakpoint.User.Edit.RemoveOnHit"
var0.CallstackStepInto = "Debugger.Callstack.User.StepInto"
var0.CallstackStepOver = "Debugger.Callstack.User.StepOver"
var0.CallstackStepOut = "Debugger.Callstack.User.StepOut"
var0.CallstackChangeFrame = "Debugger.Callstack.User.ChangeFrame"
var0.WatchAdded = "Debugger.Watch.User.Add"
var0.WatchScopeEdited = "Debugger.LuaUI.Watch.User.Edit.Scope"
var0.BreakpointsColumnsEdited = "Debugger.LuaUI.Breakpoints.User.Edit.Columns"
var0.CallstackColumnsEdited = "Debugger.LuaUI.Callstack.User.Edit.Columns"
var0.VariablesColumnsEdited = "Debugger.LuaUI.Watch.User.Edit.VariablesColumns"
var0.MyWatchesColumnsEdited = "Debugger.LuaUI.Watch.User.Edit.MyWatchesColumns"
return var0
