--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["NetworkingCurrentlyWearing-a941509c-539dcfbc"]["NetworkingCurrentlyWearing"])

return Package
