--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["roact-fit-components"]["roact-fit-components"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package