[package]
name = "JestBenchmark"
version = "3.8.1"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
license = "MIT"
[dependencies.JestGlobals]
package = "JestGlobals"
version = "^3.8.1"

[dependencies.JestTypes]
package = "JestTypes"
version = "^3.8.1"

[dependencies.LuauPolyfill]
version = "^1"
