--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["ReactRoblox"]["ReactRoblox"])

export type RootType = Package.RootType


return Package
