--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["AppCommonLib"]["AppCommonLib"])

export type SignalHandle = Package.SignalHandle
export type SignalCallback = Package.SignalCallback
export type Signal = Package.Signal
export type SignalClass = Package.SignalClass
export type AsyncQueueType = Package.AsyncQueueType
export type AsyncQueueAcquireFnType = Package.AsyncQueueAcquireFnType
export type AsyncQueueReleaseFnType = Package.AsyncQueueReleaseFnType


return Package
