--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["AvatarExperienceWidgets"]["AvatarExperienceWidgets"])

export type WidgetHeaderProps = Package.WidgetHeaderProps
export type WidgetLayoutProps = Package.WidgetLayoutProps


return Package
