--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["GameInvite"]["GameInvite"])

export type GameInviteServiceModule = Package.GameInviteServiceModule
export type GameInviteService = Package.GameInviteService


return Package
