--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["GameLaunch"]["GameLaunch"])

export type PlayButtonLaunchGame = Package.PlayButtonLaunchGame


return Package
