--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["GameTile"]["GameTile"])

export type ExperienceFooterProps = Package.ExperienceFooterProps
export type GameTileLayoutType = Package.GameTileLayoutType
export type PlayerCountStyleType = Package.PlayerCountStyleType


return Package
