--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["InExperienceCapabilities"]["InExperienceCapabilities"])

return Package
