--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["OtaPatchValidation"]["OtaPatchValidation"])

export type otaValidator = Package.otaValidator
export type VersionedApiInterface = Package.VersionedApiInterface


return Package
