--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["SystemInfoProtocol"]["SystemInfoProtocol"])

export type SystemInfo = Package.SystemInfo
export type SystemInfoProtocol = Package.SystemInfoProtocol
export type SystemInfoProtocolModule = Package.SystemInfoProtocolModule


return Package
