--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["VerifiedParentalConsentDialog"]["VerifiedParentalConsentDialog"])

return Package
