--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["VideoProtocol"]["VideoProtocol"])

export type VideoProtocol = Package.VideoProtocol


return Package
