--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Workspace

local Package = require(PackageIndex["VirtualEvents"]["VirtualEvents"])

export type Event = Package.Event
export type Host = Package.Host
export type VirtualEvent = Package.VirtualEvent
export type RsvpStatus = Package.RsvpStatus
export type EventNotificationsModalProps = Package.EventNotificationsModalProps


return Package
