local Framework = script.Parent.Parent

local isUsedAsPackage = require(Framework.Util.isUsedAsPackage)
if game:GetFastFlag("DevFrameworkUseSiblingPackages") and isUsedAsPackage() then
	return require(Framework.Parent["mock"])
end
--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["jtaylor_mock"]["mock"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package
