local MAX_LAYOUT_ORDER = 2147483648
local MIN_LAYOUT_ORDER = -2147483648
-- this should live in tokens
local DISABLED_TRANSPARENCY = 0.5

return {
	MAX_LAYOUT_ORDER = MAX_LAYOUT_ORDER,
	MIN_LAYOUT_ORDER = MIN_LAYOUT_ORDER,
	DISABLED_TRANSPARENCY = DISABLED_TRANSPARENCY,
}
