-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent.Parent
local var1 = require(var0.Packages.Framework).Styling.createStyleRule
local var2 = require(var0.Src.Resources.StyleTips)
local var18 = {}
var18.Size = UDim2.new(1, 0, 1, 0)
var18.BackgroundColor3 = "$SecondaryMuted"
local var29 = {}
var29.Padding = UDim.new(0, 16)
local var4 = var1("::UIListLayout", var29)
local var37 = {}
var37.TextXAlignment = Enum.TextXAlignment.Center
var37.TextColor3 = "$TextPrimary"
var37.TextSize = var2.detailFontSize
local var5 = var1("> #Text", var37)
local var44 = {}
var44.BackgroundColor3 = "$PrimaryMain"
var44.TextColor3 = "$TextContrast"
var44.TextSize = var2.buttonFontSize
local var51 = {}
var51.PaddingTop = UDim.new(0, 8)
var51.PaddingBottom = UDim.new(0, 8)
var51.PaddingLeft = UDim.new(0, 16)
var51.PaddingRight = UDim.new(0, 16)
local var6 = var1("::UIPadding", var51)
local var71 = {}
var71.BackgroundColor3 = "$PrimaryHoverBackground"
local var7 = var1(":hover", var71)
local var8 = var1("> #Button", var44, {})
return var1(".Component-EnableTeamCreate", var18, {})
