--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["Rodux-31ab8d40-4.0.0-rc.0"]["Rodux"])

export type Action<Type = any> = Package.Action<Type > 
export type AnyAction = Package.AnyAction
export type ActionCreator<Type, Action, Args...> = Package.ActionCreator<Type, Action, Args...> 
export type Reducer<State = any, Action = AnyAction> = Package.Reducer<State , Action > 
export type Store<State = any> = Package.Store<State > 
export type ThunkAction<ReturnType, State = any> = Package.ThunkAction<ReturnType, State > 
export type ThunkfulStore<State = any> = Package.ThunkfulStore<State > 


return Package
