--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["GenericAbuseReporting"]["GenericAbuseReporting"])

return Package
