--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	GetEligiblePromptsResponse: _GetEligiblePromptsResponseMessage,
	GetEligiblePromptsResponse_TemplatesEntry: _GetEligiblePromptsResponse_TemplatesEntryMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_hydration_content =
	require(script.Parent.Parent.Parent.shared.v1beta1.hydration_content)
local _roblox_apppageplatform_shared_v1beta1_page_entry_content =
	require(script.Parent.Parent.Parent.shared.v1beta1.page_entry_content)
local _roblox_apppageplatform_shared_v1beta1_template_entry =
	require(script.Parent.Parent.Parent.shared.v1beta1.template_entry)

type _GetEligiblePromptsResponseImpl = {
	__index: _GetEligiblePromptsResponseImpl,
	new: (fields: _GetEligiblePromptsResponsePartialFields?) -> GetEligiblePromptsResponse,
	encode: (self: GetEligiblePromptsResponse) -> buffer,
	decode: (input: buffer) -> GetEligiblePromptsResponse,
	jsonEncode: (self: GetEligiblePromptsResponse) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> GetEligiblePromptsResponse,
	descriptor: proto.Descriptor,
}

type _GetEligiblePromptsResponseFields = {
	page_entries: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry },
	hydration_data: _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent?,
	templates: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry },
}

type _GetEligiblePromptsResponsePartialFields = {
	page_entries: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry }?,
	hydration_data: _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent?,
	templates: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry }?,
}

export type GetEligiblePromptsResponse = typeof(setmetatable(
	{} :: _GetEligiblePromptsResponseFields,
	{} :: _GetEligiblePromptsResponseImpl
))
type _GetEligiblePromptsResponseMessage = proto.Message<
	GetEligiblePromptsResponse,
	_GetEligiblePromptsResponsePartialFields
>

type _GetEligiblePromptsResponse_TemplatesEntryImpl = {
	__index: _GetEligiblePromptsResponse_TemplatesEntryImpl,
	new: (
		fields: _GetEligiblePromptsResponse_TemplatesEntryPartialFields?
	) -> GetEligiblePromptsResponse_TemplatesEntry,
	encode: (self: GetEligiblePromptsResponse_TemplatesEntry) -> buffer,
	decode: (input: buffer) -> GetEligiblePromptsResponse_TemplatesEntry,
	jsonEncode: (self: GetEligiblePromptsResponse_TemplatesEntry) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> GetEligiblePromptsResponse_TemplatesEntry,
	descriptor: proto.Descriptor,
}

type _GetEligiblePromptsResponse_TemplatesEntryFields = {
	key: string,
	value: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry?,
}

type _GetEligiblePromptsResponse_TemplatesEntryPartialFields = {
	key: string?,
	value: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry?,
}

export type GetEligiblePromptsResponse_TemplatesEntry = typeof(setmetatable(
	{} :: _GetEligiblePromptsResponse_TemplatesEntryFields,
	{} :: _GetEligiblePromptsResponse_TemplatesEntryImpl
))
type _GetEligiblePromptsResponse_TemplatesEntryMessage = proto.Message<
	GetEligiblePromptsResponse_TemplatesEntry,
	_GetEligiblePromptsResponse_TemplatesEntryPartialFields
>

do
	local _GetEligiblePromptsResponseImpl = {}
	_GetEligiblePromptsResponseImpl.__index = _GetEligiblePromptsResponseImpl

	function _GetEligiblePromptsResponseImpl.new(
		data: _GetEligiblePromptsResponsePartialFields?
	): GetEligiblePromptsResponse
		return setmetatable({
			page_entries = if data == nil or data.page_entries == nil then {} else data.page_entries,
			hydration_data = if data == nil or data.hydration_data == nil then nil else data.hydration_data,
			templates = if data == nil or data.templates == nil then {} else data.templates,
		}, _GetEligiblePromptsResponseImpl :: _GetEligiblePromptsResponseImpl)
	end

	function _GetEligiblePromptsResponseImpl.encode(self: GetEligiblePromptsResponse): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.page_entries ~= nil and #self.page_entries > 0 then
			for _, value in self.page_entries do
				local encoded = value:encode()
				output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			end
		end

		if self.hydration_data ~= nil then
			local encoded = self.hydration_data:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.templates ~= nil and next(self.templates) ~= nil then
			for key, value in self.templates do
				local mapBuffer = buffer.create(0)
				local mapCursor = 0
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 1, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, key)
				local encoded = value:encode()
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 2, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeBuffer(mapBuffer, mapCursor, encoded, buffer.len(encoded))
				output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, mapBuffer, mapCursor)
			end
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _GetEligiblePromptsResponseImpl.decode(input: buffer): GetEligiblePromptsResponse
		local self = _GetEligiblePromptsResponseImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					table.insert(
						self.page_entries,
						_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.decode(value)
					)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.hydration_data =
						_roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)

					local mapEntry = messages.GetEligiblePromptsResponse_TemplatesEntry.decode(value)

					local keyDefault = ""
					local valueDefault = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.new()

					self.templates[mapEntry.key or keyDefault] = mapEntry.value or valueDefault

					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _GetEligiblePromptsResponseImpl.jsonEncode(self: GetEligiblePromptsResponse): any
		local output = {}

		if self.page_entries ~= nil and #self.page_entries > 0 then
			local newOutput = {}
			for _, value in self.page_entries do
				table.insert(newOutput, value:jsonEncode())
			end
			output.pageEntries = newOutput
		end

		if self.hydration_data ~= nil then
			output.hydrationData = self.hydration_data:jsonEncode()
		end

		if self.templates ~= nil and next(self.templates) ~= nil then
			local newOutput = {}
			for key, value in self.templates do
				newOutput[key] = value:jsonEncode()
			end
			output.templates = newOutput
		end

		return output
	end

	function _GetEligiblePromptsResponseImpl.jsonDecode(input: { [string]: any }): GetEligiblePromptsResponse
		local self = _GetEligiblePromptsResponseImpl.new()

		if input.page_entries ~= nil then
			local newOutput: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry } = {}
			for _, value in input.page_entries do
				table.insert(
					newOutput,
					_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.jsonDecode(value)
				)
			end

			self.page_entries = newOutput
		end

		if input.pageEntries ~= nil then
			local newOutput: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry } = {}
			for _, value in input.pageEntries do
				table.insert(
					newOutput,
					_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.jsonDecode(value)
				)
			end

			self.page_entries = newOutput
		end

		if input.hydration_data ~= nil then
			self.hydration_data = _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.jsonDecode(
				input.hydration_data
			)
		end

		if input.hydrationData ~= nil then
			self.hydration_data = _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.jsonDecode(
				input.hydrationData
			)
		end

		if input.templates ~= nil then
			local newOutput: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry } = {}
			for key, value in input.templates do
				newOutput[key] = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.jsonDecode(value)
			end

			self.templates = newOutput
		end

		return self
	end

	_GetEligiblePromptsResponseImpl.descriptor = {
		name = "GetEligiblePromptsResponse",
		fullName = "roblox.apppageplatform.prompts.v1beta1.GetEligiblePromptsResponse",
	}

	messages.GetEligiblePromptsResponse = _GetEligiblePromptsResponseImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.GetEligiblePromptsResponse)
end

do
	local _GetEligiblePromptsResponse_TemplatesEntryImpl = {}
	_GetEligiblePromptsResponse_TemplatesEntryImpl.__index = _GetEligiblePromptsResponse_TemplatesEntryImpl

	function _GetEligiblePromptsResponse_TemplatesEntryImpl.new(
		data: _GetEligiblePromptsResponse_TemplatesEntryPartialFields?
	): GetEligiblePromptsResponse_TemplatesEntry
		return setmetatable({
			key = if data == nil or data.key == nil then "" else data.key,
			value = if data == nil or data.value == nil then nil else data.value,
		}, _GetEligiblePromptsResponse_TemplatesEntryImpl :: _GetEligiblePromptsResponse_TemplatesEntryImpl)
	end

	function _GetEligiblePromptsResponse_TemplatesEntryImpl.encode(
		self: GetEligiblePromptsResponse_TemplatesEntry
	): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.key ~= nil and self.key ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.key)
		end

		if self.value ~= nil then
			local encoded = self.value:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _GetEligiblePromptsResponse_TemplatesEntryImpl.decode(
		input: buffer
	): GetEligiblePromptsResponse_TemplatesEntry
		local self = _GetEligiblePromptsResponse_TemplatesEntryImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.key = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.value = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _GetEligiblePromptsResponse_TemplatesEntryImpl.jsonEncode(
		self: GetEligiblePromptsResponse_TemplatesEntry
	): any
		local output = {}

		if self.key ~= nil and self.key ~= "" then
			output.key = self.key
		end

		if self.value ~= nil then
			output.value = self.value:jsonEncode()
		end

		return output
	end

	function _GetEligiblePromptsResponse_TemplatesEntryImpl.jsonDecode(
		input: { [string]: any }
	): GetEligiblePromptsResponse_TemplatesEntry
		local self = _GetEligiblePromptsResponse_TemplatesEntryImpl.new()

		if input.key ~= nil then
			self.key = input.key
		end

		if input.value ~= nil then
			self.value = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.jsonDecode(input.value)
		end

		return self
	end

	_GetEligiblePromptsResponse_TemplatesEntryImpl.descriptor = {
		name = "GetEligiblePromptsResponse_TemplatesEntry",
		fullName = "roblox.apppageplatform.prompts.v1beta1.TemplatesEntry",
	}

	messages.GetEligiblePromptsResponse_TemplatesEntry = _GetEligiblePromptsResponse_TemplatesEntryImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.GetEligiblePromptsResponse_TemplatesEntry)
end

return {
	GetEligiblePromptsResponse = messages.GetEligiblePromptsResponse,
}
