--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["Screenshots"]["Screenshots"])

export type ScreenshotsApp = Package.ScreenshotsApp
export type Capture = Package.Capture


return Package
