--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["roblox_networking-friends-32008de9-e175ee4d"]["networking-friends"])

return Package
