[package]
name = "DomTestingLibrary"
version = "8.14.7"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
    "!**/.robloxrc",
]
publish = true
authors = [
    "Ignacio Falk <flakolefluk@gmail.com>",
    "Allan Jeremy <dev@allanjeremy.com>",
    "Paul Doyle <pdoyle@roblox.com>",
]
[dependencies.Chalk]
target = "https://github.com/roblox/chalk-lua"
package = "ChalkLua"
version = "^0.2.0"

[dependencies.JestGetType]
target = "https://github.com/roblox/jest-roblox"
version = "^3.6.1"

[dependencies.JestGlobals]
target = "https://github.com/roblox/jest-roblox"
version = "^3.6.1"

[dependencies.LuauPolyfill]
target = "https://github.com/roblox/luau-polyfill"
version = "^1"

[dependencies.LuauRegExp]
target = "https://github.com/roblox/luau-regexp"
package = "RegExp"
version = "^0.2.0"

[dependencies.PrettyFormat]
target = "https://github.com/roblox/jest-roblox"
version = "^3.6.1"

[dependencies.Promise]
target = "https://github.com/roblox/roblox-lua-promise"
version = "^3.3.0"

[dependencies.RobloxShared]
target = "https://github.com/roblox/jest-roblox"
version = "^3.6.1"
[dev_dependencies.Jest]
target = "https://github.com/roblox/jest-roblox"
version = "^3.6.1"
