--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	AttributionRowSchema: _AttributionRowSchemaMessage,
	AttributionRowSchema_Props: _AttributionRowSchema_PropsMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_prop_types = require(script.Parent.prop_types)
local _roblox_apppageplatform_shared_v1beta1_actions = require(script.Parent.actions)
local _roblox_apppageplatform_shared_v1beta1_component_shared = require(script.Parent.component_shared)

type _AttributionRowSchemaImpl = {
	__index: _AttributionRowSchemaImpl,
	new: (fields: _AttributionRowSchemaPartialFields?) -> AttributionRowSchema,
	encode: (self: AttributionRowSchema) -> buffer,
	decode: (input: buffer) -> AttributionRowSchema,
	jsonEncode: (self: AttributionRowSchema) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> AttributionRowSchema,
	descriptor: proto.Descriptor,
}

type _AttributionRowSchemaFields = {
	props: AttributionRowSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

type _AttributionRowSchemaPartialFields = {
	props: AttributionRowSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

export type AttributionRowSchema = typeof(setmetatable(
	{} :: _AttributionRowSchemaFields,
	{} :: _AttributionRowSchemaImpl
))
type _AttributionRowSchemaMessage = proto.Message<AttributionRowSchema, _AttributionRowSchemaPartialFields>

type _AttributionRowSchema_PropsImpl = {
	__index: _AttributionRowSchema_PropsImpl,
	new: (fields: _AttributionRowSchema_PropsPartialFields?) -> AttributionRowSchema_Props,
	encode: (self: AttributionRowSchema_Props) -> buffer,
	decode: (input: buffer) -> AttributionRowSchema_Props,
	jsonEncode: (self: AttributionRowSchema_Props) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> AttributionRowSchema_Props,
	descriptor: proto.Descriptor,
}

type _AttributionRowSchema_PropsFields = {
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	right_button_content: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	position: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	image: _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp?,
}

type _AttributionRowSchema_PropsPartialFields = {
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	right_button_content: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	position: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	image: _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp?,
}

export type AttributionRowSchema_Props = typeof(setmetatable(
	{} :: _AttributionRowSchema_PropsFields,
	{} :: _AttributionRowSchema_PropsImpl
))
type _AttributionRowSchema_PropsMessage = proto.Message<
	AttributionRowSchema_Props,
	_AttributionRowSchema_PropsPartialFields
>

do
	local _AttributionRowSchemaImpl = {}
	_AttributionRowSchemaImpl.__index = _AttributionRowSchemaImpl

	function _AttributionRowSchemaImpl.new(data: _AttributionRowSchemaPartialFields?): AttributionRowSchema
		return setmetatable({
			props = if data == nil or data.props == nil then nil else data.props,
			shared = if data == nil or data.shared == nil then nil else data.shared,
		}, _AttributionRowSchemaImpl :: _AttributionRowSchemaImpl)
	end

	function _AttributionRowSchemaImpl.encode(self: AttributionRowSchema): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.props ~= nil then
			local encoded = self.props:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.shared ~= nil then
			local encoded = self.shared:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _AttributionRowSchemaImpl.decode(input: buffer): AttributionRowSchema
		local self = _AttributionRowSchemaImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.props = messages.AttributionRowSchema_Props.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.shared = _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _AttributionRowSchemaImpl.jsonEncode(self: AttributionRowSchema): any
		local output = {}

		if self.props ~= nil then
			output.props = self.props:jsonEncode()
		end

		if self.shared ~= nil then
			output.shared = self.shared:jsonEncode()
		end

		return output
	end

	function _AttributionRowSchemaImpl.jsonDecode(input: { [string]: any }): AttributionRowSchema
		local self = _AttributionRowSchemaImpl.new()

		if input.props ~= nil then
			self.props = messages.AttributionRowSchema_Props.jsonDecode(input.props)
		end

		if input.shared ~= nil then
			self.shared =
				_roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.jsonDecode(input.shared)
		end

		return self
	end

	_AttributionRowSchemaImpl.descriptor = {
		name = "AttributionRowSchema",
		fullName = "roblox.apppageplatform.shared.v1beta1.AttributionRowSchema",
	}

	messages.AttributionRowSchema = _AttributionRowSchemaImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.AttributionRowSchema)
end

do
	local _AttributionRowSchema_PropsImpl = {}
	_AttributionRowSchema_PropsImpl.__index = _AttributionRowSchema_PropsImpl

	function _AttributionRowSchema_PropsImpl.new(
		data: _AttributionRowSchema_PropsPartialFields?
	): AttributionRowSchema_Props
		return setmetatable({
			on_activated = if data == nil or data.on_activated == nil then nil else data.on_activated,
			right_button_content = if data == nil or data.right_button_content == nil
				then nil
				else data.right_button_content,
			layout_order = if data == nil or data.layout_order == nil then nil else data.layout_order,
			position = if data == nil or data.position == nil then nil else data.position,
			image = if data == nil or data.image == nil then nil else data.image,
		}, _AttributionRowSchema_PropsImpl :: _AttributionRowSchema_PropsImpl)
	end

	function _AttributionRowSchema_PropsImpl.encode(self: AttributionRowSchema_Props): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.on_activated ~= nil then
			local encoded = self.on_activated:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.right_button_content ~= nil then
			local encoded = self.right_button_content:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.layout_order ~= nil then
			local encoded = self.layout_order:encode()
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.position ~= nil then
			local encoded = self.position:encode()
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.image ~= nil then
			local encoded = self.image:encode()
			output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _AttributionRowSchema_PropsImpl.decode(input: buffer): AttributionRowSchema_Props
		local self = _AttributionRowSchema_PropsImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.right_button_content =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.layout_order = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.position = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.decode(value)
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image = _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _AttributionRowSchema_PropsImpl.jsonEncode(self: AttributionRowSchema_Props): any
		local output = {}

		if self.on_activated ~= nil then
			output.onActivated = self.on_activated:jsonEncode()
		end

		if self.right_button_content ~= nil then
			output.rightButtonContent = self.right_button_content:jsonEncode()
		end

		if self.layout_order ~= nil then
			output.layoutOrder = self.layout_order:jsonEncode()
		end

		if self.position ~= nil then
			output.position = self.position:jsonEncode()
		end

		if self.image ~= nil then
			output.image = self.image:jsonEncode()
		end

		return output
	end

	function _AttributionRowSchema_PropsImpl.jsonDecode(input: { [string]: any }): AttributionRowSchema_Props
		local self = _AttributionRowSchema_PropsImpl.new()

		if input.on_activated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.on_activated)
		end

		if input.onActivated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.onActivated)
		end

		if input.right_button_content ~= nil then
			self.right_button_content =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.right_button_content
				)
		end

		if input.rightButtonContent ~= nil then
			self.right_button_content =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.rightButtonContent
				)
		end

		if input.layout_order ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layout_order)
		end

		if input.layoutOrder ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layoutOrder)
		end

		if input.position ~= nil then
			self.position = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.position)
		end

		if input.image ~= nil then
			self.image = _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp.jsonDecode(input.image)
		end

		return self
	end

	_AttributionRowSchema_PropsImpl.descriptor = {
		name = "AttributionRowSchema_Props",
		fullName = "roblox.apppageplatform.shared.v1beta1.Props",
	}

	messages.AttributionRowSchema_Props = _AttributionRowSchema_PropsImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.AttributionRowSchema_Props)
end

return {
	AttributionRowSchema = messages.AttributionRowSchema,
	AttributionRowSchema_Props = messages.AttributionRowSchema_Props,
}
