--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	ClientCapabilities: _ClientCapabilitiesMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_capability = require(script.Parent.capability)

type _ClientCapabilitiesImpl = {
	__index: _ClientCapabilitiesImpl,
	new: (fields: _ClientCapabilitiesPartialFields?) -> ClientCapabilities,
	encode: (self: ClientCapabilities) -> buffer,
	decode: (input: buffer) -> ClientCapabilities,
	jsonEncode: (self: ClientCapabilities) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ClientCapabilities,
	descriptor: proto.Descriptor,
}

type _ClientCapabilitiesFields = {
	enabled_capabilities: { _roblox_apppageplatform_shared_v1beta1_capability.Capability },
	proto_version: string,
}

type _ClientCapabilitiesPartialFields = {
	enabled_capabilities: { _roblox_apppageplatform_shared_v1beta1_capability.Capability }?,
	proto_version: string?,
}

export type ClientCapabilities = typeof(setmetatable({} :: _ClientCapabilitiesFields, {} :: _ClientCapabilitiesImpl))
type _ClientCapabilitiesMessage = proto.Message<ClientCapabilities, _ClientCapabilitiesPartialFields>

do
	local _ClientCapabilitiesImpl = {}
	_ClientCapabilitiesImpl.__index = _ClientCapabilitiesImpl

	function _ClientCapabilitiesImpl.new(data: _ClientCapabilitiesPartialFields?): ClientCapabilities
		return setmetatable({
			enabled_capabilities = if data == nil or data.enabled_capabilities == nil
				then {}
				else data.enabled_capabilities,
			proto_version = if data == nil or data.proto_version == nil then "" else data.proto_version,
		}, _ClientCapabilitiesImpl :: _ClientCapabilitiesImpl)
	end

	function _ClientCapabilitiesImpl.encode(self: ClientCapabilities): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.enabled_capabilities ~= nil and #self.enabled_capabilities > 0 then
			for _, value in self.enabled_capabilities do
				output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.varint)
				output, cursor = proto.writeVarInt(
					output,
					cursor,
					_roblox_apppageplatform_shared_v1beta1_capability.Capability.toNumber(value :: any)
				)
			end
		end

		if self.proto_version ~= nil and self.proto_version ~= "" then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.proto_version)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ClientCapabilitiesImpl.decode(input: buffer): ClientCapabilities
		local self = _ClientCapabilitiesImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				if field == 1 then
					local value
					value, cursor = proto.readVarIntI32(input, cursor)
					table.insert(
						self.enabled_capabilities,
						(_roblox_apppageplatform_shared_v1beta1_capability.Capability.fromNumber(value) or value) :: any --[[ Luau: Enums are a string intersection which Luau is quick to dismantle ]]
					)
					continue
				end

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.proto_version = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ClientCapabilitiesImpl.jsonEncode(self: ClientCapabilities): any
		local output = {}

		if self.enabled_capabilities ~= nil and #self.enabled_capabilities > 0 then
			local newOutput = {}
			for _, value in self.enabled_capabilities do
				table.insert(
					newOutput,
					if typeof(value) == "number"
						then value
						else _roblox_apppageplatform_shared_v1beta1_capability.Capability.toNumber(value :: any)
				)
			end
			output.enabledCapabilities = newOutput
		end

		if self.proto_version ~= nil and self.proto_version ~= "" then
			output.protoVersion = self.proto_version
		end

		return output
	end

	function _ClientCapabilitiesImpl.jsonDecode(input: { [string]: any }): ClientCapabilities
		local self = _ClientCapabilitiesImpl.new()

		if input.enabled_capabilities ~= nil then
			local newOutput: { _roblox_apppageplatform_shared_v1beta1_capability.Capability } = {}
			for _, value in input.enabled_capabilities do
				table.insert(
					newOutput,
					if typeof(value) == "number"
						then (_roblox_apppageplatform_shared_v1beta1_capability.Capability.fromNumber(value) or value)
						else (_roblox_apppageplatform_shared_v1beta1_capability.Capability.fromName(value) or value)
				)
			end

			self.enabled_capabilities = newOutput
		end

		if input.enabledCapabilities ~= nil then
			local newOutput: { _roblox_apppageplatform_shared_v1beta1_capability.Capability } = {}
			for _, value in input.enabledCapabilities do
				table.insert(
					newOutput,
					if typeof(value) == "number"
						then (_roblox_apppageplatform_shared_v1beta1_capability.Capability.fromNumber(value) or value)
						else (_roblox_apppageplatform_shared_v1beta1_capability.Capability.fromName(value) or value)
				)
			end

			self.enabled_capabilities = newOutput
		end

		if input.proto_version ~= nil then
			self.proto_version = input.proto_version
		end

		if input.protoVersion ~= nil then
			self.proto_version = input.protoVersion
		end

		return self
	end

	_ClientCapabilitiesImpl.descriptor = {
		name = "ClientCapabilities",
		fullName = "roblox.apppageplatform.shared.v1beta1.ClientCapabilities",
	}

	messages.ClientCapabilities = _ClientCapabilitiesImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ClientCapabilities)
end

return {
	ClientCapabilities = messages.ClientCapabilities,
}
