--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	ContactData: _ContactDataMessage,
}
local messages: _Messages = {} :: _Messages

type _ContactDataImpl = {
	__index: _ContactDataImpl,
	new: (fields: _ContactDataPartialFields?) -> ContactData,
	encode: (self: ContactData) -> buffer,
	decode: (input: buffer) -> ContactData,
	jsonEncode: (self: ContactData) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ContactData,
	descriptor: proto.Descriptor,
}

type _ContactDataFields = {
	contact_name: string?,
	avatar_thumbnail_url: string?,
	headshot_thumbnail_url: string?,
}

type _ContactDataPartialFields = {
	contact_name: string?,
	avatar_thumbnail_url: string?,
	headshot_thumbnail_url: string?,
}

export type ContactData = typeof(setmetatable({} :: _ContactDataFields, {} :: _ContactDataImpl))
type _ContactDataMessage = proto.Message<ContactData, _ContactDataPartialFields>

do
	local _ContactDataImpl = {}
	_ContactDataImpl.__index = _ContactDataImpl

	function _ContactDataImpl.new(data: _ContactDataPartialFields?): ContactData
		return setmetatable({
			contact_name = if data == nil or data.contact_name == nil then nil else data.contact_name,
			avatar_thumbnail_url = if data == nil or data.avatar_thumbnail_url == nil
				then nil
				else data.avatar_thumbnail_url,
			headshot_thumbnail_url = if data == nil or data.headshot_thumbnail_url == nil
				then nil
				else data.headshot_thumbnail_url,
		}, _ContactDataImpl :: _ContactDataImpl)
	end

	function _ContactDataImpl.encode(self: ContactData): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.contact_name ~= nil then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.contact_name)
		end

		if self.avatar_thumbnail_url ~= nil then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.avatar_thumbnail_url)
		end

		if self.headshot_thumbnail_url ~= nil then
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.headshot_thumbnail_url)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ContactDataImpl.decode(input: buffer): ContactData
		local self = _ContactDataImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.contact_name = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.avatar_thumbnail_url = buffer.tostring(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.headshot_thumbnail_url = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ContactDataImpl.jsonEncode(self: ContactData): any
		local output = {}

		if self.contact_name ~= nil then
			output.contactName = self.contact_name
		end

		if self.avatar_thumbnail_url ~= nil then
			output.avatarThumbnailUrl = self.avatar_thumbnail_url
		end

		if self.headshot_thumbnail_url ~= nil then
			output.headshotThumbnailUrl = self.headshot_thumbnail_url
		end

		return output
	end

	function _ContactDataImpl.jsonDecode(input: { [string]: any }): ContactData
		local self = _ContactDataImpl.new()

		if input.contact_name ~= nil then
			self.contact_name = input.contact_name
		end

		if input.contactName ~= nil then
			self.contact_name = input.contactName
		end

		if input.avatar_thumbnail_url ~= nil then
			self.avatar_thumbnail_url = input.avatar_thumbnail_url
		end

		if input.avatarThumbnailUrl ~= nil then
			self.avatar_thumbnail_url = input.avatarThumbnailUrl
		end

		if input.headshot_thumbnail_url ~= nil then
			self.headshot_thumbnail_url = input.headshot_thumbnail_url
		end

		if input.headshotThumbnailUrl ~= nil then
			self.headshot_thumbnail_url = input.headshotThumbnailUrl
		end

		return self
	end

	_ContactDataImpl.descriptor = {
		name = "ContactData",
		fullName = "roblox.apppageplatform.shared.v1beta1.ContactData",
	}

	messages.ContactData = _ContactDataImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ContactData)
end

return {
	ContactData = messages.ContactData,
}
