--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	ContentRatingLabelSchema: _ContentRatingLabelSchemaMessage,
	ContentRatingLabelSchema_Props: _ContentRatingLabelSchema_PropsMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_prop_types = require(script.Parent.prop_types)
local _roblox_apppageplatform_shared_v1beta1_actions = require(script.Parent.actions)
local _roblox_apppageplatform_shared_v1beta1_component_shared = require(script.Parent.component_shared)

type _ContentRatingLabelSchemaImpl = {
	__index: _ContentRatingLabelSchemaImpl,
	new: (fields: _ContentRatingLabelSchemaPartialFields?) -> ContentRatingLabelSchema,
	encode: (self: ContentRatingLabelSchema) -> buffer,
	decode: (input: buffer) -> ContentRatingLabelSchema,
	jsonEncode: (self: ContentRatingLabelSchema) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ContentRatingLabelSchema,
	descriptor: proto.Descriptor,
}

type _ContentRatingLabelSchemaFields = {
	props: ContentRatingLabelSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

type _ContentRatingLabelSchemaPartialFields = {
	props: ContentRatingLabelSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

export type ContentRatingLabelSchema = typeof(setmetatable(
	{} :: _ContentRatingLabelSchemaFields,
	{} :: _ContentRatingLabelSchemaImpl
))
type _ContentRatingLabelSchemaMessage = proto.Message<ContentRatingLabelSchema, _ContentRatingLabelSchemaPartialFields>

type _ContentRatingLabelSchema_PropsImpl = {
	__index: _ContentRatingLabelSchema_PropsImpl,
	new: (fields: _ContentRatingLabelSchema_PropsPartialFields?) -> ContentRatingLabelSchema_Props,
	encode: (self: ContentRatingLabelSchema_Props) -> buffer,
	decode: (input: buffer) -> ContentRatingLabelSchema_Props,
	jsonEncode: (self: ContentRatingLabelSchema_Props) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ContentRatingLabelSchema_Props,
	descriptor: proto.Descriptor,
}

type _ContentRatingLabelSchema_PropsFields = {
	rating: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	display_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	font_style: _roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp?,
	width: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
}

type _ContentRatingLabelSchema_PropsPartialFields = {
	rating: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	display_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	font_style: _roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp?,
	width: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
}

export type ContentRatingLabelSchema_Props = typeof(setmetatable(
	{} :: _ContentRatingLabelSchema_PropsFields,
	{} :: _ContentRatingLabelSchema_PropsImpl
))
type _ContentRatingLabelSchema_PropsMessage = proto.Message<
	ContentRatingLabelSchema_Props,
	_ContentRatingLabelSchema_PropsPartialFields
>

do
	local _ContentRatingLabelSchemaImpl = {}
	_ContentRatingLabelSchemaImpl.__index = _ContentRatingLabelSchemaImpl

	function _ContentRatingLabelSchemaImpl.new(data: _ContentRatingLabelSchemaPartialFields?): ContentRatingLabelSchema
		return setmetatable({
			props = if data == nil or data.props == nil then nil else data.props,
			shared = if data == nil or data.shared == nil then nil else data.shared,
		}, _ContentRatingLabelSchemaImpl :: _ContentRatingLabelSchemaImpl)
	end

	function _ContentRatingLabelSchemaImpl.encode(self: ContentRatingLabelSchema): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.props ~= nil then
			local encoded = self.props:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.shared ~= nil then
			local encoded = self.shared:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ContentRatingLabelSchemaImpl.decode(input: buffer): ContentRatingLabelSchema
		local self = _ContentRatingLabelSchemaImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.props = messages.ContentRatingLabelSchema_Props.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.shared = _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ContentRatingLabelSchemaImpl.jsonEncode(self: ContentRatingLabelSchema): any
		local output = {}

		if self.props ~= nil then
			output.props = self.props:jsonEncode()
		end

		if self.shared ~= nil then
			output.shared = self.shared:jsonEncode()
		end

		return output
	end

	function _ContentRatingLabelSchemaImpl.jsonDecode(input: { [string]: any }): ContentRatingLabelSchema
		local self = _ContentRatingLabelSchemaImpl.new()

		if input.props ~= nil then
			self.props = messages.ContentRatingLabelSchema_Props.jsonDecode(input.props)
		end

		if input.shared ~= nil then
			self.shared =
				_roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.jsonDecode(input.shared)
		end

		return self
	end

	_ContentRatingLabelSchemaImpl.descriptor = {
		name = "ContentRatingLabelSchema",
		fullName = "roblox.apppageplatform.shared.v1beta1.ContentRatingLabelSchema",
	}

	messages.ContentRatingLabelSchema = _ContentRatingLabelSchemaImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ContentRatingLabelSchema)
end

do
	local _ContentRatingLabelSchema_PropsImpl = {}
	_ContentRatingLabelSchema_PropsImpl.__index = _ContentRatingLabelSchema_PropsImpl

	function _ContentRatingLabelSchema_PropsImpl.new(
		data: _ContentRatingLabelSchema_PropsPartialFields?
	): ContentRatingLabelSchema_Props
		return setmetatable({
			rating = if data == nil or data.rating == nil then nil else data.rating,
			display_text = if data == nil or data.display_text == nil then nil else data.display_text,
			font_style = if data == nil or data.font_style == nil then nil else data.font_style,
			width = if data == nil or data.width == nil then nil else data.width,
			on_activated = if data == nil or data.on_activated == nil then nil else data.on_activated,
			layout_order = if data == nil or data.layout_order == nil then nil else data.layout_order,
		}, _ContentRatingLabelSchema_PropsImpl :: _ContentRatingLabelSchema_PropsImpl)
	end

	function _ContentRatingLabelSchema_PropsImpl.encode(self: ContentRatingLabelSchema_Props): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.rating ~= nil then
			local encoded = self.rating:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.display_text ~= nil then
			local encoded = self.display_text:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.font_style ~= nil then
			local encoded = self.font_style:encode()
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.width ~= nil then
			local encoded = self.width:encode()
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.on_activated ~= nil then
			local encoded = self.on_activated:encode()
			output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.layout_order ~= nil then
			local encoded = self.layout_order:encode()
			output, cursor = proto.writeTag(output, cursor, 6, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ContentRatingLabelSchema_PropsImpl.decode(input: buffer): ContentRatingLabelSchema_Props
		local self = _ContentRatingLabelSchema_PropsImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.rating = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.display_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.font_style = _roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp.decode(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.width = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 6 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.layout_order = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ContentRatingLabelSchema_PropsImpl.jsonEncode(self: ContentRatingLabelSchema_Props): any
		local output = {}

		if self.rating ~= nil then
			output.rating = self.rating:jsonEncode()
		end

		if self.display_text ~= nil then
			output.displayText = self.display_text:jsonEncode()
		end

		if self.font_style ~= nil then
			output.fontStyle = self.font_style:jsonEncode()
		end

		if self.width ~= nil then
			output.width = self.width:jsonEncode()
		end

		if self.on_activated ~= nil then
			output.onActivated = self.on_activated:jsonEncode()
		end

		if self.layout_order ~= nil then
			output.layoutOrder = self.layout_order:jsonEncode()
		end

		return output
	end

	function _ContentRatingLabelSchema_PropsImpl.jsonDecode(input: { [string]: any }): ContentRatingLabelSchema_Props
		local self = _ContentRatingLabelSchema_PropsImpl.new()

		if input.rating ~= nil then
			self.rating = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.rating)
		end

		if input.display_text ~= nil then
			self.display_text =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.display_text)
		end

		if input.displayText ~= nil then
			self.display_text =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.displayText)
		end

		if input.font_style ~= nil then
			self.font_style =
				_roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp.jsonDecode(input.font_style)
		end

		if input.fontStyle ~= nil then
			self.font_style =
				_roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp.jsonDecode(input.fontStyle)
		end

		if input.width ~= nil then
			self.width = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.width)
		end

		if input.on_activated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.on_activated)
		end

		if input.onActivated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.onActivated)
		end

		if input.layout_order ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layout_order)
		end

		if input.layoutOrder ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layoutOrder)
		end

		return self
	end

	_ContentRatingLabelSchema_PropsImpl.descriptor = {
		name = "ContentRatingLabelSchema_Props",
		fullName = "roblox.apppageplatform.shared.v1beta1.Props",
	}

	messages.ContentRatingLabelSchema_Props = _ContentRatingLabelSchema_PropsImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ContentRatingLabelSchema_Props)
end

return {
	ContentRatingLabelSchema = messages.ContentRatingLabelSchema,
	ContentRatingLabelSchema_Props = messages.ContentRatingLabelSchema_Props,
}
