--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	ClientSideHydrationField: _ClientSideHydrationFieldMessage,
}
local messages: _Messages = {} :: _Messages

type _ClientSideHydrationFieldImpl = {
	__index: _ClientSideHydrationFieldImpl,
	new: (fields: _ClientSideHydrationFieldPartialFields?) -> ClientSideHydrationField,
	encode: (self: ClientSideHydrationField) -> buffer,
	decode: (input: buffer) -> ClientSideHydrationField,
	jsonEncode: (self: ClientSideHydrationField) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ClientSideHydrationField,
	descriptor: proto.Descriptor,
}

type _ClientSideHydrationFieldFields = {
	name: string,
	description: string,
}

type _ClientSideHydrationFieldPartialFields = {
	name: string?,
	description: string?,
}

export type ClientSideHydrationField = typeof(setmetatable(
	{} :: _ClientSideHydrationFieldFields,
	{} :: _ClientSideHydrationFieldImpl
))
type _ClientSideHydrationFieldMessage = proto.Message<ClientSideHydrationField, _ClientSideHydrationFieldPartialFields>

do
	local _ClientSideHydrationFieldImpl = {}
	_ClientSideHydrationFieldImpl.__index = _ClientSideHydrationFieldImpl

	function _ClientSideHydrationFieldImpl.new(data: _ClientSideHydrationFieldPartialFields?): ClientSideHydrationField
		return setmetatable({
			name = if data == nil or data.name == nil then "" else data.name,
			description = if data == nil or data.description == nil then "" else data.description,
		}, _ClientSideHydrationFieldImpl :: _ClientSideHydrationFieldImpl)
	end

	function _ClientSideHydrationFieldImpl.encode(self: ClientSideHydrationField): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.name ~= nil and self.name ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.name)
		end

		if self.description ~= nil and self.description ~= "" then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.description)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ClientSideHydrationFieldImpl.decode(input: buffer): ClientSideHydrationField
		local self = _ClientSideHydrationFieldImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.name = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.description = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ClientSideHydrationFieldImpl.jsonEncode(self: ClientSideHydrationField): any
		local output = {}

		if self.name ~= nil and self.name ~= "" then
			output.name = self.name
		end

		if self.description ~= nil and self.description ~= "" then
			output.description = self.description
		end

		return output
	end

	function _ClientSideHydrationFieldImpl.jsonDecode(input: { [string]: any }): ClientSideHydrationField
		local self = _ClientSideHydrationFieldImpl.new()

		if input.name ~= nil then
			self.name = input.name
		end

		if input.description ~= nil then
			self.description = input.description
		end

		return self
	end

	_ClientSideHydrationFieldImpl.descriptor = {
		name = "ClientSideHydrationField",
		fullName = "roblox.apppageplatform.shared.v1beta1.ClientSideHydrationField",
	}

	messages.ClientSideHydrationField = _ClientSideHydrationFieldImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ClientSideHydrationField)
end

return {
	ClientSideHydrationField = messages.ClientSideHydrationField,
}
