--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	DialogSchema: _DialogSchemaMessage,
	DialogSchema_Props: _DialogSchema_PropsMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_prop_types = require(script.Parent.prop_types)
local _roblox_apppageplatform_shared_v1beta1_actions = require(script.Parent.actions)
local _roblox_apppageplatform_shared_v1beta1_component_shared = require(script.Parent.component_shared)

type _DialogSchemaImpl = {
	__index: _DialogSchemaImpl,
	new: (fields: _DialogSchemaPartialFields?) -> DialogSchema,
	encode: (self: DialogSchema) -> buffer,
	decode: (input: buffer) -> DialogSchema,
	jsonEncode: (self: DialogSchema) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> DialogSchema,
	descriptor: proto.Descriptor,
}

type _DialogSchemaFields = {
	props: DialogSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

type _DialogSchemaPartialFields = {
	props: DialogSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

export type DialogSchema = typeof(setmetatable({} :: _DialogSchemaFields, {} :: _DialogSchemaImpl))
type _DialogSchemaMessage = proto.Message<DialogSchema, _DialogSchemaPartialFields>

type _DialogSchema_PropsImpl = {
	__index: _DialogSchema_PropsImpl,
	new: (fields: _DialogSchema_PropsPartialFields?) -> DialogSchema_Props,
	encode: (self: DialogSchema_Props) -> buffer,
	decode: (input: buffer) -> DialogSchema_Props,
	jsonEncode: (self: DialogSchema_Props) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> DialogSchema_Props,
	descriptor: proto.Descriptor,
}

type _DialogSchema_PropsFields = {
	size: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	image: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	image_aspect_ratio: _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp?,
	title_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	body_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	body_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	actions_label: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	actions_orientation: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	primary_button_action: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	primary_button_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	primary_button_icon: _roblox_apppageplatform_shared_v1beta1_prop_types.IconProp?,
	primary_button_input_delay: _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp?,
	primary_button_side_effect_action: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	secondary_button_action: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	secondary_button_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	secondary_button_icon: _roblox_apppageplatform_shared_v1beta1_prop_types.IconProp?,
	secondary_button_input_delay: _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp?,
	secondary_button_side_effect_action: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	on_close: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	disable_portal: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	has_backdrop: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
}

type _DialogSchema_PropsPartialFields = {
	size: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	image: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	image_aspect_ratio: _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp?,
	title_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	body_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	body_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	actions_label: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	actions_orientation: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	primary_button_action: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	primary_button_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	primary_button_icon: _roblox_apppageplatform_shared_v1beta1_prop_types.IconProp?,
	primary_button_input_delay: _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp?,
	primary_button_side_effect_action: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	secondary_button_action: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	secondary_button_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	secondary_button_icon: _roblox_apppageplatform_shared_v1beta1_prop_types.IconProp?,
	secondary_button_input_delay: _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp?,
	secondary_button_side_effect_action: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	on_close: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	disable_portal: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	has_backdrop: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
}

export type DialogSchema_Props = typeof(setmetatable({} :: _DialogSchema_PropsFields, {} :: _DialogSchema_PropsImpl))
type _DialogSchema_PropsMessage = proto.Message<DialogSchema_Props, _DialogSchema_PropsPartialFields>

do
	local _DialogSchemaImpl = {}
	_DialogSchemaImpl.__index = _DialogSchemaImpl

	function _DialogSchemaImpl.new(data: _DialogSchemaPartialFields?): DialogSchema
		return setmetatable({
			props = if data == nil or data.props == nil then nil else data.props,
			shared = if data == nil or data.shared == nil then nil else data.shared,
		}, _DialogSchemaImpl :: _DialogSchemaImpl)
	end

	function _DialogSchemaImpl.encode(self: DialogSchema): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.props ~= nil then
			local encoded = self.props:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.shared ~= nil then
			local encoded = self.shared:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _DialogSchemaImpl.decode(input: buffer): DialogSchema
		local self = _DialogSchemaImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.props = messages.DialogSchema_Props.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.shared = _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _DialogSchemaImpl.jsonEncode(self: DialogSchema): any
		local output = {}

		if self.props ~= nil then
			output.props = self.props:jsonEncode()
		end

		if self.shared ~= nil then
			output.shared = self.shared:jsonEncode()
		end

		return output
	end

	function _DialogSchemaImpl.jsonDecode(input: { [string]: any }): DialogSchema
		local self = _DialogSchemaImpl.new()

		if input.props ~= nil then
			self.props = messages.DialogSchema_Props.jsonDecode(input.props)
		end

		if input.shared ~= nil then
			self.shared =
				_roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.jsonDecode(input.shared)
		end

		return self
	end

	_DialogSchemaImpl.descriptor = {
		name = "DialogSchema",
		fullName = "roblox.apppageplatform.shared.v1beta1.DialogSchema",
	}

	messages.DialogSchema = _DialogSchemaImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.DialogSchema)
end

do
	local _DialogSchema_PropsImpl = {}
	_DialogSchema_PropsImpl.__index = _DialogSchema_PropsImpl

	function _DialogSchema_PropsImpl.new(data: _DialogSchema_PropsPartialFields?): DialogSchema_Props
		return setmetatable({
			size = if data == nil or data.size == nil then nil else data.size,
			image = if data == nil or data.image == nil then nil else data.image,
			image_aspect_ratio = if data == nil or data.image_aspect_ratio == nil then nil else data.image_aspect_ratio,
			title_text = if data == nil or data.title_text == nil then nil else data.title_text,
			body_text = if data == nil or data.body_text == nil then nil else data.body_text,
			body_component = if data == nil or data.body_component == nil then nil else data.body_component,
			actions_label = if data == nil or data.actions_label == nil then nil else data.actions_label,
			actions_orientation = if data == nil or data.actions_orientation == nil
				then nil
				else data.actions_orientation,
			primary_button_action = if data == nil or data.primary_button_action == nil
				then nil
				else data.primary_button_action,
			primary_button_text = if data == nil or data.primary_button_text == nil
				then nil
				else data.primary_button_text,
			primary_button_icon = if data == nil or data.primary_button_icon == nil
				then nil
				else data.primary_button_icon,
			primary_button_input_delay = if data == nil or data.primary_button_input_delay == nil
				then nil
				else data.primary_button_input_delay,
			primary_button_side_effect_action = if data == nil
					or data.primary_button_side_effect_action == nil
				then nil
				else data.primary_button_side_effect_action,
			secondary_button_action = if data == nil or data.secondary_button_action == nil
				then nil
				else data.secondary_button_action,
			secondary_button_text = if data == nil or data.secondary_button_text == nil
				then nil
				else data.secondary_button_text,
			secondary_button_icon = if data == nil or data.secondary_button_icon == nil
				then nil
				else data.secondary_button_icon,
			secondary_button_input_delay = if data == nil or data.secondary_button_input_delay == nil
				then nil
				else data.secondary_button_input_delay,
			secondary_button_side_effect_action = if data == nil
					or data.secondary_button_side_effect_action == nil
				then nil
				else data.secondary_button_side_effect_action,
			on_close = if data == nil or data.on_close == nil then nil else data.on_close,
			disable_portal = if data == nil or data.disable_portal == nil then nil else data.disable_portal,
			has_backdrop = if data == nil or data.has_backdrop == nil then nil else data.has_backdrop,
		}, _DialogSchema_PropsImpl :: _DialogSchema_PropsImpl)
	end

	function _DialogSchema_PropsImpl.encode(self: DialogSchema_Props): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.size ~= nil then
			local encoded = self.size:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.image ~= nil then
			local encoded = self.image:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.image_aspect_ratio ~= nil then
			local encoded = self.image_aspect_ratio:encode()
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.title_text ~= nil then
			local encoded = self.title_text:encode()
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.body_text ~= nil then
			local encoded = self.body_text:encode()
			output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.body_component ~= nil then
			local encoded = self.body_component:encode()
			output, cursor = proto.writeTag(output, cursor, 6, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.actions_label ~= nil then
			local encoded = self.actions_label:encode()
			output, cursor = proto.writeTag(output, cursor, 7, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.actions_orientation ~= nil then
			local encoded = self.actions_orientation:encode()
			output, cursor = proto.writeTag(output, cursor, 8, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.primary_button_action ~= nil then
			local encoded = self.primary_button_action:encode()
			output, cursor = proto.writeTag(output, cursor, 9, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.primary_button_text ~= nil then
			local encoded = self.primary_button_text:encode()
			output, cursor = proto.writeTag(output, cursor, 10, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.primary_button_icon ~= nil then
			local encoded = self.primary_button_icon:encode()
			output, cursor = proto.writeTag(output, cursor, 11, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.primary_button_input_delay ~= nil then
			local encoded = self.primary_button_input_delay:encode()
			output, cursor = proto.writeTag(output, cursor, 12, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.primary_button_side_effect_action ~= nil then
			local encoded = self.primary_button_side_effect_action:encode()
			output, cursor = proto.writeTag(output, cursor, 13, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.secondary_button_action ~= nil then
			local encoded = self.secondary_button_action:encode()
			output, cursor = proto.writeTag(output, cursor, 14, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.secondary_button_text ~= nil then
			local encoded = self.secondary_button_text:encode()
			output, cursor = proto.writeTag(output, cursor, 15, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.secondary_button_icon ~= nil then
			local encoded = self.secondary_button_icon:encode()
			output, cursor = proto.writeTag(output, cursor, 16, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.secondary_button_input_delay ~= nil then
			local encoded = self.secondary_button_input_delay:encode()
			output, cursor = proto.writeTag(output, cursor, 17, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.secondary_button_side_effect_action ~= nil then
			local encoded = self.secondary_button_side_effect_action:encode()
			output, cursor = proto.writeTag(output, cursor, 18, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.on_close ~= nil then
			local encoded = self.on_close:encode()
			output, cursor = proto.writeTag(output, cursor, 19, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.disable_portal ~= nil then
			local encoded = self.disable_portal:encode()
			output, cursor = proto.writeTag(output, cursor, 20, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.has_backdrop ~= nil then
			local encoded = self.has_backdrop:encode()
			output, cursor = proto.writeTag(output, cursor, 21, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _DialogSchema_PropsImpl.decode(input: buffer): DialogSchema_Props
		local self = _DialogSchema_PropsImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.size = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image_aspect_ratio = _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.decode(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.title_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.body_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 6 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.body_component =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 7 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.actions_label = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 8 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.actions_orientation =
						_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 9 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.primary_button_action = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 10 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.primary_button_text =
						_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 11 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.primary_button_icon = _roblox_apppageplatform_shared_v1beta1_prop_types.IconProp.decode(value)
					continue
				elseif field == 12 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.primary_button_input_delay =
						_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.decode(value)
					continue
				elseif field == 13 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.primary_button_side_effect_action =
						_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 14 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.secondary_button_action =
						_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 15 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.secondary_button_text =
						_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 16 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.secondary_button_icon =
						_roblox_apppageplatform_shared_v1beta1_prop_types.IconProp.decode(value)
					continue
				elseif field == 17 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.secondary_button_input_delay =
						_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.decode(value)
					continue
				elseif field == 18 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.secondary_button_side_effect_action =
						_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 19 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.on_close = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 20 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.disable_portal = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 21 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.has_backdrop = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _DialogSchema_PropsImpl.jsonEncode(self: DialogSchema_Props): any
		local output = {}

		if self.size ~= nil then
			output.size = self.size:jsonEncode()
		end

		if self.image ~= nil then
			output.image = self.image:jsonEncode()
		end

		if self.image_aspect_ratio ~= nil then
			output.imageAspectRatio = self.image_aspect_ratio:jsonEncode()
		end

		if self.title_text ~= nil then
			output.titleText = self.title_text:jsonEncode()
		end

		if self.body_text ~= nil then
			output.bodyText = self.body_text:jsonEncode()
		end

		if self.body_component ~= nil then
			output.bodyComponent = self.body_component:jsonEncode()
		end

		if self.actions_label ~= nil then
			output.actionsLabel = self.actions_label:jsonEncode()
		end

		if self.actions_orientation ~= nil then
			output.actionsOrientation = self.actions_orientation:jsonEncode()
		end

		if self.primary_button_action ~= nil then
			output.primaryButtonAction = self.primary_button_action:jsonEncode()
		end

		if self.primary_button_text ~= nil then
			output.primaryButtonText = self.primary_button_text:jsonEncode()
		end

		if self.primary_button_icon ~= nil then
			output.primaryButtonIcon = self.primary_button_icon:jsonEncode()
		end

		if self.primary_button_input_delay ~= nil then
			output.primaryButtonInputDelay = self.primary_button_input_delay:jsonEncode()
		end

		if self.primary_button_side_effect_action ~= nil then
			output.primaryButtonSideEffectAction = self.primary_button_side_effect_action:jsonEncode()
		end

		if self.secondary_button_action ~= nil then
			output.secondaryButtonAction = self.secondary_button_action:jsonEncode()
		end

		if self.secondary_button_text ~= nil then
			output.secondaryButtonText = self.secondary_button_text:jsonEncode()
		end

		if self.secondary_button_icon ~= nil then
			output.secondaryButtonIcon = self.secondary_button_icon:jsonEncode()
		end

		if self.secondary_button_input_delay ~= nil then
			output.secondaryButtonInputDelay = self.secondary_button_input_delay:jsonEncode()
		end

		if self.secondary_button_side_effect_action ~= nil then
			output.secondaryButtonSideEffectAction = self.secondary_button_side_effect_action:jsonEncode()
		end

		if self.on_close ~= nil then
			output.onClose = self.on_close:jsonEncode()
		end

		if self.disable_portal ~= nil then
			output.disablePortal = self.disable_portal:jsonEncode()
		end

		if self.has_backdrop ~= nil then
			output.hasBackdrop = self.has_backdrop:jsonEncode()
		end

		return output
	end

	function _DialogSchema_PropsImpl.jsonDecode(input: { [string]: any }): DialogSchema_Props
		local self = _DialogSchema_PropsImpl.new()

		if input.size ~= nil then
			self.size = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.size)
		end

		if input.image ~= nil then
			self.image = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.image)
		end

		if input.image_aspect_ratio ~= nil then
			self.image_aspect_ratio =
				_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.jsonDecode(input.image_aspect_ratio)
		end

		if input.imageAspectRatio ~= nil then
			self.image_aspect_ratio =
				_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.jsonDecode(input.imageAspectRatio)
		end

		if input.title_text ~= nil then
			self.title_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.title_text)
		end

		if input.titleText ~= nil then
			self.title_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.titleText)
		end

		if input.body_text ~= nil then
			self.body_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.body_text)
		end

		if input.bodyText ~= nil then
			self.body_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.bodyText)
		end

		if input.body_component ~= nil then
			self.body_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(input.body_component)
		end

		if input.bodyComponent ~= nil then
			self.body_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(input.bodyComponent)
		end

		if input.actions_label ~= nil then
			self.actions_label =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.actions_label)
		end

		if input.actionsLabel ~= nil then
			self.actions_label =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.actionsLabel)
		end

		if input.actions_orientation ~= nil then
			self.actions_orientation =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.actions_orientation)
		end

		if input.actionsOrientation ~= nil then
			self.actions_orientation =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.actionsOrientation)
		end

		if input.primary_button_action ~= nil then
			self.primary_button_action =
				_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.primary_button_action)
		end

		if input.primaryButtonAction ~= nil then
			self.primary_button_action =
				_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.primaryButtonAction)
		end

		if input.primary_button_text ~= nil then
			self.primary_button_text =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.primary_button_text)
		end

		if input.primaryButtonText ~= nil then
			self.primary_button_text =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.primaryButtonText)
		end

		if input.primary_button_icon ~= nil then
			self.primary_button_icon =
				_roblox_apppageplatform_shared_v1beta1_prop_types.IconProp.jsonDecode(input.primary_button_icon)
		end

		if input.primaryButtonIcon ~= nil then
			self.primary_button_icon =
				_roblox_apppageplatform_shared_v1beta1_prop_types.IconProp.jsonDecode(input.primaryButtonIcon)
		end

		if input.primary_button_input_delay ~= nil then
			self.primary_button_input_delay =
				_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.jsonDecode(input.primary_button_input_delay)
		end

		if input.primaryButtonInputDelay ~= nil then
			self.primary_button_input_delay =
				_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.jsonDecode(input.primaryButtonInputDelay)
		end

		if input.primary_button_side_effect_action ~= nil then
			self.primary_button_side_effect_action =
				_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(
					input.primary_button_side_effect_action
				)
		end

		if input.primaryButtonSideEffectAction ~= nil then
			self.primary_button_side_effect_action =
				_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(
					input.primaryButtonSideEffectAction
				)
		end

		if input.secondary_button_action ~= nil then
			self.secondary_button_action =
				_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.secondary_button_action)
		end

		if input.secondaryButtonAction ~= nil then
			self.secondary_button_action =
				_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.secondaryButtonAction)
		end

		if input.secondary_button_text ~= nil then
			self.secondary_button_text =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.secondary_button_text)
		end

		if input.secondaryButtonText ~= nil then
			self.secondary_button_text =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.secondaryButtonText)
		end

		if input.secondary_button_icon ~= nil then
			self.secondary_button_icon =
				_roblox_apppageplatform_shared_v1beta1_prop_types.IconProp.jsonDecode(input.secondary_button_icon)
		end

		if input.secondaryButtonIcon ~= nil then
			self.secondary_button_icon =
				_roblox_apppageplatform_shared_v1beta1_prop_types.IconProp.jsonDecode(input.secondaryButtonIcon)
		end

		if input.secondary_button_input_delay ~= nil then
			self.secondary_button_input_delay = _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.jsonDecode(
				input.secondary_button_input_delay
			)
		end

		if input.secondaryButtonInputDelay ~= nil then
			self.secondary_button_input_delay =
				_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.jsonDecode(input.secondaryButtonInputDelay)
		end

		if input.secondary_button_side_effect_action ~= nil then
			self.secondary_button_side_effect_action =
				_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(
					input.secondary_button_side_effect_action
				)
		end

		if input.secondaryButtonSideEffectAction ~= nil then
			self.secondary_button_side_effect_action =
				_roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(
					input.secondaryButtonSideEffectAction
				)
		end

		if input.on_close ~= nil then
			self.on_close = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.on_close)
		end

		if input.onClose ~= nil then
			self.on_close = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.onClose)
		end

		if input.disable_portal ~= nil then
			self.disable_portal =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.disable_portal)
		end

		if input.disablePortal ~= nil then
			self.disable_portal =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.disablePortal)
		end

		if input.has_backdrop ~= nil then
			self.has_backdrop =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.has_backdrop)
		end

		if input.hasBackdrop ~= nil then
			self.has_backdrop = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.hasBackdrop)
		end

		return self
	end

	_DialogSchema_PropsImpl.descriptor = {
		name = "DialogSchema_Props",
		fullName = "roblox.apppageplatform.shared.v1beta1.Props",
	}

	messages.DialogSchema_Props = _DialogSchema_PropsImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.DialogSchema_Props)
end

return {
	DialogSchema = messages.DialogSchema,
	DialogSchema_Props = messages.DialogSchema_Props,
}
