--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	DisplayLocation: _DisplayLocationMessage,
}
local messages: _Messages = {} :: _Messages

type _DisplayLocationMessage = proto.Enum<DisplayLocation>
export type DisplayLocation =
	"DISPLAY_LOCATION_INVALID"
	| "DISPLAY_LOCATION_GLOBAL"
	| "DISPLAY_LOCATION_BADGE_SEE_ALL"
	| "DISPLAY_LOCATION_BADGE_DETAILS"
	| "DISPLAY_LOCATION_PROMPTS"
	| "DISPLAY_LOCATION_EXPERIENCE_DETAILS"
	| "DISPLAY_LOCATION_DEV_STORE_SEE_ALL"
	| "DISPLAY_LOCATION_CHARTS"
	| "DISPLAY_LOCATION_EVENT_DETAILS"
	| "DISPLAY_LOCATION_MARKETPLACE_LANDING"
	| "DISPLAY_LOCATION_SEARCH_RESULTS"
	| "DISPLAY_LOCATION_SEARCH_LANDING"
	| "DISPLAY_LOCATION_SPOTLIGHT"
	| "DISPLAY_LOCATION_HOME"
	| number -- Unknown

messages.DisplayLocation = {
	fromNumber = function(value: number): DisplayLocation?
		if value == 0 then
			return "DISPLAY_LOCATION_INVALID"
		elseif value == 1 then
			return "DISPLAY_LOCATION_GLOBAL"
		elseif value == 2 then
			return "DISPLAY_LOCATION_BADGE_SEE_ALL"
		elseif value == 3 then
			return "DISPLAY_LOCATION_BADGE_DETAILS"
		elseif value == 4 then
			return "DISPLAY_LOCATION_PROMPTS"
		elseif value == 5 then
			return "DISPLAY_LOCATION_EXPERIENCE_DETAILS"
		elseif value == 6 then
			return "DISPLAY_LOCATION_DEV_STORE_SEE_ALL"
		elseif value == 7 then
			return "DISPLAY_LOCATION_CHARTS"
		elseif value == 8 then
			return "DISPLAY_LOCATION_EVENT_DETAILS"
		elseif value == 9 then
			return "DISPLAY_LOCATION_MARKETPLACE_LANDING"
		elseif value == 10 then
			return "DISPLAY_LOCATION_SEARCH_RESULTS"
		elseif value == 11 then
			return "DISPLAY_LOCATION_SEARCH_LANDING"
		elseif value == 12 then
			return "DISPLAY_LOCATION_SPOTLIGHT"
		elseif value == 13 then
			return "DISPLAY_LOCATION_HOME"
		else
			return nil
		end
	end,

	toNumber = function(self: DisplayLocation): number
		if self == "DISPLAY_LOCATION_INVALID" then
			return 0
		elseif self == "DISPLAY_LOCATION_GLOBAL" then
			return 1
		elseif self == "DISPLAY_LOCATION_BADGE_SEE_ALL" then
			return 2
		elseif self == "DISPLAY_LOCATION_BADGE_DETAILS" then
			return 3
		elseif self == "DISPLAY_LOCATION_PROMPTS" then
			return 4
		elseif self == "DISPLAY_LOCATION_EXPERIENCE_DETAILS" then
			return 5
		elseif self == "DISPLAY_LOCATION_DEV_STORE_SEE_ALL" then
			return 6
		elseif self == "DISPLAY_LOCATION_CHARTS" then
			return 7
		elseif self == "DISPLAY_LOCATION_EVENT_DETAILS" then
			return 8
		elseif self == "DISPLAY_LOCATION_MARKETPLACE_LANDING" then
			return 9
		elseif self == "DISPLAY_LOCATION_SEARCH_RESULTS" then
			return 10
		elseif self == "DISPLAY_LOCATION_SEARCH_LANDING" then
			return 11
		elseif self == "DISPLAY_LOCATION_SPOTLIGHT" then
			return 12
		elseif self == "DISPLAY_LOCATION_HOME" then
			return 13
		else
			return self
		end
	end,

	fromName = function(name: string): DisplayLocation?
		if name == "DISPLAY_LOCATION_INVALID" then
			return "DISPLAY_LOCATION_INVALID"
		elseif name == "DISPLAY_LOCATION_GLOBAL" then
			return "DISPLAY_LOCATION_GLOBAL"
		elseif name == "DISPLAY_LOCATION_BADGE_SEE_ALL" then
			return "DISPLAY_LOCATION_BADGE_SEE_ALL"
		elseif name == "DISPLAY_LOCATION_BADGE_DETAILS" then
			return "DISPLAY_LOCATION_BADGE_DETAILS"
		elseif name == "DISPLAY_LOCATION_PROMPTS" then
			return "DISPLAY_LOCATION_PROMPTS"
		elseif name == "DISPLAY_LOCATION_EXPERIENCE_DETAILS" then
			return "DISPLAY_LOCATION_EXPERIENCE_DETAILS"
		elseif name == "DISPLAY_LOCATION_DEV_STORE_SEE_ALL" then
			return "DISPLAY_LOCATION_DEV_STORE_SEE_ALL"
		elseif name == "DISPLAY_LOCATION_CHARTS" then
			return "DISPLAY_LOCATION_CHARTS"
		elseif name == "DISPLAY_LOCATION_EVENT_DETAILS" then
			return "DISPLAY_LOCATION_EVENT_DETAILS"
		elseif name == "DISPLAY_LOCATION_MARKETPLACE_LANDING" then
			return "DISPLAY_LOCATION_MARKETPLACE_LANDING"
		elseif name == "DISPLAY_LOCATION_SEARCH_RESULTS" then
			return "DISPLAY_LOCATION_SEARCH_RESULTS"
		elseif name == "DISPLAY_LOCATION_SEARCH_LANDING" then
			return "DISPLAY_LOCATION_SEARCH_LANDING"
		elseif name == "DISPLAY_LOCATION_SPOTLIGHT" then
			return "DISPLAY_LOCATION_SPOTLIGHT"
		elseif name == "DISPLAY_LOCATION_HOME" then
			return "DISPLAY_LOCATION_HOME"
		else
			return nil
		end
	end,
}

return {
	DisplayLocation = messages.DisplayLocation,
}
