--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	EventTileSchema: _EventTileSchemaMessage,
	EventTileSchema_Props: _EventTileSchema_PropsMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_prop_types = require(script.Parent.prop_types)
local _roblox_apppageplatform_shared_v1beta1_actions = require(script.Parent.actions)
local _roblox_apppageplatform_shared_v1beta1_component_shared = require(script.Parent.component_shared)

type _EventTileSchemaImpl = {
	__index: _EventTileSchemaImpl,
	new: (fields: _EventTileSchemaPartialFields?) -> EventTileSchema,
	encode: (self: EventTileSchema) -> buffer,
	decode: (input: buffer) -> EventTileSchema,
	jsonEncode: (self: EventTileSchema) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> EventTileSchema,
	descriptor: proto.Descriptor,
}

type _EventTileSchemaFields = {
	props: EventTileSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

type _EventTileSchemaPartialFields = {
	props: EventTileSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

export type EventTileSchema = typeof(setmetatable({} :: _EventTileSchemaFields, {} :: _EventTileSchemaImpl))
type _EventTileSchemaMessage = proto.Message<EventTileSchema, _EventTileSchemaPartialFields>

type _EventTileSchema_PropsImpl = {
	__index: _EventTileSchema_PropsImpl,
	new: (fields: _EventTileSchema_PropsPartialFields?) -> EventTileSchema_Props,
	encode: (self: EventTileSchema_Props) -> buffer,
	decode: (input: buffer) -> EventTileSchema_Props,
	jsonEncode: (self: EventTileSchema_Props) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> EventTileSchema_Props,
	descriptor: proto.Descriptor,
}

type _EventTileSchema_PropsFields = {
	image_aspect_ratio: _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp?,
	title_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	image: _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp?,
	is_contained: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	background_image: _roblox_apppageplatform_shared_v1beta1_prop_types.ImageSetProp?,
	containment_padding: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	corner_radius: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	title_lines: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	background_image_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	cta_button_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	footer_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	image_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	thumbnail_overlay_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	title_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	focus_navigation_actions_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	thumbnail_background_style: _roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp?,
	title_font: _roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp?,
	enable_legacy_hover_state: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	event_id: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	universe_id: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	disable_default_overlay: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	disable_default_footer: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	disable_default_cta: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	is_active: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	formatted_start_date: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	subtitle: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	user_rsvp: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
}

type _EventTileSchema_PropsPartialFields = {
	image_aspect_ratio: _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp?,
	title_text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	image: _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp?,
	is_contained: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	background_image: _roblox_apppageplatform_shared_v1beta1_prop_types.ImageSetProp?,
	containment_padding: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	corner_radius: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	title_lines: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	background_image_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	cta_button_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	footer_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	image_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	thumbnail_overlay_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	title_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	focus_navigation_actions_component: _roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp?,
	thumbnail_background_style: _roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp?,
	title_font: _roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp?,
	enable_legacy_hover_state: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	event_id: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	universe_id: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	disable_default_overlay: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	disable_default_footer: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	disable_default_cta: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	is_active: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	formatted_start_date: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	subtitle: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	user_rsvp: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
}

export type EventTileSchema_Props = typeof(setmetatable(
	{} :: _EventTileSchema_PropsFields,
	{} :: _EventTileSchema_PropsImpl
))
type _EventTileSchema_PropsMessage = proto.Message<EventTileSchema_Props, _EventTileSchema_PropsPartialFields>

do
	local _EventTileSchemaImpl = {}
	_EventTileSchemaImpl.__index = _EventTileSchemaImpl

	function _EventTileSchemaImpl.new(data: _EventTileSchemaPartialFields?): EventTileSchema
		return setmetatable({
			props = if data == nil or data.props == nil then nil else data.props,
			shared = if data == nil or data.shared == nil then nil else data.shared,
		}, _EventTileSchemaImpl :: _EventTileSchemaImpl)
	end

	function _EventTileSchemaImpl.encode(self: EventTileSchema): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.props ~= nil then
			local encoded = self.props:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.shared ~= nil then
			local encoded = self.shared:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _EventTileSchemaImpl.decode(input: buffer): EventTileSchema
		local self = _EventTileSchemaImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.props = messages.EventTileSchema_Props.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.shared = _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _EventTileSchemaImpl.jsonEncode(self: EventTileSchema): any
		local output = {}

		if self.props ~= nil then
			output.props = self.props:jsonEncode()
		end

		if self.shared ~= nil then
			output.shared = self.shared:jsonEncode()
		end

		return output
	end

	function _EventTileSchemaImpl.jsonDecode(input: { [string]: any }): EventTileSchema
		local self = _EventTileSchemaImpl.new()

		if input.props ~= nil then
			self.props = messages.EventTileSchema_Props.jsonDecode(input.props)
		end

		if input.shared ~= nil then
			self.shared =
				_roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.jsonDecode(input.shared)
		end

		return self
	end

	_EventTileSchemaImpl.descriptor = {
		name = "EventTileSchema",
		fullName = "roblox.apppageplatform.shared.v1beta1.EventTileSchema",
	}

	messages.EventTileSchema = _EventTileSchemaImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.EventTileSchema)
end

do
	local _EventTileSchema_PropsImpl = {}
	_EventTileSchema_PropsImpl.__index = _EventTileSchema_PropsImpl

	function _EventTileSchema_PropsImpl.new(data: _EventTileSchema_PropsPartialFields?): EventTileSchema_Props
		return setmetatable({
			image_aspect_ratio = if data == nil or data.image_aspect_ratio == nil then nil else data.image_aspect_ratio,
			title_text = if data == nil or data.title_text == nil then nil else data.title_text,
			image = if data == nil or data.image == nil then nil else data.image,
			is_contained = if data == nil or data.is_contained == nil then nil else data.is_contained,
			on_activated = if data == nil or data.on_activated == nil then nil else data.on_activated,
			background_image = if data == nil or data.background_image == nil then nil else data.background_image,
			containment_padding = if data == nil or data.containment_padding == nil
				then nil
				else data.containment_padding,
			corner_radius = if data == nil or data.corner_radius == nil then nil else data.corner_radius,
			title_lines = if data == nil or data.title_lines == nil then nil else data.title_lines,
			background_image_component = if data == nil or data.background_image_component == nil
				then nil
				else data.background_image_component,
			cta_button_component = if data == nil or data.cta_button_component == nil
				then nil
				else data.cta_button_component,
			footer_component = if data == nil or data.footer_component == nil then nil else data.footer_component,
			image_component = if data == nil or data.image_component == nil then nil else data.image_component,
			thumbnail_overlay_component = if data == nil or data.thumbnail_overlay_component == nil
				then nil
				else data.thumbnail_overlay_component,
			title_component = if data == nil or data.title_component == nil then nil else data.title_component,
			focus_navigation_actions_component = if data == nil
					or data.focus_navigation_actions_component == nil
				then nil
				else data.focus_navigation_actions_component,
			thumbnail_background_style = if data == nil or data.thumbnail_background_style == nil
				then nil
				else data.thumbnail_background_style,
			title_font = if data == nil or data.title_font == nil then nil else data.title_font,
			enable_legacy_hover_state = if data == nil or data.enable_legacy_hover_state == nil
				then nil
				else data.enable_legacy_hover_state,
			event_id = if data == nil or data.event_id == nil then nil else data.event_id,
			universe_id = if data == nil or data.universe_id == nil then nil else data.universe_id,
			disable_default_overlay = if data == nil or data.disable_default_overlay == nil
				then nil
				else data.disable_default_overlay,
			disable_default_footer = if data == nil or data.disable_default_footer == nil
				then nil
				else data.disable_default_footer,
			disable_default_cta = if data == nil or data.disable_default_cta == nil
				then nil
				else data.disable_default_cta,
			is_active = if data == nil or data.is_active == nil then nil else data.is_active,
			formatted_start_date = if data == nil or data.formatted_start_date == nil
				then nil
				else data.formatted_start_date,
			subtitle = if data == nil or data.subtitle == nil then nil else data.subtitle,
			user_rsvp = if data == nil or data.user_rsvp == nil then nil else data.user_rsvp,
		}, _EventTileSchema_PropsImpl :: _EventTileSchema_PropsImpl)
	end

	function _EventTileSchema_PropsImpl.encode(self: EventTileSchema_Props): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.image_aspect_ratio ~= nil then
			local encoded = self.image_aspect_ratio:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.title_text ~= nil then
			local encoded = self.title_text:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.image ~= nil then
			local encoded = self.image:encode()
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.is_contained ~= nil then
			local encoded = self.is_contained:encode()
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.on_activated ~= nil then
			local encoded = self.on_activated:encode()
			output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.background_image ~= nil then
			local encoded = self.background_image:encode()
			output, cursor = proto.writeTag(output, cursor, 6, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.containment_padding ~= nil then
			local encoded = self.containment_padding:encode()
			output, cursor = proto.writeTag(output, cursor, 7, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.corner_radius ~= nil then
			local encoded = self.corner_radius:encode()
			output, cursor = proto.writeTag(output, cursor, 8, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.title_lines ~= nil then
			local encoded = self.title_lines:encode()
			output, cursor = proto.writeTag(output, cursor, 9, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.background_image_component ~= nil then
			local encoded = self.background_image_component:encode()
			output, cursor = proto.writeTag(output, cursor, 10, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.cta_button_component ~= nil then
			local encoded = self.cta_button_component:encode()
			output, cursor = proto.writeTag(output, cursor, 11, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.footer_component ~= nil then
			local encoded = self.footer_component:encode()
			output, cursor = proto.writeTag(output, cursor, 12, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.image_component ~= nil then
			local encoded = self.image_component:encode()
			output, cursor = proto.writeTag(output, cursor, 13, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.thumbnail_overlay_component ~= nil then
			local encoded = self.thumbnail_overlay_component:encode()
			output, cursor = proto.writeTag(output, cursor, 14, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.title_component ~= nil then
			local encoded = self.title_component:encode()
			output, cursor = proto.writeTag(output, cursor, 15, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.focus_navigation_actions_component ~= nil then
			local encoded = self.focus_navigation_actions_component:encode()
			output, cursor = proto.writeTag(output, cursor, 16, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.thumbnail_background_style ~= nil then
			local encoded = self.thumbnail_background_style:encode()
			output, cursor = proto.writeTag(output, cursor, 17, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.title_font ~= nil then
			local encoded = self.title_font:encode()
			output, cursor = proto.writeTag(output, cursor, 18, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.enable_legacy_hover_state ~= nil then
			local encoded = self.enable_legacy_hover_state:encode()
			output, cursor = proto.writeTag(output, cursor, 19, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.event_id ~= nil then
			local encoded = self.event_id:encode()
			output, cursor = proto.writeTag(output, cursor, 100, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.universe_id ~= nil then
			local encoded = self.universe_id:encode()
			output, cursor = proto.writeTag(output, cursor, 101, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.disable_default_overlay ~= nil then
			local encoded = self.disable_default_overlay:encode()
			output, cursor = proto.writeTag(output, cursor, 102, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.disable_default_footer ~= nil then
			local encoded = self.disable_default_footer:encode()
			output, cursor = proto.writeTag(output, cursor, 103, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.disable_default_cta ~= nil then
			local encoded = self.disable_default_cta:encode()
			output, cursor = proto.writeTag(output, cursor, 104, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.is_active ~= nil then
			local encoded = self.is_active:encode()
			output, cursor = proto.writeTag(output, cursor, 105, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.formatted_start_date ~= nil then
			local encoded = self.formatted_start_date:encode()
			output, cursor = proto.writeTag(output, cursor, 106, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.subtitle ~= nil then
			local encoded = self.subtitle:encode()
			output, cursor = proto.writeTag(output, cursor, 107, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.user_rsvp ~= nil then
			local encoded = self.user_rsvp:encode()
			output, cursor = proto.writeTag(output, cursor, 108, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _EventTileSchema_PropsImpl.decode(input: buffer): EventTileSchema_Props
		local self = _EventTileSchema_PropsImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image_aspect_ratio = _roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.title_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image = _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp.decode(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.is_contained = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 6 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.background_image = _roblox_apppageplatform_shared_v1beta1_prop_types.ImageSetProp.decode(value)
					continue
				elseif field == 7 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.containment_padding = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 8 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.corner_radius = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 9 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.title_lines = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 10 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.background_image_component =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 11 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.cta_button_component =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 12 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.footer_component =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 13 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image_component =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 14 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.thumbnail_overlay_component =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 15 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.title_component =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 16 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.focus_navigation_actions_component =
						_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.decode(value)
					continue
				elseif field == 17 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.thumbnail_background_style =
						_roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp.decode(value)
					continue
				elseif field == 18 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.title_font = _roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp.decode(value)
					continue
				elseif field == 19 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.enable_legacy_hover_state =
						_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 100 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.event_id = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 101 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.universe_id = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 102 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.disable_default_overlay =
						_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 103 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.disable_default_footer =
						_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 104 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.disable_default_cta = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 105 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.is_active = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 106 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.formatted_start_date =
						_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 107 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.subtitle = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 108 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.user_rsvp = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _EventTileSchema_PropsImpl.jsonEncode(self: EventTileSchema_Props): any
		local output = {}

		if self.image_aspect_ratio ~= nil then
			output.imageAspectRatio = self.image_aspect_ratio:jsonEncode()
		end

		if self.title_text ~= nil then
			output.titleText = self.title_text:jsonEncode()
		end

		if self.image ~= nil then
			output.image = self.image:jsonEncode()
		end

		if self.is_contained ~= nil then
			output.isContained = self.is_contained:jsonEncode()
		end

		if self.on_activated ~= nil then
			output.onActivated = self.on_activated:jsonEncode()
		end

		if self.background_image ~= nil then
			output.backgroundImage = self.background_image:jsonEncode()
		end

		if self.containment_padding ~= nil then
			output.containmentPadding = self.containment_padding:jsonEncode()
		end

		if self.corner_radius ~= nil then
			output.cornerRadius = self.corner_radius:jsonEncode()
		end

		if self.title_lines ~= nil then
			output.titleLines = self.title_lines:jsonEncode()
		end

		if self.background_image_component ~= nil then
			output.backgroundImageComponent = self.background_image_component:jsonEncode()
		end

		if self.cta_button_component ~= nil then
			output.ctaButtonComponent = self.cta_button_component:jsonEncode()
		end

		if self.footer_component ~= nil then
			output.footerComponent = self.footer_component:jsonEncode()
		end

		if self.image_component ~= nil then
			output.imageComponent = self.image_component:jsonEncode()
		end

		if self.thumbnail_overlay_component ~= nil then
			output.thumbnailOverlayComponent = self.thumbnail_overlay_component:jsonEncode()
		end

		if self.title_component ~= nil then
			output.titleComponent = self.title_component:jsonEncode()
		end

		if self.focus_navigation_actions_component ~= nil then
			output.focusNavigationActionsComponent = self.focus_navigation_actions_component:jsonEncode()
		end

		if self.thumbnail_background_style ~= nil then
			output.thumbnailBackgroundStyle = self.thumbnail_background_style:jsonEncode()
		end

		if self.title_font ~= nil then
			output.titleFont = self.title_font:jsonEncode()
		end

		if self.enable_legacy_hover_state ~= nil then
			output.enableLegacyHoverState = self.enable_legacy_hover_state:jsonEncode()
		end

		if self.event_id ~= nil then
			output.eventId = self.event_id:jsonEncode()
		end

		if self.universe_id ~= nil then
			output.universeId = self.universe_id:jsonEncode()
		end

		if self.disable_default_overlay ~= nil then
			output.disableDefaultOverlay = self.disable_default_overlay:jsonEncode()
		end

		if self.disable_default_footer ~= nil then
			output.disableDefaultFooter = self.disable_default_footer:jsonEncode()
		end

		if self.disable_default_cta ~= nil then
			output.disableDefaultCta = self.disable_default_cta:jsonEncode()
		end

		if self.is_active ~= nil then
			output.isActive = self.is_active:jsonEncode()
		end

		if self.formatted_start_date ~= nil then
			output.formattedStartDate = self.formatted_start_date:jsonEncode()
		end

		if self.subtitle ~= nil then
			output.subtitle = self.subtitle:jsonEncode()
		end

		if self.user_rsvp ~= nil then
			output.userRsvp = self.user_rsvp:jsonEncode()
		end

		return output
	end

	function _EventTileSchema_PropsImpl.jsonDecode(input: { [string]: any }): EventTileSchema_Props
		local self = _EventTileSchema_PropsImpl.new()

		if input.image_aspect_ratio ~= nil then
			self.image_aspect_ratio =
				_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.jsonDecode(input.image_aspect_ratio)
		end

		if input.imageAspectRatio ~= nil then
			self.image_aspect_ratio =
				_roblox_apppageplatform_shared_v1beta1_prop_types.FloatProp.jsonDecode(input.imageAspectRatio)
		end

		if input.title_text ~= nil then
			self.title_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.title_text)
		end

		if input.titleText ~= nil then
			self.title_text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.titleText)
		end

		if input.image ~= nil then
			self.image = _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp.jsonDecode(input.image)
		end

		if input.is_contained ~= nil then
			self.is_contained =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.is_contained)
		end

		if input.isContained ~= nil then
			self.is_contained = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.isContained)
		end

		if input.on_activated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.on_activated)
		end

		if input.onActivated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.onActivated)
		end

		if input.background_image ~= nil then
			self.background_image =
				_roblox_apppageplatform_shared_v1beta1_prop_types.ImageSetProp.jsonDecode(input.background_image)
		end

		if input.backgroundImage ~= nil then
			self.background_image =
				_roblox_apppageplatform_shared_v1beta1_prop_types.ImageSetProp.jsonDecode(input.backgroundImage)
		end

		if input.containment_padding ~= nil then
			self.containment_padding =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.containment_padding)
		end

		if input.containmentPadding ~= nil then
			self.containment_padding =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.containmentPadding)
		end

		if input.corner_radius ~= nil then
			self.corner_radius =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.corner_radius)
		end

		if input.cornerRadius ~= nil then
			self.corner_radius =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.cornerRadius)
		end

		if input.title_lines ~= nil then
			self.title_lines = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.title_lines)
		end

		if input.titleLines ~= nil then
			self.title_lines = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.titleLines)
		end

		if input.background_image_component ~= nil then
			self.background_image_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.background_image_component
				)
		end

		if input.backgroundImageComponent ~= nil then
			self.background_image_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.backgroundImageComponent
				)
		end

		if input.cta_button_component ~= nil then
			self.cta_button_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.cta_button_component
				)
		end

		if input.ctaButtonComponent ~= nil then
			self.cta_button_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.ctaButtonComponent
				)
		end

		if input.footer_component ~= nil then
			self.footer_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(input.footer_component)
		end

		if input.footerComponent ~= nil then
			self.footer_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(input.footerComponent)
		end

		if input.image_component ~= nil then
			self.image_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(input.image_component)
		end

		if input.imageComponent ~= nil then
			self.image_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(input.imageComponent)
		end

		if input.thumbnail_overlay_component ~= nil then
			self.thumbnail_overlay_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.thumbnail_overlay_component
				)
		end

		if input.thumbnailOverlayComponent ~= nil then
			self.thumbnail_overlay_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.thumbnailOverlayComponent
				)
		end

		if input.title_component ~= nil then
			self.title_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(input.title_component)
		end

		if input.titleComponent ~= nil then
			self.title_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(input.titleComponent)
		end

		if input.focus_navigation_actions_component ~= nil then
			self.focus_navigation_actions_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.focus_navigation_actions_component
				)
		end

		if input.focusNavigationActionsComponent ~= nil then
			self.focus_navigation_actions_component =
				_roblox_apppageplatform_shared_v1beta1_prop_types.NestedComponentProp.jsonDecode(
					input.focusNavigationActionsComponent
				)
		end

		if input.thumbnail_background_style ~= nil then
			self.thumbnail_background_style =
				_roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp.jsonDecode(input.thumbnail_background_style)
		end

		if input.thumbnailBackgroundStyle ~= nil then
			self.thumbnail_background_style =
				_roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp.jsonDecode(input.thumbnailBackgroundStyle)
		end

		if input.title_font ~= nil then
			self.title_font =
				_roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp.jsonDecode(input.title_font)
		end

		if input.titleFont ~= nil then
			self.title_font =
				_roblox_apppageplatform_shared_v1beta1_prop_types.TypographyProp.jsonDecode(input.titleFont)
		end

		if input.enable_legacy_hover_state ~= nil then
			self.enable_legacy_hover_state =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.enable_legacy_hover_state)
		end

		if input.enableLegacyHoverState ~= nil then
			self.enable_legacy_hover_state =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.enableLegacyHoverState)
		end

		if input.event_id ~= nil then
			self.event_id = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.event_id)
		end

		if input.eventId ~= nil then
			self.event_id = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.eventId)
		end

		if input.universe_id ~= nil then
			self.universe_id =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.universe_id)
		end

		if input.universeId ~= nil then
			self.universe_id = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.universeId)
		end

		if input.disable_default_overlay ~= nil then
			self.disable_default_overlay =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.disable_default_overlay)
		end

		if input.disableDefaultOverlay ~= nil then
			self.disable_default_overlay =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.disableDefaultOverlay)
		end

		if input.disable_default_footer ~= nil then
			self.disable_default_footer =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.disable_default_footer)
		end

		if input.disableDefaultFooter ~= nil then
			self.disable_default_footer =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.disableDefaultFooter)
		end

		if input.disable_default_cta ~= nil then
			self.disable_default_cta =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.disable_default_cta)
		end

		if input.disableDefaultCta ~= nil then
			self.disable_default_cta =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.disableDefaultCta)
		end

		if input.is_active ~= nil then
			self.is_active = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.is_active)
		end

		if input.isActive ~= nil then
			self.is_active = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.isActive)
		end

		if input.formatted_start_date ~= nil then
			self.formatted_start_date =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.formatted_start_date)
		end

		if input.formattedStartDate ~= nil then
			self.formatted_start_date =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.formattedStartDate)
		end

		if input.subtitle ~= nil then
			self.subtitle = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.subtitle)
		end

		if input.user_rsvp ~= nil then
			self.user_rsvp = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.user_rsvp)
		end

		if input.userRsvp ~= nil then
			self.user_rsvp = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.userRsvp)
		end

		return self
	end

	_EventTileSchema_PropsImpl.descriptor = {
		name = "EventTileSchema_Props",
		fullName = "roblox.apppageplatform.shared.v1beta1.Props",
	}

	messages.EventTileSchema_Props = _EventTileSchema_PropsImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.EventTileSchema_Props)
end

return {
	EventTileSchema = messages.EventTileSchema,
	EventTileSchema_Props = messages.EventTileSchema_Props,
}
