--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	EventData: _EventDataMessage,
}
local messages: _Messages = {} :: _Messages

type _EventDataImpl = {
	__index: _EventDataImpl,
	new: (fields: _EventDataPartialFields?) -> EventData,
	encode: (self: EventData) -> buffer,
	decode: (input: buffer) -> EventData,
	jsonEncode: (self: EventData) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> EventData,
	descriptor: proto.Descriptor,
}

type _EventDataFields = {
	id: string,
	title: string,
	subtitle: string,
	event_start: string,
	event_end: string,
	user_rsvp: boolean,
	media_asset_id: number,
	description: string,
	rsvp_count: number,
	place_id: string,
}

type _EventDataPartialFields = {
	id: string?,
	title: string?,
	subtitle: string?,
	event_start: string?,
	event_end: string?,
	user_rsvp: boolean?,
	media_asset_id: number?,
	description: string?,
	rsvp_count: number?,
	place_id: string?,
}

export type EventData = typeof(setmetatable({} :: _EventDataFields, {} :: _EventDataImpl))
type _EventDataMessage = proto.Message<EventData, _EventDataPartialFields>

do
	local _EventDataImpl = {}
	_EventDataImpl.__index = _EventDataImpl

	function _EventDataImpl.new(data: _EventDataPartialFields?): EventData
		return setmetatable({
			id = if data == nil or data.id == nil then "" else data.id,
			title = if data == nil or data.title == nil then "" else data.title,
			subtitle = if data == nil or data.subtitle == nil then "" else data.subtitle,
			event_start = if data == nil or data.event_start == nil then "" else data.event_start,
			event_end = if data == nil or data.event_end == nil then "" else data.event_end,
			user_rsvp = if data == nil or data.user_rsvp == nil then false else data.user_rsvp,
			media_asset_id = if data == nil or data.media_asset_id == nil then 0 else data.media_asset_id,
			description = if data == nil or data.description == nil then "" else data.description,
			rsvp_count = if data == nil or data.rsvp_count == nil then 0 else data.rsvp_count,
			place_id = if data == nil or data.place_id == nil then "" else data.place_id,
		}, _EventDataImpl :: _EventDataImpl)
	end

	function _EventDataImpl.encode(self: EventData): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.id ~= nil and self.id ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.id)
		end

		if self.title ~= nil and self.title ~= "" then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.title)
		end

		if self.subtitle ~= nil and self.subtitle ~= "" then
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.subtitle)
		end

		if self.event_start ~= nil and self.event_start ~= "" then
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.event_start)
		end

		if self.event_end ~= nil and self.event_end ~= "" then
			output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.event_end)
		end

		if self.user_rsvp then
			output, cursor = proto.writeTag(output, cursor, 6, proto.wireTypes.varint)
			output, cursor = proto.writeVarInt(output, cursor, if self.user_rsvp then 1 else 0)
		end

		if self.media_asset_id ~= nil and self.media_asset_id ~= 0 then
			output, cursor = proto.writeTag(output, cursor, 7, proto.wireTypes.varint)
			output, cursor = proto.writeVarInt(output, cursor, self.media_asset_id)
		end

		if self.description ~= nil and self.description ~= "" then
			output, cursor = proto.writeTag(output, cursor, 8, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.description)
		end

		if self.rsvp_count ~= nil and self.rsvp_count ~= 0 then
			output, cursor = proto.writeTag(output, cursor, 9, proto.wireTypes.varint)
			output, cursor = proto.writeVarInt(output, cursor, self.rsvp_count)
		end

		if self.place_id ~= nil and self.place_id ~= "" then
			output, cursor = proto.writeTag(output, cursor, 10, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.place_id)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _EventDataImpl.decode(input: buffer): EventData
		local self = _EventDataImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				if field == 6 then
					local value
					value, cursor = proto.readVarInt(input, cursor)
					self.user_rsvp = value ~= 0
					continue
				elseif field == 7 then
					local value
					value, cursor = proto.readVarIntI64(input, cursor)
					self.media_asset_id = value
					continue
				elseif field == 9 then
					local value
					value, cursor = proto.readVarIntI64(input, cursor)
					self.rsvp_count = value
					continue
				end

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.id = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.title = buffer.tostring(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.subtitle = buffer.tostring(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.event_start = buffer.tostring(value)
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.event_end = buffer.tostring(value)
					continue
				elseif field == 8 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.description = buffer.tostring(value)
					continue
				elseif field == 10 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.place_id = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _EventDataImpl.jsonEncode(self: EventData): any
		local output = {}

		if self.id ~= nil and self.id ~= "" then
			output.id = self.id
		end

		if self.title ~= nil and self.title ~= "" then
			output.title = self.title
		end

		if self.subtitle ~= nil and self.subtitle ~= "" then
			output.subtitle = self.subtitle
		end

		if self.event_start ~= nil and self.event_start ~= "" then
			output.eventStart = self.event_start
		end

		if self.event_end ~= nil and self.event_end ~= "" then
			output.eventEnd = self.event_end
		end

		if self.user_rsvp then
			output.userRsvp = self.user_rsvp
		end

		if self.media_asset_id ~= nil and self.media_asset_id ~= 0 then
			output.mediaAssetId = self.media_asset_id
		end

		if self.description ~= nil and self.description ~= "" then
			output.description = self.description
		end

		if self.rsvp_count ~= nil and self.rsvp_count ~= 0 then
			output.rsvpCount = self.rsvp_count
		end

		if self.place_id ~= nil and self.place_id ~= "" then
			output.placeId = self.place_id
		end

		return output
	end

	function _EventDataImpl.jsonDecode(input: { [string]: any }): EventData
		local self = _EventDataImpl.new()

		if input.id ~= nil then
			self.id = input.id
		end

		if input.title ~= nil then
			self.title = input.title
		end

		if input.subtitle ~= nil then
			self.subtitle = input.subtitle
		end

		if input.event_start ~= nil then
			self.event_start = input.event_start
		end

		if input.eventStart ~= nil then
			self.event_start = input.eventStart
		end

		if input.event_end ~= nil then
			self.event_end = input.event_end
		end

		if input.eventEnd ~= nil then
			self.event_end = input.eventEnd
		end

		if input.user_rsvp ~= nil then
			self.user_rsvp = input.user_rsvp
		end

		if input.userRsvp ~= nil then
			self.user_rsvp = input.userRsvp
		end

		if input.media_asset_id ~= nil then
			self.media_asset_id = input.media_asset_id
		end

		if input.mediaAssetId ~= nil then
			self.media_asset_id = input.mediaAssetId
		end

		if input.description ~= nil then
			self.description = input.description
		end

		if input.rsvp_count ~= nil then
			self.rsvp_count = input.rsvp_count
		end

		if input.rsvpCount ~= nil then
			self.rsvp_count = input.rsvpCount
		end

		if input.place_id ~= nil then
			self.place_id = input.place_id
		end

		if input.placeId ~= nil then
			self.place_id = input.placeId
		end

		return self
	end

	_EventDataImpl.descriptor = {
		name = "EventData",
		fullName = "roblox.apppageplatform.shared.v1beta1.EventData",
	}

	messages.EventData = _EventDataImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.EventData)
end

return {
	EventData = messages.EventData,
}
