--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	ExpandableTextSchema: _ExpandableTextSchemaMessage,
	ExpandableTextSchema_Props: _ExpandableTextSchema_PropsMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_prop_types = require(script.Parent.prop_types)
local _roblox_apppageplatform_shared_v1beta1_component_shared = require(script.Parent.component_shared)

type _ExpandableTextSchemaImpl = {
	__index: _ExpandableTextSchemaImpl,
	new: (fields: _ExpandableTextSchemaPartialFields?) -> ExpandableTextSchema,
	encode: (self: ExpandableTextSchema) -> buffer,
	decode: (input: buffer) -> ExpandableTextSchema,
	jsonEncode: (self: ExpandableTextSchema) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ExpandableTextSchema,
	descriptor: proto.Descriptor,
}

type _ExpandableTextSchemaFields = {
	props: ExpandableTextSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

type _ExpandableTextSchemaPartialFields = {
	props: ExpandableTextSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

export type ExpandableTextSchema = typeof(setmetatable(
	{} :: _ExpandableTextSchemaFields,
	{} :: _ExpandableTextSchemaImpl
))
type _ExpandableTextSchemaMessage = proto.Message<ExpandableTextSchema, _ExpandableTextSchemaPartialFields>

type _ExpandableTextSchema_PropsImpl = {
	__index: _ExpandableTextSchema_PropsImpl,
	new: (fields: _ExpandableTextSchema_PropsPartialFields?) -> ExpandableTextSchema_Props,
	encode: (self: ExpandableTextSchema_Props) -> buffer,
	decode: (input: buffer) -> ExpandableTextSchema_Props,
	jsonEncode: (self: ExpandableTextSchema_Props) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ExpandableTextSchema_Props,
	descriptor: proto.Descriptor,
}

type _ExpandableTextSchema_PropsFields = {
	text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	compact_number_of_lines: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	expanded_initially: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	anchor_point: _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop?,
	position: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	size: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
}

type _ExpandableTextSchema_PropsPartialFields = {
	text: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	compact_number_of_lines: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	expanded_initially: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	anchor_point: _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop?,
	position: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	size: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
}

export type ExpandableTextSchema_Props = typeof(setmetatable(
	{} :: _ExpandableTextSchema_PropsFields,
	{} :: _ExpandableTextSchema_PropsImpl
))
type _ExpandableTextSchema_PropsMessage = proto.Message<
	ExpandableTextSchema_Props,
	_ExpandableTextSchema_PropsPartialFields
>

do
	local _ExpandableTextSchemaImpl = {}
	_ExpandableTextSchemaImpl.__index = _ExpandableTextSchemaImpl

	function _ExpandableTextSchemaImpl.new(data: _ExpandableTextSchemaPartialFields?): ExpandableTextSchema
		return setmetatable({
			props = if data == nil or data.props == nil then nil else data.props,
			shared = if data == nil or data.shared == nil then nil else data.shared,
		}, _ExpandableTextSchemaImpl :: _ExpandableTextSchemaImpl)
	end

	function _ExpandableTextSchemaImpl.encode(self: ExpandableTextSchema): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.props ~= nil then
			local encoded = self.props:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.shared ~= nil then
			local encoded = self.shared:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ExpandableTextSchemaImpl.decode(input: buffer): ExpandableTextSchema
		local self = _ExpandableTextSchemaImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.props = messages.ExpandableTextSchema_Props.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.shared = _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ExpandableTextSchemaImpl.jsonEncode(self: ExpandableTextSchema): any
		local output = {}

		if self.props ~= nil then
			output.props = self.props:jsonEncode()
		end

		if self.shared ~= nil then
			output.shared = self.shared:jsonEncode()
		end

		return output
	end

	function _ExpandableTextSchemaImpl.jsonDecode(input: { [string]: any }): ExpandableTextSchema
		local self = _ExpandableTextSchemaImpl.new()

		if input.props ~= nil then
			self.props = messages.ExpandableTextSchema_Props.jsonDecode(input.props)
		end

		if input.shared ~= nil then
			self.shared =
				_roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.jsonDecode(input.shared)
		end

		return self
	end

	_ExpandableTextSchemaImpl.descriptor = {
		name = "ExpandableTextSchema",
		fullName = "roblox.apppageplatform.shared.v1beta1.ExpandableTextSchema",
	}

	messages.ExpandableTextSchema = _ExpandableTextSchemaImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ExpandableTextSchema)
end

do
	local _ExpandableTextSchema_PropsImpl = {}
	_ExpandableTextSchema_PropsImpl.__index = _ExpandableTextSchema_PropsImpl

	function _ExpandableTextSchema_PropsImpl.new(
		data: _ExpandableTextSchema_PropsPartialFields?
	): ExpandableTextSchema_Props
		return setmetatable({
			text = if data == nil or data.text == nil then nil else data.text,
			compact_number_of_lines = if data == nil or data.compact_number_of_lines == nil
				then nil
				else data.compact_number_of_lines,
			expanded_initially = if data == nil or data.expanded_initially == nil then nil else data.expanded_initially,
			layout_order = if data == nil or data.layout_order == nil then nil else data.layout_order,
			anchor_point = if data == nil or data.anchor_point == nil then nil else data.anchor_point,
			position = if data == nil or data.position == nil then nil else data.position,
			size = if data == nil or data.size == nil then nil else data.size,
		}, _ExpandableTextSchema_PropsImpl :: _ExpandableTextSchema_PropsImpl)
	end

	function _ExpandableTextSchema_PropsImpl.encode(self: ExpandableTextSchema_Props): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.text ~= nil then
			local encoded = self.text:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.compact_number_of_lines ~= nil then
			local encoded = self.compact_number_of_lines:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.expanded_initially ~= nil then
			local encoded = self.expanded_initially:encode()
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.layout_order ~= nil then
			local encoded = self.layout_order:encode()
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.anchor_point ~= nil then
			local encoded = self.anchor_point:encode()
			output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.position ~= nil then
			local encoded = self.position:encode()
			output, cursor = proto.writeTag(output, cursor, 6, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.size ~= nil then
			local encoded = self.size:encode()
			output, cursor = proto.writeTag(output, cursor, 7, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ExpandableTextSchema_PropsImpl.decode(input: buffer): ExpandableTextSchema_Props
		local self = _ExpandableTextSchema_PropsImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.compact_number_of_lines =
						_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.expanded_initially = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.layout_order = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.anchor_point = _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.decode(value)
					continue
				elseif field == 6 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.position = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.decode(value)
					continue
				elseif field == 7 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ExpandableTextSchema_PropsImpl.jsonEncode(self: ExpandableTextSchema_Props): any
		local output = {}

		if self.text ~= nil then
			output.text = self.text:jsonEncode()
		end

		if self.compact_number_of_lines ~= nil then
			output.compactNumberOfLines = self.compact_number_of_lines:jsonEncode()
		end

		if self.expanded_initially ~= nil then
			output.expandedInitially = self.expanded_initially:jsonEncode()
		end

		if self.layout_order ~= nil then
			output.layoutOrder = self.layout_order:jsonEncode()
		end

		if self.anchor_point ~= nil then
			output.anchorPoint = self.anchor_point:jsonEncode()
		end

		if self.position ~= nil then
			output.position = self.position:jsonEncode()
		end

		if self.size ~= nil then
			output.size = self.size:jsonEncode()
		end

		return output
	end

	function _ExpandableTextSchema_PropsImpl.jsonDecode(input: { [string]: any }): ExpandableTextSchema_Props
		local self = _ExpandableTextSchema_PropsImpl.new()

		if input.text ~= nil then
			self.text = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.text)
		end

		if input.compact_number_of_lines ~= nil then
			self.compact_number_of_lines =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.compact_number_of_lines)
		end

		if input.compactNumberOfLines ~= nil then
			self.compact_number_of_lines =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.compactNumberOfLines)
		end

		if input.expanded_initially ~= nil then
			self.expanded_initially =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.expanded_initially)
		end

		if input.expandedInitially ~= nil then
			self.expanded_initially =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.expandedInitially)
		end

		if input.layout_order ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layout_order)
		end

		if input.layoutOrder ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layoutOrder)
		end

		if input.anchor_point ~= nil then
			self.anchor_point =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.jsonDecode(input.anchor_point)
		end

		if input.anchorPoint ~= nil then
			self.anchor_point =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.jsonDecode(input.anchorPoint)
		end

		if input.position ~= nil then
			self.position = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.position)
		end

		if input.size ~= nil then
			self.size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.size)
		end

		return self
	end

	_ExpandableTextSchema_PropsImpl.descriptor = {
		name = "ExpandableTextSchema_Props",
		fullName = "roblox.apppageplatform.shared.v1beta1.Props",
	}

	messages.ExpandableTextSchema_Props = _ExpandableTextSchema_PropsImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ExpandableTextSchema_Props)
end

return {
	ExpandableTextSchema = messages.ExpandableTextSchema,
	ExpandableTextSchema_Props = messages.ExpandableTextSchema_Props,
}
