--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	ImageSchema: _ImageSchemaMessage,
	ImageSchema_Props: _ImageSchema_PropsMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_prop_types = require(script.Parent.prop_types)
local _roblox_apppageplatform_shared_v1beta1_actions = require(script.Parent.actions)
local _roblox_apppageplatform_shared_v1beta1_component_shared = require(script.Parent.component_shared)

type _ImageSchemaImpl = {
	__index: _ImageSchemaImpl,
	new: (fields: _ImageSchemaPartialFields?) -> ImageSchema,
	encode: (self: ImageSchema) -> buffer,
	decode: (input: buffer) -> ImageSchema,
	jsonEncode: (self: ImageSchema) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ImageSchema,
	descriptor: proto.Descriptor,
}

type _ImageSchemaFields = {
	props: ImageSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

type _ImageSchemaPartialFields = {
	props: ImageSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

export type ImageSchema = typeof(setmetatable({} :: _ImageSchemaFields, {} :: _ImageSchemaImpl))
type _ImageSchemaMessage = proto.Message<ImageSchema, _ImageSchemaPartialFields>

type _ImageSchema_PropsImpl = {
	__index: _ImageSchema_PropsImpl,
	new: (fields: _ImageSchema_PropsPartialFields?) -> ImageSchema_Props,
	encode: (self: ImageSchema_Props) -> buffer,
	decode: (input: buffer) -> ImageSchema_Props,
	jsonEncode: (self: ImageSchema_Props) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ImageSchema_Props,
	descriptor: proto.Descriptor,
}

type _ImageSchema_PropsFields = {
	anchor_point: _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop?,
	clips_descendants: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	position: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	size: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	image: _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp?,
	scale_type: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	resample_mode: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	tile_size: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	slice: _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp?,
	image_rect: _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp?,
	image_style: _roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp?,
}

type _ImageSchema_PropsPartialFields = {
	anchor_point: _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop?,
	clips_descendants: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	position: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	size: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
	image: _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp?,
	scale_type: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	resample_mode: _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp?,
	tile_size: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	slice: _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp?,
	image_rect: _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp?,
	image_style: _roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp?,
}

export type ImageSchema_Props = typeof(setmetatable({} :: _ImageSchema_PropsFields, {} :: _ImageSchema_PropsImpl))
type _ImageSchema_PropsMessage = proto.Message<ImageSchema_Props, _ImageSchema_PropsPartialFields>

do
	local _ImageSchemaImpl = {}
	_ImageSchemaImpl.__index = _ImageSchemaImpl

	function _ImageSchemaImpl.new(data: _ImageSchemaPartialFields?): ImageSchema
		return setmetatable({
			props = if data == nil or data.props == nil then nil else data.props,
			shared = if data == nil or data.shared == nil then nil else data.shared,
		}, _ImageSchemaImpl :: _ImageSchemaImpl)
	end

	function _ImageSchemaImpl.encode(self: ImageSchema): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.props ~= nil then
			local encoded = self.props:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.shared ~= nil then
			local encoded = self.shared:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ImageSchemaImpl.decode(input: buffer): ImageSchema
		local self = _ImageSchemaImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.props = messages.ImageSchema_Props.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.shared = _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ImageSchemaImpl.jsonEncode(self: ImageSchema): any
		local output = {}

		if self.props ~= nil then
			output.props = self.props:jsonEncode()
		end

		if self.shared ~= nil then
			output.shared = self.shared:jsonEncode()
		end

		return output
	end

	function _ImageSchemaImpl.jsonDecode(input: { [string]: any }): ImageSchema
		local self = _ImageSchemaImpl.new()

		if input.props ~= nil then
			self.props = messages.ImageSchema_Props.jsonDecode(input.props)
		end

		if input.shared ~= nil then
			self.shared =
				_roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.jsonDecode(input.shared)
		end

		return self
	end

	_ImageSchemaImpl.descriptor = {
		name = "ImageSchema",
		fullName = "roblox.apppageplatform.shared.v1beta1.ImageSchema",
	}

	messages.ImageSchema = _ImageSchemaImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ImageSchema)
end

do
	local _ImageSchema_PropsImpl = {}
	_ImageSchema_PropsImpl.__index = _ImageSchema_PropsImpl

	function _ImageSchema_PropsImpl.new(data: _ImageSchema_PropsPartialFields?): ImageSchema_Props
		return setmetatable({
			anchor_point = if data == nil or data.anchor_point == nil then nil else data.anchor_point,
			clips_descendants = if data == nil or data.clips_descendants == nil then nil else data.clips_descendants,
			layout_order = if data == nil or data.layout_order == nil then nil else data.layout_order,
			position = if data == nil or data.position == nil then nil else data.position,
			size = if data == nil or data.size == nil then nil else data.size,
			on_activated = if data == nil or data.on_activated == nil then nil else data.on_activated,
			image = if data == nil or data.image == nil then nil else data.image,
			scale_type = if data == nil or data.scale_type == nil then nil else data.scale_type,
			resample_mode = if data == nil or data.resample_mode == nil then nil else data.resample_mode,
			tile_size = if data == nil or data.tile_size == nil then nil else data.tile_size,
			slice = if data == nil or data.slice == nil then nil else data.slice,
			image_rect = if data == nil or data.image_rect == nil then nil else data.image_rect,
			image_style = if data == nil or data.image_style == nil then nil else data.image_style,
		}, _ImageSchema_PropsImpl :: _ImageSchema_PropsImpl)
	end

	function _ImageSchema_PropsImpl.encode(self: ImageSchema_Props): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.anchor_point ~= nil then
			local encoded = self.anchor_point:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.clips_descendants ~= nil then
			local encoded = self.clips_descendants:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.layout_order ~= nil then
			local encoded = self.layout_order:encode()
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.position ~= nil then
			local encoded = self.position:encode()
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.size ~= nil then
			local encoded = self.size:encode()
			output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.on_activated ~= nil then
			local encoded = self.on_activated:encode()
			output, cursor = proto.writeTag(output, cursor, 6, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.image ~= nil then
			local encoded = self.image:encode()
			output, cursor = proto.writeTag(output, cursor, 7, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.scale_type ~= nil then
			local encoded = self.scale_type:encode()
			output, cursor = proto.writeTag(output, cursor, 8, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.resample_mode ~= nil then
			local encoded = self.resample_mode:encode()
			output, cursor = proto.writeTag(output, cursor, 9, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.tile_size ~= nil then
			local encoded = self.tile_size:encode()
			output, cursor = proto.writeTag(output, cursor, 10, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.slice ~= nil then
			local encoded = self.slice:encode()
			output, cursor = proto.writeTag(output, cursor, 11, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.image_rect ~= nil then
			local encoded = self.image_rect:encode()
			output, cursor = proto.writeTag(output, cursor, 12, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.image_style ~= nil then
			local encoded = self.image_style:encode()
			output, cursor = proto.writeTag(output, cursor, 13, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ImageSchema_PropsImpl.decode(input: buffer): ImageSchema_Props
		local self = _ImageSchema_PropsImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.anchor_point = _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.clips_descendants = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.layout_order = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.position = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.decode(value)
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.decode(value)
					continue
				elseif field == 6 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				elseif field == 7 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image = _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp.decode(value)
					continue
				elseif field == 8 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.scale_type = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 9 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.resample_mode = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.decode(value)
					continue
				elseif field == 10 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.tile_size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.decode(value)
					continue
				elseif field == 11 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.slice = _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp.decode(value)
					continue
				elseif field == 12 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image_rect = _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp.decode(value)
					continue
				elseif field == 13 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.image_style = _roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ImageSchema_PropsImpl.jsonEncode(self: ImageSchema_Props): any
		local output = {}

		if self.anchor_point ~= nil then
			output.anchorPoint = self.anchor_point:jsonEncode()
		end

		if self.clips_descendants ~= nil then
			output.clipsDescendants = self.clips_descendants:jsonEncode()
		end

		if self.layout_order ~= nil then
			output.layoutOrder = self.layout_order:jsonEncode()
		end

		if self.position ~= nil then
			output.position = self.position:jsonEncode()
		end

		if self.size ~= nil then
			output.size = self.size:jsonEncode()
		end

		if self.on_activated ~= nil then
			output.onActivated = self.on_activated:jsonEncode()
		end

		if self.image ~= nil then
			output.image = self.image:jsonEncode()
		end

		if self.scale_type ~= nil then
			output.scaleType = self.scale_type:jsonEncode()
		end

		if self.resample_mode ~= nil then
			output.resampleMode = self.resample_mode:jsonEncode()
		end

		if self.tile_size ~= nil then
			output.tileSize = self.tile_size:jsonEncode()
		end

		if self.slice ~= nil then
			output.slice = self.slice:jsonEncode()
		end

		if self.image_rect ~= nil then
			output.imageRect = self.image_rect:jsonEncode()
		end

		if self.image_style ~= nil then
			output.imageStyle = self.image_style:jsonEncode()
		end

		return output
	end

	function _ImageSchema_PropsImpl.jsonDecode(input: { [string]: any }): ImageSchema_Props
		local self = _ImageSchema_PropsImpl.new()

		if input.anchor_point ~= nil then
			self.anchor_point =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.jsonDecode(input.anchor_point)
		end

		if input.anchorPoint ~= nil then
			self.anchor_point =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.jsonDecode(input.anchorPoint)
		end

		if input.clips_descendants ~= nil then
			self.clips_descendants =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.clips_descendants)
		end

		if input.clipsDescendants ~= nil then
			self.clips_descendants =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.clipsDescendants)
		end

		if input.layout_order ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layout_order)
		end

		if input.layoutOrder ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layoutOrder)
		end

		if input.position ~= nil then
			self.position = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.position)
		end

		if input.size ~= nil then
			self.size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.size)
		end

		if input.on_activated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.on_activated)
		end

		if input.onActivated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.onActivated)
		end

		if input.image ~= nil then
			self.image = _roblox_apppageplatform_shared_v1beta1_prop_types.ImageStringProp.jsonDecode(input.image)
		end

		if input.scale_type ~= nil then
			self.scale_type = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.scale_type)
		end

		if input.scaleType ~= nil then
			self.scale_type = _roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.scaleType)
		end

		if input.resample_mode ~= nil then
			self.resample_mode =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.resample_mode)
		end

		if input.resampleMode ~= nil then
			self.resample_mode =
				_roblox_apppageplatform_shared_v1beta1_prop_types.StringProp.jsonDecode(input.resampleMode)
		end

		if input.tile_size ~= nil then
			self.tile_size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.tile_size)
		end

		if input.tileSize ~= nil then
			self.tile_size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.tileSize)
		end

		if input.slice ~= nil then
			self.slice = _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp.jsonDecode(input.slice)
		end

		if input.image_rect ~= nil then
			self.image_rect = _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp.jsonDecode(input.image_rect)
		end

		if input.imageRect ~= nil then
			self.image_rect = _roblox_apppageplatform_shared_v1beta1_prop_types.StructProp.jsonDecode(input.imageRect)
		end

		if input.image_style ~= nil then
			self.image_style = _roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp.jsonDecode(input.image_style)
		end

		if input.imageStyle ~= nil then
			self.image_style = _roblox_apppageplatform_shared_v1beta1_prop_types.ColorProp.jsonDecode(input.imageStyle)
		end

		return self
	end

	_ImageSchema_PropsImpl.descriptor = {
		name = "ImageSchema_Props",
		fullName = "roblox.apppageplatform.shared.v1beta1.Props",
	}

	messages.ImageSchema_Props = _ImageSchema_PropsImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ImageSchema_Props)
end

return {
	ImageSchema = messages.ImageSchema,
	ImageSchema_Props = messages.ImageSchema_Props,
}
