--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	MarketplaceAssetData: _MarketplaceAssetDataMessage,
}
local messages: _Messages = {} :: _Messages

type _MarketplaceAssetDataImpl = {
	__index: _MarketplaceAssetDataImpl,
	new: (fields: _MarketplaceAssetDataPartialFields?) -> MarketplaceAssetData,
	encode: (self: MarketplaceAssetData) -> buffer,
	decode: (input: buffer) -> MarketplaceAssetData,
	jsonEncode: (self: MarketplaceAssetData) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> MarketplaceAssetData,
	descriptor: proto.Descriptor,
}

type _MarketplaceAssetDataFields = {
	id: string,
}

type _MarketplaceAssetDataPartialFields = {
	id: string?,
}

export type MarketplaceAssetData = typeof(setmetatable(
	{} :: _MarketplaceAssetDataFields,
	{} :: _MarketplaceAssetDataImpl
))
type _MarketplaceAssetDataMessage = proto.Message<MarketplaceAssetData, _MarketplaceAssetDataPartialFields>

do
	local _MarketplaceAssetDataImpl = {}
	_MarketplaceAssetDataImpl.__index = _MarketplaceAssetDataImpl

	function _MarketplaceAssetDataImpl.new(data: _MarketplaceAssetDataPartialFields?): MarketplaceAssetData
		return setmetatable({
			id = if data == nil or data.id == nil then "" else data.id,
		}, _MarketplaceAssetDataImpl :: _MarketplaceAssetDataImpl)
	end

	function _MarketplaceAssetDataImpl.encode(self: MarketplaceAssetData): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.id ~= nil and self.id ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.id)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _MarketplaceAssetDataImpl.decode(input: buffer): MarketplaceAssetData
		local self = _MarketplaceAssetDataImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.id = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _MarketplaceAssetDataImpl.jsonEncode(self: MarketplaceAssetData): any
		local output = {}

		if self.id ~= nil and self.id ~= "" then
			output.id = self.id
		end

		return output
	end

	function _MarketplaceAssetDataImpl.jsonDecode(input: { [string]: any }): MarketplaceAssetData
		local self = _MarketplaceAssetDataImpl.new()

		if input.id ~= nil then
			self.id = input.id
		end

		return self
	end

	_MarketplaceAssetDataImpl.descriptor = {
		name = "MarketplaceAssetData",
		fullName = "roblox.apppageplatform.shared.v1beta1.MarketplaceAssetData",
	}

	messages.MarketplaceAssetData = _MarketplaceAssetDataImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.MarketplaceAssetData)
end

return {
	MarketplaceAssetData = messages.MarketplaceAssetData,
}
