--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	SongData: _SongDataMessage,
}
local messages: _Messages = {} :: _Messages

type _SongDataImpl = {
	__index: _SongDataImpl,
	new: (fields: _SongDataPartialFields?) -> SongData,
	encode: (self: SongData) -> buffer,
	decode: (input: buffer) -> SongData,
	jsonEncode: (self: SongData) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> SongData,
	descriptor: proto.Descriptor,
}

type _SongDataFields = {
	id: string,
	media_asset_id: string,
	title: string,
	artist: string,
}

type _SongDataPartialFields = {
	id: string?,
	media_asset_id: string?,
	title: string?,
	artist: string?,
}

export type SongData = typeof(setmetatable({} :: _SongDataFields, {} :: _SongDataImpl))
type _SongDataMessage = proto.Message<SongData, _SongDataPartialFields>

do
	local _SongDataImpl = {}
	_SongDataImpl.__index = _SongDataImpl

	function _SongDataImpl.new(data: _SongDataPartialFields?): SongData
		return setmetatable({
			id = if data == nil or data.id == nil then "" else data.id,
			media_asset_id = if data == nil or data.media_asset_id == nil then "" else data.media_asset_id,
			title = if data == nil or data.title == nil then "" else data.title,
			artist = if data == nil or data.artist == nil then "" else data.artist,
		}, _SongDataImpl :: _SongDataImpl)
	end

	function _SongDataImpl.encode(self: SongData): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.id ~= nil and self.id ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.id)
		end

		if self.media_asset_id ~= nil and self.media_asset_id ~= "" then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.media_asset_id)
		end

		if self.title ~= nil and self.title ~= "" then
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.title)
		end

		if self.artist ~= nil and self.artist ~= "" then
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.artist)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _SongDataImpl.decode(input: buffer): SongData
		local self = _SongDataImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.id = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.media_asset_id = buffer.tostring(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.title = buffer.tostring(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.artist = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _SongDataImpl.jsonEncode(self: SongData): any
		local output = {}

		if self.id ~= nil and self.id ~= "" then
			output.id = self.id
		end

		if self.media_asset_id ~= nil and self.media_asset_id ~= "" then
			output.mediaAssetId = self.media_asset_id
		end

		if self.title ~= nil and self.title ~= "" then
			output.title = self.title
		end

		if self.artist ~= nil and self.artist ~= "" then
			output.artist = self.artist
		end

		return output
	end

	function _SongDataImpl.jsonDecode(input: { [string]: any }): SongData
		local self = _SongDataImpl.new()

		if input.id ~= nil then
			self.id = input.id
		end

		if input.media_asset_id ~= nil then
			self.media_asset_id = input.media_asset_id
		end

		if input.mediaAssetId ~= nil then
			self.media_asset_id = input.mediaAssetId
		end

		if input.title ~= nil then
			self.title = input.title
		end

		if input.artist ~= nil then
			self.artist = input.artist
		end

		return self
	end

	_SongDataImpl.descriptor = {
		name = "SongData",
		fullName = "roblox.apppageplatform.shared.v1beta1.SongData",
	}

	messages.SongData = _SongDataImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.SongData)
end

return {
	SongData = messages.SongData,
}
