--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	UiComponentSchema: _UiComponentSchemaMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_tile = require(script.Parent.tile)
local _roblox_apppageplatform_shared_v1beta1_badge_tile = require(script.Parent.badge_tile)
local _roblox_apppageplatform_shared_v1beta1_game_tile = require(script.Parent.game_tile)
local _roblox_apppageplatform_shared_v1beta1_button = require(script.Parent.button)
local _roblox_apppageplatform_shared_v1beta1_image = require(script.Parent.image)
local _roblox_apppageplatform_shared_v1beta1_text = require(script.Parent.text)
local _roblox_apppageplatform_shared_v1beta1_view = require(script.Parent.view)
local _roblox_apppageplatform_shared_v1beta1_divider = require(script.Parent.divider)
local _roblox_apppageplatform_shared_v1beta1_dialog = require(script.Parent.dialog)
local _roblox_apppageplatform_shared_v1beta1_text_icon_row = require(script.Parent.text_icon_row)
local _roblox_apppageplatform_shared_v1beta1_text_pill = require(script.Parent.text_pill)
local _roblox_apppageplatform_shared_v1beta1_section_header = require(script.Parent.section_header)
local _roblox_apppageplatform_shared_v1beta1_slot_overlay = require(script.Parent.slot_overlay)
local _roblox_apppageplatform_shared_v1beta1_tile_footer = require(script.Parent.tile_footer)
local _roblox_apppageplatform_shared_v1beta1_attribution_row = require(script.Parent.attribution_row)
local _roblox_apppageplatform_shared_v1beta1_game_tile_active_friends_footer =
	require(script.Parent.game_tile_active_friends_footer)
local _roblox_apppageplatform_shared_v1beta1_hero_unit = require(script.Parent.hero_unit)
local _roblox_apppageplatform_shared_v1beta1_hold_to_play = require(script.Parent.hold_to_play)
local _roblox_apppageplatform_shared_v1beta1_play_button = require(script.Parent.play_button)
local _roblox_apppageplatform_shared_v1beta1_countdown_text_icon_row = require(script.Parent.countdown_text_icon_row)
local _roblox_apppageplatform_shared_v1beta1_collection_carousel = require(script.Parent.collection_carousel)
local _roblox_apppageplatform_shared_v1beta1_collection_grid = require(script.Parent.collection_grid)
local _roblox_apppageplatform_shared_v1beta1_single_item_collection = require(script.Parent.single_item_collection)
local _roblox_apppageplatform_shared_v1beta1_see_all_tile = require(script.Parent.see_all_tile)
local _roblox_apppageplatform_shared_v1beta1_focus_nav_actions = require(script.Parent.focus_nav_actions)
local _roblox_apppageplatform_shared_v1beta1_fragment = require(script.Parent.fragment)
local _roblox_apppageplatform_shared_v1beta1_vertical_feed = require(script.Parent.vertical_feed)
local _roblox_apppageplatform_shared_v1beta1_info_table = require(script.Parent.info_table)
local _roblox_apppageplatform_shared_v1beta1_info_table_cell = require(script.Parent.info_table_cell)
local _roblox_apppageplatform_shared_v1beta1_chip = require(script.Parent.chip)
local _roblox_apppageplatform_shared_v1beta1_dual_action_chip = require(script.Parent.dual_action_chip)
local _roblox_apppageplatform_shared_v1beta1_expandable_text = require(script.Parent.expandable_text)
local _roblox_apppageplatform_shared_v1beta1_associated_items_row = require(script.Parent.associated_items_row)
local _roblox_apppageplatform_shared_v1beta1_overflow_menu = require(script.Parent.overflow_menu)
local _roblox_apppageplatform_shared_v1beta1_details_page_image_header =
	require(script.Parent.details_page_image_header)
local _roblox_apppageplatform_shared_v1beta1_card = require(script.Parent.card)
local _roblox_apppageplatform_shared_v1beta1_tabs = require(script.Parent.tabs)
local _roblox_apppageplatform_shared_v1beta1_action_bar = require(script.Parent.action_bar)
local _roblox_apppageplatform_shared_v1beta1_catalog_virtualized_feed = require(script.Parent.catalog_virtualized_feed)
local _roblox_apppageplatform_shared_v1beta1_catalog_item_group = require(script.Parent.catalog_item_group)
local _roblox_apppageplatform_shared_v1beta1_catalog_item_carousel = require(script.Parent.catalog_item_carousel)
local _roblox_apppageplatform_shared_v1beta1_catalog_category_menu = require(script.Parent.catalog_category_menu)
local _roblox_apppageplatform_shared_v1beta1_icon = require(script.Parent.icon)
local _roblox_apppageplatform_shared_v1beta1_circle_icon = require(script.Parent.circle_icon)
local _roblox_apppageplatform_shared_v1beta1_content_rating_label = require(script.Parent.content_rating_label)
local _roblox_apppageplatform_shared_v1beta1_link_text = require(script.Parent.link_text)
local _roblox_apppageplatform_shared_v1beta1_media_gallery = require(script.Parent.media_gallery)
local _roblox_apppageplatform_shared_v1beta1_play_button_contextual_message =
	require(script.Parent.play_button_contextual_message)
local _roblox_apppageplatform_shared_v1beta1_content_row = require(script.Parent.content_row)
local _roblox_apppageplatform_shared_v1beta1_filter_pills_carousel = require(script.Parent.filter_pills_carousel)
local _roblox_apppageplatform_shared_v1beta1_coachmark = require(script.Parent.coachmark)

type _UiComponentSchemaImpl = {
	__index: _UiComponentSchemaImpl,
	new: (fields: _UiComponentSchemaPartialFields?) -> UiComponentSchema,
	encode: (self: UiComponentSchema) -> buffer,
	decode: (input: buffer) -> UiComponentSchema,
	jsonEncode: (self: UiComponentSchema) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> UiComponentSchema,
	descriptor: proto.Descriptor,
}

type _UiComponentSchemaFields = {
	kind: (
		{ type: "tile", value: _roblox_apppageplatform_shared_v1beta1_tile.TileSchema }
		| { type: "game_tile", value: _roblox_apppageplatform_shared_v1beta1_game_tile.GameTileSchema }
		| { type: "button", value: _roblox_apppageplatform_shared_v1beta1_button.ButtonSchema }
		| { type: "image", value: _roblox_apppageplatform_shared_v1beta1_image.ImageSchema }
		| { type: "text", value: _roblox_apppageplatform_shared_v1beta1_text.TextSchema }
		| { type: "view", value: _roblox_apppageplatform_shared_v1beta1_view.ViewSchema }
		| { type: "divider", value: _roblox_apppageplatform_shared_v1beta1_divider.DividerSchema }
		| { type: "dialog", value: _roblox_apppageplatform_shared_v1beta1_dialog.DialogSchema }
		| { type: "text_icon_row", value: _roblox_apppageplatform_shared_v1beta1_text_icon_row.TextIconRowSchema }
		| { type: "text_pill", value: _roblox_apppageplatform_shared_v1beta1_text_pill.TextPillSchema }
		| { type: "section_header", value: _roblox_apppageplatform_shared_v1beta1_section_header.SectionHeaderSchema }
		| { type: "slot_overlay", value: _roblox_apppageplatform_shared_v1beta1_slot_overlay.SlotOverlaySchema }
		| { type: "tile_footer", value: _roblox_apppageplatform_shared_v1beta1_tile_footer.TileFooterSchema }
		| { type: "attribution_row", value: _roblox_apppageplatform_shared_v1beta1_attribution_row.AttributionRowSchema }
		| {
			type: "game_tile_active_friends_footer",
			value: _roblox_apppageplatform_shared_v1beta1_game_tile_active_friends_footer.GameTileActiveFriendsFooterSchema,
		}
		| { type: "hero_unit", value: _roblox_apppageplatform_shared_v1beta1_hero_unit.HeroUnitSchema }
		| { type: "hold_to_play", value: _roblox_apppageplatform_shared_v1beta1_hold_to_play.HoldToPlaySchema }
		| { type: "play_button", value: _roblox_apppageplatform_shared_v1beta1_play_button.PlayButtonSchema }
		| {
			type: "countdown_text_icon_row",
			value: _roblox_apppageplatform_shared_v1beta1_countdown_text_icon_row.CountdownTextIconRowSchema,
		}
		| {
			type: "collection_carousel",
			value: _roblox_apppageplatform_shared_v1beta1_collection_carousel.CollectionCarouselSchema,
		}
		| { type: "collection_grid", value: _roblox_apppageplatform_shared_v1beta1_collection_grid.CollectionGridSchema }
		| {
			type: "single_item_collection",
			value: _roblox_apppageplatform_shared_v1beta1_single_item_collection.SingleItemCollectionSchema,
		}
		| { type: "see_all_tile", value: _roblox_apppageplatform_shared_v1beta1_see_all_tile.SeeAllTileSchema }
		| {
			type: "focus_nav_actions",
			value: _roblox_apppageplatform_shared_v1beta1_focus_nav_actions.FocusNavActionsSchema,
		}
		| { type: "fragment", value: _roblox_apppageplatform_shared_v1beta1_fragment.FragmentSchema }
		| { type: "badge_tile", value: _roblox_apppageplatform_shared_v1beta1_badge_tile.BadgeTileSchema }
		| { type: "vertical_feed", value: _roblox_apppageplatform_shared_v1beta1_vertical_feed.VerticalFeedSchema }
		| { type: "info_table", value: _roblox_apppageplatform_shared_v1beta1_info_table.InfoTableSchema }
		| { type: "info_table_cell", value: _roblox_apppageplatform_shared_v1beta1_info_table_cell.InfoTableCellSchema }
		| { type: "chip", value: _roblox_apppageplatform_shared_v1beta1_chip.ChipSchema }
		| {
			type: "dual_action_chip",
			value: _roblox_apppageplatform_shared_v1beta1_dual_action_chip.DualActionChipSchema,
		}
		| { type: "expandable_text", value: _roblox_apppageplatform_shared_v1beta1_expandable_text.ExpandableTextSchema }
		| {
			type: "associated_items_row",
			value: _roblox_apppageplatform_shared_v1beta1_associated_items_row.AssociatedItemsRowSchema,
		}
		| { type: "overflow_menu", value: _roblox_apppageplatform_shared_v1beta1_overflow_menu.OverflowMenuSchema }
		| {
			type: "details_page_image_header",
			value: _roblox_apppageplatform_shared_v1beta1_details_page_image_header.DetailsPageImageHeaderSchema,
		}
		| { type: "card", value: _roblox_apppageplatform_shared_v1beta1_card.CardSchema }
		| { type: "tabs", value: _roblox_apppageplatform_shared_v1beta1_tabs.TabsSchema }
		| { type: "action_bar", value: _roblox_apppageplatform_shared_v1beta1_action_bar.ActionBarSchema }
		| {
			type: "catalog_virtualized_feed",
			value: _roblox_apppageplatform_shared_v1beta1_catalog_virtualized_feed.CatalogVirtualizedFeedSchema,
		}
		| {
			type: "catalog_item_group",
			value: _roblox_apppageplatform_shared_v1beta1_catalog_item_group.CatalogItemGroupSchema,
		}
		| {
			type: "catalog_item_carousel",
			value: _roblox_apppageplatform_shared_v1beta1_catalog_item_carousel.CatalogItemCarouselSchema,
		}
		| {
			type: "catalog_category_menu",
			value: _roblox_apppageplatform_shared_v1beta1_catalog_category_menu.CatalogCategoryMenuSchema,
		}
		| { type: "icon", value: _roblox_apppageplatform_shared_v1beta1_icon.IconSchema }
		| { type: "circle_icon", value: _roblox_apppageplatform_shared_v1beta1_circle_icon.CircleIconSchema }
		| {
			type: "content_rating_label",
			value: _roblox_apppageplatform_shared_v1beta1_content_rating_label.ContentRatingLabelSchema,
		}
		| {
			type: "play_button_contextual_message",
			value: _roblox_apppageplatform_shared_v1beta1_play_button_contextual_message.PlayButtonContextualMessageSchema,
		}
		| { type: "media_gallery", value: _roblox_apppageplatform_shared_v1beta1_media_gallery.MediaGallerySchema }
		| { type: "content_row", value: _roblox_apppageplatform_shared_v1beta1_content_row.ContentRowSchema }
		| { type: "link_text", value: _roblox_apppageplatform_shared_v1beta1_link_text.LinkTextSchema }
		| {
			type: "filter_pills_carousel",
			value: _roblox_apppageplatform_shared_v1beta1_filter_pills_carousel.FilterPillsCarouselSchema,
		}
		| { type: "coachmark", value: _roblox_apppageplatform_shared_v1beta1_coachmark.CoachmarkSchema }
	)?,
}

type _UiComponentSchemaPartialFields = {
	kind: (
		{ type: "tile", value: _roblox_apppageplatform_shared_v1beta1_tile.TileSchema }
		| { type: "game_tile", value: _roblox_apppageplatform_shared_v1beta1_game_tile.GameTileSchema }
		| { type: "button", value: _roblox_apppageplatform_shared_v1beta1_button.ButtonSchema }
		| { type: "image", value: _roblox_apppageplatform_shared_v1beta1_image.ImageSchema }
		| { type: "text", value: _roblox_apppageplatform_shared_v1beta1_text.TextSchema }
		| { type: "view", value: _roblox_apppageplatform_shared_v1beta1_view.ViewSchema }
		| { type: "divider", value: _roblox_apppageplatform_shared_v1beta1_divider.DividerSchema }
		| { type: "dialog", value: _roblox_apppageplatform_shared_v1beta1_dialog.DialogSchema }
		| { type: "text_icon_row", value: _roblox_apppageplatform_shared_v1beta1_text_icon_row.TextIconRowSchema }
		| { type: "text_pill", value: _roblox_apppageplatform_shared_v1beta1_text_pill.TextPillSchema }
		| { type: "section_header", value: _roblox_apppageplatform_shared_v1beta1_section_header.SectionHeaderSchema }
		| { type: "slot_overlay", value: _roblox_apppageplatform_shared_v1beta1_slot_overlay.SlotOverlaySchema }
		| { type: "tile_footer", value: _roblox_apppageplatform_shared_v1beta1_tile_footer.TileFooterSchema }
		| { type: "attribution_row", value: _roblox_apppageplatform_shared_v1beta1_attribution_row.AttributionRowSchema }
		| {
			type: "game_tile_active_friends_footer",
			value: _roblox_apppageplatform_shared_v1beta1_game_tile_active_friends_footer.GameTileActiveFriendsFooterSchema,
		}
		| { type: "hero_unit", value: _roblox_apppageplatform_shared_v1beta1_hero_unit.HeroUnitSchema }
		| { type: "hold_to_play", value: _roblox_apppageplatform_shared_v1beta1_hold_to_play.HoldToPlaySchema }
		| { type: "play_button", value: _roblox_apppageplatform_shared_v1beta1_play_button.PlayButtonSchema }
		| {
			type: "countdown_text_icon_row",
			value: _roblox_apppageplatform_shared_v1beta1_countdown_text_icon_row.CountdownTextIconRowSchema,
		}
		| {
			type: "collection_carousel",
			value: _roblox_apppageplatform_shared_v1beta1_collection_carousel.CollectionCarouselSchema,
		}
		| { type: "collection_grid", value: _roblox_apppageplatform_shared_v1beta1_collection_grid.CollectionGridSchema }
		| {
			type: "single_item_collection",
			value: _roblox_apppageplatform_shared_v1beta1_single_item_collection.SingleItemCollectionSchema,
		}
		| { type: "see_all_tile", value: _roblox_apppageplatform_shared_v1beta1_see_all_tile.SeeAllTileSchema }
		| {
			type: "focus_nav_actions",
			value: _roblox_apppageplatform_shared_v1beta1_focus_nav_actions.FocusNavActionsSchema,
		}
		| { type: "fragment", value: _roblox_apppageplatform_shared_v1beta1_fragment.FragmentSchema }
		| { type: "badge_tile", value: _roblox_apppageplatform_shared_v1beta1_badge_tile.BadgeTileSchema }
		| { type: "vertical_feed", value: _roblox_apppageplatform_shared_v1beta1_vertical_feed.VerticalFeedSchema }
		| { type: "info_table", value: _roblox_apppageplatform_shared_v1beta1_info_table.InfoTableSchema }
		| { type: "info_table_cell", value: _roblox_apppageplatform_shared_v1beta1_info_table_cell.InfoTableCellSchema }
		| { type: "chip", value: _roblox_apppageplatform_shared_v1beta1_chip.ChipSchema }
		| {
			type: "dual_action_chip",
			value: _roblox_apppageplatform_shared_v1beta1_dual_action_chip.DualActionChipSchema,
		}
		| { type: "expandable_text", value: _roblox_apppageplatform_shared_v1beta1_expandable_text.ExpandableTextSchema }
		| {
			type: "associated_items_row",
			value: _roblox_apppageplatform_shared_v1beta1_associated_items_row.AssociatedItemsRowSchema,
		}
		| { type: "overflow_menu", value: _roblox_apppageplatform_shared_v1beta1_overflow_menu.OverflowMenuSchema }
		| {
			type: "details_page_image_header",
			value: _roblox_apppageplatform_shared_v1beta1_details_page_image_header.DetailsPageImageHeaderSchema,
		}
		| { type: "card", value: _roblox_apppageplatform_shared_v1beta1_card.CardSchema }
		| { type: "tabs", value: _roblox_apppageplatform_shared_v1beta1_tabs.TabsSchema }
		| { type: "action_bar", value: _roblox_apppageplatform_shared_v1beta1_action_bar.ActionBarSchema }
		| {
			type: "catalog_virtualized_feed",
			value: _roblox_apppageplatform_shared_v1beta1_catalog_virtualized_feed.CatalogVirtualizedFeedSchema,
		}
		| {
			type: "catalog_item_group",
			value: _roblox_apppageplatform_shared_v1beta1_catalog_item_group.CatalogItemGroupSchema,
		}
		| {
			type: "catalog_item_carousel",
			value: _roblox_apppageplatform_shared_v1beta1_catalog_item_carousel.CatalogItemCarouselSchema,
		}
		| {
			type: "catalog_category_menu",
			value: _roblox_apppageplatform_shared_v1beta1_catalog_category_menu.CatalogCategoryMenuSchema,
		}
		| { type: "icon", value: _roblox_apppageplatform_shared_v1beta1_icon.IconSchema }
		| { type: "circle_icon", value: _roblox_apppageplatform_shared_v1beta1_circle_icon.CircleIconSchema }
		| {
			type: "content_rating_label",
			value: _roblox_apppageplatform_shared_v1beta1_content_rating_label.ContentRatingLabelSchema,
		}
		| {
			type: "play_button_contextual_message",
			value: _roblox_apppageplatform_shared_v1beta1_play_button_contextual_message.PlayButtonContextualMessageSchema,
		}
		| { type: "media_gallery", value: _roblox_apppageplatform_shared_v1beta1_media_gallery.MediaGallerySchema }
		| { type: "content_row", value: _roblox_apppageplatform_shared_v1beta1_content_row.ContentRowSchema }
		| { type: "link_text", value: _roblox_apppageplatform_shared_v1beta1_link_text.LinkTextSchema }
		| {
			type: "filter_pills_carousel",
			value: _roblox_apppageplatform_shared_v1beta1_filter_pills_carousel.FilterPillsCarouselSchema,
		}
		| { type: "coachmark", value: _roblox_apppageplatform_shared_v1beta1_coachmark.CoachmarkSchema }
	)?,
}

export type UiComponentSchema = typeof(setmetatable({} :: _UiComponentSchemaFields, {} :: _UiComponentSchemaImpl))
type _UiComponentSchemaMessage = proto.Message<UiComponentSchema, _UiComponentSchemaPartialFields>

do
	local _UiComponentSchemaImpl = {}
	_UiComponentSchemaImpl.__index = _UiComponentSchemaImpl

	function _UiComponentSchemaImpl.new(data: _UiComponentSchemaPartialFields?): UiComponentSchema
		return setmetatable({
			kind = if data == nil or data.kind == nil then nil else data.kind,
		}, _UiComponentSchemaImpl :: _UiComponentSchemaImpl)
	end

	function _UiComponentSchemaImpl.encode(self: UiComponentSchema): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.kind ~= nil then
			if self.kind.type == "tile" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "game_tile" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "button" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "image" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "text" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "view" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 6, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "divider" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 7, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "dialog" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 8, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "text_icon_row" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 9, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "text_pill" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 10, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "section_header" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 11, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "slot_overlay" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 12, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "tile_footer" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 13, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "attribution_row" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 14, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "game_tile_active_friends_footer" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 15, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "hero_unit" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 16, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "hold_to_play" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 17, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "play_button" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 18, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "countdown_text_icon_row" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 19, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "collection_carousel" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 20, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "collection_grid" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 21, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "single_item_collection" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 22, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "see_all_tile" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 23, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "focus_nav_actions" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 24, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "fragment" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 25, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "badge_tile" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 26, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "vertical_feed" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 27, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "info_table" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 28, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "info_table_cell" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 29, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "chip" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 30, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "dual_action_chip" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 31, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "expandable_text" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 32, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "associated_items_row" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 33, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "overflow_menu" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 34, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "details_page_image_header" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 35, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "card" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 36, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "tabs" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 37, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "action_bar" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 38, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "catalog_virtualized_feed" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 39, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "catalog_item_group" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 40, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "catalog_item_carousel" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 41, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "catalog_category_menu" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 42, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "icon" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 43, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "circle_icon" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 44, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "content_rating_label" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 45, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "play_button_contextual_message" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 46, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "media_gallery" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 47, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "content_row" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 48, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "link_text" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 49, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "filter_pills_carousel" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 50, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			elseif self.kind.type == "coachmark" then
				local encoded = self.kind.value:encode()
				output, cursor = proto.writeTag(output, cursor, 51, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			end
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _UiComponentSchemaImpl.decode(input: buffer): UiComponentSchema
		local self = _UiComponentSchemaImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind =
						{ type = "tile", value = _roblox_apppageplatform_shared_v1beta1_tile.TileSchema.decode(value) }
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "game_tile",
						value = _roblox_apppageplatform_shared_v1beta1_game_tile.GameTileSchema.decode(value),
					}
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "button",
						value = _roblox_apppageplatform_shared_v1beta1_button.ButtonSchema.decode(value),
					}
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "image",
						value = _roblox_apppageplatform_shared_v1beta1_image.ImageSchema.decode(value),
					}
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind =
						{ type = "text", value = _roblox_apppageplatform_shared_v1beta1_text.TextSchema.decode(value) }
					continue
				elseif field == 6 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind =
						{ type = "view", value = _roblox_apppageplatform_shared_v1beta1_view.ViewSchema.decode(value) }
					continue
				elseif field == 7 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "divider",
						value = _roblox_apppageplatform_shared_v1beta1_divider.DividerSchema.decode(value),
					}
					continue
				elseif field == 8 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "dialog",
						value = _roblox_apppageplatform_shared_v1beta1_dialog.DialogSchema.decode(value),
					}
					continue
				elseif field == 9 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "text_icon_row",
						value = _roblox_apppageplatform_shared_v1beta1_text_icon_row.TextIconRowSchema.decode(value),
					}
					continue
				elseif field == 10 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "text_pill",
						value = _roblox_apppageplatform_shared_v1beta1_text_pill.TextPillSchema.decode(value),
					}
					continue
				elseif field == 11 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "section_header",
						value = _roblox_apppageplatform_shared_v1beta1_section_header.SectionHeaderSchema.decode(value),
					}
					continue
				elseif field == 12 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "slot_overlay",
						value = _roblox_apppageplatform_shared_v1beta1_slot_overlay.SlotOverlaySchema.decode(value),
					}
					continue
				elseif field == 13 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "tile_footer",
						value = _roblox_apppageplatform_shared_v1beta1_tile_footer.TileFooterSchema.decode(value),
					}
					continue
				elseif field == 14 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "attribution_row",
						value = _roblox_apppageplatform_shared_v1beta1_attribution_row.AttributionRowSchema.decode(
							value
						),
					}
					continue
				elseif field == 15 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "game_tile_active_friends_footer",
						value = _roblox_apppageplatform_shared_v1beta1_game_tile_active_friends_footer.GameTileActiveFriendsFooterSchema.decode(
							value
						),
					}
					continue
				elseif field == 16 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "hero_unit",
						value = _roblox_apppageplatform_shared_v1beta1_hero_unit.HeroUnitSchema.decode(value),
					}
					continue
				elseif field == 17 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "hold_to_play",
						value = _roblox_apppageplatform_shared_v1beta1_hold_to_play.HoldToPlaySchema.decode(value),
					}
					continue
				elseif field == 18 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "play_button",
						value = _roblox_apppageplatform_shared_v1beta1_play_button.PlayButtonSchema.decode(value),
					}
					continue
				elseif field == 19 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "countdown_text_icon_row",
						value = _roblox_apppageplatform_shared_v1beta1_countdown_text_icon_row.CountdownTextIconRowSchema.decode(
							value
						),
					}
					continue
				elseif field == 20 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "collection_carousel",
						value = _roblox_apppageplatform_shared_v1beta1_collection_carousel.CollectionCarouselSchema.decode(
							value
						),
					}
					continue
				elseif field == 21 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "collection_grid",
						value = _roblox_apppageplatform_shared_v1beta1_collection_grid.CollectionGridSchema.decode(
							value
						),
					}
					continue
				elseif field == 22 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "single_item_collection",
						value = _roblox_apppageplatform_shared_v1beta1_single_item_collection.SingleItemCollectionSchema.decode(
							value
						),
					}
					continue
				elseif field == 23 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "see_all_tile",
						value = _roblox_apppageplatform_shared_v1beta1_see_all_tile.SeeAllTileSchema.decode(value),
					}
					continue
				elseif field == 24 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "focus_nav_actions",
						value = _roblox_apppageplatform_shared_v1beta1_focus_nav_actions.FocusNavActionsSchema.decode(
							value
						),
					}
					continue
				elseif field == 25 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "fragment",
						value = _roblox_apppageplatform_shared_v1beta1_fragment.FragmentSchema.decode(value),
					}
					continue
				elseif field == 26 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "badge_tile",
						value = _roblox_apppageplatform_shared_v1beta1_badge_tile.BadgeTileSchema.decode(value),
					}
					continue
				elseif field == 27 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "vertical_feed",
						value = _roblox_apppageplatform_shared_v1beta1_vertical_feed.VerticalFeedSchema.decode(value),
					}
					continue
				elseif field == 28 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "info_table",
						value = _roblox_apppageplatform_shared_v1beta1_info_table.InfoTableSchema.decode(value),
					}
					continue
				elseif field == 29 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "info_table_cell",
						value = _roblox_apppageplatform_shared_v1beta1_info_table_cell.InfoTableCellSchema.decode(
							value
						),
					}
					continue
				elseif field == 30 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind =
						{ type = "chip", value = _roblox_apppageplatform_shared_v1beta1_chip.ChipSchema.decode(value) }
					continue
				elseif field == 31 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "dual_action_chip",
						value = _roblox_apppageplatform_shared_v1beta1_dual_action_chip.DualActionChipSchema.decode(
							value
						),
					}
					continue
				elseif field == 32 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "expandable_text",
						value = _roblox_apppageplatform_shared_v1beta1_expandable_text.ExpandableTextSchema.decode(
							value
						),
					}
					continue
				elseif field == 33 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "associated_items_row",
						value = _roblox_apppageplatform_shared_v1beta1_associated_items_row.AssociatedItemsRowSchema.decode(
							value
						),
					}
					continue
				elseif field == 34 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "overflow_menu",
						value = _roblox_apppageplatform_shared_v1beta1_overflow_menu.OverflowMenuSchema.decode(value),
					}
					continue
				elseif field == 35 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "details_page_image_header",
						value = _roblox_apppageplatform_shared_v1beta1_details_page_image_header.DetailsPageImageHeaderSchema.decode(
							value
						),
					}
					continue
				elseif field == 36 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind =
						{ type = "card", value = _roblox_apppageplatform_shared_v1beta1_card.CardSchema.decode(value) }
					continue
				elseif field == 37 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind =
						{ type = "tabs", value = _roblox_apppageplatform_shared_v1beta1_tabs.TabsSchema.decode(value) }
					continue
				elseif field == 38 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "action_bar",
						value = _roblox_apppageplatform_shared_v1beta1_action_bar.ActionBarSchema.decode(value),
					}
					continue
				elseif field == 39 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "catalog_virtualized_feed",
						value = _roblox_apppageplatform_shared_v1beta1_catalog_virtualized_feed.CatalogVirtualizedFeedSchema.decode(
							value
						),
					}
					continue
				elseif field == 40 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "catalog_item_group",
						value = _roblox_apppageplatform_shared_v1beta1_catalog_item_group.CatalogItemGroupSchema.decode(
							value
						),
					}
					continue
				elseif field == 41 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "catalog_item_carousel",
						value = _roblox_apppageplatform_shared_v1beta1_catalog_item_carousel.CatalogItemCarouselSchema.decode(
							value
						),
					}
					continue
				elseif field == 42 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "catalog_category_menu",
						value = _roblox_apppageplatform_shared_v1beta1_catalog_category_menu.CatalogCategoryMenuSchema.decode(
							value
						),
					}
					continue
				elseif field == 43 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind =
						{ type = "icon", value = _roblox_apppageplatform_shared_v1beta1_icon.IconSchema.decode(value) }
					continue
				elseif field == 44 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "circle_icon",
						value = _roblox_apppageplatform_shared_v1beta1_circle_icon.CircleIconSchema.decode(value),
					}
					continue
				elseif field == 45 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "content_rating_label",
						value = _roblox_apppageplatform_shared_v1beta1_content_rating_label.ContentRatingLabelSchema.decode(
							value
						),
					}
					continue
				elseif field == 46 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "play_button_contextual_message",
						value = _roblox_apppageplatform_shared_v1beta1_play_button_contextual_message.PlayButtonContextualMessageSchema.decode(
							value
						),
					}
					continue
				elseif field == 47 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "media_gallery",
						value = _roblox_apppageplatform_shared_v1beta1_media_gallery.MediaGallerySchema.decode(value),
					}
					continue
				elseif field == 48 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "content_row",
						value = _roblox_apppageplatform_shared_v1beta1_content_row.ContentRowSchema.decode(value),
					}
					continue
				elseif field == 49 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "link_text",
						value = _roblox_apppageplatform_shared_v1beta1_link_text.LinkTextSchema.decode(value),
					}
					continue
				elseif field == 50 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "filter_pills_carousel",
						value = _roblox_apppageplatform_shared_v1beta1_filter_pills_carousel.FilterPillsCarouselSchema.decode(
							value
						),
					}
					continue
				elseif field == 51 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.kind = {
						type = "coachmark",
						value = _roblox_apppageplatform_shared_v1beta1_coachmark.CoachmarkSchema.decode(value),
					}
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _UiComponentSchemaImpl.jsonEncode(self: UiComponentSchema): any
		local output = {}

		if self.kind ~= nil then
			if self.kind.type == "tile" then
				output.tile = self.kind.value:jsonEncode()
			elseif self.kind.type == "game_tile" then
				output.gameTile = self.kind.value:jsonEncode()
			elseif self.kind.type == "button" then
				output.button = self.kind.value:jsonEncode()
			elseif self.kind.type == "image" then
				output.image = self.kind.value:jsonEncode()
			elseif self.kind.type == "text" then
				output.text = self.kind.value:jsonEncode()
			elseif self.kind.type == "view" then
				output.view = self.kind.value:jsonEncode()
			elseif self.kind.type == "divider" then
				output.divider = self.kind.value:jsonEncode()
			elseif self.kind.type == "dialog" then
				output.dialog = self.kind.value:jsonEncode()
			elseif self.kind.type == "text_icon_row" then
				output.textIconRow = self.kind.value:jsonEncode()
			elseif self.kind.type == "text_pill" then
				output.textPill = self.kind.value:jsonEncode()
			elseif self.kind.type == "section_header" then
				output.sectionHeader = self.kind.value:jsonEncode()
			elseif self.kind.type == "slot_overlay" then
				output.slotOverlay = self.kind.value:jsonEncode()
			elseif self.kind.type == "tile_footer" then
				output.tileFooter = self.kind.value:jsonEncode()
			elseif self.kind.type == "attribution_row" then
				output.attributionRow = self.kind.value:jsonEncode()
			elseif self.kind.type == "game_tile_active_friends_footer" then
				output.gameTileActiveFriendsFooter = self.kind.value:jsonEncode()
			elseif self.kind.type == "hero_unit" then
				output.heroUnit = self.kind.value:jsonEncode()
			elseif self.kind.type == "hold_to_play" then
				output.holdToPlay = self.kind.value:jsonEncode()
			elseif self.kind.type == "play_button" then
				output.playButton = self.kind.value:jsonEncode()
			elseif self.kind.type == "countdown_text_icon_row" then
				output.countdownTextIconRow = self.kind.value:jsonEncode()
			elseif self.kind.type == "collection_carousel" then
				output.collectionCarousel = self.kind.value:jsonEncode()
			elseif self.kind.type == "collection_grid" then
				output.collectionGrid = self.kind.value:jsonEncode()
			elseif self.kind.type == "single_item_collection" then
				output.singleItemCollection = self.kind.value:jsonEncode()
			elseif self.kind.type == "see_all_tile" then
				output.seeAllTile = self.kind.value:jsonEncode()
			elseif self.kind.type == "focus_nav_actions" then
				output.focusNavActions = self.kind.value:jsonEncode()
			elseif self.kind.type == "fragment" then
				output.fragment = self.kind.value:jsonEncode()
			elseif self.kind.type == "badge_tile" then
				output.badgeTile = self.kind.value:jsonEncode()
			elseif self.kind.type == "vertical_feed" then
				output.verticalFeed = self.kind.value:jsonEncode()
			elseif self.kind.type == "info_table" then
				output.infoTable = self.kind.value:jsonEncode()
			elseif self.kind.type == "info_table_cell" then
				output.infoTableCell = self.kind.value:jsonEncode()
			elseif self.kind.type == "chip" then
				output.chip = self.kind.value:jsonEncode()
			elseif self.kind.type == "dual_action_chip" then
				output.dualActionChip = self.kind.value:jsonEncode()
			elseif self.kind.type == "expandable_text" then
				output.expandableText = self.kind.value:jsonEncode()
			elseif self.kind.type == "associated_items_row" then
				output.associatedItemsRow = self.kind.value:jsonEncode()
			elseif self.kind.type == "overflow_menu" then
				output.overflowMenu = self.kind.value:jsonEncode()
			elseif self.kind.type == "details_page_image_header" then
				output.detailsPageImageHeader = self.kind.value:jsonEncode()
			elseif self.kind.type == "card" then
				output.card = self.kind.value:jsonEncode()
			elseif self.kind.type == "tabs" then
				output.tabs = self.kind.value:jsonEncode()
			elseif self.kind.type == "action_bar" then
				output.actionBar = self.kind.value:jsonEncode()
			elseif self.kind.type == "catalog_virtualized_feed" then
				output.catalogVirtualizedFeed = self.kind.value:jsonEncode()
			elseif self.kind.type == "catalog_item_group" then
				output.catalogItemGroup = self.kind.value:jsonEncode()
			elseif self.kind.type == "catalog_item_carousel" then
				output.catalogItemCarousel = self.kind.value:jsonEncode()
			elseif self.kind.type == "catalog_category_menu" then
				output.catalogCategoryMenu = self.kind.value:jsonEncode()
			elseif self.kind.type == "icon" then
				output.icon = self.kind.value:jsonEncode()
			elseif self.kind.type == "circle_icon" then
				output.circleIcon = self.kind.value:jsonEncode()
			elseif self.kind.type == "content_rating_label" then
				output.contentRatingLabel = self.kind.value:jsonEncode()
			elseif self.kind.type == "play_button_contextual_message" then
				output.playButtonContextualMessage = self.kind.value:jsonEncode()
			elseif self.kind.type == "media_gallery" then
				output.mediaGallery = self.kind.value:jsonEncode()
			elseif self.kind.type == "content_row" then
				output.contentRow = self.kind.value:jsonEncode()
			elseif self.kind.type == "link_text" then
				output.linkText = self.kind.value:jsonEncode()
			elseif self.kind.type == "filter_pills_carousel" then
				output.filterPillsCarousel = self.kind.value:jsonEncode()
			elseif self.kind.type == "coachmark" then
				output.coachmark = self.kind.value:jsonEncode()
			end
		end

		return output
	end

	function _UiComponentSchemaImpl.jsonDecode(input: { [string]: any }): UiComponentSchema
		local self = _UiComponentSchemaImpl.new()

		if input.tile ~= nil then
			self.kind =
				{ type = "tile", value = _roblox_apppageplatform_shared_v1beta1_tile.TileSchema.jsonDecode(input.tile) }
		end

		if input.game_tile ~= nil then
			self.kind = {
				type = "game_tile",
				value = _roblox_apppageplatform_shared_v1beta1_game_tile.GameTileSchema.jsonDecode(input.game_tile),
			}
		end

		if input.gameTile ~= nil then
			self.kind = {
				type = "game_tile",
				value = _roblox_apppageplatform_shared_v1beta1_game_tile.GameTileSchema.jsonDecode(input.gameTile),
			}
		end

		if input.button ~= nil then
			self.kind = {
				type = "button",
				value = _roblox_apppageplatform_shared_v1beta1_button.ButtonSchema.jsonDecode(input.button),
			}
		end

		if input.image ~= nil then
			self.kind = {
				type = "image",
				value = _roblox_apppageplatform_shared_v1beta1_image.ImageSchema.jsonDecode(input.image),
			}
		end

		if input.text ~= nil then
			self.kind =
				{ type = "text", value = _roblox_apppageplatform_shared_v1beta1_text.TextSchema.jsonDecode(input.text) }
		end

		if input.view ~= nil then
			self.kind =
				{ type = "view", value = _roblox_apppageplatform_shared_v1beta1_view.ViewSchema.jsonDecode(input.view) }
		end

		if input.divider ~= nil then
			self.kind = {
				type = "divider",
				value = _roblox_apppageplatform_shared_v1beta1_divider.DividerSchema.jsonDecode(input.divider),
			}
		end

		if input.dialog ~= nil then
			self.kind = {
				type = "dialog",
				value = _roblox_apppageplatform_shared_v1beta1_dialog.DialogSchema.jsonDecode(input.dialog),
			}
		end

		if input.text_icon_row ~= nil then
			self.kind = {
				type = "text_icon_row",
				value = _roblox_apppageplatform_shared_v1beta1_text_icon_row.TextIconRowSchema.jsonDecode(
					input.text_icon_row
				),
			}
		end

		if input.textIconRow ~= nil then
			self.kind = {
				type = "text_icon_row",
				value = _roblox_apppageplatform_shared_v1beta1_text_icon_row.TextIconRowSchema.jsonDecode(
					input.textIconRow
				),
			}
		end

		if input.text_pill ~= nil then
			self.kind = {
				type = "text_pill",
				value = _roblox_apppageplatform_shared_v1beta1_text_pill.TextPillSchema.jsonDecode(input.text_pill),
			}
		end

		if input.textPill ~= nil then
			self.kind = {
				type = "text_pill",
				value = _roblox_apppageplatform_shared_v1beta1_text_pill.TextPillSchema.jsonDecode(input.textPill),
			}
		end

		if input.section_header ~= nil then
			self.kind = {
				type = "section_header",
				value = _roblox_apppageplatform_shared_v1beta1_section_header.SectionHeaderSchema.jsonDecode(
					input.section_header
				),
			}
		end

		if input.sectionHeader ~= nil then
			self.kind = {
				type = "section_header",
				value = _roblox_apppageplatform_shared_v1beta1_section_header.SectionHeaderSchema.jsonDecode(
					input.sectionHeader
				),
			}
		end

		if input.slot_overlay ~= nil then
			self.kind = {
				type = "slot_overlay",
				value = _roblox_apppageplatform_shared_v1beta1_slot_overlay.SlotOverlaySchema.jsonDecode(
					input.slot_overlay
				),
			}
		end

		if input.slotOverlay ~= nil then
			self.kind = {
				type = "slot_overlay",
				value = _roblox_apppageplatform_shared_v1beta1_slot_overlay.SlotOverlaySchema.jsonDecode(
					input.slotOverlay
				),
			}
		end

		if input.tile_footer ~= nil then
			self.kind = {
				type = "tile_footer",
				value = _roblox_apppageplatform_shared_v1beta1_tile_footer.TileFooterSchema.jsonDecode(
					input.tile_footer
				),
			}
		end

		if input.tileFooter ~= nil then
			self.kind = {
				type = "tile_footer",
				value = _roblox_apppageplatform_shared_v1beta1_tile_footer.TileFooterSchema.jsonDecode(
					input.tileFooter
				),
			}
		end

		if input.attribution_row ~= nil then
			self.kind = {
				type = "attribution_row",
				value = _roblox_apppageplatform_shared_v1beta1_attribution_row.AttributionRowSchema.jsonDecode(
					input.attribution_row
				),
			}
		end

		if input.attributionRow ~= nil then
			self.kind = {
				type = "attribution_row",
				value = _roblox_apppageplatform_shared_v1beta1_attribution_row.AttributionRowSchema.jsonDecode(
					input.attributionRow
				),
			}
		end

		if input.game_tile_active_friends_footer ~= nil then
			self.kind = {
				type = "game_tile_active_friends_footer",
				value = _roblox_apppageplatform_shared_v1beta1_game_tile_active_friends_footer.GameTileActiveFriendsFooterSchema.jsonDecode(
					input.game_tile_active_friends_footer
				),
			}
		end

		if input.gameTileActiveFriendsFooter ~= nil then
			self.kind = {
				type = "game_tile_active_friends_footer",
				value = _roblox_apppageplatform_shared_v1beta1_game_tile_active_friends_footer.GameTileActiveFriendsFooterSchema.jsonDecode(
					input.gameTileActiveFriendsFooter
				),
			}
		end

		if input.hero_unit ~= nil then
			self.kind = {
				type = "hero_unit",
				value = _roblox_apppageplatform_shared_v1beta1_hero_unit.HeroUnitSchema.jsonDecode(input.hero_unit),
			}
		end

		if input.heroUnit ~= nil then
			self.kind = {
				type = "hero_unit",
				value = _roblox_apppageplatform_shared_v1beta1_hero_unit.HeroUnitSchema.jsonDecode(input.heroUnit),
			}
		end

		if input.hold_to_play ~= nil then
			self.kind = {
				type = "hold_to_play",
				value = _roblox_apppageplatform_shared_v1beta1_hold_to_play.HoldToPlaySchema.jsonDecode(
					input.hold_to_play
				),
			}
		end

		if input.holdToPlay ~= nil then
			self.kind = {
				type = "hold_to_play",
				value = _roblox_apppageplatform_shared_v1beta1_hold_to_play.HoldToPlaySchema.jsonDecode(
					input.holdToPlay
				),
			}
		end

		if input.play_button ~= nil then
			self.kind = {
				type = "play_button",
				value = _roblox_apppageplatform_shared_v1beta1_play_button.PlayButtonSchema.jsonDecode(
					input.play_button
				),
			}
		end

		if input.playButton ~= nil then
			self.kind = {
				type = "play_button",
				value = _roblox_apppageplatform_shared_v1beta1_play_button.PlayButtonSchema.jsonDecode(
					input.playButton
				),
			}
		end

		if input.countdown_text_icon_row ~= nil then
			self.kind = {
				type = "countdown_text_icon_row",
				value = _roblox_apppageplatform_shared_v1beta1_countdown_text_icon_row.CountdownTextIconRowSchema.jsonDecode(
					input.countdown_text_icon_row
				),
			}
		end

		if input.countdownTextIconRow ~= nil then
			self.kind = {
				type = "countdown_text_icon_row",
				value = _roblox_apppageplatform_shared_v1beta1_countdown_text_icon_row.CountdownTextIconRowSchema.jsonDecode(
					input.countdownTextIconRow
				),
			}
		end

		if input.collection_carousel ~= nil then
			self.kind = {
				type = "collection_carousel",
				value = _roblox_apppageplatform_shared_v1beta1_collection_carousel.CollectionCarouselSchema.jsonDecode(
					input.collection_carousel
				),
			}
		end

		if input.collectionCarousel ~= nil then
			self.kind = {
				type = "collection_carousel",
				value = _roblox_apppageplatform_shared_v1beta1_collection_carousel.CollectionCarouselSchema.jsonDecode(
					input.collectionCarousel
				),
			}
		end

		if input.collection_grid ~= nil then
			self.kind = {
				type = "collection_grid",
				value = _roblox_apppageplatform_shared_v1beta1_collection_grid.CollectionGridSchema.jsonDecode(
					input.collection_grid
				),
			}
		end

		if input.collectionGrid ~= nil then
			self.kind = {
				type = "collection_grid",
				value = _roblox_apppageplatform_shared_v1beta1_collection_grid.CollectionGridSchema.jsonDecode(
					input.collectionGrid
				),
			}
		end

		if input.single_item_collection ~= nil then
			self.kind = {
				type = "single_item_collection",
				value = _roblox_apppageplatform_shared_v1beta1_single_item_collection.SingleItemCollectionSchema.jsonDecode(
					input.single_item_collection
				),
			}
		end

		if input.singleItemCollection ~= nil then
			self.kind = {
				type = "single_item_collection",
				value = _roblox_apppageplatform_shared_v1beta1_single_item_collection.SingleItemCollectionSchema.jsonDecode(
					input.singleItemCollection
				),
			}
		end

		if input.see_all_tile ~= nil then
			self.kind = {
				type = "see_all_tile",
				value = _roblox_apppageplatform_shared_v1beta1_see_all_tile.SeeAllTileSchema.jsonDecode(
					input.see_all_tile
				),
			}
		end

		if input.seeAllTile ~= nil then
			self.kind = {
				type = "see_all_tile",
				value = _roblox_apppageplatform_shared_v1beta1_see_all_tile.SeeAllTileSchema.jsonDecode(
					input.seeAllTile
				),
			}
		end

		if input.focus_nav_actions ~= nil then
			self.kind = {
				type = "focus_nav_actions",
				value = _roblox_apppageplatform_shared_v1beta1_focus_nav_actions.FocusNavActionsSchema.jsonDecode(
					input.focus_nav_actions
				),
			}
		end

		if input.focusNavActions ~= nil then
			self.kind = {
				type = "focus_nav_actions",
				value = _roblox_apppageplatform_shared_v1beta1_focus_nav_actions.FocusNavActionsSchema.jsonDecode(
					input.focusNavActions
				),
			}
		end

		if input.fragment ~= nil then
			self.kind = {
				type = "fragment",
				value = _roblox_apppageplatform_shared_v1beta1_fragment.FragmentSchema.jsonDecode(input.fragment),
			}
		end

		if input.badge_tile ~= nil then
			self.kind = {
				type = "badge_tile",
				value = _roblox_apppageplatform_shared_v1beta1_badge_tile.BadgeTileSchema.jsonDecode(input.badge_tile),
			}
		end

		if input.badgeTile ~= nil then
			self.kind = {
				type = "badge_tile",
				value = _roblox_apppageplatform_shared_v1beta1_badge_tile.BadgeTileSchema.jsonDecode(input.badgeTile),
			}
		end

		if input.vertical_feed ~= nil then
			self.kind = {
				type = "vertical_feed",
				value = _roblox_apppageplatform_shared_v1beta1_vertical_feed.VerticalFeedSchema.jsonDecode(
					input.vertical_feed
				),
			}
		end

		if input.verticalFeed ~= nil then
			self.kind = {
				type = "vertical_feed",
				value = _roblox_apppageplatform_shared_v1beta1_vertical_feed.VerticalFeedSchema.jsonDecode(
					input.verticalFeed
				),
			}
		end

		if input.info_table ~= nil then
			self.kind = {
				type = "info_table",
				value = _roblox_apppageplatform_shared_v1beta1_info_table.InfoTableSchema.jsonDecode(input.info_table),
			}
		end

		if input.infoTable ~= nil then
			self.kind = {
				type = "info_table",
				value = _roblox_apppageplatform_shared_v1beta1_info_table.InfoTableSchema.jsonDecode(input.infoTable),
			}
		end

		if input.info_table_cell ~= nil then
			self.kind = {
				type = "info_table_cell",
				value = _roblox_apppageplatform_shared_v1beta1_info_table_cell.InfoTableCellSchema.jsonDecode(
					input.info_table_cell
				),
			}
		end

		if input.infoTableCell ~= nil then
			self.kind = {
				type = "info_table_cell",
				value = _roblox_apppageplatform_shared_v1beta1_info_table_cell.InfoTableCellSchema.jsonDecode(
					input.infoTableCell
				),
			}
		end

		if input.chip ~= nil then
			self.kind =
				{ type = "chip", value = _roblox_apppageplatform_shared_v1beta1_chip.ChipSchema.jsonDecode(input.chip) }
		end

		if input.dual_action_chip ~= nil then
			self.kind = {
				type = "dual_action_chip",
				value = _roblox_apppageplatform_shared_v1beta1_dual_action_chip.DualActionChipSchema.jsonDecode(
					input.dual_action_chip
				),
			}
		end

		if input.dualActionChip ~= nil then
			self.kind = {
				type = "dual_action_chip",
				value = _roblox_apppageplatform_shared_v1beta1_dual_action_chip.DualActionChipSchema.jsonDecode(
					input.dualActionChip
				),
			}
		end

		if input.expandable_text ~= nil then
			self.kind = {
				type = "expandable_text",
				value = _roblox_apppageplatform_shared_v1beta1_expandable_text.ExpandableTextSchema.jsonDecode(
					input.expandable_text
				),
			}
		end

		if input.expandableText ~= nil then
			self.kind = {
				type = "expandable_text",
				value = _roblox_apppageplatform_shared_v1beta1_expandable_text.ExpandableTextSchema.jsonDecode(
					input.expandableText
				),
			}
		end

		if input.associated_items_row ~= nil then
			self.kind = {
				type = "associated_items_row",
				value = _roblox_apppageplatform_shared_v1beta1_associated_items_row.AssociatedItemsRowSchema.jsonDecode(
					input.associated_items_row
				),
			}
		end

		if input.associatedItemsRow ~= nil then
			self.kind = {
				type = "associated_items_row",
				value = _roblox_apppageplatform_shared_v1beta1_associated_items_row.AssociatedItemsRowSchema.jsonDecode(
					input.associatedItemsRow
				),
			}
		end

		if input.overflow_menu ~= nil then
			self.kind = {
				type = "overflow_menu",
				value = _roblox_apppageplatform_shared_v1beta1_overflow_menu.OverflowMenuSchema.jsonDecode(
					input.overflow_menu
				),
			}
		end

		if input.overflowMenu ~= nil then
			self.kind = {
				type = "overflow_menu",
				value = _roblox_apppageplatform_shared_v1beta1_overflow_menu.OverflowMenuSchema.jsonDecode(
					input.overflowMenu
				),
			}
		end

		if input.details_page_image_header ~= nil then
			self.kind = {
				type = "details_page_image_header",
				value = _roblox_apppageplatform_shared_v1beta1_details_page_image_header.DetailsPageImageHeaderSchema.jsonDecode(
					input.details_page_image_header
				),
			}
		end

		if input.detailsPageImageHeader ~= nil then
			self.kind = {
				type = "details_page_image_header",
				value = _roblox_apppageplatform_shared_v1beta1_details_page_image_header.DetailsPageImageHeaderSchema.jsonDecode(
					input.detailsPageImageHeader
				),
			}
		end

		if input.card ~= nil then
			self.kind =
				{ type = "card", value = _roblox_apppageplatform_shared_v1beta1_card.CardSchema.jsonDecode(input.card) }
		end

		if input.tabs ~= nil then
			self.kind =
				{ type = "tabs", value = _roblox_apppageplatform_shared_v1beta1_tabs.TabsSchema.jsonDecode(input.tabs) }
		end

		if input.action_bar ~= nil then
			self.kind = {
				type = "action_bar",
				value = _roblox_apppageplatform_shared_v1beta1_action_bar.ActionBarSchema.jsonDecode(input.action_bar),
			}
		end

		if input.actionBar ~= nil then
			self.kind = {
				type = "action_bar",
				value = _roblox_apppageplatform_shared_v1beta1_action_bar.ActionBarSchema.jsonDecode(input.actionBar),
			}
		end

		if input.catalog_virtualized_feed ~= nil then
			self.kind = {
				type = "catalog_virtualized_feed",
				value = _roblox_apppageplatform_shared_v1beta1_catalog_virtualized_feed.CatalogVirtualizedFeedSchema.jsonDecode(
					input.catalog_virtualized_feed
				),
			}
		end

		if input.catalogVirtualizedFeed ~= nil then
			self.kind = {
				type = "catalog_virtualized_feed",
				value = _roblox_apppageplatform_shared_v1beta1_catalog_virtualized_feed.CatalogVirtualizedFeedSchema.jsonDecode(
					input.catalogVirtualizedFeed
				),
			}
		end

		if input.catalog_item_group ~= nil then
			self.kind = {
				type = "catalog_item_group",
				value = _roblox_apppageplatform_shared_v1beta1_catalog_item_group.CatalogItemGroupSchema.jsonDecode(
					input.catalog_item_group
				),
			}
		end

		if input.catalogItemGroup ~= nil then
			self.kind = {
				type = "catalog_item_group",
				value = _roblox_apppageplatform_shared_v1beta1_catalog_item_group.CatalogItemGroupSchema.jsonDecode(
					input.catalogItemGroup
				),
			}
		end

		if input.catalog_item_carousel ~= nil then
			self.kind = {
				type = "catalog_item_carousel",
				value = _roblox_apppageplatform_shared_v1beta1_catalog_item_carousel.CatalogItemCarouselSchema.jsonDecode(
					input.catalog_item_carousel
				),
			}
		end

		if input.catalogItemCarousel ~= nil then
			self.kind = {
				type = "catalog_item_carousel",
				value = _roblox_apppageplatform_shared_v1beta1_catalog_item_carousel.CatalogItemCarouselSchema.jsonDecode(
					input.catalogItemCarousel
				),
			}
		end

		if input.catalog_category_menu ~= nil then
			self.kind = {
				type = "catalog_category_menu",
				value = _roblox_apppageplatform_shared_v1beta1_catalog_category_menu.CatalogCategoryMenuSchema.jsonDecode(
					input.catalog_category_menu
				),
			}
		end

		if input.catalogCategoryMenu ~= nil then
			self.kind = {
				type = "catalog_category_menu",
				value = _roblox_apppageplatform_shared_v1beta1_catalog_category_menu.CatalogCategoryMenuSchema.jsonDecode(
					input.catalogCategoryMenu
				),
			}
		end

		if input.icon ~= nil then
			self.kind =
				{ type = "icon", value = _roblox_apppageplatform_shared_v1beta1_icon.IconSchema.jsonDecode(input.icon) }
		end

		if input.circle_icon ~= nil then
			self.kind = {
				type = "circle_icon",
				value = _roblox_apppageplatform_shared_v1beta1_circle_icon.CircleIconSchema.jsonDecode(
					input.circle_icon
				),
			}
		end

		if input.circleIcon ~= nil then
			self.kind = {
				type = "circle_icon",
				value = _roblox_apppageplatform_shared_v1beta1_circle_icon.CircleIconSchema.jsonDecode(
					input.circleIcon
				),
			}
		end

		if input.content_rating_label ~= nil then
			self.kind = {
				type = "content_rating_label",
				value = _roblox_apppageplatform_shared_v1beta1_content_rating_label.ContentRatingLabelSchema.jsonDecode(
					input.content_rating_label
				),
			}
		end

		if input.contentRatingLabel ~= nil then
			self.kind = {
				type = "content_rating_label",
				value = _roblox_apppageplatform_shared_v1beta1_content_rating_label.ContentRatingLabelSchema.jsonDecode(
					input.contentRatingLabel
				),
			}
		end

		if input.play_button_contextual_message ~= nil then
			self.kind = {
				type = "play_button_contextual_message",
				value = _roblox_apppageplatform_shared_v1beta1_play_button_contextual_message.PlayButtonContextualMessageSchema.jsonDecode(
					input.play_button_contextual_message
				),
			}
		end

		if input.playButtonContextualMessage ~= nil then
			self.kind = {
				type = "play_button_contextual_message",
				value = _roblox_apppageplatform_shared_v1beta1_play_button_contextual_message.PlayButtonContextualMessageSchema.jsonDecode(
					input.playButtonContextualMessage
				),
			}
		end

		if input.media_gallery ~= nil then
			self.kind = {
				type = "media_gallery",
				value = _roblox_apppageplatform_shared_v1beta1_media_gallery.MediaGallerySchema.jsonDecode(
					input.media_gallery
				),
			}
		end

		if input.mediaGallery ~= nil then
			self.kind = {
				type = "media_gallery",
				value = _roblox_apppageplatform_shared_v1beta1_media_gallery.MediaGallerySchema.jsonDecode(
					input.mediaGallery
				),
			}
		end

		if input.content_row ~= nil then
			self.kind = {
				type = "content_row",
				value = _roblox_apppageplatform_shared_v1beta1_content_row.ContentRowSchema.jsonDecode(
					input.content_row
				),
			}
		end

		if input.contentRow ~= nil then
			self.kind = {
				type = "content_row",
				value = _roblox_apppageplatform_shared_v1beta1_content_row.ContentRowSchema.jsonDecode(
					input.contentRow
				),
			}
		end

		if input.link_text ~= nil then
			self.kind = {
				type = "link_text",
				value = _roblox_apppageplatform_shared_v1beta1_link_text.LinkTextSchema.jsonDecode(input.link_text),
			}
		end

		if input.linkText ~= nil then
			self.kind = {
				type = "link_text",
				value = _roblox_apppageplatform_shared_v1beta1_link_text.LinkTextSchema.jsonDecode(input.linkText),
			}
		end

		if input.filter_pills_carousel ~= nil then
			self.kind = {
				type = "filter_pills_carousel",
				value = _roblox_apppageplatform_shared_v1beta1_filter_pills_carousel.FilterPillsCarouselSchema.jsonDecode(
					input.filter_pills_carousel
				),
			}
		end

		if input.filterPillsCarousel ~= nil then
			self.kind = {
				type = "filter_pills_carousel",
				value = _roblox_apppageplatform_shared_v1beta1_filter_pills_carousel.FilterPillsCarouselSchema.jsonDecode(
					input.filterPillsCarousel
				),
			}
		end

		if input.coachmark ~= nil then
			self.kind = {
				type = "coachmark",
				value = _roblox_apppageplatform_shared_v1beta1_coachmark.CoachmarkSchema.jsonDecode(input.coachmark),
			}
		end

		return self
	end

	_UiComponentSchemaImpl.descriptor = {
		name = "UiComponentSchema",
		fullName = "roblox.apppageplatform.shared.v1beta1.UiComponentSchema",
	}

	messages.UiComponentSchema = _UiComponentSchemaImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.UiComponentSchema)
end

return {
	UiComponentSchema = messages.UiComponentSchema,
}
