--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages = {
	ViewSchema: _ViewSchemaMessage,
	ViewSchema_Props: _ViewSchema_PropsMessage,
}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_prop_types = require(script.Parent.prop_types)
local _roblox_apppageplatform_shared_v1beta1_actions = require(script.Parent.actions)
local _roblox_apppageplatform_shared_v1beta1_component_shared = require(script.Parent.component_shared)

type _ViewSchemaImpl = {
	__index: _ViewSchemaImpl,
	new: (fields: _ViewSchemaPartialFields?) -> ViewSchema,
	encode: (self: ViewSchema) -> buffer,
	decode: (input: buffer) -> ViewSchema,
	jsonEncode: (self: ViewSchema) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ViewSchema,
	descriptor: proto.Descriptor,
}

type _ViewSchemaFields = {
	props: ViewSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

type _ViewSchemaPartialFields = {
	props: ViewSchema_Props?,
	shared: _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared?,
}

export type ViewSchema = typeof(setmetatable({} :: _ViewSchemaFields, {} :: _ViewSchemaImpl))
type _ViewSchemaMessage = proto.Message<ViewSchema, _ViewSchemaPartialFields>

type _ViewSchema_PropsImpl = {
	__index: _ViewSchema_PropsImpl,
	new: (fields: _ViewSchema_PropsPartialFields?) -> ViewSchema_Props,
	encode: (self: ViewSchema_Props) -> buffer,
	decode: (input: buffer) -> ViewSchema_Props,
	jsonEncode: (self: ViewSchema_Props) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> ViewSchema_Props,
	descriptor: proto.Descriptor,
}

type _ViewSchema_PropsFields = {
	anchor_point: _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop?,
	clips_descendants: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	position: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	size: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
}

type _ViewSchema_PropsPartialFields = {
	anchor_point: _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop?,
	clips_descendants: _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp?,
	layout_order: _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop?,
	position: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	size: _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop?,
	on_activated: _roblox_apppageplatform_shared_v1beta1_actions.ActionProp?,
}

export type ViewSchema_Props = typeof(setmetatable({} :: _ViewSchema_PropsFields, {} :: _ViewSchema_PropsImpl))
type _ViewSchema_PropsMessage = proto.Message<ViewSchema_Props, _ViewSchema_PropsPartialFields>

do
	local _ViewSchemaImpl = {}
	_ViewSchemaImpl.__index = _ViewSchemaImpl

	function _ViewSchemaImpl.new(data: _ViewSchemaPartialFields?): ViewSchema
		return setmetatable({
			props = if data == nil or data.props == nil then nil else data.props,
			shared = if data == nil or data.shared == nil then nil else data.shared,
		}, _ViewSchemaImpl :: _ViewSchemaImpl)
	end

	function _ViewSchemaImpl.encode(self: ViewSchema): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.props ~= nil then
			local encoded = self.props:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.shared ~= nil then
			local encoded = self.shared:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ViewSchemaImpl.decode(input: buffer): ViewSchema
		local self = _ViewSchemaImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.props = messages.ViewSchema_Props.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.shared = _roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ViewSchemaImpl.jsonEncode(self: ViewSchema): any
		local output = {}

		if self.props ~= nil then
			output.props = self.props:jsonEncode()
		end

		if self.shared ~= nil then
			output.shared = self.shared:jsonEncode()
		end

		return output
	end

	function _ViewSchemaImpl.jsonDecode(input: { [string]: any }): ViewSchema
		local self = _ViewSchemaImpl.new()

		if input.props ~= nil then
			self.props = messages.ViewSchema_Props.jsonDecode(input.props)
		end

		if input.shared ~= nil then
			self.shared =
				_roblox_apppageplatform_shared_v1beta1_component_shared.ComponentShared.jsonDecode(input.shared)
		end

		return self
	end

	_ViewSchemaImpl.descriptor = {
		name = "ViewSchema",
		fullName = "roblox.apppageplatform.shared.v1beta1.ViewSchema",
	}

	messages.ViewSchema = _ViewSchemaImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ViewSchema)
end

do
	local _ViewSchema_PropsImpl = {}
	_ViewSchema_PropsImpl.__index = _ViewSchema_PropsImpl

	function _ViewSchema_PropsImpl.new(data: _ViewSchema_PropsPartialFields?): ViewSchema_Props
		return setmetatable({
			anchor_point = if data == nil or data.anchor_point == nil then nil else data.anchor_point,
			clips_descendants = if data == nil or data.clips_descendants == nil then nil else data.clips_descendants,
			layout_order = if data == nil or data.layout_order == nil then nil else data.layout_order,
			position = if data == nil or data.position == nil then nil else data.position,
			size = if data == nil or data.size == nil then nil else data.size,
			on_activated = if data == nil or data.on_activated == nil then nil else data.on_activated,
		}, _ViewSchema_PropsImpl :: _ViewSchema_PropsImpl)
	end

	function _ViewSchema_PropsImpl.encode(self: ViewSchema_Props): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.anchor_point ~= nil then
			local encoded = self.anchor_point:encode()
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.clips_descendants ~= nil then
			local encoded = self.clips_descendants:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.layout_order ~= nil then
			local encoded = self.layout_order:encode()
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.position ~= nil then
			local encoded = self.position:encode()
			output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.size ~= nil then
			local encoded = self.size:encode()
			output, cursor = proto.writeTag(output, cursor, 5, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.on_activated ~= nil then
			local encoded = self.on_activated:encode()
			output, cursor = proto.writeTag(output, cursor, 6, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _ViewSchema_PropsImpl.decode(input: buffer): ViewSchema_Props
		local self = _ViewSchema_PropsImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.anchor_point = _roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.decode(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.clips_descendants = _roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.layout_order = _roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.decode(value)
					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.position = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.decode(value)
					continue
				elseif field == 5 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.decode(value)
					continue
				elseif field == 6 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _ViewSchema_PropsImpl.jsonEncode(self: ViewSchema_Props): any
		local output = {}

		if self.anchor_point ~= nil then
			output.anchorPoint = self.anchor_point:jsonEncode()
		end

		if self.clips_descendants ~= nil then
			output.clipsDescendants = self.clips_descendants:jsonEncode()
		end

		if self.layout_order ~= nil then
			output.layoutOrder = self.layout_order:jsonEncode()
		end

		if self.position ~= nil then
			output.position = self.position:jsonEncode()
		end

		if self.size ~= nil then
			output.size = self.size:jsonEncode()
		end

		if self.on_activated ~= nil then
			output.onActivated = self.on_activated:jsonEncode()
		end

		return output
	end

	function _ViewSchema_PropsImpl.jsonDecode(input: { [string]: any }): ViewSchema_Props
		local self = _ViewSchema_PropsImpl.new()

		if input.anchor_point ~= nil then
			self.anchor_point =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.jsonDecode(input.anchor_point)
		end

		if input.anchorPoint ~= nil then
			self.anchor_point =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Vector2Prop.jsonDecode(input.anchorPoint)
		end

		if input.clips_descendants ~= nil then
			self.clips_descendants =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.clips_descendants)
		end

		if input.clipsDescendants ~= nil then
			self.clips_descendants =
				_roblox_apppageplatform_shared_v1beta1_prop_types.BoolProp.jsonDecode(input.clipsDescendants)
		end

		if input.layout_order ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layout_order)
		end

		if input.layoutOrder ~= nil then
			self.layout_order =
				_roblox_apppageplatform_shared_v1beta1_prop_types.Int32Prop.jsonDecode(input.layoutOrder)
		end

		if input.position ~= nil then
			self.position = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.position)
		end

		if input.size ~= nil then
			self.size = _roblox_apppageplatform_shared_v1beta1_prop_types.UDim2Prop.jsonDecode(input.size)
		end

		if input.on_activated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.on_activated)
		end

		if input.onActivated ~= nil then
			self.on_activated = _roblox_apppageplatform_shared_v1beta1_actions.ActionProp.jsonDecode(input.onActivated)
		end

		return self
	end

	_ViewSchema_PropsImpl.descriptor = {
		name = "ViewSchema_Props",
		fullName = "roblox.apppageplatform.shared.v1beta1.Props",
	}

	messages.ViewSchema_Props = _ViewSchema_PropsImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.ViewSchema_Props)
end

return {
	ViewSchema = messages.ViewSchema,
	ViewSchema_Props = messages.ViewSchema_Props,
}
