--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["RobloxAppHooks"]["RobloxAppHooks"])

export type UiModeInfo = Package.UiModeInfo


return Package
