--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package
if game:GetFastFlag("PublishPlaceAsDeduplicatePackages") then
	package = PackageIndex["UILibrary"]["UILibrary"]
else
	local OldPackages = PackageIndex.Parent.Parent.OldPackages
	package = OldPackages.UILibrary
end

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package
