return {
	UnplayableOtherReason = "UnplayableOtherReason",
	Playable = "Playable",
	GuestProhibited = "GuestProhibited",
	GameUnapproved = "GameUnapproved",
	IncorrectConfiguration = "IncorrectConfiguration",
	UniverseRootPlaceIsPrivate = "UniverseRootPlaceIsPrivate",
	InsufficientPermissionFriendsOnly = "InsufficientPermissionFriendsOnly",
	InsufficientPermissionGroupOnly = "InsufficientPermissionGroupOnly",
	DeviceRestricted = "DeviceRestricted",
	UnderReview = "UnderReview",
	PurchaseRequired = "PurchaseRequired",
	AccountRestricted = "AccountRestricted",
	TemporarilyUnavailable = "TemporarilyUnavailable",
	ComplianceBlocked = "ComplianceBlocked",
	ContextualPlayabilityAgeRecommendationParentalControls = "ContextualPlayabilityAgeRecommendationParentalControls",
	ContextualPlayabilityRegionalAvailability = "ContextualPlayabilityRegionalAvailability",
	ContextualPlayabilityRegionalCompliance = "ContextualPlayabilityRegionalCompliance",
}
