--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["JestGetType-edcba0e9-3.4.1"]["JestGetType"])

return Package
