local MessageBus = game:GetService("MessageBusService")

local NAME = "Call"

local MESSAGE_INIT_CALL = MessageBus:GetMessageId(NAME, "initCall")
local MESSAGE_ANSWER_CALL = MessageBus:GetMessageId(NAME, "answerCall")
local MESSAGE_REJECT_CALL = MessageBus:GetMessageId(NAME, "rejectCall")
local MESSAGE_CANCEL_CALL = MessageBus:GetMessageId(NAME, "cancelCall")
local MESSAGE_HANDLE_INIT_CALL = MessageBus:GetMessageId(NAME, "handleInitCall")
local MESSAGE_HANDLE_ANSWER_CALL = MessageBus:GetMessageId(NAME, "handleAnswerCall")
local MESSAGE_HANDLE_REJECT_CALL = MessageBus:GetMessageId(NAME, "handleRejectCall")
local MESSAGE_HANDLE_CANCEL_CALL = MessageBus:GetMessageId(NAME, "handleCancelCall")
local MESSAGE_HANDLE_CALL_NOTIFICATION_UPDATE = MessageBus:GetMessageId(NAME, "handleCallNotificationUpdate")

local METHOD_GET_CALL_STATE = "getCallState"

return {
	NAME = NAME,

	MESSAGE_INIT_CALL = MESSAGE_INIT_CALL,
	MESSAGE_ANSWER_CALL = MESSAGE_ANSWER_CALL,
	MESSAGE_REJECT_CALL = MESSAGE_REJECT_CALL,
	MESSAGE_CANCEL_CALL = MESSAGE_CANCEL_CALL,
	MESSAGE_HANDLE_INIT_CALL = MESSAGE_HANDLE_INIT_CALL,
	MESSAGE_HANDLE_ANSWER_CALL = MESSAGE_HANDLE_ANSWER_CALL,
	MESSAGE_HANDLE_REJECT_CALL = MESSAGE_HANDLE_REJECT_CALL,
	MESSAGE_HANDLE_CANCEL_CALL = MESSAGE_HANDLE_CANCEL_CALL,
	MESSAGE_HANDLE_CALL_NOTIFICATION_UPDATE = MESSAGE_HANDLE_CALL_NOTIFICATION_UPDATE,

	METHOD_GET_CALL_STATE = METHOD_GET_CALL_STATE,
}
