--[[
	Package link auto-generated by manage_libraries and Rotriever
]]
local FFlagPluginManagementDeduplicatePackages = game:GetFastFlag("PluginManagementDeduplicatePackages")
if FFlagPluginManagementDeduplicatePackages then
	local PackageIndex = script.Parent._Index
	local Package = require(PackageIndex["roblox_roact-navigation"]["roact-navigation"])
	return Package
else
	local PackageIndex = script.Parent._Old

	local package = PackageIndex["roblox_roact-navigation"]["roact-navigation"]

	if package.ClassName == "ModuleScript" then
		return require(package)
	end

	return package
end
