--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

if game:GetFastFlag("PluginManagementUseRoactv14") then
	return require(PackageIndex["roblox_roact-rodux"]["roact-rodux"])
end

return require(PackageIndex["RoactRodux-9dcb3c30-f36097a9"].Packages["RoactRodux"])
