--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["TestEZ-28fc8954-17e1408b"].Packages["TestEZ"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package