-- Jest Roblox Snapshot v1, http://roblox.github.io/jest-roblox/snapshot-testing
local exports = {}
exports[ [=[should match snapshot 1]=] ] = [=[

ImageButton {
  "AbsolutePosition": Vector2(0, 0),
  "AbsoluteRotation": 0,
  "AbsoluteSize": Vector2(0, 0),
  "Active": true,
  "AnchorPoint": Vector2(0, 0),
  "Archivable": true,
  "AutoButtonColor": false,
  "AutoLocalize": true,
  "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
  "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
  "BackgroundTransparency": 1,
  "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
  "BorderMode": EnumItem(Enum.BorderMode.Outline),
  "BorderSizePixel": 1,
  "ClassName": "ImageButton",
  "ClipsDescendants": false,
  "HoverImage": "",
  "Image": "rbxassetid://14755017532",
  "ImageColor3": Color3(1, 1, 1),
  "ImageRectOffset": Vector2(152, 494),
  "ImageRectSize": Vector2(17, 17),
  "ImageTransparency": 0.30000001192092896,
  "IsLoaded": false,
  "LayoutOrder": 0,
  "Modal": false,
  "Name": "TheButton",
  "NextSelectionDown": nil,
  "NextSelectionLeft": nil,
  "NextSelectionRight": nil,
  "NextSelectionUp": nil,
  "Parent": "StyleProvider" [Frame],
  "Position": UDim2({0, 0}, {0, 0}),
  "PressedImage": "",
  "ResampleMode": EnumItem(Enum.ResamplerMode.Default),
  "RootLocalizationTable": nil,
  "Rotation": 0,
  "ScaleType": EnumItem(Enum.ScaleType.Slice),
  "Selectable": true,
  "Selected": false,
  "SelectionImageObject": nil,
  "Size": UDim2({0, 0}, {0, 0}),
  "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
  "SliceCenter": Rect(8, 8, 9, 9),
  "SliceScale": 1,
  "Style": EnumItem(Enum.ButtonStyle.Custom),
  "TileSize": UDim2({1, 0}, {1, 0}),
  "Visible": true,
  "ZIndex": 1,
  "ButtonContent": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 1,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "ButtonContent",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "TheButton" [ImageButton],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({1, 0}, {1, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "ButtonMiddleContent": Frame {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 1,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "Frame",
      "ClipsDescendants": false,
      "LayoutOrder": 0,
      "Name": "ButtonMiddleContent",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "ButtonContent" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({1, 0}, {1, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Style": EnumItem(Enum.FrameStyle.Custom),
      "Visible": true,
      "ZIndex": 1,
      "UIListLayout": UIListLayout {
        "AbsoluteContentSize": Vector2(0, 0),
        "Archivable": true,
        "ClassName": "UIListLayout",
        "FillDirection": EnumItem(Enum.FillDirection.Horizontal),
        "HorizontalAlignment": EnumItem(Enum.HorizontalAlignment.Center),
        "Name": "UIListLayout",
        "Padding": UDim(0, 5),
        "Parent": "ButtonMiddleContent" [Frame],
        "SortOrder": EnumItem(Enum.SortOrder.LayoutOrder),
        "VerticalAlignment": EnumItem(Enum.VerticalAlignment.Center),
      },
    },
  },
}
]=]

exports[ [=[should match snapshot with isDisabled = true 1]=] ] = [=[

ImageButton {
  "AbsolutePosition": Vector2(0, 0),
  "AbsoluteRotation": 0,
  "AbsoluteSize": Vector2(0, 0),
  "Active": false,
  "AnchorPoint": Vector2(0, 0),
  "Archivable": true,
  "AutoButtonColor": false,
  "AutoLocalize": true,
  "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
  "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
  "BackgroundTransparency": 1,
  "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
  "BorderMode": EnumItem(Enum.BorderMode.Outline),
  "BorderSizePixel": 1,
  "ClassName": "ImageButton",
  "ClipsDescendants": false,
  "HoverImage": "",
  "Image": "rbxassetid://14755017532",
  "ImageColor3": Color3(1, 1, 1),
  "ImageRectOffset": Vector2(152, 494),
  "ImageRectSize": Vector2(17, 17),
  "ImageTransparency": 0.6499999761581421,
  "IsLoaded": false,
  "LayoutOrder": 0,
  "Modal": false,
  "Name": "TheButton",
  "NextSelectionDown": nil,
  "NextSelectionLeft": nil,
  "NextSelectionRight": nil,
  "NextSelectionUp": nil,
  "Parent": "StyleProvider" [Frame],
  "Position": UDim2({0, 0}, {0, 0}),
  "PressedImage": "",
  "ResampleMode": EnumItem(Enum.ResamplerMode.Default),
  "RootLocalizationTable": nil,
  "Rotation": 0,
  "ScaleType": EnumItem(Enum.ScaleType.Slice),
  "Selectable": true,
  "Selected": false,
  "SelectionImageObject": nil,
  "Size": UDim2({0, 0}, {0, 0}),
  "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
  "SliceCenter": Rect(8, 8, 9, 9),
  "SliceScale": 1,
  "Style": EnumItem(Enum.ButtonStyle.Custom),
  "TileSize": UDim2({1, 0}, {1, 0}),
  "Visible": true,
  "ZIndex": 1,
  "ButtonContent": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 1,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "ButtonContent",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "TheButton" [ImageButton],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({1, 0}, {1, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "ButtonMiddleContent": Frame {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 1,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "Frame",
      "ClipsDescendants": false,
      "LayoutOrder": 0,
      "Name": "ButtonMiddleContent",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "ButtonContent" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({1, 0}, {1, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Style": EnumItem(Enum.FrameStyle.Custom),
      "Visible": true,
      "ZIndex": 1,
      "UIListLayout": UIListLayout {
        "AbsoluteContentSize": Vector2(0, 0),
        "Archivable": true,
        "ClassName": "UIListLayout",
        "FillDirection": EnumItem(Enum.FillDirection.Horizontal),
        "HorizontalAlignment": EnumItem(Enum.HorizontalAlignment.Center),
        "Name": "UIListLayout",
        "Padding": UDim(0, 5),
        "Parent": "ButtonMiddleContent" [Frame],
        "SortOrder": EnumItem(Enum.SortOrder.LayoutOrder),
        "VerticalAlignment": EnumItem(Enum.VerticalAlignment.Center),
      },
    },
  },
}
]=]

exports[ [=[should match snapshot with isLoading = true 1]=] ] = [=[

ImageButton {
  "AbsolutePosition": Vector2(0, 0),
  "AbsoluteRotation": 0,
  "AbsoluteSize": Vector2(0, 0),
  "Active": false,
  "AnchorPoint": Vector2(0, 0),
  "Archivable": true,
  "AutoButtonColor": false,
  "AutoLocalize": true,
  "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
  "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
  "BackgroundTransparency": 1,
  "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
  "BorderMode": EnumItem(Enum.BorderMode.Outline),
  "BorderSizePixel": 1,
  "ClassName": "ImageButton",
  "ClipsDescendants": false,
  "HoverImage": "",
  "Image": "rbxassetid://14755017532",
  "ImageColor3": Color3(1, 1, 1),
  "ImageRectOffset": Vector2(152, 494),
  "ImageRectSize": Vector2(17, 17),
  "ImageTransparency": 0.6499999761581421,
  "IsLoaded": false,
  "LayoutOrder": 0,
  "Modal": false,
  "Name": "TheButton",
  "NextSelectionDown": nil,
  "NextSelectionLeft": nil,
  "NextSelectionRight": nil,
  "NextSelectionUp": nil,
  "Parent": "StyleProvider" [Frame],
  "Position": UDim2({0, 0}, {0, 0}),
  "PressedImage": "",
  "ResampleMode": EnumItem(Enum.ResamplerMode.Default),
  "RootLocalizationTable": nil,
  "Rotation": 0,
  "ScaleType": EnumItem(Enum.ScaleType.Slice),
  "Selectable": true,
  "Selected": false,
  "SelectionImageObject": nil,
  "Size": UDim2({0, 0}, {0, 0}),
  "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
  "SliceCenter": Rect(8, 8, 9, 9),
  "SliceScale": 1,
  "Style": EnumItem(Enum.ButtonStyle.Custom),
  "TileSize": UDim2({1, 0}, {1, 0}),
  "Visible": true,
  "ZIndex": 1,
  "ButtonContent": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 1,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "ButtonContent",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "TheButton" [ImageButton],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({1, 0}, {1, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "isLoadingShimmer": Frame {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.223529, 0.231373, 0.239216),
      "BackgroundTransparency": 0.5,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 0,
      "ClassName": "Frame",
      "ClipsDescendants": false,
      "LayoutOrder": 0,
      "Name": "isLoadingShimmer",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "ButtonContent" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({1, 0}, {1, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Style": EnumItem(Enum.FrameStyle.Custom),
      "Visible": true,
      "ZIndex": 1,
      "TextureScrollerImage": ImageLabel {
        "AbsolutePosition": Vector2(0, 0),
        "AbsoluteRotation": 0,
        "AbsoluteSize": Vector2(0, 0),
        "Active": false,
        "AnchorPoint": Vector2(0, 0),
        "Archivable": true,
        "AutoLocalize": true,
        "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
        "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
        "BackgroundTransparency": 1,
        "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
        "BorderMode": EnumItem(Enum.BorderMode.Outline),
        "BorderSizePixel": 1,
        "ClassName": "ImageLabel",
        "ClipsDescendants": false,
        "Image": "rbxasset://textures/ui/LuaApp/graphic/shimmer.png",
        "ImageColor3": Color3(1, 1, 1),
        "ImageRectOffset": Vector2(0, 0),
        "ImageRectSize": Vector2(87.5999985, 100),
        "ImageTransparency": 0,
        "IsLoaded": false,
        "LayoutOrder": 0,
        "Name": "TextureScrollerImage",
        "NextSelectionDown": nil,
        "NextSelectionLeft": nil,
        "NextSelectionRight": nil,
        "NextSelectionUp": nil,
        "Parent": "isLoadingShimmer" [Frame],
        "Position": UDim2({0, 0}, {0, 0}),
        "ResampleMode": EnumItem(Enum.ResamplerMode.Default),
        "RootLocalizationTable": nil,
        "Rotation": 0,
        "ScaleType": EnumItem(Enum.ScaleType.Slice),
        "Selectable": false,
        "SelectionImageObject": nil,
        "Size": UDim2({1, 0}, {1, 0}),
        "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
        "SliceCenter": Rect(0, 0, 87.5999985, 100),
        "SliceScale": 1,
        "TileSize": UDim2({1, 0}, {1, 0}),
        "Visible": true,
        "ZIndex": 1,
      },
    },
  },
}
]=]

return exports
