-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent.Parent
local var1 = require(var0.Packages.Framework).Styling.createStyleRule
local var2 = require(var0.Src.Components.NotificationMenu.constants)
local var22 = {}
var22.BackgroundColor3 = "$BackgroundPaper"
local var27 = {}
var27.CornerRadius = UDim.new(0, 4)
local var3 = var1("::UICorner", var27)
local var35 = {}
var35.BackgroundColor3 = "$SecondaryMain"
local var40 = {}
var40.CornerRadius = UDim.new(0, 4)
local var5 = var1("::UICorner", var40)
local var48 = {}
var48.FillDirection = Enum.FillDirection.Vertical
var48.HorizontalAlignment = Enum.HorizontalAlignment.Left
var48.SortOrder = Enum.SortOrder.LayoutOrder
var48.VerticalAlignment = Enum.VerticalAlignment.Top
local var6 = var1("::UIListLayout", var48)
local var56 = {}
var56.BorderSizePixel = 0
var56.Font = var2.TEXT_FONT
var56.TextSize = var2.TEXT_SIZE
var56.TextTruncate = Enum.TextTruncate.AtEnd
var56.TextWrapped = true
var56.TextXAlignment = Enum.TextXAlignment.Left
var56.TextYAlignment = Enum.TextYAlignment.Center
var56.TextColor3 = "$TextPrimary"
var56.BackgroundColor3 = "$SecondaryMain"
local var69 = {}
var69.CornerRadius = UDim.new(0, 4)
local var8 = var1("::UICorner", var69)
local var77 = {}
var77.MaxSize = Vector2.new(∞, 48)
local var10 = var1("::UISizeConstraint", var77)
local var85 = {}
var85.PaddingLeft = UDim.new(0, var2.LEFT_RIGHT_BUTTON_PADDING)
var85.PaddingRight = UDim.new(0, var2.LEFT_RIGHT_BUTTON_PADDING)
var85.PaddingTop = UDim.new(0, 4)
var85.PaddingBottom = UDim.new(0, 4)
local var12 = var1("::UIPadding", var85)
local var105 = {}
var105.BackgroundColor3 = "$ActionHover"
local var13 = var1(":hover", var105)
local var110 = {}
var110.BackgroundColor3 = "$ActionActivated"
local var14 = var1(":pressed", var110)
local var15 = var1(">> .Component-NotificationMenuOptionButton", var56, {})
local var16 = var1(">> .Component-NotificationMenuInner", var35, {})
return var1(".Component-NotificationMenu", var22, {})
