-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent.Parent
local var1 = require(var0.Packages.Framework).Styling.createStyleRule
local var2 = require(var0.Src.Components.NotificationMenu.constants)
local var83 = {}
var83.BackgroundColor3 = "$BackgroundPaper"
local var88 = {}
var88.CornerRadius = UDim.new(0, 4)
local var3 = var1("::UICorner", var88)
local var96 = {}
var96.BackgroundColor3 = "$SecondaryMain"
local var101 = {}
var101.CornerRadius = UDim.new(0, 4)
local var5 = var1("::UICorner", var101)
local var109 = {}
var109.FillDirection = Enum.FillDirection.Vertical
var109.HorizontalAlignment = Enum.HorizontalAlignment.Left
var109.SortOrder = Enum.SortOrder.LayoutOrder
var109.VerticalAlignment = Enum.VerticalAlignment.Top
local var6 = var1("::UIListLayout", var109)
local var117 = {}
var117.BorderSizePixel = 0
var117.Font = var2.TEXT_FONT
var117.TextSize = var2.TEXT_SIZE
var117.TextTruncate = Enum.TextTruncate.AtEnd
var117.TextWrapped = true
var117.TextXAlignment = Enum.TextXAlignment.Left
var117.TextYAlignment = Enum.TextYAlignment.Center
var117.TextColor3 = "$TextPrimary"
var117.BackgroundColor3 = "$SecondaryMain"
local var130 = {}
var130.CornerRadius = UDim.new(0, 4)
local var8 = var1("::UICorner", var130)
local var138 = {}
var138.MaxSize = Vector2.new(∞, 48)
local var10 = var1("::UISizeConstraint", var138)
local var146 = {}
var146.PaddingLeft = UDim.new(0, var2.LEFT_RIGHT_BUTTON_PADDING)
var146.PaddingRight = UDim.new(0, var2.LEFT_RIGHT_BUTTON_PADDING)
var146.PaddingTop = UDim.new(0, 4)
var146.PaddingBottom = UDim.new(0, 4)
local var12 = var1("::UIPadding", var146)
local var166 = {}
var166.BackgroundColor3 = "$ActionHover"
local var13 = var1(":hover", var166)
local var171 = {}
var171.BackgroundColor3 = "$ActionActivated"
local var14 = var1(":pressed", var171)
local var15 = var1(">> .Component-NotificationMenuOptionButton", var117, {})
local var16 = var1(">> .Component-NotificationMenuInner", var96, {})
return var1(".Component-NotificationMenu", var83, {})
