-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.UserId = "userId"
var0.UserName = "userName"
var0.GroupId = "groupId"
var0.GroupName = "groupName"
var0.RoleId = "rolesetId"
var0.RoleName = "rolesetName"
var0.RoleRank = "rank"
var0.Action = "action"
var0.AllowedPermissions = "allowedPermissions"
var0.PlayAction = "Play"
var0.EditAction = "Edit"
var0.AdminAction = "Admin"
var0.SubjectType = "subjectType"
var0.SubjectId = "subjectId"
var0.UserSubject = "User"
var0.GroupSubject = "Group"
var0.RoleSubject = "Roleset"
return var0
