return function(t)
	return {
		Size_0 = t.number,
		Size_25 = t.number,
		Size_50 = t.number,
		Size_75 = t.number,
		Size_100 = t.number,
		Size_150 = t.number,
		Size_200 = t.number,
		Size_250 = t.number,
		Size_300 = t.number,
		Size_350 = t.number,
		Size_400 = t.number,
		Size_450 = t.number,
		Size_500 = t.number,
		Size_600 = t.number,
		Size_700 = t.number,
		Size_800 = t.number,
		Size_900 = t.number,
		Size_1000 = t.number,
		Size_1100 = t.number,
		Size_1200 = t.number,
		Size_1300 = t.number,
		Size_1400 = t.number,
		Space_0 = t.number,
		Space_25 = t.number,
		Space_50 = t.number,
		Space_75 = t.number,
		Space_100 = t.number,
		Space_150 = t.number,
		Space_200 = t.number,
		Space_250 = t.number,
		Space_300 = t.number,
		Space_400 = t.number,
		Space_500 = t.number,
		Space_600 = t.number,
		Space_800 = t.number,
		Space_1000 = t.number,
		FontSize_25 = t.number,
		FontSize_50 = t.number,
		FontSize_75 = t.number,
		FontSize_100 = t.number,
		FontSize_200 = t.number,
		FontSize_300 = t.number,
		FontSize_400 = t.number,
		FontSize_500 = t.number,
		FontSize_600 = t.number,
		FontSize_700 = t.number,
		FontSize_800 = t.number,
		FontSize_900 = t.number,
		FontSize_1000 = t.number,
		Family = t.strictInterface({
			Standard = t.string,
		}),
		Weight_300 = t.string,
		Weight_400 = t.string,
		Weight_600 = t.string,
		Weight_700 = t.string,
		Weight_900 = t.string,
		LetterSpacing = t.strictInterface({
			Default = t.number,
		}),
		LineHeight_100 = t.number,
		LineHeight_200 = t.number,
		LineHeight_300 = t.number,
		LineHeight_400 = t.number,
		Stroke_50 = t.number,
		Stroke_100 = t.number,
		Stroke_150 = t.number,
		Stroke_200 = t.number,
		Stroke_250 = t.number,
		Stroke_300 = t.number,
		Stroke_400 = t.number,
		Opacity_0 = t.number,
		Opacity_8 = t.number,
		Opacity_12 = t.number,
		Opacity_16 = t.number,
		Opacity_32 = t.number,
		Opacity_68 = t.number,
		Opacity_84 = t.number,
		Opacity_88 = t.number,
		Opacity_92 = t.number,
		Opacity_100 = t.number,
		Color = t.strictInterface({
			Black = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			White = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Green = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Red = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Blue = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Carbon = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Flint = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Graphite = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Obsidian = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Pumice = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Slate = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Alabaster = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Ash = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Chalk = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
			Smoke = t.strictInterface({
				Color3 = t.Color3,
				Transparency = t.number,
			}),
		}),
	}
end
