--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["Cryo-d467f4c6a862-1ba35bb23d0f"].Packages["Cryo"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package