return {
    {
        Key = "GameChat_ChatCommandsTeller_AllChannelWelcomeMessage",
        Values = {
            ["de"] = "Gib „/?“ oder „/help“ im Chat ein, um eine Liste der Chatbefehle zu erhalten.",
            ["en-us"] = "Chat '/?' or '/help' for a list of chat commands.",
            ["es"] = "Envía \"/?\" o \"/help\" para obtener la lista de comandos del chat.",
            ["es-es"] = "Envía \"/?\" o \"/help\" para obtener la lista de comandos del chat.",
            ["fr"] = "Dans le chat, « /? » ou « /help » pour la liste des commandes du chat.",
            ["it"] = "Scrivi \"/?\" o \"/help\" per avere l'elenco dei comandi della chat.",
            ["ja"] = "チャットで 「/?」 または 「/help」を入力するとチャットコマンドの一覧を表示します。",
            ["ko"] = "채팅창에 '/?' 또는 '/도움말'을 입력하면 채팅 명령어 목록을 볼 수 있어요.",
            ["pt"] = "Digite '/?' ou '/help' no chat para ver uma lista de comandos.",
            ["pt-br"] = "Digite '/?' ou '/help' no chat para ver uma lista de comandos.",
            ["ru"] = "Введите «/?» или «/help», чтобы увидеть список команд чата.",
            ["zh-cjv"] = "输入 “/?”或 “/help” 可获取聊天指令清单。",
            ["zh-cn"] = "输入 “/?”或 “/help” 可获取聊天指令清单。",
            ["zh-tw"] = "輸入「/?」或「/help」取得聊天指令清單。",
        },
    },
    {
        Key = "GameChat_SwallowGuestChat_Message",
        Values = {
            ["de"] = "Erstelle ein kostenloses Konto, um Zugriff auf Chatberechtigungen zu erhalten!",
            ["en-us"] = "Create a free account to get access to chat permissions!",
            ["es"] = "¡Crea una cuenta gratuita para obtener los permisos de acceso al chat!",
            ["es-es"] = "¡Crea una cuenta gratuita para obtener los permisos de acceso al chat!",
            ["fr"] = "Créez un compte gratuit pour accéder aux permissions de chat !",
            ["it"] = "Crea un account gratuito per avere accesso ai permessi della chat!",
            ["ja"] = "フリーアカウントを作ってチャット権限にアクセス！",
            ["ko"] = "무료 계정을 생성해 채팅 권한을 이용하세요!",
            ["pt"] = "Crie uma conta grátis para ter acesso a permissões de chat!",
            ["pt-br"] = "Crie uma conta grátis para ter acesso a permissões de chat!",
            ["ru"] = "Создайте бесплатную учетную запись, чтобы настроить права доступа в чате!",
            ["zh-cjv"] = "创建免费帐户以获取聊天权限！",
            ["zh-cn"] = "创建免费帐户以获取聊天权限！",
            ["zh-tw"] = "若要使用聊天功能，請建立免費帳號。",
        },
    },
    {
        Key = "GameChat_ChatCommandsTeller_SwitchChannelCommand",
        Values = {
            ["de"] = "/c <Kanal> : Zum Wechseln zwischen Kanalmenüreitern.",
            ["en-us"] = "/c <channel> : switch channel menu tabs.",
            ["es"] = "/c <channel>: alternar pestañas del menú del chat.",
            ["es-es"] = "/c <channel>: alternar pestañas del menú del chat.",
            ["fr"] = "/c <canal> : échanger les onglets du menu Canal.",
            ["it"] = "/c <canale>: cambia scheda nel menu dei canali.",
            ["ja"] = "/c <チャンネル> : チャンネルメニュータブを切り替える。",
            ["ko"] = "/c <채널> : 채널 메뉴 탭 전환.",
            ["pt"] = "/c <canal> : trocar abas de menu de canal.",
            ["pt-br"] = "/c <canal> : trocar abas de menu de canal.",
            ["ru"] = "/c <канал> : переключить вкладку в меню каналов.",
            ["zh-cjv"] = "/c <频道名称> : 切换频道菜单标签。",
            ["zh-cn"] = "/c <频道名称> : 切换频道菜单标签。",
            ["zh-tw"] = "/c <頻道名稱>：切換頻道選單標籤。",
        },
    },
    {
        Key = "GameChat_ChatCommandsTeller_MeCommand",
        Values = {
            ["de"] = "/me <Text> : Rollenspielbefehl für Aktionen.",
            ["en-us"] = "/me <text> : roleplaying command for doing actions.",
            ["es"] = "/me <text>: comando de rol para realizar acciones.",
            ["es-es"] = "/me <text>: comando de rol para realizar acciones.",
            ["fr"] = "/me <texte> : commande jeu de rôle pour accomplir des actions.",
            ["it"] = "/me <testo>: comando per descrivere azioni e giocare di ruolo.",
            ["ja"] = "/me <テキスト> : アクションのためのロールプレイングコマンド。",
            ["ko"] = "/me <텍스트> : 작업 수행을 위한 역할 놀이 명령어.",
            ["pt"] = "/me <texto> : comando de RPG para realizar ações.",
            ["pt-br"] = "/me <texto> : comando de RPG para realizar ações.",
            ["ru"] = "/me <текст> : сообщить о выполнении какого-либо действия.",
            ["zh-cjv"] = "/me <text> : 做动作的角色扮演指令。",
            ["zh-cn"] = "/me <text> : 做动作的角色扮演指令。",
            ["zh-tw"] = "/me <文字>：角色扮演動作的指令。",
        },
    },
    {
        Key = "GameChat_ChatCommandsTeller_MuteCommand",
        Values = {
            ["de"] = "/mute <Sprecher> : Schaltet Sprecher:in stumm.",
            ["en-us"] = "/mute <speaker> : mute a speaker.",
            ["es"] = "/mute <usuario>: silenciar a un usuario.",
            ["es-es"] = "/mute <usuario>: silenciar a un usuario.",
            ["fr"] = "/mute <interlocuteur> : bâillonne un interlocuteur.",
            ["it"] = "/mute <giocatore>: togli la parola a un giocatore.",
            ["ja"] = "/mute <スピーカー> : 相手をミュート。",
            ["ko"] = "/mute <스피커> : 스피커 음소거.",
            ["pt"] = "/mute <pessoa> : silenciar uma pessoa.",
            ["pt-br"] = "/mute <pessoa> : silenciar uma pessoa.",
            ["ru"] = "/mute <пользователь> : игнорировать пользователя.",
            ["zh-cjv"] = "/mute <用户名称>：将用户禁言。",
            ["zh-cn"] = "/mute <用户名称>：将用户禁言。",
            ["zh-tw"] = "/mute <使用者名稱> : 將此使用者靜音。",
        },
    },
    {
        Key = "GameChat_ChatCommandsTeller_UnMuteCommand",
        Values = {
            ["de"] = "/unmute <Sprecher> : Hebt Stummschaltung eines Sprechers auf.",
            ["en-us"] = "/unmute <speaker> : unmute a speaker.",
            ["es"] = "/unmute <speaker>: cancelar silencio de un usuario.",
            ["es-es"] = "/unmute <speaker>: cancelar silencio de un usuario.",
            ["fr"] = "/unmute <interlocuteur> : retire le bâillon d'un interlocuteur.",
            ["it"] = "/unmute <giocatore>: restituisci la parola a un giocatore.",
            ["ja"] = "/unmute <スピーカー> : 相手のミュートを解除.",
            ["ko"] = "/unmute <스피커> : 스피커 음소거 해제.",
            ["pt"] = "/unmute <pessoa> : remover silêncio de uma pessoa.",
            ["pt-br"] = "/unmute <pessoa> : remover silêncio de uma pessoa.",
            ["ru"] = "/unmute <пользователь> : перестать игнорировать пользователя.",
            ["zh-cjv"] = "/unmute <用户名称> : 取消该用户禁言。",
            ["zh-cn"] = "/unmute <用户名称> : 取消该用户禁言。",
            ["zh-tw"] = "/unmute <使用者名稱> : 將此使用者解除靜音。",
        },
    },
    {
        Key = "GameChat_ChatCommandsTeller_WhisperCommand",
        Values = {
            ["de"] = "/whisper <Sprecher:in> oder /w <Sprecher:in> : Öffnet privaten Nachrichtenkanal mit Sprecher:in.",
            ["en-us"] = "/whisper <speaker> or /w <speaker> : open private message channel with speaker.",
            ["es"] = "/whisper <usuario> o /w <usuario>: abrir canal de mensajes privados con un usuario.",
            ["es-es"] = "/whisper <usuario> o /w <usuario>: abrir canal de mensajes privados con un usuario.",
            ["fr"] = "/whisper <interlocuteur> ou /w <interlocuteur> : ouvre un canal de discussion privé avec l'interlocuteur.",
            ["it"] = "/whisper <giocatore> o /w <giocatore>: apri un canale privato con un giocatore.",
            ["ja"] = "/whisper <スピーカー> または /w <スピーカー> : プライベートメッセージチャンネルを開く",
            ["ko"] = "/whisper <스피커> 또는 /w <스피커> : 스피커 채널에서 비공개 메시지 열기.",
            ["pt"] = "/whisper <pessoa> ou /w <pessoa> : abrir um canal de mensagem privada com uma pessoa.",
            ["pt-br"] = "/whisper <pessoa> ou /w <pessoa> : abrir um canal de mensagem privada com uma pessoa.",
            ["ru"] = "/whisper <пользователь> или /w <пользователь> : открыть канал для личной переписки с пользователем.",
            ["zh-cjv"] = "/whisper <用户名称> 或 /w <用户名称> : 与此用户开启私人消息频道。",
            ["zh-cn"] = "/whisper <用户名称> 或 /w <用户名称> : 与此用户开启私人消息频道。",
            ["zh-tw"] = "/whisper <使用者名稱> 或 /w <使用者名稱> : 與此使用者開啟私人訊息頻道。",
        },
    },
    {
        Key = "GameChat_ChatMain_SpeakerHasBeenMuted",
        Values = {
            ["de"] = "Sprecher:in „{RBX_NAME}“ wurde stummgeschaltet.",
            ["en-us"] = "Speaker '{RBX_NAME}' has been muted.",
            ["es"] = "Se ha silenciado al usuario \"{RBX_NAME}\".",
            ["es-es"] = "Se ha silenciado al usuario \"{RBX_NAME}\".",
            ["fr"] = "L'interlocuteur {RBX_NAME} a été bâillonné.",
            ["it"] = "Hai tolto la parola al giocatore \"{RBX_NAME}\".",
            ["ja"] = "「{RBX_NAME}」をミュートしました。",
            ["ko"] = "스피커 '{RBX_NAME}'이(가) 음소거되었어요.",
            ["pt"] = "'{RBX_NAME}' foi silenciado(a).",
            ["pt-br"] = "'{RBX_NAME}' foi silenciado(a).",
            ["ru"] = "Пользователь {RBX_NAME} добавлен в список игнорируемых.",
            ["zh-cjv"] = "发言者“{RBX_NAME}”已被禁言。",
            ["zh-cn"] = "发言者“{RBX_NAME}”已被禁言。",
            ["zh-tw"] = "已將使用者「{RBX_NAME}」靜音。",
        },
    },
    {
        Key = "GameChat_ChatMain_SpeakerHasBeenUnMuted",
        Values = {
            ["de"] = "Stummschaltung von Sprecher:in „{RBX_NAME}“ wurde aufgehoben.",
            ["en-us"] = "Speaker '{RBX_NAME}' has been unmuted.",
            ["es"] = "Se ha cancelado el silencio del usuario \"{RBX_NAME}\".",
            ["es-es"] = "Se ha cancelado el silencio del usuario \"{RBX_NAME}\".",
            ["fr"] = "L'interlocuteur {RBX_NAME} n'est plus bâillonné.",
            ["it"] = "Hai restituito la parola al giocatore \"{RBX_NAME}\".",
            ["ja"] = "「{RBX_NAME}」のミュートを解除しました。",
            ["ko"] = "스피커 '{RBX_NAME}'의 음소거가 해제되었어요.",
            ["pt"] = "O silêncio de '{RBX_NAME}' foi removido.",
            ["pt-br"] = "O silêncio de '{RBX_NAME}' foi removido.",
            ["ru"] = "Пользователь {RBX_NAME} удален из списка игнорируемых.",
            ["zh-cjv"] = "发言者“{RBX_NAME}”已被取消禁言。",
            ["zh-cn"] = "发言者“{RBX_NAME}”已被取消禁言。",
            ["zh-tw"] = "已將使用者「{RBX_NAME}」解除靜音。",
        },
    },
    {
        Key = "GameChat_ChatCommandsTeller_Desc",
        Values = {
            ["de"] = "Das sind die grundlegenden Chatbefehle.",
            ["en-us"] = "These are the basic chat commands.",
            ["es"] = "Estos son los comandos básicos del chat.",
            ["es-es"] = "Estos son los comandos básicos del chat.",
            ["fr"] = "Voici les commandes de chat basiques.",
            ["it"] = "Questi sono i comandi base della chat.",
            ["ja"] = "これらは基本的なチャットコマンドです。",
            ["ko"] = "기본 채팅 명령어에요.",
            ["pt"] = "Esses são os comandos de chat básicos.",
            ["pt-br"] = "Esses são os comandos de chat básicos.",
            ["ru"] = "Это основные команды чата.",
            ["zh-cjv"] = "这些是基本聊天指令。",
            ["zh-cn"] = "这些是基本聊天指令。",
            ["zh-tw"] = "以下是基本聊天室指令。",
        },
    },
    {
        Key = "GameChat_GetVersion_Message",
        Values = {
            ["de"] = "Die Chatversion dieses Spiels ist [{RBX_NUMBER}.{RBX_NUMBER}].",
            ["en-us"] = "This experience is running chat version [{RBX_NUMBER}.{RBX_NUMBER}].",
            ["es"] = "Este juego utiliza la versión del chat [{RBX_NUMBER} {RBX_NUMBER}].",
            ["es-es"] = "Este juego utiliza la versión del chat [{RBX_NUMBER} {RBX_NUMBER}].",
            ["fr"] = "Le jeu utilise la version de chat [{RBX_NUMBER} {RBX_NUMBER}].",
            ["it"] = "Questo gioco usa la versione [{RBX_NUMBER}.{RBX_NUMBER}] della chat.",
            ["ja"] = "このゲームはチャットバージョン [{RBX_NUMBER}.{RBX_NUMBER}]を実行しています。",
            ["ko"] = "이 게임은 채팅 버전 [{RBX_NUMBER}. {RBX_NUMBER}]을(를) 실행합니다.",
            ["pt"] = "Este jogo está rodando a versão de chat [{RBX_NUMBER}.{RBX_NUMBER}].",
            ["pt-br"] = "Este jogo está rodando a versão de chat [{RBX_NUMBER}.{RBX_NUMBER}].",
            ["ru"] = "Эта игра поддерживает чат версии [{RBX_NUMBER}.{RBX_NUMBER}].",
            ["zh-cjv"] = "此挑战正在运行聊天版本 [{RBX_NUMBER}.{RBX_NUMBER}]。",
            ["zh-cn"] = "此游戏正在运行聊天版本 [{RBX_NUMBER}.{RBX_NUMBER}]。",
            ["zh-tw"] = "此遊戲正在使用聊天室版本 [{RBX_NUMBER}.{RBX_NUMBER}]。",
        },
    },
    {
        Key = "GameChat_SwitchChannel_NowInChannel",
        Values = {
            ["de"] = "Du chattest jetzt in Kanal „{RBX_NAME}“.",
            ["en-us"] = "You are now chatting in channel: '{RBX_NAME}'",
            ["es"] = "Estás chateando en el canal \"{RBX_NAME}\".",
            ["es-es"] = "Estás chateando en el canal \"{RBX_NAME}\".",
            ["fr"] = "Maintenant, vous discutez sur le canal : {RBX_NAME}",
            ["it"] = "Ora stai parlando nel canale: \"{RBX_NAME}\"",
            ["ja"] = "あなたの現在のチャットチャンネルは: 「{RBX_NAME}」です。",
            ["ko"] = "'{RBX_NAME}' 채널에서 채팅 중이에요",
            ["pt"] = "Você agora está no canal de chat: '{RBX_NAME}'",
            ["pt-br"] = "Você agora está no canal de chat: '{RBX_NAME}'",
            ["ru"] = "Вы общаетесь на канале «{RBX_NAME}»",
            ["zh-cjv"] = "你当前的聊天频道为：“{RBX_NAME}”",
            ["zh-cn"] = "你当前的聊天频道为：“{RBX_NAME}”",
            ["zh-tw"] = "您目前在「{RBX_NAME}」頻道聊天",
        },
    },
    {
        Key = "GameChat_SwitchChannel_NotInChannel",
        Values = {
            ["de"] = "Du befindest dich nicht in Kanal „{RBX_NAME}“.",
            ["en-us"] = "You are not in channel: '{RBX_NAME}'",
            ["es"] = "No estás en el canal \"{RBX_NAME}\".",
            ["es-es"] = "No estás en el canal \"{RBX_NAME}\".",
            ["fr"] = "Vous n'êtes pas sur le canal : {RBX_NAME}",
            ["it"] = "Non ti trovi nel canale: \"{RBX_NAME}\"",
            ["ja"] = "あなたはチャネル: 「{RBX_NAME}」にいません。",
            ["ko"] = "{RBX_NAME}' 채널에 있지 않아요",
            ["pt"] = "Você não está no canal: '{RBX_NAME}'",
            ["pt-br"] = "Você não está no canal: '{RBX_NAME}'",
            ["ru"] = "Вы не на канале «{RBX_NAME}»",
            ["zh-cjv"] = "你不在频道：“{RBX_NAME}”",
            ["zh-cn"] = "你不在频道：“{RBX_NAME}”",
            ["zh-tw"] = "您不在「{RBX_NAME}」頻道",
        },
    },
    {
        Key = "GameChat_ChatMain_ChatBarText",
        Values = {
            ["de"] = "Klicke zum Chatten hier oder drücke die „/“-Taste.",
            ["en-us"] = "To chat click here or press \"/\" key",
            ["es"] = "Para chatear, haz clic aquí o pulsa la tecla \"/\".",
            ["es-es"] = "Para chatear, haz clic aquí o pulsa la tecla \"/\".",
            ["fr"] = "Pour discuter, cliquez ici ou sur la touche « / »",
            ["it"] = "Per chattare, clicca qui o premi il tasto \"/\"",
            ["ja"] = "チャットするにはここをクリックするか 「 / 」 キーを押します。",
            ["ko"] = "여기를 클릭하거나 \"/\" 키를 누른 후 채팅을 시작하세요",
            ["pt"] = "Para escrever clique aqui ou aperte a tecla \"/\"",
            ["pt-br"] = "Para escrever clique aqui ou aperte a tecla \"/\"",
            ["ru"] = "Чтобы общаться в чате, нажмите здесь или на клавишу «/»",
            ["zh-cjv"] = "若要聊天，请点按此处或按下“/”键",
            ["zh-cn"] = "若要聊天，请点按此处或按下“/”键",
            ["zh-tw"] = "若要聊天，請按下此處或「/」鍵",
        },
    },
    {
        Key = "GameChat_ChatMain_ChatBarTextTouch",
        Values = {
            ["de"] = "Tippe zum Chatten hier.",
            ["en-us"] = "Tap here to chat",
            ["es"] = "Toca aquí para chatear",
            ["es-es"] = "Toca aquí para chatear",
            ["fr"] = "Touchez ici pour discuter",
            ["it"] = "Tocca qui per chattare",
            ["ja"] = "ここをタップしてチャットする",
            ["ko"] = "여기를 클릭한 후 내용을 입력하세요",
            ["pt"] = "Toque aqui para escrever",
            ["pt-br"] = "Toque aqui para escrever",
            ["ru"] = "Коснитесь здесь, чтобы общаться в чате",
            ["zh-cjv"] = "轻点此处以聊天",
            ["zh-cn"] = "轻点此处以聊天",
            ["zh-tw"] = "按下此處聊天",
        },
    },
    {
        Key = "GameChat_ChatMain_SpeakerHasBeenBlocked",
        Values = {
            ["de"] = "Sprecher:in „{RBX_NAME}“ wurde blockiert.",
            ["en-us"] = "Speaker '{RBX_NAME}' has been blocked.",
            ["es"] = "Se ha bloqueado al usuario \"{RBX_NAME}\".",
            ["es-es"] = "Se ha bloqueado al usuario \"{RBX_NAME}\".",
            ["fr"] = "L'interlocuteur {RBX_NAME} a été bloqué.",
            ["it"] = "Hai bloccato il giocatore \"{RBX_NAME}\".",
            ["ja"] = "「{RBX_NAME}」はブロック中です。",
            ["ko"] = "스피커 '{RBX_NAME}'님을 차단했어요.",
            ["pt"] = "'{RBX_NAME}' foi bloqueado.",
            ["pt-br"] = "'{RBX_NAME}' foi bloqueado.",
            ["ru"] = "Пользователь {RBX_NAME} заблокирован.",
            ["zh-cjv"] = "发言者“{RBX_NAME}”已被屏蔽。",
            ["zh-cn"] = "发言者“{RBX_NAME}”已被屏蔽。",
            ["zh-tw"] = "已封鎖使用者「{RBX_NAME}」。",
        },
    },
    {
        Key = "GameChat_ChatMain_SpeakerHasBeenUnBlocked",
        Values = {
            ["de"] = "Blockierung von Sprecher:in „{RBX_NAME}“ wurde aufgehoben.",
            ["en-us"] = "Speaker '{RBX_NAME}' has been unblocked.",
            ["es"] = "Se ha desbloqueado al usuario \"{RBX_NAME}\".",
            ["es-es"] = "Se ha desbloqueado al usuario \"{RBX_NAME}\".",
            ["fr"] = "L'interlocuteur {RBX_NAME} n'est plus bloqué.",
            ["it"] = "Hai sbloccato il giocatore \"{RBX_NAME}\".",
            ["ja"] = "「{RBX_NAME}」のブロックが解除されました。",
            ["ko"] = "스피커 '{RBX_NAME}'님 차단을 해제했어요.",
            ["pt"] = "'{RBX_NAME}' foi desbloqueado.",
            ["pt-br"] = "'{RBX_NAME}' foi desbloqueado.",
            ["ru"] = "Пользователь {RBX_NAME} разблокирован.",
            ["zh-cjv"] = "发言者“{RBX_NAME}”已被取消屏蔽。",
            ["zh-cn"] = "发言者“{RBX_NAME}”已被取消屏蔽。",
            ["zh-tw"] = "已解除封鎖使用者「{RBX_NAME}」。",
        },
    },
    {
        Key = "GameChat_ChatCommandsTeller_TeamCommand",
        Values = {
            ["de"] = "/team <Nachricht> oder /t <Nachricht> : Sendet eine Teamnachricht an Spieler:innen deines Teams.",
            ["en-us"] = "/team <message> or /t <message> : send a team chat to people on your team.",
            ["es"] = "/team <message> o /t <message>: enviar un mensaje de chat de equipo a los jugadores de tu equipo.",
            ["es-es"] = "/team <message> o /t <message>: enviar un mensaje de chat de equipo a los jugadores de tu equipo.",
            ["fr"] = "/team <message> ou /t <message> : envoyer un message aux joueurs de votre équipe.",
            ["it"] = "/team <messaggio> o /t <messaggio>: invia un messaggio a tutti i giocatori della tua squadra.",
            ["ja"] = "/team <メッセージ> または /t <メッセージ> : 自分のチームメンバーにチームチャットを送る。",
            ["ko"] = "/team <메시지> 또는 /t <메시지> : 팀 내 플레이어에게 팀 채팅 전송.",
            ["pt"] = "/team <mensagem> ou /t <mensagem> : enviar um chat de equipe aos jogadores da sua equipe.",
            ["pt-br"] = "/team <mensagem> ou /t <mensagem> : enviar um chat de equipe aos jogadores da sua equipe.",
            ["ru"] = "/team <сообщение> или /t <сообщение> : отправить сообщение игрокам из вашей команды.",
            ["zh-cjv"] = "/team <message> 或 /t <message> : 向你团队的玩家发送团队聊天。",
            ["zh-cn"] = "/team <message> 或 /t <message> : 向你团队的玩家发送团队聊天。",
            ["zh-tw"] = "/team <訊息> 或 /t <訊息> : 傳送訊息給隊伍中的玩家。",
        },
    },
    {
        Key = "GameChat_ChatFloodDetector_MessageDisplaySeconds",
        Values = {
            ["de"] = "Du musst {RBX_NUMBER} Sekunden lang warten, bevor du eine weitere Nachricht senden kannst!",
            ["en-us"] = "You must wait {RBX_NUMBER} seconds before sending another message!",
            ["es"] = "¡Debes esperar {RBX_NUMBER} segundos antes de enviar otro mensaje!",
            ["es-es"] = "¡Debes esperar {RBX_NUMBER} segundos antes de enviar otro mensaje!",
            ["fr"] = "Vous devez attendre {RBX_NUMBER} secondes avant d'envoyer un autre message !",
            ["it"] = "Devi aspettare {RBX_NUMBER} secondi prima di inviare un altro messaggio!",
            ["ja"] = "{RBX_NUMBER} 秒待ってから次のメッセージを送ってください!",
            ["ko"] = "추가 메시지를 보내기 전에 {RBX_NUMBER}초 동안 기다려야 해요!",
            ["pt"] = "Você precisa esperar {RBX_NUMBER} segundos antes de enviar outra mensagem!",
            ["pt-br"] = "Você precisa esperar {RBX_NUMBER} segundos antes de enviar outra mensagem!",
            ["ru"] = "Вы сможете отправить новое сообщение только через {RBX_NUMBER} сек.!",
            ["zh-cjv"] = "发送另一条消息前你必须等待 {RBX_NUMBER} 秒！",
            ["zh-cn"] = "发送另一条消息前你必须等待 {RBX_NUMBER} 秒！",
            ["zh-tw"] = "請 {RBX_NUMBER} 秒後再傳送訊息。",
        },
    },
    {
        Key = "GameChat_ChatFloodDetector_Message",
        Values = {
            ["de"] = "Du musst warten, bevor du eine weitere Nachricht senden kannst!",
            ["en-us"] = "You must wait before sending another message!",
            ["es"] = "¡Debes esperar antes de enviar otro mensaje!",
            ["es-es"] = "¡Debes esperar antes de enviar otro mensaje!",
            ["fr"] = "Vous devez attendre avant d'envoyer un autre message !",
            ["it"] = "Devi aspettare prima di inviare un altro messaggio!",
            ["ja"] = "少し待ってから次のメッセージを送ってください!",
            ["ko"] = "추가 메시지를 보내기 전에 기다려야 해요!",
            ["pt"] = "Você precisa esperar antes de enviar outra mensagem!",
            ["pt-br"] = "Você precisa esperar antes de enviar outra mensagem!",
            ["ru"] = "Необходимо подождать, прежде чем отправлять новое сообщение!",
            ["zh-cjv"] = "发送另一条消息前你必须等待！",
            ["zh-cn"] = "发送另一条消息前你必须等待！",
            ["zh-tw"] = "請稍後再傳送訊息。",
        },
    },
    {
        Key = "GameChat_ChatMessageValidator_SettingsError",
        Values = {
            ["de"] = "Aufgrund deiner Chateinstellungen kannst du keine Nachrichten senden.",
            ["en-us"] = "Your chat settings prevent you from sending messages.",
            ["es"] = "Tu configuración de chat te impide enviar mensajes.",
            ["es-es"] = "Tu configuración de chat te impide enviar mensajes.",
            ["fr"] = "Vos paramètres de chat vous empêchent d'envoyer des messages.",
            ["it"] = "Non puoi inviare messaggi per le impostazioni della tua chat.",
            ["ja"] = "メッセージが送れないチャット設定です。",
            ["ko"] = "채팅 설정 때문에 메시지를 보낼 수 없어요.",
            ["pt"] = "Suas configurações de chat impedem que você envie mensagens.",
            ["pt-br"] = "Suas configurações de chat impedem que você envie mensagens.",
            ["ru"] = "В ваших настройках чата заблокирована возможность отправлять сообщения.",
            ["zh-cjv"] = "你的聊天设置禁止你发送消息。",
            ["zh-cn"] = "你的聊天设置禁止你发送消息。",
            ["zh-tw"] = "您的聊天設定禁止您傳送訊息。",
        },
    },
    {
        Key = "GameChat_ChatMessageValidator_MaxLengthError",
        Values = {
            ["de"] = "Deine Nachricht überschreitet die zulässige Nachrichtenlänge.",
            ["en-us"] = "Your message exceeds the maximum message length.",
            ["es"] = "Tu mensaje supera la longitud máxima permitida.",
            ["es-es"] = "Tu mensaje supera la longitud máxima permitida.",
            ["fr"] = "Votre message dépasse la longueur maximale.",
            ["it"] = "Il tuo messaggio supera la lunghezza massima consentita.",
            ["ja"] = "メッセージが最大文字数を超えています。",
            ["ko"] = "메시지 길이 한도를 초과했어요.",
            ["pt"] = "Sua mensagem ultrapassa o tamanho máximo de mensagem.",
            ["pt-br"] = "Sua mensagem ultrapassa o tamanho máximo de mensagem.",
            ["ru"] = "Превышено максимально допустимое количество символов в сообщении.",
            ["zh-cjv"] = "你的消息已超过最大长度限制。",
            ["zh-cn"] = "你的消息已超过最大长度限制。",
            ["zh-tw"] = "您的訊息超過長度限制。",
        },
    },
    {
        Key = "GameChat_ChatMessageValidator_WhitespaceError",
        Values = {
            ["de"] = "Deine Nachricht enthält unzulässige Leerräume.",
            ["en-us"] = "Your message contains whitespace that is not allowed.",
            ["es"] = "Tu mensaje contiene espacios vacíos que no se permiten.",
            ["es-es"] = "Tu mensaje contiene espacios vacíos que no se permiten.",
            ["fr"] = "Votre message contient des espaces blancs qui sont interdits.",
            ["it"] = "Il tuo messaggio contiene spazi vuoti non consentiti.",
            ["ja"] = "メッセージに許可されていないスペースが含まれています。",
            ["ko"] = "메시지에 허용되지 않는 여백이 있어요.",
            ["pt"] = "Sua mensagem contém um espaço em branco, que não é permitido.",
            ["pt-br"] = "Sua mensagem contém um espaço em branco, que não é permitido.",
            ["ru"] = "Ваше сообщение содержит недопустимый пробел.",
            ["zh-cjv"] = "你的消息包含不被允许的空格。",
            ["zh-cn"] = "你的消息包含不被允许的空格。",
            ["zh-tw"] = "訊息禁止使用空白字元。",
        },
    },
    {
        Key = "GameChat_DoMuteCommand_CannotMuteSelf",
        Values = {
            ["de"] = "Du kannst dich nicht selbst stummschalten.",
            ["en-us"] = "You cannot mute yourself.",
            ["es"] = "No puedes silenciarte a ti mismo.",
            ["es-es"] = "No puedes silenciarte a ti mismo.",
            ["fr"] = "Vous ne pouvez pas vous bâillonner.",
            ["it"] = "Non puoi togliere la parola a te stesso.",
            ["ja"] = "自分をミュートすることは出来ません。",
            ["ko"] = "자신을 음소거할 수 없어요.",
            ["pt"] = "Você não pode silenciar a si mesmo.",
            ["pt-br"] = "Você não pode silenciar a si mesmo.",
            ["ru"] = "Невозможно добавить себя в список игнорируемых.",
            ["zh-cjv"] = "你无法将自己禁言。",
            ["zh-cn"] = "你无法将自己禁言。",
            ["zh-tw"] = "您無法將自己靜音。",
        },
    },
    {
        Key = "GameChat_MuteSpeaker_SpeakerDoesNotExist",
        Values = {
            ["de"] = "Sprecher:in „{RBX_NAME}“ existiert nicht.",
            ["en-us"] = "Speaker '{RBX_NAME}' does not exist.",
            ["es"] = "El usuario \"{RBX_NAME}\" no existe.",
            ["es-es"] = "El usuario \"{RBX_NAME}\" no existe.",
            ["fr"] = "L'interlocuteur {RBX_NAME} n'existe pas.",
            ["it"] = "Il giocatore \"{RBX_NAME}\" non esiste.",
            ["ja"] = "「{RBX_NAME}」は存在しません。",
            ["ko"] = "스피커 '{RBX_NAME}'이(가) 없어요.",
            ["pt"] = "'{RBX_NAME}' não existe.",
            ["pt-br"] = "'{RBX_NAME}' não existe.",
            ["ru"] = "Пользователя {RBX_NAME} не существует.",
            ["zh-cjv"] = "发言者“{RBX_NAME}”不存在。",
            ["zh-cn"] = "发言者“{RBX_NAME}”不存在。",
            ["zh-tw"] = "使用者「{RBX_NAME}」不存在。",
        },
    },
    {
        Key = "GameChat_PrivateMessaging_CannotChat",
        Values = {
            ["de"] = "Du kannst mit diesem Spieler bzw. dieser Spielerin nicht chatten.",
            ["en-us"] = "You are not able to chat with this person.",
            ["es"] = "No puedes chatear con este jugador.",
            ["es-es"] = "No puedes chatear con este jugador.",
            ["fr"] = "Vous ne pouvez pas discuter avec ce joueur.",
            ["it"] = "Non puoi chattare con questo giocatore.",
            ["ja"] = "このプレイヤーとチャットすることは出来ません。",
            ["ko"] = "이 플레이어와 채팅할 수 없어요.",
            ["pt"] = "Você não pode participar de chat com este jogador.",
            ["pt-br"] = "Você não pode participar de chat com este jogador.",
            ["ru"] = "Вы не можете общаться в чате с этим игроком.",
            ["zh-cjv"] = "你无法与此玩家聊天。",
            ["zh-cn"] = "你无法与此玩家聊天。",
            ["zh-tw"] = "您無法與此玩家聊天。",
        },
    },
    {
        Key = "GameChat_PrivateMessaging_CannotWhisperToSelf",
        Values = {
            ["de"] = "Du kannst dir nicht selbst etwas zuflüstern.",
            ["en-us"] = "You cannot whisper to yourself.",
            ["es"] = "No puedes enviarte mensajes privados a ti mismo.",
            ["es-es"] = "No puedes enviarte mensajes privados a ti mismo.",
            ["fr"] = "Vous ne pouvez pas murmurer à votre propre oreille.",
            ["it"] = "Non puoi aprire un canale privato con te stesso.",
            ["ja"] = "自分自身に話しかけることは出来ません。",
            ["ko"] = "자신에게 귓속말할 수 없어요.",
            ["pt"] = "Você não pode sussurrar para si mesmo.",
            ["pt-br"] = "Você não pode sussurrar para si mesmo.",
            ["ru"] = "Нельзя отправлять себе личные сообщения.",
            ["zh-cjv"] = "你无法与自己开启私人频道。",
            ["zh-cn"] = "你无法与自己开启私人频道。",
            ["zh-tw"] = "您無法與自己開啟私人頻道。",
        },
    },
    {
        Key = "GameChat_PrivateMessaging_NowChattingWith",
        Values = {
            ["de"] = "Du unterhältst dich nun privat mit {RBX_NAME}.",
            ["en-us"] = "You are now privately chatting with {RBX_NAME}",
            ["es"] = "Estás chateando en privado con {RBX_NAME}.",
            ["es-es"] = "Estás chateando en privado con {RBX_NAME}.",
            ["fr"] = "Maintenant, vous discutez en privé avec {RBX_NAME}",
            ["it"] = "Ora stai chattando in privato con {RBX_NAME}",
            ["ja"] = "あなたは現在、{RBX_NAME} さんとプライベートチャット中です。",
            ["ko"] = "현재 {RBX_NAME}님과 비공개 채팅 중이에요",
            ["pt"] = "Você agora está em um chat privado com {RBX_NAME}",
            ["pt-br"] = "Você agora está em um chat privado com {RBX_NAME}",
            ["ru"] = "Открыт канал для личного общения с пользователем {RBX_NAME}",
            ["zh-cjv"] = "你正在与“{RBX_NAME}”私聊",
            ["zh-cn"] = "你正在与“{RBX_NAME}”私聊",
            ["zh-tw"] = "您正在與{RBX_NAME}私聊",
        },
    },
    {
        Key = "GameChat_TeamChat_WelcomeMessage",
        Values = {
            ["de"] = "Dies ist ein privater Kanal für dich und deine Teammitglieder.",
            ["en-us"] = "This is a private channel between you and your team members.",
            ["es"] = "Este es un canal privado entre tú y los miembros de tu equipo.",
            ["es-es"] = "Este es un canal privado entre tú y los miembros de tu equipo.",
            ["fr"] = "Ceci est un canal privé entre les membres de votre équipe et vous.",
            ["it"] = "Questo è un canale privato tra te e i membri della tua squadra.",
            ["ja"] = "これはあなたとあなたのチームメンバーとのプライベートチャンネルです。",
            ["ko"] = "회원님과 팀원 간의 비공개 채널이에요.",
            ["pt"] = "Este é um canal privado entre você e os membros da sua equipe.",
            ["pt-br"] = "Este é um canal privado entre você e os membros da sua equipe.",
            ["ru"] = "Это канал для личного общения участников вашей команды.",
            ["zh-cjv"] = "这是你与团队成员之间的私人频道。",
            ["zh-cn"] = "这是你与团队成员之间的私人频道。",
            ["zh-tw"] = "這是您與隊伍成員的私人頻道。",
        },
    },
    {
        Key = "GameChat_TeamChat_CannotTeamChatIfNotInTeam",
        Values = {
            ["de"] = "Teamchat ist nur verfügbar, wenn du Mitglied eines Teams bist!",
            ["en-us"] = "You cannot team chat if you are not on a team!",
            ["es"] = "¡No puedes chatear con tu equipo si no formas parte de un equipo!",
            ["es-es"] = "¡No puedes chatear con tu equipo si no formas parte de un equipo!",
            ["fr"] = "Vous ne pouvez pas avoir de discussion d'équipe si vous n'appartenez pas à une équipe !",
            ["it"] = "Non puoi chattare con la squadra se non sei in una squadra!",
            ["ja"] = "チームに所属していなければチームチャットは出来ません。",
            ["ko"] = "팀에 속하지 않으면 팀 채팅을 이용할 수 없어요!",
            ["pt"] = "Você não pode participar de chat de equipe se não estiver em uma!",
            ["pt-br"] = "Você não pode participar de chat de equipe se não estiver em uma!",
            ["ru"] = "Вы не можете общаться в командном чате, если не состоите в команде!",
            ["zh-cjv"] = "如果你不在该团队，则无法进行团队聊天。",
            ["zh-cn"] = "如果你不在该团队，则无法进行团队聊天。",
            ["zh-tw"] = "若您不在隊伍中，您無法使用隊伍頻道。",
        },
    },
    {
        Key = "GameChat_TeamChat_NowInTeam",
        Values = {
            ["de"] = "Du bist nun Mitglied im Team „{RBX_NAME}“.",
            ["en-us"] = "You are now on the '{RBX_NAME}' team.",
            ["es"] = "Ahora formas parte del equipo \"{RBX_NAME}\".",
            ["es-es"] = "Ahora formas parte del equipo \"{RBX_NAME}\".",
            ["fr"] = "Vous êtes désormais dans l'équipe {RBX_NAME}.",
            ["it"] = "Ora sei nella squadra \"{RBX_NAME}\".",
            ["ja"] = "あなたは現在「{RBX_NAME}」チームに所属しています。",
            ["ko"] = "현재 '{RBX_NAME}'팀에 속해 있어요.",
            ["pt"] = "Você agora está na equipe '{RBX_NAME}'.",
            ["pt-br"] = "Você agora está na equipe '{RBX_NAME}'.",
            ["ru"] = "Вы вступили в команду {RBX_NAME}.",
            ["zh-cjv"] = "你正在团队“{RBX_NAME}”中。",
            ["zh-cn"] = "你正在团队“{RBX_NAME}”中。",
            ["zh-tw"] = "您在「{RBX_NAME}」隊伍。",
        },
    },
    {
        Key = "GameChat_ChatChannel_MutedInChannel",
        Values = {
            ["de"] = "Du wurdest stummgeschaltet und kannst in diesem Kanal nicht kommunizieren.",
            ["en-us"] = "You are muted and cannot talk in this channel",
            ["es"] = "Se te ha silenciado y no puedes hablar en este canal.",
            ["es-es"] = "Se te ha silenciado y no puedes hablar en este canal.",
            ["fr"] = "Vous êtes bâillonné et ne pouvez pas parler sur ce canal",
            ["it"] = "Non hai più la parola e non puoi chattare in questo canale",
            ["ja"] = "あなたはミュートされこのチャンネルで話すことは出来ません。",
            ["ko"] = "이 채널에서 음소거되어 이야기할 수 없어요",
            ["pt"] = "Você está silenciado(a) e não pode falar neste canal",
            ["pt-br"] = "Você está silenciado(a) e não pode falar neste canal",
            ["ru"] = "Вы добавлены в список игнорируемых и не можете общаться на этом канале",
            ["zh-cjv"] = "你已被禁言，无法在此频道聊天",
            ["zh-cn"] = "你已被禁言，无法在此频道聊天",
            ["zh-tw"] = "您遭到靜音，無法在此頻道聊天",
        },
    },
    {
        Key = "GameChat_ChatService_ChatFilterIssues",
        Values = {
            ["de"] = "Es gibt derzeit Probleme mit dem Chatfilter. Nachrichten können deshalb mit Verzögerung angezeigt werden.",
            ["en-us"] = "The chat filter is currently experiencing issues and messages may be slow to appear.",
            ["es"] = "El filtro del chat sufre problemas en este momento y es posible que los mensajes tarden un poco en aparecer.",
            ["es-es"] = "El filtro del chat sufre problemas en este momento y es posible que los mensajes tarden un poco en aparecer.",
            ["fr"] = "Le filtre de chat connaît actuellement des problèmes et les messages pourraient mettre du temps à apparaître.",
            ["it"] = "Il filtro della chat sta riscontrando dei problemi e i messaggi potrebbero apparire in ritardo.",
            ["ja"] = "現在、チャットフィルターに問題があるためメッセージの表示が遅れています。",
            ["ko"] = "현재 채팅 필터에 문제가 있어 메시지 표시가 느릴 수 있어요.",
            ["pt"] = "O filtro de chat está com problemas no momento e as mensagens podem demorar para aparecer.",
            ["pt-br"] = "O filtro de chat está com problemas no momento e as mensagens podem demorar para aparecer.",
            ["ru"] = "Могут возникать задержки в передаче сообщений из-за проблем с фильтром чата.",
            ["zh-cjv"] = "聊天过滤器当前遇到问题，消息显示可能出现延迟。",
            ["zh-cn"] = "聊天过滤器当前遇到问题，消息显示可能出现延迟。",
            ["zh-tw"] = "文字過濾系統發生問題，訊息可能會延遲顯示。",
        },
    },
    {
        Key = "GameChat_ChatService_YouHaveLeftChannel",
        Values = {
            ["de"] = "Du hast Kanal „{RBX_NAME}“ verlassen.",
            ["en-us"] = "You have left channel '{RBX_NAME}'",
            ["es"] = "Has salido del canal \"{RBX_NAME}\".",
            ["es-es"] = "Has salido del canal \"{RBX_NAME}\".",
            ["fr"] = "Vous avez quitté le canal {RBX_NAME}",
            ["it"] = "Hai lasciato il canale \"{RBX_NAME}\"",
            ["ja"] = "チャンネル 「{RBX_NAME}」を退出しました。",
            ["ko"] = "{RBX_NAME}' 채널에서 나왔어요",
            ["pt"] = "Você saiu do canal '{RBX_NAME}'",
            ["pt-br"] = "Você saiu do canal '{RBX_NAME}'",
            ["ru"] = "Вы покинули канал «{RBX_NAME}»",
            ["zh-cjv"] = "你已离开频道“{RBX_NAME}”",
            ["zh-cn"] = "你已离开频道“{RBX_NAME}”",
            ["zh-tw"] = "您已離開「{RBX_NAME}」頻道",
        },
    },
    {
        Key = "GameChat_ChatService_CannotLeaveChannel",
        Values = {
            ["de"] = "Du kannst diesen Kanal nicht verlassen.",
            ["en-us"] = "You cannot leave this channel.",
            ["es"] = "No puedes salir de este canal.",
            ["es-es"] = "No puedes salir de este canal.",
            ["fr"] = "Vous ne pouvez pas quitter ce canal.",
            ["it"] = "Non puoi lasciare questo canale.",
            ["ja"] = "このチャンネルを終了できません。",
            ["ko"] = "채널에서 나갈 수 없어요.",
            ["pt"] = "Você não pode sair deste canal.",
            ["pt-br"] = "Você não pode sair deste canal.",
            ["ru"] = "Вы не можете покинуть этот канал.",
            ["zh-cjv"] = "你无法离开此频道。",
            ["zh-cn"] = "你无法离开此频道。",
            ["zh-tw"] = "您無法離開此頻道。",
        },
    },
    {
        Key = "GameChat_ChatServiceRunner_YouCannotJoinChannel",
        Values = {
            ["de"] = "Du kannst Kanal „{RBX_NAME}“ nicht beitreten.",
            ["en-us"] = "You cannot join channel {RBX_NAME}",
            ["es"] = "No puedes unirte al canal {RBX_NAME}.",
            ["es-es"] = "No puedes unirte al canal {RBX_NAME}.",
            ["fr"] = "Vous ne pouvez pas rejoindre le canal {RBX_NAME}",
            ["it"] = "Non puoi accedere al canale {RBX_NAME}",
            ["ja"] = "チャンネル {RBX_NAME} に参加することは出来ません。",
            ["ko"] = "{RBX_NAME} 채널에 가입할 수 없어요",
            ["pt"] = "Você não pode entrar no canal {RBX_NAME}",
            ["pt-br"] = "Você não pode entrar no canal {RBX_NAME}",
            ["ru"] = "Вы не можете подключиться к каналу «{RBX_NAME}»",
            ["zh-cjv"] = "你无法加入频道“{RBX_NAME}”",
            ["zh-cn"] = "你无法加入频道“{RBX_NAME}”",
            ["zh-tw"] = "您無法加入{RBX_NAME} 頻道",
        },
    },
    {
        Key = "GameChat_ChatServiceRunner_ChannelDoesNotExist",
        Values = {
            ["de"] = "Kanal „{RBX_NAME}“ existiert nicht.",
            ["en-us"] = "Channel {RBX_NAME} does not exist.",
            ["es"] = "El canal {RBX_NAME} no existe.",
            ["es-es"] = "El canal {RBX_NAME} no existe.",
            ["fr"] = "Le canal {RBX_NAME} n'existe pas.",
            ["it"] = "Il canale {RBX_NAME} non esiste.",
            ["ja"] = "チャンネル {RBX_NAME} は存在しません。",
            ["ko"] = "{RBX_NAME} 채널이 없어요.",
            ["pt"] = "O canal {RBX_NAME} não existe.",
            ["pt-br"] = "O canal {RBX_NAME} não existe.",
            ["ru"] = "Канала «{RBX_NAME}» не существует.",
            ["zh-cjv"] = "频道“{RBX_NAME}”不存在。",
            ["zh-cn"] = "频道“{RBX_NAME}”不存在。",
            ["zh-tw"] = "頻道「{RBX_NAME}」不存在。",
        },
    },
    {
        Key = "GameChat_ChatServiceRunner_YouCannotLeaveChannel",
        Values = {
            ["de"] = "Du kannst Kanal „{RBX_NAME}“ nicht verlassen.",
            ["en-us"] = "You cannot leave channel {RBX_NAME}",
            ["es"] = "No puedes salir del canal {RBX_NAME}.",
            ["es-es"] = "No puedes salir del canal {RBX_NAME}.",
            ["fr"] = "Vous ne pouvez pas quitter le canal {RBX_NAME}",
            ["it"] = "Non puoi lasciare il canale {RBX_NAME}",
            ["ja"] = "チャンネル {RBX_NAME} を終了できません。",
            ["ko"] = "{RBX_NAME} 채널에서 나갈 수 없어요",
            ["pt"] = "Você não pode sair do canal {RBX_NAME}",
            ["pt-br"] = "Você não pode sair do canal {RBX_NAME}",
            ["ru"] = "Вы не можете покинуть канал «{RBX_NAME}».",
            ["zh-cjv"] = "你无法离开频道“{RBX_NAME}”",
            ["zh-cn"] = "你无法离开频道“{RBX_NAME}”",
            ["zh-tw"] = "您無法離開 {RBX_NAME} 頻道",
        },
    },
    {
        Key = "GameChat_ChatServiceRunner_YouAreNotInChannel",
        Values = {
            ["de"] = "Du befindest dich nicht in Kanal „{RBX_NAME}“.",
            ["en-us"] = "You are not in channel {RBX_NAME}",
            ["es"] = "No estás en el canal {RBX_NAME}.",
            ["es-es"] = "No estás en el canal {RBX_NAME}.",
            ["fr"] = "Vous n'êtes pas sur le canal {RBX_NAME}",
            ["it"] = "Non ti trovi nel canale {RBX_NAME}",
            ["ja"] = "あなたはチャンネル {RBX_NAME} にいません。",
            ["ko"] = "{RBX_NAME} 채널에 있지 않아요",
            ["pt"] = "Você não está no canal {RBX_NAME}",
            ["pt-br"] = "Você não está no canal {RBX_NAME}",
            ["ru"] = "Вы не на канале «{RBX_NAME}»",
            ["zh-cjv"] = "你不在频道“{RBX_NAME}”",
            ["zh-cn"] = "你不在频道“{RBX_NAME}”",
            ["zh-tw"] = "您不在 {RBX_NAME} 頻道",
        },
    },
    {
        Key = "GameChat_ChatServiceRunner_SystemChannelWelcomeMessage",
        Values = {
            ["de"] = "Dieser Kanal ist für System- und Spielbenachrichtigungen.",
            ["en-us"] = "This channel is for system and experience notifications.",
            ["es"] = "Este canal es para notificaciones del sistema y del juego.",
            ["es-es"] = "Este canal es para notificaciones del sistema y del juego.",
            ["fr"] = "Ce canal est réservé aux notifications système et de jeu.",
            ["it"] = "Questo canale è per le notifiche di gioco e del sistema.",
            ["ja"] = "このチャンネルはシステムとゲーム通知のためのものです。",
            ["ko"] = "이 채널은 시스템 및 게임 알림용이에요.",
            ["pt"] = "Este canal é destinado a notificações do sistema e jogo.",
            ["pt-br"] = "Este canal é destinado a notificações do sistema e jogo.",
            ["ru"] = "Этот канал предназначен для системных и игровых уведомлений.",
            ["zh-cjv"] = "此频道用于发送系统及挑战通知。",
            ["zh-cn"] = "此频道用于发送系统及游戏通知。",
            ["zh-tw"] = "此頻道為系統及遊戲通知專用。",
        },
    },
    {
        Key = "GameChat_FriendChatNotifier_JoinMessage",
        Values = {
            ["de"] = "Dein:e Freund:in {RBX_NAME} ist dem Spiel beigetreten.",
            ["en-us"] = "Your friend {RBX_NAME} has joined the experience.",
            ["es"] = "Tu amigo {RBX_NAME} se ha unido al juego.",
            ["es-es"] = "Tu amigo {RBX_NAME} se ha unido al juego.",
            ["fr"] = "Votre ami {RBX_NAME} a rejoint le jeu.",
            ["it"] = "Il tuo amico {RBX_NAME} è entrato nel gioco.",
            ["ja"] = "あなたの友人、{RBX_NAME} さんがゲームに参加しました。",
            ["ko"] = "친구 {RBX_NAME}님이 게임에 참가했어요.",
            ["pt"] = "Seu amigo {RBX_NAME} juntou-se ao jogo.",
            ["pt-br"] = "Seu amigo {RBX_NAME} juntou-se ao jogo.",
            ["ru"] = "Ваш друг {RBX_NAME} присоединился к игре.",
            ["zh-cjv"] = "你的朋友“{RBX_NAME}”已加入挑战。",
            ["zh-cn"] = "你的朋友“{RBX_NAME}”已加入游戏。",
            ["zh-tw"] = "您的好友 {RBX_NAME} 已加入遊戲。",
        },
    },
    {
        Key = "InGame.Chat.Response.EmoteNotAvailable",
        Values = {
            ["de"] = "Du kannst dieses Emote nicht benutzen.",
            ["en-us"] = "You can't use that Emote.",
            ["es"] = "No puedes usar ese emoticono.",
            ["es-es"] = "No puedes usar ese emoticono.",
            ["fr"] = "Tu ne peux pas utiliser cette Emote.",
            ["it"] = "Non puoi usare quell'emoticon.",
            ["ja"] = "そのエモートは使えません。",
            ["ko"] = "이 감정 표현은 사용할 수 없어요.",
            ["pt"] = "Você não pode usar esse emote.",
            ["pt-br"] = "Você não pode usar esse emote.",
            ["ru"] = "Вы не можете использовать эту эмоцию.",
            ["zh-cjv"] = "无法使用该动作。",
            ["zh-cn"] = "无法使用该动作。",
            ["zh-tw"] = "無法使用該動作。",
        },
    },
    {
        Key = "InGame.Chat.Response.EmotesNotSupported",
        Values = {
            ["de"] = "Du kannst hier keine Emotes verwenden.",
            ["en-us"] = "You can't use Emotes here.",
            ["es"] = "No puedes usar emoticonos aquí.",
            ["es-es"] = "No puedes usar emoticonos aquí.",
            ["fr"] = "Tu ne peux pas utiliser les Emotes ici.",
            ["it"] = "Qui non puoi usare le emoticon.",
            ["ja"] = "ここではエモートはここでは使えません。",
            ["ko"] = "여기서는 감정 표현을 사용할 수 없어요.",
            ["pt"] = "Você não pode usar emotes aqui.",
            ["pt-br"] = "Você não pode usar emotes aqui.",
            ["ru"] = "Здесь нельзя использовать эмоции.",
            ["zh-cjv"] = "无法在此挑战中使用动作。",
            ["zh-cn"] = "无法在此游戏中使用动作。",
            ["zh-tw"] = "無法在此遊戲使用動作。",
        },
    },
    {
        Key = "InGame.Chat.Response.EmotesWrongAvatarType",
        Values = {
            ["de"] = "Nur R15 Avatars können Emotes verwenden.",
            ["en-us"] = "Only R15 avatars can use Emotes.",
            ["es"] = "Solo los avatares R15 pueden usar emoticonos.",
            ["es-es"] = "Solo los avatares R15 pueden usar emoticonos.",
            ["fr"] = "Seuls les avatars R15 peuvent utiliser les Emotes.",
            ["it"] = "Solo gli avatar R15 possono usare le emoticon.",
            ["ja"] = "R15指定のアバターのみエモートを使えます。",
            ["ko"] = "R15 아바타만 감정 표현을 사용할 수 있어요.",
            ["pt"] = "Apenas avatares R15 podem usar emotes.",
            ["pt-br"] = "Apenas avatares R15 podem usar emotes.",
            ["ru"] = "Только аватары R15 могут использовать эмоции.",
            ["zh-cjv"] = "只有 R15 虚拟形象可以使用动作。",
            ["zh-cn"] = "只有 R15 虚拟形象可以使用动作。",
            ["zh-tw"] = "只有 R15 虛擬人偶可以使用動作。",
        },
    },
    {
        Key = "InGame.Chat.Response.EmotesTemporarilyUnavailable",
        Values = {
            ["de"] = "You can't use Emotes right now.",
            ["en-us"] = "You can't use Emotes right now.",
            ["es"] = "No puedes usar emoticonos en este momento.",
            ["es-es"] = "No puedes usar emoticonos en este momento.",
            ["fr"] = "Tu ne peux pas utiliser d'Emote maintenant.",
            ["it"] = "Adesso non puoi usare le emoticon.",
            ["ja"] = "今はエモートを使えません。",
            ["ko"] = "지금은 감정 표현을 사용할 수 없어요.",
            ["pt"] = "Você não pode usar emotes no momento.",
            ["pt-br"] = "Você não pode usar emotes no momento.",
            ["ru"] = "Вы не можете использовать эмоции прямо сейчас.",
            ["zh-cjv"] = "当前无法使用动作。",
            ["zh-cn"] = "当前无法使用动作。",
            ["zh-tw"] = "現在無法使用動作。",
        },
    },
    {
        Key = "InGame.Chat.Label.SystemMessagePrefix",
        Values = {
            ["de"] = "System",
            ["en-us"] = "System",
            ["es"] = "Sistema",
            ["es-es"] = "Sistema",
            ["fr"] = "Système",
            ["it"] = "Sistema",
            ["ja"] = "システム",
            ["ko"] = "시스템",
            ["pt"] = "Sistema",
            ["pt-br"] = "Sistema",
            ["ru"] = "Система",
            ["zh-cjv"] = "系统",
            ["zh-cn"] = "系统",
            ["zh-tw"] = "系統",
        },
    },
    {
        Key = "InGame.Chat.Label.TeamMessagePrefix",
        Values = {
            ["de"] = "Team",
            ["en-us"] = "Team",
            ["es"] = "Equipo",
            ["es-es"] = "Equipo",
            ["fr"] = "Équipe",
            ["it"] = "Squadra",
            ["ja"] = "チーム",
            ["ko"] = "팀",
            ["pt"] = "Equipe",
            ["pt-br"] = "Equipe",
            ["ru"] = "Команда",
            ["zh-cjv"] = "队伍",
            ["zh-cn"] = "队伍",
            ["zh-tw"] = "隊伍",
        },
    },
    {
        Key = "InGame.Chat.Label.From",
        Values = {
            ["de"] = "Von",
            ["en-us"] = "From",
            ["es"] = "De",
            ["es-es"] = "De",
            ["fr"] = "De",
            ["it"] = "Da",
            ["ja"] = "から",
            ["ko"] = "발신:",
            ["pt"] = "De",
            ["pt-br"] = "De",
            ["ru"] = "От ",
            ["zh-cjv"] = "来自于",
            ["zh-cn"] = "来自于",
            ["zh-tw"] = "自",
        },
    },
    {
        Key = "InGame.Chat.Label.To",
        Values = {
            ["de"] = "Bis",
            ["en-us"] = "To",
            ["es"] = "Para",
            ["es-es"] = "Para",
            ["fr"] = "À",
            ["it"] = "A",
            ["ja"] = "へ",
            ["ko"] = "수신:",
            ["pt"] = "Para",
            ["pt-br"] = "Para",
            ["ru"] = "Для",
            ["zh-cjv"] = "发送至",
            ["zh-cn"] = "发送至",
            ["zh-tw"] = "對",
        },
    },
    {
        Key = "InGame.Chat.Response.DisplayNameMultipleMatches",
        Values = {
            ["de"] = "Warnung: Die folgenden Benutzer:innen haben diesen angezeigten Namen: ",
            ["en-us"] = "Warning: The following users have this display name: ",
            ["es"] = "Advertencia: Los siguientes jugadores tienen este nombre de usuario: ",
            ["es-es"] = "Advertencia: Los siguientes jugadores tienen este nombre de usuario: ",
            ["fr"] = "Avertissement - Les utilisateurs suivants ont ce nom d'affichage : ",
            ["it"] = "Attenzione, i seguenti utenti hanno questo nome: ",
            ["ja"] = "警告: 以下のユーザーには、この表示名があります: ",
            ["ko"] = "주의: 다음 사용자들이 이 표시 이름을 사용하고 있습니다.",
            ["pt"] = "Aviso! Os seguintes usuários têm esse nome de exibição: ",
            ["pt-br"] = "Aviso! Os seguintes usuários têm esse nome de exibição: ",
            ["ru"] = "Внимание! Такое имя есть у нескольких пользователей: ",
            ["zh-cjv"] = "注意：以下用户正在使用此昵称：",
            ["zh-cn"] = "注意：以下用户正在使用此昵称：",
            ["zh-tw"] = "注意：以下使用者正在使用此顯示名稱：",
        },
    },
    {
        Key = "InGame.Chat.ErrorMessageSwitchToR15",
        Values = {
            ["de"] = "Wechsle zu deinem R15-Avatar, um das Emote abzuspielen.",
            ["en-us"] = "Switch to your R15 avatar to play Emote.",
            ["es"] = "Cambia tu avatar a R15 para usar los emotes.",
            ["es-es"] = "Cambia tu avatar a R15 para usar los emotes.",
            ["fr"] = "Passe à ton avatar R15 pour jouer à Emote.",
            ["it"] = "Passa al tuo avatar R15 per giocare a Emote.",
            ["ja"] = "エモートを表示するにはR15アバターに切り替えてください。",
            ["ko"] = "감정 표현을 적용하려면 R15 아바타로 전환하세요.",
            ["pt"] = "Mude seu avatar para o modelo R15 para usar emotes.",
            ["pt-br"] = "Mude seu avatar para o modelo R15 para usar emotes.",
            ["zh-cjv"] = "切换成 R15 虚拟形象以使用此动作。",
            ["zh-cn"] = "切换成 R15 虚拟形象以使用此动作。",
            ["zh-tw"] = "切換成 R15 虛擬人偶即可使用此動作。",
        },
    },
    {
        Key = "InGame.Chat.ErrorMessageAnimationPlaying",
        Values = {
            ["de"] = "Du kannst das Emote während dieser Aktion nicht abspielen.",
            ["en-us"] = "You cannot play Emotes during this action.",
            ["es"] = "No puedes usar los emotes durante esta acción.",
            ["es-es"] = "No puedes usar los emotes durante esta acción.",
            ["fr"] = "Tu ne peux pas jouer à Emotes pendant cette action.",
            ["it"] = "Non puoi giocare Emote durante questa azione.",
            ["ja"] = "この動作中はエモートを表示できません。",
            ["ko"] = "이 동작 중에는 감정 표현을 적용할 수 없습니다.",
            ["pt"] = "Você não pode usar emotes durante esta ação.",
            ["pt-br"] = "Você não pode usar emotes durante esta ação.",
            ["zh-cjv"] = "无法在此动作进行时使用其他动作。",
            ["zh-cn"] = "无法在此动作进行时使用其他动作。",
            ["zh-tw"] = "無法在此動作執行時使用其他動作。",
        },
    },
}
