-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("DynamicHeadExportTool")
local var1 = require(var0.Src.Constants)
local var2 = require(var0.Src.Actions.SetEnabled)
local var3 = require(var0.Src.Actions.SetErrorText)
local var4 = require(var0.Src.Actions.SetScreen)
return function(arg1, arg2)
   local var57 = var2(true)
   arg1:dispatch()
   local var61 = var3(arg2)
   arg1:dispatch()
   local var2 = var4(var1.Screens.Error)
   arg1:dispatch()
end
