return function()

	local UrlBuilder = require(script.Parent.Parent.UrlBuilder)

	describe("info/community-guidelines", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.about.guidelines()
			expect(url).to.equal("https://www.roblox.com/info/community-guidelines")
		end)
	end)

	describe("info/terms", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.about.terms()
			expect(url).to.equal("https://www.roblox.com/info/terms")
		end)
	end)

	describe("support", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.about.support()
			expect(url).to.equal("https://www.roblox.com/support")
		end)
	end)

	describe("settings/account", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.settings.account()
			expect(url).to.equal("https://www.roblox.com/my/account#!/info")
		end)
	end)

	describe("settings/security", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.settings.security()
			expect(url).to.equal("https://www.roblox.com/my/account#!/security")
		end)
	end)

	describe("settings/privacy", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.settings.privacy()
			expect(url).to.equal("https://www.roblox.com/my/account#!/privacy")
		end)
	end)

	describe("settings/parentalControls", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.settings.parentalControls()
			expect(url).to.equal("https://www.roblox.com/my/account#!/parental-controls")
		end)
	end)

	describe("settings/billing", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.settings.billing()
			expect(url).to.equal("https://www.roblox.com/my/account#!/billing")
		end)
	end)

	describe("settings/notifications", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.settings.notifications()
			expect(url).to.equal("https://www.roblox.com/my/account#!/notifications")
		end)
	end)

	describe("tencent/luobuThirdPartyDataUse", function()
		it("should generate proper url", function()
			local url = UrlBuilder.static.tencent.luobuThirdPartyDataUse()
			expect(url).to.equal("https://game.qq.com/zlkdatasys/privacy_SDK.html")
		end)
	end)
end
