--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["UniversalAppPolicy"]["UniversalAppPolicy"])

export type AppFeaturePolicies = Package.AppFeaturePolicies
export type AvatarPolicies = Package.AvatarPolicies
export type ChatPolicies = Package.ChatPolicies
export type SharePolicies = Package.SharePolicies
export type ShareTargetGamePolicies = Package.ShareTargetGamePolicies
export type Policies = Package.Policies
export type MorePageLayout = Package.MorePageLayout
export type CrossPlayCapability = Package.CrossPlayCapability


return Package
