[package]
name = "LazyRequire"
version = "0.1.4"
content_root = "src"
files = [
    "*",
    "!**/*.test.lua",
    "!**/*.spec.lua",
]
publish = true
[dependencies.Cryo]
version = "^1.1.0"

[dependencies.React]
version = "^17.0.3"
