--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["RobloxShared-edcba0e9-2.4.1"]["RobloxShared"])

export type Writeable = Package.Writeable


return Package
