--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["ReactRoblox-a406e214-4230f473"]["ReactRoblox"])

export type RootType = Package.RootType


return Package
