-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.NAME = "AvatarImporter"
var0.TITLE = "Avatar Importer"
var0.TOOLBAR_NAME = "Avatar"
var0.BUTTON_NAME = "Avatar Importer"
var0.BUTTON_TOOLTIP = "Import an Avatar with a .fbx file"
var0.AVATAR_IMPORTER_DEVHUB = "articles/using-avatar-importer"
var0.AVATAR_IMPORTER_DEVHUB_URL = "https://developer.roblox.com/en-us/articles/using-avatar-importer"
local var142 = {}
var142.RTHRO = "Rthro"
var142.RTHRO_SLENDER = "RthroSlender"
var142.R15 = "R15"
var142.CUSTOM = "Custom"
var0.AVATAR_TYPE = var142
local var147 = {}
var147.Rthro = "ProportionsNormal"
var147.RthroSlender = "ProportionsSlender"
var147.R15 = "Classic"
var0.TYPE_TO_SCALE = var147
local var151 = {}
var151.title = "Rthro Type"
var151.height = 6.25
var151.description = "shoulders wider than hips"
var0.RTHRO_INFO = var151
local var155 = {}
var155.title = "Rthro Slender Type"
var155.height = 5.625
var155.description = "shoulders narrower than hips"
var0.RTHRO_SLENDER_INFO = var155
local var159 = {}
var159.title = "R15 Type"
var159.height = 5
var0.R15_INFO = var159
local var162 = {}
var162.title = "Custom Type"
var0.CUSTOM_INFO = var162
var0.BUTTON_AMT = 4
var0.BUTTON_WIDTH = 146
var0.BUTTON_HEIGHT = 219
var0.BUTTON_SIDE_PADDING = 67
var0.BUTTON_CENTER_PADDING = 37
var0.BUTTON_TOP_PADDING = 63
var0.BACKGROUND_WIDTH = var0.BUTTON_SIDE_PADDING + var0.BUTTON_WIDTH * var0.BUTTON_AMT + var0.BUTTON_CENTER_PADDING * (var0.BUTTON_AMT - 1) + var0.BUTTON_SIDE_PADDING
local var182 = 413
var0.BACKGROUND_HEIGHT = var182
var182 = require(script.Parent.Parent.src.utils.convertArrayToTable)
local var185 = "LOADING"
local var9 = "ERROR"
local var10 = "REDIRECT_RIG"
var0.SCREENS = var182({ "AVATAR" })
local var192 = {}
var192.HeadScale = 1
var192.BodyHeightScale = 1
var192.BodyWidthScale = 1
var192.BodyDepthScale = 1
var192.BodyTypeScale = 0
var192.BodyProportionScale = 0
var0.AVATAR_TYPE.R15 = var192
local var201 = {}
var201.HeadScale = 1
var201.BodyHeightScale = 1
var201.BodyWidthScale = 1
var201.BodyDepthScale = 1
var201.BodyTypeScale = 1
var201.BodyProportionScale = 0
var0.AVATAR_TYPE.RTHRO = var201
local var13 = {}
var13.HeadScale = 1
var13.BodyHeightScale = 1
var13.BodyWidthScale = 1
var13.BodyDepthScale = 1
var13.BodyTypeScale = 1
var13.BodyProportionScale = 1
var0.AVATAR_TYPE.RTHRO_SLENDER = var13
var0.SCALE_VALUES_DEFAULTS = {}
var0.ERROR_NO_FILE = "No FBX file selected"
var0.FONT = Enum.Font.SourceSans
var0.FONT_SEMIBOLD = Enum.Font.SourceSansSemibold
var0.FONT_BOLD = Enum.Font.SourceSansBold
var0.FONT_SIZE_SMALL = 14
var0.FONT_SIZE_MEDIUM = 16
var0.FONT_SIZE_LARGE = 18
var0.FONT_SIZE_TITLE = 20
var0.REQUIREMENTS_DESCRIPTION = "Avatar file needs to be FBX file following Avatar types and import requirements"
var0.REQUIREMENTS_LINK_TEXT = "What are Avatar types and import requirements?"
var0.WARNING_COLOR = Color3.fromHex("#FFC107")
var0.WARNING_TEXT_COLOR = Color3.fromHex("#212529")
return var0
