-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.NAME = "AvatarImporter"
var0.TITLE = "Avatar Importer"
var0.TOOLBAR_NAME = "Avatar"
var0.BUTTON_NAME = "Avatar Importer"
var0.BUTTON_TOOLTIP = "Import an Avatar with a .fbx file"
var0.AVATAR_IMPORTER_DEVHUB = "articles/using-avatar-importer"
var0.AVATAR_IMPORTER_DEVHUB_URL = "https://developer.roblox.com/en-us/articles/using-avatar-importer"
var0.CLICK_HERE = "Click here to learn more."
local var143 = {}
var143.RTHRO = "Rthro"
var143.RTHRO_SLENDER = "RthroSlender"
var143.R15 = "R15"
var143.CUSTOM = "Custom"
var0.AVATAR_TYPE = var143
local var148 = {}
var148.Rthro = "ProportionsNormal"
var148.RthroSlender = "ProportionsSlender"
var148.R15 = "Classic"
var0.TYPE_TO_SCALE = var148
local var152 = {}
var152.title = "Rthro Type"
var152.height = 6.25
var152.description = "shoulders wider than hips"
var0.RTHRO_INFO = var152
local var156 = {}
var156.title = "Rthro Slender Type"
var156.height = 5.625
var156.description = "shoulders narrower than hips"
var0.RTHRO_SLENDER_INFO = var156
local var160 = {}
var160.title = "R15 Type"
var160.height = 5
var0.R15_INFO = var160
local var163 = {}
var163.title = "Custom Type"
var0.CUSTOM_INFO = var163
var0.BUTTON_AMT = 4
var0.BUTTON_WIDTH = 146
var0.BUTTON_HEIGHT = 219
var0.BUTTON_SIDE_PADDING = 67
var0.BUTTON_CENTER_PADDING = 37
var0.BUTTON_TOP_PADDING = 63
var0.BACKGROUND_WIDTH = var0.BUTTON_SIDE_PADDING + var0.BUTTON_WIDTH * var0.BUTTON_AMT + var0.BUTTON_CENTER_PADDING * (var0.BUTTON_AMT - 1) + var0.BUTTON_SIDE_PADDING
local var183 = 413
var0.BACKGROUND_HEIGHT = var183
var183 = require(script.Parent.Parent.src.utils.convertArrayToTable)
local var186 = "LOADING"
local var9 = "ERROR"
local var10 = "REDIRECT_RIG"
var0.SCREENS = var183({ "AVATAR" })
local var193 = {}
var193.HeadScale = 1
var193.BodyHeightScale = 1
var193.BodyWidthScale = 1
var193.BodyDepthScale = 1
var193.BodyTypeScale = 0
var193.BodyProportionScale = 0
var0.AVATAR_TYPE.R15 = var193
local var202 = {}
var202.HeadScale = 1
var202.BodyHeightScale = 1
var202.BodyWidthScale = 1
var202.BodyDepthScale = 1
var202.BodyTypeScale = 1
var202.BodyProportionScale = 0
var0.AVATAR_TYPE.RTHRO = var202
local var13 = {}
var13.HeadScale = 1
var13.BodyHeightScale = 1
var13.BodyWidthScale = 1
var13.BodyDepthScale = 1
var13.BodyTypeScale = 1
var13.BodyProportionScale = 1
var0.AVATAR_TYPE.RTHRO_SLENDER = var13
var0.SCALE_VALUES_DEFAULTS = {}
var0.ERROR_NO_FILE = "No FBX file selected"
var0.FONT = Enum.Font.SourceSans
var0.FONT_SEMIBOLD = Enum.Font.SourceSansSemibold
var0.FONT_BOLD = Enum.Font.SourceSansBold
var0.FONT_SIZE_SMALL = 14
var0.FONT_SIZE_MEDIUM = 16
var0.FONT_SIZE_LARGE = 18
var0.FONT_SIZE_TITLE = 20
var0.REQUIREMENTS_DESCRIPTION = "Avatar file needs to be FBX file following Avatar types and import requirements"
var0.REQUIREMENTS_LINK_TEXT = "What are Avatar types and import requirements?"
var0.WARNING_COLOR = Color3.fromHex("#FFC107")
var0.WARNING_TEXT_COLOR = Color3.fromHex("#212529")
return var0
