-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent
local var1 = require(var0.Packages.Roact)
local var2 = require(var0.Src.Util.Constants)
local var3 = require(var0.Packages.Framework)
local var4 = var3.ContextServices
local var5 = var3.UI
local var6 = var5.Button
local var7 = var5.Dialog
local var8 = var1.PureComponent:extend("MovedDialog")
local function fun0(arg1)
   local var0 = arg1.props
   local var1 = var0.Localization
   local var2 = arg1.props.Stylizer
   local var34 = {}
   var34.Title = var1:getText("Moved", "Title")
   var34.Enabled = true
   var34.Modal = true
   var34.Size = Vector2.new(var2.MOVED_DIALOG_WIDTH, var2.MOVED_DIALOG_HEIGHT)
   var34.Resizable = false
   var34.OnClose = var0.OnClose
   local var49 = {}
   local var53 = {}
   var53.Size = UDim2.new(1, 0, 1, 0)
   var53.BackgroundColor3 = var2.BackgroundColor
   local var61 = {}
   local var65 = {}
   var65.Size = UDim2.new(1, 0, 0, var2.MOVED_DIALOG_LABEL_HEIGHT)
   var65.Position = UDim2.new(0, var2.MOVED_DIALOG_SIDE_PADDING, 0, var2.MOVED_DIALOG_TOP_PADDING)
   var65.AnchorPoint = Vector2.new(0, 0)
   var65.Text = var1:getText("Moved", "MovedMessage")
   var65.TextSize = 22
   var65.TextColor3 = var2.TextColor
   var65.TextXAlignment = Enum.TextXAlignment.Left
   var65.Font = Enum.Font.SourceSans
   var65.BackgroundTransparency = 1
   var61.Label = var1.createElement("TextLabel", var65)
   local var98 = {}
   var98.Size = UDim2.new(1, 0, 0, var2.MOVED_DIALOG_LABEL_HEIGHT)
   var98.Position = UDim2.new(0, var2.MOVED_DIALOG_SIDE_PADDING, 0, var2.MOVED_DIALOG_TOP_PADDING + var2.MOVED_DIALOG_LABEL_HEIGHT + var2.MOVED_DIALOG_INTRA_PADDING)
   var98.AnchorPoint = Vector2.new(0, 0)
   var98.Text = var1:getText("Moved", "NewLocationMessage")
   var98.TextSize = 17
   var98.TextColor3 = var2.TextColor
   var98.TextXAlignment = Enum.TextXAlignment.Left
   var98.Font = Enum.Font.SourceSansLight
   var98.BackgroundTransparency = 1
   var61.Label2 = var1.createElement("TextLabel", var98)
   local var137 = {}
   var137.AnchorPoint = Vector2.new(0.5, 1)
   var137.Position = UDim2.new(0.5, 0, 1, var2.MOVED_DIALOG_BOTTOM_PADDING)
   var137.Size = UDim2.new(0, var2.MOVED_DIALOG_BUTTON_WIDTH, 0, var2.MOVED_DIALOG_BUTTON_HEIGHT)
   var137.OnClick = var0.OnClose
   var137.Style = "RoundPrimary"
   local var160 = {}
   local var164 = {}
   var164.Size = UDim2.new(1, 0, 1, 0)
   var164.Text = var1:getText("Moved", "GotIt")
   var164.TextColor3 = var2.White
   var164.Font = Enum.Font.SourceSans
   var164.TextSize = 19
   var164.BackgroundTransparency = 1
   var160.Label = var1.createElement("TextLabel", var164)
   var61.CloseButton = var1.createElement(var6, var137, var160)
   var49.Background = var1.createElement("Frame", var53, var61)
   return var1.createElement(var7, var34, var49)
end

function var8.render(arg1)
   local var0 = arg1.props
   local var1 = var0.Localization
   local var2 = arg1.props.Stylizer
   local var34 = {}
   var34.Title = var1:getText("Moved", "Title")
   var34.Enabled = true
   var34.Modal = true
   var34.Size = Vector2.new(var2.MOVED_DIALOG_WIDTH, var2.MOVED_DIALOG_HEIGHT)
   var34.Resizable = false
   var34.OnClose = var0.OnClose
   local var49 = {}
   local var53 = {}
   var53.Size = UDim2.new(1, 0, 1, 0)
   var53.BackgroundColor3 = var2.BackgroundColor
   local var61 = {}
   local var65 = {}
   var65.Size = UDim2.new(1, 0, 0, var2.MOVED_DIALOG_LABEL_HEIGHT)
   var65.Position = UDim2.new(0, var2.MOVED_DIALOG_SIDE_PADDING, 0, var2.MOVED_DIALOG_TOP_PADDING)
   var65.AnchorPoint = Vector2.new(0, 0)
   var65.Text = var1:getText("Moved", "MovedMessage")
   var65.TextSize = 22
   var65.TextColor3 = var2.TextColor
   var65.TextXAlignment = Enum.TextXAlignment.Left
   var65.Font = Enum.Font.SourceSans
   var65.BackgroundTransparency = 1
   var61.Label = var1.createElement("TextLabel", var65)
   local var98 = {}
   var98.Size = UDim2.new(1, 0, 0, var2.MOVED_DIALOG_LABEL_HEIGHT)
   var98.Position = UDim2.new(0, var2.MOVED_DIALOG_SIDE_PADDING, 0, var2.MOVED_DIALOG_TOP_PADDING + var2.MOVED_DIALOG_LABEL_HEIGHT + var2.MOVED_DIALOG_INTRA_PADDING)
   var98.AnchorPoint = Vector2.new(0, 0)
   var98.Text = var1:getText("Moved", "NewLocationMessage")
   var98.TextSize = 17
   var98.TextColor3 = var2.TextColor
   var98.TextXAlignment = Enum.TextXAlignment.Left
   var98.Font = Enum.Font.SourceSansLight
   var98.BackgroundTransparency = 1
   var61.Label2 = var1.createElement("TextLabel", var98)
   local var137 = {}
   var137.AnchorPoint = Vector2.new(0.5, 1)
   var137.Position = UDim2.new(0.5, 0, 1, var2.MOVED_DIALOG_BOTTOM_PADDING)
   var137.Size = UDim2.new(0, var2.MOVED_DIALOG_BUTTON_WIDTH, 0, var2.MOVED_DIALOG_BUTTON_HEIGHT)
   var137.OnClick = var0.OnClose
   var137.Style = "RoundPrimary"
   local var160 = {}
   local var164 = {}
   var164.Size = UDim2.new(1, 0, 1, 0)
   var164.Text = var1:getText("Moved", "GotIt")
   var164.TextColor3 = var2.White
   var164.Font = Enum.Font.SourceSans
   var164.TextSize = 19
   var164.BackgroundTransparency = 1
   var160.Label = var1.createElement("TextLabel", var164)
   var61.CloseButton = var1.createElement(var6, var137, var160)
   var49.Background = var1.createElement("Frame", var53, var61)
   return var1.createElement(var7, var34, var49)
end

fun0 = var4.withContext
local var183 = {}
var183.Localization = var4.Localization
var183.Stylizer = var4.Stylizer
var8 = fun0(var183)(var8)
return var8
