-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent
local var1 = require(var0.Packages.Roact)
local var2 = require(var0.Src.Util.Constants)
local var3 = require(var0.Packages.Framework)
local var4 = var3.ContextServices
local var5 = var3.UI
local var6 = var5.Button
local var7 = var5.Dialog
local var8 = var1.PureComponent:extend("MovedDialog")
local function fun0(arg1)
   local var0 = arg1.props
   local var1 = var0.Localization
   local var2 = arg1.props.Stylizer
   local var53 = {}
   var53.Title = var1:getText("Moved", "Title")
   var53.Enabled = true
   var53.Modal = true
   var53.Size = Vector2.new(var2.MOVED_DIALOG_WIDTH, var2.MOVED_DIALOG_HEIGHT)
   var53.Resizable = false
   var53.OnClose = var0.OnClose
   local var68 = {}
   local var72 = {}
   var72.Size = UDim2.new(1, 0, 1, 0)
   var72.BackgroundColor3 = var2.BackgroundColor
   local var80 = {}
   local var84 = {}
   var84.Size = UDim2.new(1, 0, 0, var2.MOVED_DIALOG_LABEL_HEIGHT)
   var84.Position = UDim2.new(0, var2.MOVED_DIALOG_SIDE_PADDING, 0, var2.MOVED_DIALOG_TOP_PADDING)
   var84.AnchorPoint = Vector2.new(0, 0)
   var84.Text = var1:getText("Moved", "MovedMessage")
   var84.TextSize = 22
   var84.TextColor3 = var2.TextColor
   var84.TextXAlignment = Enum.TextXAlignment.Left
   var84.Font = Enum.Font.SourceSans
   var84.BackgroundTransparency = 1
   var80.Label = var1.createElement("TextLabel", var84)
   local var117 = {}
   var117.Size = UDim2.new(1, 0, 0, var2.MOVED_DIALOG_LABEL_HEIGHT)
   var117.Position = UDim2.new(0, var2.MOVED_DIALOG_SIDE_PADDING, 0, var2.MOVED_DIALOG_TOP_PADDING + var2.MOVED_DIALOG_LABEL_HEIGHT + var2.MOVED_DIALOG_INTRA_PADDING)
   var117.AnchorPoint = Vector2.new(0, 0)
   var117.Text = var1:getText("Moved", "NewLocationMessage")
   var117.TextSize = 17
   var117.TextColor3 = var2.TextColor
   var117.TextXAlignment = Enum.TextXAlignment.Left
   var117.Font = Enum.Font.SourceSansLight
   var117.BackgroundTransparency = 1
   var80.Label2 = var1.createElement("TextLabel", var117)
   local var156 = {}
   var156.AnchorPoint = Vector2.new(0.5, 1)
   var156.Position = UDim2.new(0.5, 0, 1, var2.MOVED_DIALOG_BOTTOM_PADDING)
   var156.Size = UDim2.new(0, var2.MOVED_DIALOG_BUTTON_WIDTH, 0, var2.MOVED_DIALOG_BUTTON_HEIGHT)
   var156.OnClick = var0.OnClose
   var156.Style = "RoundPrimary"
   local var179 = {}
   local var183 = {}
   var183.Size = UDim2.new(1, 0, 1, 0)
   var183.Text = var1:getText("Moved", "GotIt")
   var183.TextColor3 = var2.White
   var183.Font = Enum.Font.SourceSans
   var183.TextSize = 19
   var183.BackgroundTransparency = 1
   var179.Label = var1.createElement("TextLabel", var183)
   var80.CloseButton = var1.createElement(var6, var156, var179)
   var68.Background = var1.createElement("Frame", var72, var80)
   return var1.createElement(var7, var53, var68)
end

function var8.render(arg1)
   local var0 = arg1.props
   local var1 = var0.Localization
   local var2 = arg1.props.Stylizer
   local var53 = {}
   var53.Title = var1:getText("Moved", "Title")
   var53.Enabled = true
   var53.Modal = true
   var53.Size = Vector2.new(var2.MOVED_DIALOG_WIDTH, var2.MOVED_DIALOG_HEIGHT)
   var53.Resizable = false
   var53.OnClose = var0.OnClose
   local var68 = {}
   local var72 = {}
   var72.Size = UDim2.new(1, 0, 1, 0)
   var72.BackgroundColor3 = var2.BackgroundColor
   local var80 = {}
   local var84 = {}
   var84.Size = UDim2.new(1, 0, 0, var2.MOVED_DIALOG_LABEL_HEIGHT)
   var84.Position = UDim2.new(0, var2.MOVED_DIALOG_SIDE_PADDING, 0, var2.MOVED_DIALOG_TOP_PADDING)
   var84.AnchorPoint = Vector2.new(0, 0)
   var84.Text = var1:getText("Moved", "MovedMessage")
   var84.TextSize = 22
   var84.TextColor3 = var2.TextColor
   var84.TextXAlignment = Enum.TextXAlignment.Left
   var84.Font = Enum.Font.SourceSans
   var84.BackgroundTransparency = 1
   var80.Label = var1.createElement("TextLabel", var84)
   local var117 = {}
   var117.Size = UDim2.new(1, 0, 0, var2.MOVED_DIALOG_LABEL_HEIGHT)
   var117.Position = UDim2.new(0, var2.MOVED_DIALOG_SIDE_PADDING, 0, var2.MOVED_DIALOG_TOP_PADDING + var2.MOVED_DIALOG_LABEL_HEIGHT + var2.MOVED_DIALOG_INTRA_PADDING)
   var117.AnchorPoint = Vector2.new(0, 0)
   var117.Text = var1:getText("Moved", "NewLocationMessage")
   var117.TextSize = 17
   var117.TextColor3 = var2.TextColor
   var117.TextXAlignment = Enum.TextXAlignment.Left
   var117.Font = Enum.Font.SourceSansLight
   var117.BackgroundTransparency = 1
   var80.Label2 = var1.createElement("TextLabel", var117)
   local var156 = {}
   var156.AnchorPoint = Vector2.new(0.5, 1)
   var156.Position = UDim2.new(0.5, 0, 1, var2.MOVED_DIALOG_BOTTOM_PADDING)
   var156.Size = UDim2.new(0, var2.MOVED_DIALOG_BUTTON_WIDTH, 0, var2.MOVED_DIALOG_BUTTON_HEIGHT)
   var156.OnClick = var0.OnClose
   var156.Style = "RoundPrimary"
   local var179 = {}
   local var183 = {}
   var183.Size = UDim2.new(1, 0, 1, 0)
   var183.Text = var1:getText("Moved", "GotIt")
   var183.TextColor3 = var2.White
   var183.Font = Enum.Font.SourceSans
   var183.TextSize = 19
   var183.BackgroundTransparency = 1
   var179.Label = var1.createElement("TextLabel", var183)
   var80.CloseButton = var1.createElement(var6, var156, var179)
   var68.Background = var1.createElement("Frame", var72, var80)
   return var1.createElement(var7, var53, var68)
end

fun0 = var4.withContext
local var202 = {}
var202.Localization = var4.Localization
var202.Stylizer = var4.Stylizer
var8 = fun0(var202)(var8)
return var8
