-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent.Parent
local var1 = require(var0.Packages.Roact)
local var2 = require(var0.Packages.Cryo)
local var3 = require(var0.Packages.Framework)
local var4 = var3.Util.LayoutOrderIterator
local var5 = var3.ContextServices
local var6 = require(var0.Src.Util.DEPRECATED_Constants)
local var7 = require(var0.Src.Components.Dialog.BaseDialog)
local var8 = var1.PureComponent:extend("WarningDialog")
local function fun0(arg1)
   local var0 = arg1.props
   local var1 = var0.Stylizer
   local var2 = var4.new(65534)
   local var49 = {}
   var49.Buttons = var0.Buttons
   var49.OnResult = var0.OnResult
   local var51 = {}
   local var60 = {}
   var60.AutomaticSize = Enum.AutomaticSize.Y
   var60.Size = UDim2.new(1, var1.warningDialog.headerOffset, 0, 0)
   var60.AnchorPoint = Vector2.new(0.5, 0)
   var60.LayoutOrder = var2:getNextOrder()
   var60.BackgroundTransparency = 1
   var60.Text = var0.Header
   var60.TextXAlignment = Enum.TextXAlignment.Left
   var51.Header = var1.createElement("TextLabel", var2.Dictionary.join(var1.fontStyle.Title, var60))
   local var82 = {}
   var82.AutomaticSize = Enum.AutomaticSize.XY
   var82.BackgroundTransparency = 1
   var82.BorderSizePixel = 0
   var82.LayoutOrder = var2:getNextOrder()
   local var88 = {}
   local var92 = {}
   var92.FillDirection = Enum.FillDirection.Horizontal
   var92.Padding = UDim.new(0, var1.dialog.spacing)
   var92.SortOrder = Enum.SortOrder.LayoutOrder
   var92.VerticalAlignment = Enum.VerticalAlignment.Center
   var88.UILayout = var1.createElement("UIListLayout", var92)
   local var105 = {}
   var105.Image = var6.WARNING_IMAGE
   var105.LayoutOrder = var2:getNextOrder()
   var105.BackgroundTransparency = 1
   var105.Size = UDim2.new(0, var1.warningDialog.icon.size, 0, var1.warningDialog.icon.size)
   var88.Warning = var1.createElement("ImageLabel", var105)
   local var130 = {}
   var130.AutomaticSize = Enum.AutomaticSize.Y
   var130.LayoutOrder = var2:getNextOrder()
   var130.Size = UDim2.new(0, var1.warningDialog.description.length, 0, 0)
   var130.BackgroundTransparency = 1
   var130.Text = var0.Description
   var130.TextXAlignment = Enum.TextXAlignment.Left
   var130.TextWrapped = true
   var88.Description = var1.createElement("TextLabel", var2.Dictionary.join(var1.fontStyle.Warning, var130))
   var51.WarningDescription = var1.createElement("Frame", var82, var88)
   return var1.createElement(var7, var49, var51)
end

function var8.render(arg1)
   local var0 = arg1.props
   local var1 = var0.Stylizer
   local var2 = var4.new(65534)
   local var49 = {}
   var49.Buttons = var0.Buttons
   var49.OnResult = var0.OnResult
   local var51 = {}
   local var60 = {}
   var60.AutomaticSize = Enum.AutomaticSize.Y
   var60.Size = UDim2.new(1, var1.warningDialog.headerOffset, 0, 0)
   var60.AnchorPoint = Vector2.new(0.5, 0)
   var60.LayoutOrder = var2:getNextOrder()
   var60.BackgroundTransparency = 1
   var60.Text = var0.Header
   var60.TextXAlignment = Enum.TextXAlignment.Left
   var51.Header = var1.createElement("TextLabel", var2.Dictionary.join(var1.fontStyle.Title, var60))
   local var82 = {}
   var82.AutomaticSize = Enum.AutomaticSize.XY
   var82.BackgroundTransparency = 1
   var82.BorderSizePixel = 0
   var82.LayoutOrder = var2:getNextOrder()
   local var88 = {}
   local var92 = {}
   var92.FillDirection = Enum.FillDirection.Horizontal
   var92.Padding = UDim.new(0, var1.dialog.spacing)
   var92.SortOrder = Enum.SortOrder.LayoutOrder
   var92.VerticalAlignment = Enum.VerticalAlignment.Center
   var88.UILayout = var1.createElement("UIListLayout", var92)
   local var105 = {}
   var105.Image = var6.WARNING_IMAGE
   var105.LayoutOrder = var2:getNextOrder()
   var105.BackgroundTransparency = 1
   var105.Size = UDim2.new(0, var1.warningDialog.icon.size, 0, var1.warningDialog.icon.size)
   var88.Warning = var1.createElement("ImageLabel", var105)
   local var130 = {}
   var130.AutomaticSize = Enum.AutomaticSize.Y
   var130.LayoutOrder = var2:getNextOrder()
   var130.Size = UDim2.new(0, var1.warningDialog.description.length, 0, 0)
   var130.BackgroundTransparency = 1
   var130.Text = var0.Description
   var130.TextXAlignment = Enum.TextXAlignment.Left
   var130.TextWrapped = true
   var88.Description = var1.createElement("TextLabel", var2.Dictionary.join(var1.fontStyle.Warning, var130))
   var51.WarningDescription = var1.createElement("Frame", var82, var88)
   return var1.createElement(var7, var49, var51)
end

fun0 = var5.withContext
local var149 = {}
var149.Stylizer = var5.Stylizer
var8 = fun0(var149)(var8)
return var8
