--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["Style"]["Style"])

export type DesignTokenProviderProps = Package.DesignTokenProviderProps
export type DesignTokenMapper<FeatureTokens = any> = Package.DesignTokenMapper<FeatureTokens > 
export type DesignTokens = Package.DesignTokens
export type StyleProviderWithDefaultThemeConfig = Package.StyleProviderWithDefaultThemeConfig
export type ColorToken = Package.ColorToken
export type TypographyToken = Package.TypographyToken


return Package
