[package]
name = "ReactDevtoolsExtensions"
version = "17.0.4"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
authors = [
    "Paul Doyle <pdoyle@roblox.com>",
    "Matt Hargett <mhargett@roblox.com>",
    "Max Mines <mmines@roblox.com>",
    "Carlo Conte <cconte@roblox.com>",
    "Henry Allen <hallen@roblox.com>",
    "Olivier Trepanier <otrepanier@roblox.com>",
    "Hugh Collins <hcollins@roblox.com>",
]
[dependencies.LuauPolyfill]
version = "^1"

[dependencies.React]
package = "React"
version = "^17.0.4"

[dependencies.ReactDevtoolsShared]
package = "ReactDevtoolsShared"
version = "^17.0.4"

[dependencies.ReactRoblox]
package = "ReactRoblox"
version = "^17.0.4"

[dependencies.Shared]
package = "Shared"
version = "^17.0.4"
