-- Generated with Unluau (https://github.com/valencefun/unluau)
local var44 = {}
var44.GameOwnerMetadata = require(script.Parent.GameOwnerMetadata)
var44.Permissions = require(script.Parent.Permissions)
var44.GroupMetadata = require(script.Parent.GroupMetadata)
var44.GroupRolePermissions = require(script.Parent.GroupRolePermissions)
var44.CollaboratorSearch = require(script.Parent.CollaboratorSearch)
var44.LoadState = require(script.Parent.LoadState)
var44.SaveState = require(script.Parent.SaveState)
return require(script.Parent.Parent.Parent.Packages.Rodux).combineReducers(var44)
