--!strict
--!nolint LocalUnused
--!nolint ImportUnused
--# selene: allow(empty_if, if_same_then_else, manual_table_clone, unused_variable)
-- This file was @autogenerated by protoc-gen-luau
local proto = require(script.Parent.Parent.Parent.Parent.Parent.proto)
local typeRegistry = require(script.Parent.Parent.Parent.Parent.Parent.proto.typeRegistry)

type _Messages =
	{
		SettingsPageRequest: _SettingsPageRequestMessage,
		SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry: _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryMessage,
		SettingsPageResponse: _SettingsPageResponseMessage,
		SettingsPageResponse_TemplatesEntry: _SettingsPageResponse_TemplatesEntryMessage,
		SettingsPageResponse_LocalizedLiteralsEntry: _SettingsPageResponse_LocalizedLiteralsEntryMessage,
	}
local messages: _Messages = {} :: _Messages

local _roblox_apppageplatform_shared_v1beta1_client_capabilities =
	require(script.Parent.Parent.Parent.shared.v1beta1.client_capabilities)
local _roblox_apppageplatform_shared_v1beta1_hydration_content =
	require(script.Parent.Parent.Parent.shared.v1beta1.hydration_content)
local _roblox_apppageplatform_shared_v1beta1_page_entry_content =
	require(script.Parent.Parent.Parent.shared.v1beta1.page_entry_content)
local _roblox_apppageplatform_shared_v1beta1_template_entry =
	require(script.Parent.Parent.Parent.shared.v1beta1.template_entry)

type _SettingsPageRequestImpl = {
	__index: _SettingsPageRequestImpl,
	new: (fields: _SettingsPageRequestPartialFields?) -> SettingsPageRequest,
	encode: (self: SettingsPageRequest) -> buffer,
	decode: (input: buffer) -> SettingsPageRequest,
	jsonEncode: (self: SettingsPageRequest) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> SettingsPageRequest,
	descriptor: proto.Descriptor,
}

type _SettingsPageRequestFields = {
	session_id: string,
	cached_roblox_component_to_template_id: { [string]: string },
	client_capabilities: _roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities?,
}

type _SettingsPageRequestPartialFields = {
	session_id: string?,
	cached_roblox_component_to_template_id: { [string]: string }?,
	client_capabilities: _roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities?,
}

export type SettingsPageRequest = typeof(setmetatable({} :: _SettingsPageRequestFields, {} :: _SettingsPageRequestImpl))
type _SettingsPageRequestMessage = proto.Message<SettingsPageRequest, _SettingsPageRequestPartialFields>

type _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl = {
	__index: _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl,
	new: (
		fields: _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryPartialFields?
	) -> SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry,
	encode: (self: SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry) -> buffer,
	decode: (input: buffer) -> SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry,
	jsonEncode: (self: SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry,
	descriptor: proto.Descriptor,
}

type _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryFields = {
	key: string,
	value: string,
}

type _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryPartialFields = {
	key: string?,
	value: string?,
}

export type SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry = typeof(setmetatable(
	{} :: _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryFields,
	{} :: _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl
))
type _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryMessage = proto.Message<
	SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry,
	_SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryPartialFields
>

type _SettingsPageResponseImpl = {
	__index: _SettingsPageResponseImpl,
	new: (fields: _SettingsPageResponsePartialFields?) -> SettingsPageResponse,
	encode: (self: SettingsPageResponse) -> buffer,
	decode: (input: buffer) -> SettingsPageResponse,
	jsonEncode: (self: SettingsPageResponse) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> SettingsPageResponse,
	descriptor: proto.Descriptor,
}

type _SettingsPageResponseFields = {
	page_entries: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry },
	hydration_data: _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent?,
	templates: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry },
	localized_literals: { [string]: string },
}

type _SettingsPageResponsePartialFields = {
	page_entries: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry }?,
	hydration_data: _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent?,
	templates: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry }?,
	localized_literals: { [string]: string }?,
}

export type SettingsPageResponse = typeof(setmetatable(
	{} :: _SettingsPageResponseFields,
	{} :: _SettingsPageResponseImpl
))
type _SettingsPageResponseMessage = proto.Message<SettingsPageResponse, _SettingsPageResponsePartialFields>

type _SettingsPageResponse_TemplatesEntryImpl = {
	__index: _SettingsPageResponse_TemplatesEntryImpl,
	new: (fields: _SettingsPageResponse_TemplatesEntryPartialFields?) -> SettingsPageResponse_TemplatesEntry,
	encode: (self: SettingsPageResponse_TemplatesEntry) -> buffer,
	decode: (input: buffer) -> SettingsPageResponse_TemplatesEntry,
	jsonEncode: (self: SettingsPageResponse_TemplatesEntry) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> SettingsPageResponse_TemplatesEntry,
	descriptor: proto.Descriptor,
}

type _SettingsPageResponse_TemplatesEntryFields = {
	key: string,
	value: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry?,
}

type _SettingsPageResponse_TemplatesEntryPartialFields = {
	key: string?,
	value: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry?,
}

export type SettingsPageResponse_TemplatesEntry = typeof(setmetatable(
	{} :: _SettingsPageResponse_TemplatesEntryFields,
	{} :: _SettingsPageResponse_TemplatesEntryImpl
))
type _SettingsPageResponse_TemplatesEntryMessage = proto.Message<
	SettingsPageResponse_TemplatesEntry,
	_SettingsPageResponse_TemplatesEntryPartialFields
>

type _SettingsPageResponse_LocalizedLiteralsEntryImpl = {
	__index: _SettingsPageResponse_LocalizedLiteralsEntryImpl,
	new: (
		fields: _SettingsPageResponse_LocalizedLiteralsEntryPartialFields?
	) -> SettingsPageResponse_LocalizedLiteralsEntry,
	encode: (self: SettingsPageResponse_LocalizedLiteralsEntry) -> buffer,
	decode: (input: buffer) -> SettingsPageResponse_LocalizedLiteralsEntry,
	jsonEncode: (self: SettingsPageResponse_LocalizedLiteralsEntry) -> { [string]: any },
	jsonDecode: (input: { [string]: any }) -> SettingsPageResponse_LocalizedLiteralsEntry,
	descriptor: proto.Descriptor,
}

type _SettingsPageResponse_LocalizedLiteralsEntryFields = {
	key: string,
	value: string,
}

type _SettingsPageResponse_LocalizedLiteralsEntryPartialFields = {
	key: string?,
	value: string?,
}

export type SettingsPageResponse_LocalizedLiteralsEntry = typeof(setmetatable(
	{} :: _SettingsPageResponse_LocalizedLiteralsEntryFields,
	{} :: _SettingsPageResponse_LocalizedLiteralsEntryImpl
))
type _SettingsPageResponse_LocalizedLiteralsEntryMessage = proto.Message<
	SettingsPageResponse_LocalizedLiteralsEntry,
	_SettingsPageResponse_LocalizedLiteralsEntryPartialFields
>

do
	local _SettingsPageRequestImpl = {}
	_SettingsPageRequestImpl.__index = _SettingsPageRequestImpl

	function _SettingsPageRequestImpl.new(data: _SettingsPageRequestPartialFields?): SettingsPageRequest
		return setmetatable({
			session_id = if data == nil or data.session_id == nil then "" else data.session_id,
			cached_roblox_component_to_template_id = if data == nil
					or data.cached_roblox_component_to_template_id == nil
				then {}
				else data.cached_roblox_component_to_template_id,
			client_capabilities = if data == nil or data.client_capabilities == nil
				then nil
				else data.client_capabilities,
		}, _SettingsPageRequestImpl :: _SettingsPageRequestImpl)
	end

	function _SettingsPageRequestImpl.encode(self: SettingsPageRequest): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.session_id ~= nil and self.session_id ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.session_id)
		end

		if
			self.cached_roblox_component_to_template_id ~= nil
			and next(self.cached_roblox_component_to_template_id) ~= nil
		then
			for key, value in self.cached_roblox_component_to_template_id do
				local mapBuffer = buffer.create(0)
				local mapCursor = 0
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 1, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, key)
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 2, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, value)
				output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, mapBuffer, mapCursor)
			end
		end

		if self.client_capabilities ~= nil then
			local encoded = self.client_capabilities:encode()
			output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _SettingsPageRequestImpl.decode(input: buffer): SettingsPageRequest
		local self = _SettingsPageRequestImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.session_id = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)

					local mapEntry = messages.SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry.decode(value)

					local keyDefault = ""
					local valueDefault = ""

					self.cached_roblox_component_to_template_id[mapEntry.key or keyDefault] = mapEntry.value
						or valueDefault

					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.client_capabilities =
						_roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _SettingsPageRequestImpl.jsonEncode(self: SettingsPageRequest): any
		local output = {}

		if self.session_id ~= nil and self.session_id ~= "" then
			output.sessionId = self.session_id
		end

		if
			self.cached_roblox_component_to_template_id ~= nil
			and next(self.cached_roblox_component_to_template_id) ~= nil
		then
			local newOutput = {}
			for key, value in self.cached_roblox_component_to_template_id do
				newOutput[key] = value
			end
			output.cachedRobloxComponentToTemplateId = newOutput
		end

		if self.client_capabilities ~= nil then
			output.clientCapabilities = self.client_capabilities:jsonEncode()
		end

		return output
	end

	function _SettingsPageRequestImpl.jsonDecode(input: { [string]: any }): SettingsPageRequest
		local self = _SettingsPageRequestImpl.new()

		if input.session_id ~= nil then
			self.session_id = input.session_id
		end

		if input.sessionId ~= nil then
			self.session_id = input.sessionId
		end

		if input.cached_roblox_component_to_template_id ~= nil then
			local newOutput: { [string]: string } = {}
			for key, value in input.cached_roblox_component_to_template_id do
				newOutput[key] = value
			end

			self.cached_roblox_component_to_template_id = newOutput
		end

		if input.cachedRobloxComponentToTemplateId ~= nil then
			local newOutput: { [string]: string } = {}
			for key, value in input.cachedRobloxComponentToTemplateId do
				newOutput[key] = value
			end

			self.cached_roblox_component_to_template_id = newOutput
		end

		if input.client_capabilities ~= nil then
			self.client_capabilities =
				_roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities.jsonDecode(
					input.client_capabilities
				)
		end

		if input.clientCapabilities ~= nil then
			self.client_capabilities =
				_roblox_apppageplatform_shared_v1beta1_client_capabilities.ClientCapabilities.jsonDecode(
					input.clientCapabilities
				)
		end

		return self
	end

	_SettingsPageRequestImpl.descriptor = {
		name = "SettingsPageRequest",
		fullName = "roblox.apppageplatform.settings.v1beta1.SettingsPageRequest",
	}

	messages.SettingsPageRequest = _SettingsPageRequestImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.SettingsPageRequest)
end

do
	local _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl = {}
	_SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.__index =
		_SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl

	function _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.new(
		data: _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryPartialFields?
	): SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry
		return setmetatable(
			{
				key = if data == nil or data.key == nil then "" else data.key,
				value = if data == nil or data.value == nil then "" else data.value,
			},
			_SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl :: _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl
		)
	end

	function _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.encode(
		self: SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry
	): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.key ~= nil and self.key ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.key)
		end

		if self.value ~= nil and self.value ~= "" then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.value)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.decode(
		input: buffer
	): SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry
		local self = _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.key = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.value = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.jsonEncode(
		self: SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry
	): any
		local output = {}

		if self.key ~= nil and self.key ~= "" then
			output.key = self.key
		end

		if self.value ~= nil and self.value ~= "" then
			output.value = self.value
		end

		return output
	end

	function _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.jsonDecode(
		input: { [string]: any }
	): SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry
		local self = _SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.new()

		if input.key ~= nil then
			self.key = input.key
		end

		if input.value ~= nil then
			self.value = input.value
		end

		return self
	end

	_SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl.descriptor = {
		name = "SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry",
		fullName = "roblox.apppageplatform.settings.v1beta1.CachedRobloxComponentToTemplateIdEntry",
	}

	messages.SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry =
		_SettingsPageRequest_CachedRobloxComponentToTemplateIdEntryImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.SettingsPageRequest_CachedRobloxComponentToTemplateIdEntry)
end

do
	local _SettingsPageResponseImpl = {}
	_SettingsPageResponseImpl.__index = _SettingsPageResponseImpl

	function _SettingsPageResponseImpl.new(data: _SettingsPageResponsePartialFields?): SettingsPageResponse
		return setmetatable({
			page_entries = if data == nil or data.page_entries == nil then {} else data.page_entries,
			hydration_data = if data == nil or data.hydration_data == nil then nil else data.hydration_data,
			templates = if data == nil or data.templates == nil then {} else data.templates,
			localized_literals = if data == nil or data.localized_literals == nil then {} else data.localized_literals,
		}, _SettingsPageResponseImpl :: _SettingsPageResponseImpl)
	end

	function _SettingsPageResponseImpl.encode(self: SettingsPageResponse): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.page_entries ~= nil and #self.page_entries > 0 then
			for _, value in self.page_entries do
				local encoded = value:encode()
				output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
			end
		end

		if self.hydration_data ~= nil then
			local encoded = self.hydration_data:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		if self.templates ~= nil and next(self.templates) ~= nil then
			for key, value in self.templates do
				local mapBuffer = buffer.create(0)
				local mapCursor = 0
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 1, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, key)
				local encoded = value:encode()
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 2, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeBuffer(mapBuffer, mapCursor, encoded, buffer.len(encoded))
				output, cursor = proto.writeTag(output, cursor, 3, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, mapBuffer, mapCursor)
			end
		end

		if self.localized_literals ~= nil and next(self.localized_literals) ~= nil then
			for key, value in self.localized_literals do
				local mapBuffer = buffer.create(0)
				local mapCursor = 0
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 1, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, key)
				mapBuffer, mapCursor = proto.writeTag(mapBuffer, mapCursor, 2, proto.wireTypes.lengthDelimited)
				mapBuffer, mapCursor = proto.writeString(mapBuffer, mapCursor, value)
				output, cursor = proto.writeTag(output, cursor, 4, proto.wireTypes.lengthDelimited)
				output, cursor = proto.writeBuffer(output, cursor, mapBuffer, mapCursor)
			end
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _SettingsPageResponseImpl.decode(input: buffer): SettingsPageResponse
		local self = _SettingsPageResponseImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					table.insert(
						self.page_entries,
						_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.decode(value)
					)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.hydration_data =
						_roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.decode(value)
					continue
				elseif field == 3 then
					local value
					value, cursor = proto.readBuffer(input, cursor)

					local mapEntry = messages.SettingsPageResponse_TemplatesEntry.decode(value)

					local keyDefault = ""
					local valueDefault = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.new()

					self.templates[mapEntry.key or keyDefault] = mapEntry.value or valueDefault

					continue
				elseif field == 4 then
					local value
					value, cursor = proto.readBuffer(input, cursor)

					local mapEntry = messages.SettingsPageResponse_LocalizedLiteralsEntry.decode(value)

					local keyDefault = ""
					local valueDefault = ""

					self.localized_literals[mapEntry.key or keyDefault] = mapEntry.value or valueDefault

					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _SettingsPageResponseImpl.jsonEncode(self: SettingsPageResponse): any
		local output = {}

		if self.page_entries ~= nil and #self.page_entries > 0 then
			local newOutput = {}
			for _, value in self.page_entries do
				table.insert(newOutput, value:jsonEncode())
			end
			output.pageEntries = newOutput
		end

		if self.hydration_data ~= nil then
			output.hydrationData = self.hydration_data:jsonEncode()
		end

		if self.templates ~= nil and next(self.templates) ~= nil then
			local newOutput = {}
			for key, value in self.templates do
				newOutput[key] = value:jsonEncode()
			end
			output.templates = newOutput
		end

		if self.localized_literals ~= nil and next(self.localized_literals) ~= nil then
			local newOutput = {}
			for key, value in self.localized_literals do
				newOutput[key] = value
			end
			output.localizedLiterals = newOutput
		end

		return output
	end

	function _SettingsPageResponseImpl.jsonDecode(input: { [string]: any }): SettingsPageResponse
		local self = _SettingsPageResponseImpl.new()

		if input.page_entries ~= nil then
			local newOutput: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry } = {}
			for _, value in input.page_entries do
				table.insert(
					newOutput,
					_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.jsonDecode(value)
				)
			end

			self.page_entries = newOutput
		end

		if input.pageEntries ~= nil then
			local newOutput: { _roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry } = {}
			for _, value in input.pageEntries do
				table.insert(
					newOutput,
					_roblox_apppageplatform_shared_v1beta1_page_entry_content.UniversalPageEntry.jsonDecode(value)
				)
			end

			self.page_entries = newOutput
		end

		if input.hydration_data ~= nil then
			self.hydration_data = _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.jsonDecode(
				input.hydration_data
			)
		end

		if input.hydrationData ~= nil then
			self.hydration_data = _roblox_apppageplatform_shared_v1beta1_hydration_content.HydrationContent.jsonDecode(
				input.hydrationData
			)
		end

		if input.templates ~= nil then
			local newOutput: { [string]: _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry } = {}
			for key, value in input.templates do
				newOutput[key] = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.jsonDecode(value)
			end

			self.templates = newOutput
		end

		if input.localized_literals ~= nil then
			local newOutput: { [string]: string } = {}
			for key, value in input.localized_literals do
				newOutput[key] = value
			end

			self.localized_literals = newOutput
		end

		if input.localizedLiterals ~= nil then
			local newOutput: { [string]: string } = {}
			for key, value in input.localizedLiterals do
				newOutput[key] = value
			end

			self.localized_literals = newOutput
		end

		return self
	end

	_SettingsPageResponseImpl.descriptor = {
		name = "SettingsPageResponse",
		fullName = "roblox.apppageplatform.settings.v1beta1.SettingsPageResponse",
	}

	messages.SettingsPageResponse = _SettingsPageResponseImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.SettingsPageResponse)
end

do
	local _SettingsPageResponse_TemplatesEntryImpl = {}
	_SettingsPageResponse_TemplatesEntryImpl.__index = _SettingsPageResponse_TemplatesEntryImpl

	function _SettingsPageResponse_TemplatesEntryImpl.new(
		data: _SettingsPageResponse_TemplatesEntryPartialFields?
	): SettingsPageResponse_TemplatesEntry
		return setmetatable({
			key = if data == nil or data.key == nil then "" else data.key,
			value = if data == nil or data.value == nil then nil else data.value,
		}, _SettingsPageResponse_TemplatesEntryImpl :: _SettingsPageResponse_TemplatesEntryImpl)
	end

	function _SettingsPageResponse_TemplatesEntryImpl.encode(self: SettingsPageResponse_TemplatesEntry): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.key ~= nil and self.key ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.key)
		end

		if self.value ~= nil then
			local encoded = self.value:encode()
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeBuffer(output, cursor, encoded, buffer.len(encoded))
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _SettingsPageResponse_TemplatesEntryImpl.decode(input: buffer): SettingsPageResponse_TemplatesEntry
		local self = _SettingsPageResponse_TemplatesEntryImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.key = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.value = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.decode(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _SettingsPageResponse_TemplatesEntryImpl.jsonEncode(self: SettingsPageResponse_TemplatesEntry): any
		local output = {}

		if self.key ~= nil and self.key ~= "" then
			output.key = self.key
		end

		if self.value ~= nil then
			output.value = self.value:jsonEncode()
		end

		return output
	end

	function _SettingsPageResponse_TemplatesEntryImpl.jsonDecode(
		input: { [string]: any }
	): SettingsPageResponse_TemplatesEntry
		local self = _SettingsPageResponse_TemplatesEntryImpl.new()

		if input.key ~= nil then
			self.key = input.key
		end

		if input.value ~= nil then
			self.value = _roblox_apppageplatform_shared_v1beta1_template_entry.TemplateEntry.jsonDecode(input.value)
		end

		return self
	end

	_SettingsPageResponse_TemplatesEntryImpl.descriptor = {
		name = "SettingsPageResponse_TemplatesEntry",
		fullName = "roblox.apppageplatform.settings.v1beta1.TemplatesEntry",
	}

	messages.SettingsPageResponse_TemplatesEntry = _SettingsPageResponse_TemplatesEntryImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.SettingsPageResponse_TemplatesEntry)
end

do
	local _SettingsPageResponse_LocalizedLiteralsEntryImpl = {}
	_SettingsPageResponse_LocalizedLiteralsEntryImpl.__index = _SettingsPageResponse_LocalizedLiteralsEntryImpl

	function _SettingsPageResponse_LocalizedLiteralsEntryImpl.new(
		data: _SettingsPageResponse_LocalizedLiteralsEntryPartialFields?
	): SettingsPageResponse_LocalizedLiteralsEntry
		return setmetatable({
			key = if data == nil or data.key == nil then "" else data.key,
			value = if data == nil or data.value == nil then "" else data.value,
		}, _SettingsPageResponse_LocalizedLiteralsEntryImpl :: _SettingsPageResponse_LocalizedLiteralsEntryImpl)
	end

	function _SettingsPageResponse_LocalizedLiteralsEntryImpl.encode(
		self: SettingsPageResponse_LocalizedLiteralsEntry
	): buffer
		local output = buffer.create(0)
		local cursor = 0

		if self.key ~= nil and self.key ~= "" then
			output, cursor = proto.writeTag(output, cursor, 1, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.key)
		end

		if self.value ~= nil and self.value ~= "" then
			output, cursor = proto.writeTag(output, cursor, 2, proto.wireTypes.lengthDelimited)
			output, cursor = proto.writeString(output, cursor, self.value)
		end

		local shrunkBuffer = buffer.create(cursor)
		buffer.copy(shrunkBuffer, 0, output, 0, cursor)
		return shrunkBuffer
	end

	function _SettingsPageResponse_LocalizedLiteralsEntryImpl.decode(
		input: buffer
	): SettingsPageResponse_LocalizedLiteralsEntry
		local self = _SettingsPageResponse_LocalizedLiteralsEntryImpl.new()
		local cursor = 0

		while cursor < buffer.len(input) do
			local field, wireType
			field, wireType, cursor = proto.readTag(input, cursor)

			if wireType == proto.wireTypes.varint then
				-- No fields

				local _
				_, cursor = proto.readVarInt(input, cursor)
			elseif wireType == proto.wireTypes.lengthDelimited then
				if field == 1 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.key = buffer.tostring(value)
					continue
				elseif field == 2 then
					local value
					value, cursor = proto.readBuffer(input, cursor)
					self.value = buffer.tostring(value)
					continue
				end

				local length
				length, cursor = proto.readVarInt(input, cursor)

				cursor += length
			elseif wireType == proto.wireTypes.i32 then
				-- No fields

				local _
				_, cursor = proto.readFixed32(input, cursor)
			elseif wireType == proto.wireTypes.i64 then
				-- No fields

				local _
				_, cursor = proto.readFixed64(input, cursor)
			else
				error("Unsupported wire type: " .. wireType)
			end
		end

		return self
	end

	function _SettingsPageResponse_LocalizedLiteralsEntryImpl.jsonEncode(
		self: SettingsPageResponse_LocalizedLiteralsEntry
	): any
		local output = {}

		if self.key ~= nil and self.key ~= "" then
			output.key = self.key
		end

		if self.value ~= nil and self.value ~= "" then
			output.value = self.value
		end

		return output
	end

	function _SettingsPageResponse_LocalizedLiteralsEntryImpl.jsonDecode(
		input: { [string]: any }
	): SettingsPageResponse_LocalizedLiteralsEntry
		local self = _SettingsPageResponse_LocalizedLiteralsEntryImpl.new()

		if input.key ~= nil then
			self.key = input.key
		end

		if input.value ~= nil then
			self.value = input.value
		end

		return self
	end

	_SettingsPageResponse_LocalizedLiteralsEntryImpl.descriptor = {
		name = "SettingsPageResponse_LocalizedLiteralsEntry",
		fullName = "roblox.apppageplatform.settings.v1beta1.LocalizedLiteralsEntry",
	}

	messages.SettingsPageResponse_LocalizedLiteralsEntry = _SettingsPageResponse_LocalizedLiteralsEntryImpl :: any -- Luau: Not sure why this intersection fails.

	typeRegistry.default:register(messages.SettingsPageResponse_LocalizedLiteralsEntry)
end

return {
	SettingsPageRequest = messages.SettingsPageRequest,
	SettingsPageResponse = messages.SettingsPageResponse,
}
