--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["DeepJoin-000000000000-0000000001"].Packages["DeepJoin"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package