--!strict
export type TYPE =  {
	Size_0: number,
	Size_25: number,
	Size_50: number,
	Size_75: number,
	Size_100: number,
	Size_150: number,
	Size_200: number,
	Size_250: number,
	Size_300: number,
	Size_350: number,
	Size_400: number,
	Size_450: number,
	Size_500: number,
	Size_600: number,
	Size_700: number,
	Size_800: number,
	Size_900: number,
	Size_1000: number,
	Size_1100: number,
	Size_1200: number,
	Size_1300: number,
	Size_1400: number,
	Space_0: number,
	Space_25: number,
	Space_50: number,
	Space_75: number,
	Space_100: number,
	Space_150: number,
	Space_200: number,
	Space_250: number,
	Space_300: number,
	Space_400: number,
	Space_500: number,
	Space_600: number,
	Space_800: number,
	Space_1000: number,
	FontSize_25: number,
	FontSize_50: number,
	FontSize_75: number,
	FontSize_100: number,
	FontSize_200: number,
	FontSize_300: number,
	FontSize_400: number,
	FontSize_500: number,
	FontSize_600: number,
	FontSize_700: number,
	FontSize_800: number,
	FontSize_900: number,
	FontSize_1000: number,
	Family: {
		Standard: string,
	},
	Weight_300: string,
	Weight_400: string,
	Weight_600: string,
	Weight_700: string,
	Weight_900: string,
	LetterSpacing: {
		Default: number,
	},
	LineHeight_100: number,
	LineHeight_200: number,
	LineHeight_300: number,
	LineHeight_400: number,
	Stroke_50: number,
	Stroke_100: number,
	Stroke_150: number,
	Stroke_200: number,
	Stroke_250: number,
	Stroke_300: number,
	Stroke_400: number,
	Opacity_0: number,
	Opacity_8: number,
	Opacity_12: number,
	Opacity_16: number,
	Opacity_32: number,
	Opacity_68: number,
	Opacity_84: number,
	Opacity_88: number,
	Opacity_92: number,
	Opacity_100: number,
	Color: {
		Black: {
			Color3: Color3,
			Transparency: number,
		},
		White: {
			Color3: Color3,
			Transparency: number,
		},
		Green: {
			Color3: Color3,
			Transparency: number,
		},
		Red: {
			Color3: Color3,
			Transparency: number,
		},
		Blue: {
			Color3: Color3,
			Transparency: number,
		},
		Carbon: {
			Color3: Color3,
			Transparency: number,
		},
		Flint: {
			Color3: Color3,
			Transparency: number,
		},
		Graphite: {
			Color3: Color3,
			Transparency: number,
		},
		Obsidian: {
			Color3: Color3,
			Transparency: number,
		},
		Pumice: {
			Color3: Color3,
			Transparency: number,
		},
		Slate: {
			Color3: Color3,
			Transparency: number,
		},
		Alabaster: {
			Color3: Color3,
			Transparency: number,
		},
		Ash: {
			Color3: Color3,
			Transparency: number,
		},
		Chalk: {
			Color3: Color3,
			Transparency: number,
		},
		Smoke: {
			Color3: Color3,
			Transparency: number,
		},
	},
}
return {}
