--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["RoduxFriends-85187362-f394857e"]["RoduxFriends"])

return Package
