--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["TestEZJestAdapter"]["TestEZJestAdapter"])

return Package
