-- ROBLOX upstream: https://github.com/testing-library/dom-testing-library/blob/v8.14.0/src/__tests__/pretty-dom.js
local Packages = script.Parent.Parent.Parent

local LuauPolyfill = require(Packages.LuauPolyfill)
local console = LuauPolyfill.console

local JestGlobals = require(Packages.JestGlobals)
local expect = JestGlobals.expect
local test = JestGlobals.test
local describe = JestGlobals.describe
local beforeEach = JestGlobals.beforeEach
local afterEach = JestGlobals.afterEach
local jest = JestGlobals.jest

local document = require(script.Parent.Parent.jsHelpers.document)

local pretty_domModule = require(script.Parent.Parent["pretty-dom"])
local prettyDOM = pretty_domModule.prettyDOM
local logDOM = pretty_domModule.logDOM
local getUCDModule = require(script.Parent.Parent["get-user-code-frame"])
local test_utilsModule = require(script.Parent.helpers["test-utils"])
local render = test_utilsModule.render
local renderIntoDocument = test_utilsModule.renderIntoDocument

-- ROBLOX deviation START: workaround jest.mock and jest.spyOn not available
local originalLog
local originalGetUserCodeFrame
beforeEach(function()
	originalLog = console.log
	originalGetUserCodeFrame = getUCDModule.getUserCodeFrame
	getUCDModule.getUserCodeFrame = jest.fn(originalGetUserCodeFrame)
	console.log = jest.fn().mockImplementation(function() end)
end)
afterEach(function()
	console.log = originalLog
	getUCDModule.getUserCodeFrame = originalGetUserCodeFrame
end)
-- ROBLOX deviation END
test("prettyDOM prints out the given DOM element tree", function()
	local div = Instance.new("Frame")
	local text = Instance.new("TextLabel")
	text.Text = "Hello World!"
	text.Parent = div
	local container = render({ div }).container
	expect(prettyDOM(container)).toBe([[
Frame {
  "AbsolutePosition": Vector2(0, 0),
  "AbsoluteRotation": 0,
  "AbsoluteSize": Vector2(0, 0),
  "Active": false,
  "AnchorPoint": Vector2(0, 0),
  "Archivable": true,
  "AutoLocalize": true,
  "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
  "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
  "BackgroundTransparency": 0,
  "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
  "BorderMode": EnumItem(Enum.BorderMode.Outline),
  "BorderSizePixel": 1,
  "ClassName": "Frame",
  "ClipsDescendants": false,
  "LayoutOrder": 0,
  "Name": "Frame",
  "NextSelectionDown": nil,
  "NextSelectionLeft": nil,
  "NextSelectionRight": nil,
  "NextSelectionUp": nil,
  "Parent": "Document" [Folder],
  "Position": UDim2({0, 0}, {0, 0}),
  "RootLocalizationTable": nil,
  "Rotation": 0,
  "Selectable": false,
  "SelectionImageObject": nil,
  "Size": UDim2({0, 0}, {0, 0}),
  "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
  "Style": EnumItem(Enum.FrameStyle.Custom),
  "Visible": true,
  "ZIndex": 1,
  "Frame": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 0,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "Frame",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "Frame" [Frame],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({0, 0}, {0, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "TextLabel": TextLabel {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 0,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "TextLabel",
      "ClipsDescendants": false,
      "ContentText": "Hello World!",
      "Font": EnumItem(Enum.Font.Legacy),
      "LayoutOrder": 0,
      "LineHeight": 1,
      "MaxVisibleGraphemes": -1,
      "Name": "TextLabel",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "Frame" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RichText": false,
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({0, 0}, {0, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Text": "Hello World!",
      "TextBounds": Vector2(NAN, NAN),
      "TextColor3": Color3(0.105882, 0.164706, 0.207843),
      "TextFits": false,
      "TextScaled": false,
      "TextSize": 8,
      "TextStrokeColor3": Color3(0, 0, 0),
      "TextStrokeTransparency": 1,
      "TextTransparency": 0,
      "TextTruncate": EnumItem(Enum.TextTruncate.None),
      "TextWrapped": false,
      "TextXAlignment": EnumItem(Enum.TextXAlignment.Center),
      "TextYAlignment": EnumItem(Enum.TextYAlignment.Center),
      "Visible": true,
      "ZIndex": 1,
    },
  },
}]])
end)
test("prettyDOM supports truncating the output length", function()
	local div = Instance.new("Frame")
	local text = Instance.new("TextLabel")
	text.Text = "Hello World!"
	text.Parent = div
	local container = render({ div }).container
	expect(prettyDOM(container, 5)).toMatch("%.%.%.")
	expect(prettyDOM(container, 0)).toMatch("")
	expect(prettyDOM(container, math.huge)).toBe([[
Frame {
  "AbsolutePosition": Vector2(0, 0),
  "AbsoluteRotation": 0,
  "AbsoluteSize": Vector2(0, 0),
  "Active": false,
  "AnchorPoint": Vector2(0, 0),
  "Archivable": true,
  "AutoLocalize": true,
  "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
  "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
  "BackgroundTransparency": 0,
  "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
  "BorderMode": EnumItem(Enum.BorderMode.Outline),
  "BorderSizePixel": 1,
  "ClassName": "Frame",
  "ClipsDescendants": false,
  "LayoutOrder": 0,
  "Name": "Frame",
  "NextSelectionDown": nil,
  "NextSelectionLeft": nil,
  "NextSelectionRight": nil,
  "NextSelectionUp": nil,
  "Parent": "Document" [Folder],
  "Position": UDim2({0, 0}, {0, 0}),
  "RootLocalizationTable": nil,
  "Rotation": 0,
  "Selectable": false,
  "SelectionImageObject": nil,
  "Size": UDim2({0, 0}, {0, 0}),
  "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
  "Style": EnumItem(Enum.FrameStyle.Custom),
  "Visible": true,
  "ZIndex": 1,
  "Frame": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 0,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "Frame",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "Frame" [Frame],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({0, 0}, {0, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "TextLabel": TextLabel {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 0,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "TextLabel",
      "ClipsDescendants": false,
      "ContentText": "Hello World!",
      "Font": EnumItem(Enum.Font.Legacy),
      "LayoutOrder": 0,
      "LineHeight": 1,
      "MaxVisibleGraphemes": -1,
      "Name": "TextLabel",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "Frame" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RichText": false,
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({0, 0}, {0, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Text": "Hello World!",
      "TextBounds": Vector2(NAN, NAN),
      "TextColor3": Color3(0.105882, 0.164706, 0.207843),
      "TextFits": false,
      "TextScaled": false,
      "TextSize": 8,
      "TextStrokeColor3": Color3(0, 0, 0),
      "TextStrokeTransparency": 1,
      "TextTransparency": 0,
      "TextTruncate": EnumItem(Enum.TextTruncate.None),
      "TextWrapped": false,
      "TextXAlignment": EnumItem(Enum.TextXAlignment.Center),
      "TextYAlignment": EnumItem(Enum.TextYAlignment.Center),
      "Visible": true,
      "ZIndex": 1,
    },
  },
}]])
end)
test("prettyDOM defaults to document.body", function()
	local defaultInlineSnapshot = [[
Folder {
  "Archivable": true,
  "ClassName": "Folder",
  "Name": "Document",
  "Parent": "ScreenGui" [ScreenGui],
  "Frame": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 0,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "Frame",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "Document" [Folder],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({0, 0}, {0, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "TextLabel": TextLabel {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 0,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "TextLabel",
      "ClipsDescendants": false,
      "ContentText": "Hello World!",
      "Font": EnumItem(Enum.Font.Legacy),
      "LayoutOrder": 0,
      "LineHeight": 1,
      "MaxVisibleGraphemes": -1,
      "Name": "TextLabel",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "Frame" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RichText": false,
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({0, 0}, {0, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Text": "Hello World!",
      "TextBounds": Vector2(NAN, NAN),
      "TextColor3": Color3(0.105882, 0.164706, 0.207843),
      "TextFits": false,
      "TextScaled": false,
      "TextSize": 8,
      "TextStrokeColor3": Color3(0, 0, 0),
      "TextStrokeTransparency": 1,
      "TextTransparency": 0,
      "TextTruncate": EnumItem(Enum.TextTruncate.None),
      "TextWrapped": false,
      "TextXAlignment": EnumItem(Enum.TextXAlignment.Center),
      "TextYAlignment": EnumItem(Enum.TextYAlignment.Center),
      "Visible": true,
      "ZIndex": 1,
    },
  },
}]]

	local div = Instance.new("Frame")
	local text = Instance.new("TextLabel")
	text.Text = "Hello World!"
	text.Parent = div
	renderIntoDocument({ div })
	expect(prettyDOM()).toBe(defaultInlineSnapshot)
	expect(prettyDOM(nil)).toBe(defaultInlineSnapshot)
end)
test("prettyDOM supports receiving the document element", function()
	expect(prettyDOM(document)).toBe([[
Folder {
  "Archivable": true,
  "ClassName": "Folder",
  "Name": "Document",
  "Parent": "ScreenGui" [ScreenGui],
}]])
end)
test("logDOM logs prettyDOM to the console", function()
	local div = Instance.new("Frame")
	local text = Instance.new("TextLabel")
	text.Text = "Hello World!"
	text.Parent = div
	local container = render({ div }).container
	logDOM(container)
	expect(console.log).toHaveBeenCalledTimes(1)
	expect((console.log :: any).mock.calls[1][1]).toBe([[
Frame {
  "AbsolutePosition": Vector2(0, 0),
  "AbsoluteRotation": 0,
  "AbsoluteSize": Vector2(0, 0),
  "Active": false,
  "AnchorPoint": Vector2(0, 0),
  "Archivable": true,
  "AutoLocalize": true,
  "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
  "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
  "BackgroundTransparency": 0,
  "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
  "BorderMode": EnumItem(Enum.BorderMode.Outline),
  "BorderSizePixel": 1,
  "ClassName": "Frame",
  "ClipsDescendants": false,
  "LayoutOrder": 0,
  "Name": "Frame",
  "NextSelectionDown": nil,
  "NextSelectionLeft": nil,
  "NextSelectionRight": nil,
  "NextSelectionUp": nil,
  "Parent": "Document" [Folder],
  "Position": UDim2({0, 0}, {0, 0}),
  "RootLocalizationTable": nil,
  "Rotation": 0,
  "Selectable": false,
  "SelectionImageObject": nil,
  "Size": UDim2({0, 0}, {0, 0}),
  "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
  "Style": EnumItem(Enum.FrameStyle.Custom),
  "Visible": true,
  "ZIndex": 1,
  "Frame": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 0,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "Frame",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "Frame" [Frame],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({0, 0}, {0, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "TextLabel": TextLabel {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 0,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "TextLabel",
      "ClipsDescendants": false,
      "ContentText": "Hello World!",
      "Font": EnumItem(Enum.Font.Legacy),
      "LayoutOrder": 0,
      "LineHeight": 1,
      "MaxVisibleGraphemes": -1,
      "Name": "TextLabel",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "Frame" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RichText": false,
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({0, 0}, {0, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Text": "Hello World!",
      "TextBounds": Vector2(NAN, NAN),
      "TextColor3": Color3(0.105882, 0.164706, 0.207843),
      "TextFits": false,
      "TextScaled": false,
      "TextSize": 8,
      "TextStrokeColor3": Color3(0, 0, 0),
      "TextStrokeTransparency": 1,
      "TextTransparency": 0,
      "TextTruncate": EnumItem(Enum.TextTruncate.None),
      "TextWrapped": false,
      "TextXAlignment": EnumItem(Enum.TextXAlignment.Center),
      "TextYAlignment": EnumItem(Enum.TextYAlignment.Center),
      "Visible": true,
      "ZIndex": 1,
    },
  },
}]])
end)
test("logDOM logs prettyDOM with code frame to the console", function()
	(getUCDModule.getUserCodeFrame :: any).mockImplementationOnce(function()
		return [["/home/john/projects/sample-error/error-example.js:7:14
      5 |         document.createTextNode('Hello World!')
      6 |       )
    > 7 |       screen.debug()
        |              ^
    "
  ]]
	end)
	local div = Instance.new("Frame")
	local text = Instance.new("TextLabel")
	text.Text = "Hello World!"
	text.Parent = div
	local container = render({ div }).container
	logDOM(container)
	expect(console.log).toHaveBeenCalledTimes(1)
	expect((console.log :: any).mock.calls[1][1]).toBe([[
Frame {
  "AbsolutePosition": Vector2(0, 0),
  "AbsoluteRotation": 0,
  "AbsoluteSize": Vector2(0, 0),
  "Active": false,
  "AnchorPoint": Vector2(0, 0),
  "Archivable": true,
  "AutoLocalize": true,
  "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
  "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
  "BackgroundTransparency": 0,
  "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
  "BorderMode": EnumItem(Enum.BorderMode.Outline),
  "BorderSizePixel": 1,
  "ClassName": "Frame",
  "ClipsDescendants": false,
  "LayoutOrder": 0,
  "Name": "Frame",
  "NextSelectionDown": nil,
  "NextSelectionLeft": nil,
  "NextSelectionRight": nil,
  "NextSelectionUp": nil,
  "Parent": "Document" [Folder],
  "Position": UDim2({0, 0}, {0, 0}),
  "RootLocalizationTable": nil,
  "Rotation": 0,
  "Selectable": false,
  "SelectionImageObject": nil,
  "Size": UDim2({0, 0}, {0, 0}),
  "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
  "Style": EnumItem(Enum.FrameStyle.Custom),
  "Visible": true,
  "ZIndex": 1,
  "Frame": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 0,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "Frame",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "Frame" [Frame],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({0, 0}, {0, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "TextLabel": TextLabel {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 0,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "TextLabel",
      "ClipsDescendants": false,
      "ContentText": "Hello World!",
      "Font": EnumItem(Enum.Font.Legacy),
      "LayoutOrder": 0,
      "LineHeight": 1,
      "MaxVisibleGraphemes": -1,
      "Name": "TextLabel",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "Frame" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RichText": false,
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({0, 0}, {0, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Text": "Hello World!",
      "TextBounds": Vector2(NAN, NAN),
      "TextColor3": Color3(0.105882, 0.164706, 0.207843),
      "TextFits": false,
      "TextScaled": false,
      "TextSize": 8,
      "TextStrokeColor3": Color3(0, 0, 0),
      "TextStrokeTransparency": 1,
      "TextTransparency": 0,
      "TextTruncate": EnumItem(Enum.TextTruncate.None),
      "TextWrapped": false,
      "TextXAlignment": EnumItem(Enum.TextXAlignment.Center),
      "TextYAlignment": EnumItem(Enum.TextYAlignment.Center),
      "Visible": true,
      "ZIndex": 1,
    },
  },
}

"/home/john/projects/sample-error/error-example.js:7:14
      5 |         document.createTextNode('Hello World!')
      6 |       )
    > 7 |       screen.debug()
        |              ^
    "
  ]])
end)

describe("prettyDOM fails with first parameter without outerHTML field", function()
	test("with array", function()
		expect(function()
			return prettyDOM({ "outerHTML" } :: any)
		end).toThrowError("Expected an Instance but got table")
	end)

	test("with number", function()
		expect(function()
			return prettyDOM(1 :: any)
		end).toThrowError("Expected an Instance but got number")
	end)

	test("with object", function()
		expect(function()
			return prettyDOM({} :: any)
		end).toThrowError("Expected an Instance but got table")
	end)
end)

-- ROBLOX deviation START: by default we don't ignore any Instance. Replacing with equivalents
test("prettyDOM returns all nodes by default", function()
	local div = Instance.new("Frame")
	local label = Instance.new("TextLabel")
	label.Text = "TextLabelText"
	label.Parent = div
	local button = Instance.new("TextButton")
	button.Text = "TextButtonText"
	button.Parent = div
	local container = renderIntoDocument({ div }).container
	expect(prettyDOM(container)).toBe([[
Folder {
  "Archivable": true,
  "ClassName": "Folder",
  "Name": "Document",
  "Parent": "ScreenGui" [ScreenGui],
  "Frame": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 0,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "Frame",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "Document" [Folder],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({0, 0}, {0, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "TextButton": TextButton {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": true,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoButtonColor": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 0,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "TextButton",
      "ClipsDescendants": false,
      "ContentText": "TextButtonText",
      "Font": EnumItem(Enum.Font.Legacy),
      "LayoutOrder": 0,
      "LineHeight": 1,
      "MaxVisibleGraphemes": -1,
      "Modal": false,
      "Name": "TextButton",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "Frame" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RichText": false,
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": true,
      "Selected": false,
      "SelectionImageObject": nil,
      "Size": UDim2({0, 0}, {0, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Style": EnumItem(Enum.ButtonStyle.Custom),
      "Text": "TextButtonText",
      "TextBounds": Vector2(NAN, NAN),
      "TextColor3": Color3(0.105882, 0.164706, 0.207843),
      "TextFits": false,
      "TextScaled": false,
      "TextSize": 8,
      "TextStrokeColor3": Color3(0, 0, 0),
      "TextStrokeTransparency": 1,
      "TextTransparency": 0,
      "TextTruncate": EnumItem(Enum.TextTruncate.None),
      "TextWrapped": false,
      "TextXAlignment": EnumItem(Enum.TextXAlignment.Center),
      "TextYAlignment": EnumItem(Enum.TextYAlignment.Center),
      "Visible": true,
      "ZIndex": 1,
    },
    "TextLabel": TextLabel {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 0,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "TextLabel",
      "ClipsDescendants": false,
      "ContentText": "TextLabelText",
      "Font": EnumItem(Enum.Font.Legacy),
      "LayoutOrder": 0,
      "LineHeight": 1,
      "MaxVisibleGraphemes": -1,
      "Name": "TextLabel",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "Frame" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RichText": false,
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({0, 0}, {0, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Text": "TextLabelText",
      "TextBounds": Vector2(NAN, NAN),
      "TextColor3": Color3(0.105882, 0.164706, 0.207843),
      "TextFits": false,
      "TextScaled": false,
      "TextSize": 8,
      "TextStrokeColor3": Color3(0, 0, 0),
      "TextStrokeTransparency": 1,
      "TextTransparency": 0,
      "TextTruncate": EnumItem(Enum.TextTruncate.None),
      "TextWrapped": false,
      "TextXAlignment": EnumItem(Enum.TextXAlignment.Center),
      "TextYAlignment": EnumItem(Enum.TextYAlignment.Center),
      "Visible": true,
      "ZIndex": 1,
    },
  },
}]])
end)
test("prettyDOM can use a custom filter", function()
	local div = Instance.new("Frame")
	local label = Instance.new("TextLabel")
	label.Text = "TextLabelText"
	label.Parent = div
	local button = Instance.new("TextButton")
	button.Text = "TextButtonText"
	button.Parent = div
	local container = renderIntoDocument({ div }).container
	expect(prettyDOM(container, math.huge, {
		filterNode = function(instance)
			return not instance:IsA("TextButton")
		end,
	})).toBe([[
Folder {
  "Archivable": true,
  "ClassName": "Folder",
  "Name": "Document",
  "Parent": "ScreenGui" [ScreenGui],
  "Frame": Frame {
    "AbsolutePosition": Vector2(0, 0),
    "AbsoluteRotation": 0,
    "AbsoluteSize": Vector2(0, 0),
    "Active": false,
    "AnchorPoint": Vector2(0, 0),
    "Archivable": true,
    "AutoLocalize": true,
    "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
    "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
    "BackgroundTransparency": 0,
    "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
    "BorderMode": EnumItem(Enum.BorderMode.Outline),
    "BorderSizePixel": 1,
    "ClassName": "Frame",
    "ClipsDescendants": false,
    "LayoutOrder": 0,
    "Name": "Frame",
    "NextSelectionDown": nil,
    "NextSelectionLeft": nil,
    "NextSelectionRight": nil,
    "NextSelectionUp": nil,
    "Parent": "Document" [Folder],
    "Position": UDim2({0, 0}, {0, 0}),
    "RootLocalizationTable": nil,
    "Rotation": 0,
    "Selectable": false,
    "SelectionImageObject": nil,
    "Size": UDim2({0, 0}, {0, 0}),
    "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
    "Style": EnumItem(Enum.FrameStyle.Custom),
    "Visible": true,
    "ZIndex": 1,
    "TextLabel": TextLabel {
      "AbsolutePosition": Vector2(0, 0),
      "AbsoluteRotation": 0,
      "AbsoluteSize": Vector2(0, 0),
      "Active": false,
      "AnchorPoint": Vector2(0, 0),
      "Archivable": true,
      "AutoLocalize": true,
      "AutomaticSize": EnumItem(Enum.AutomaticSize.None),
      "BackgroundColor3": Color3(0.639216, 0.635294, 0.647059),
      "BackgroundTransparency": 0,
      "BorderColor3": Color3(0.105882, 0.164706, 0.207843),
      "BorderMode": EnumItem(Enum.BorderMode.Outline),
      "BorderSizePixel": 1,
      "ClassName": "TextLabel",
      "ClipsDescendants": false,
      "ContentText": "TextLabelText",
      "Font": EnumItem(Enum.Font.Legacy),
      "LayoutOrder": 0,
      "LineHeight": 1,
      "MaxVisibleGraphemes": -1,
      "Name": "TextLabel",
      "NextSelectionDown": nil,
      "NextSelectionLeft": nil,
      "NextSelectionRight": nil,
      "NextSelectionUp": nil,
      "Parent": "Frame" [Frame],
      "Position": UDim2({0, 0}, {0, 0}),
      "RichText": false,
      "RootLocalizationTable": nil,
      "Rotation": 0,
      "Selectable": false,
      "SelectionImageObject": nil,
      "Size": UDim2({0, 0}, {0, 0}),
      "SizeConstraint": EnumItem(Enum.SizeConstraint.RelativeXY),
      "Text": "TextLabelText",
      "TextBounds": Vector2(NAN, NAN),
      "TextColor3": Color3(0.105882, 0.164706, 0.207843),
      "TextFits": false,
      "TextScaled": false,
      "TextSize": 8,
      "TextStrokeColor3": Color3(0, 0, 0),
      "TextStrokeTransparency": 1,
      "TextTransparency": 0,
      "TextTruncate": EnumItem(Enum.TextTruncate.None),
      "TextWrapped": false,
      "TextXAlignment": EnumItem(Enum.TextXAlignment.Center),
      "TextYAlignment": EnumItem(Enum.TextYAlignment.Center),
      "Visible": true,
      "ZIndex": 1,
    },
  },
}]])
end)
-- ROBLOX deviation END
return {}
