-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent.Parent
local var1 = require(var0.Packages.Roact)
local var2 = require(var0.Packages.Framework)
local var3 = var2.ContextServices
local var4 = var2.UI
local var5 = var4.Button
local var6 = var4.Pane
local var7 = var4.TextLabel
local var8 = var2.Util.LayoutOrderIterator
local var9 = var1.PureComponent:extend("ColorPickerTopControls")
local function fun0(arg1)
   local var0 = arg1.props
   local var1 = var0.Stylizer.ColorPickerTopControls
   local var2 = var0.Localization
   local var3 = var8.new()
   local var40 = {}
   var40.LayoutOrder = var0.LayoutOrder
   var40.Layout = Enum.FillDirection.Vertical
   var40.Size = var1.Size
   var40.Spacing = var1.Spacing
   local var45 = {}
   local var49 = {}
   var49.Text = var2:getText("Info", "ColorPickerTitle") ... " " ... var0.TagName
   var49.Size = var1.TitleTextSize
   var49.LayoutOrder = var3:getNextOrder()
   var45.TitleText = var1.createElement(var7, var49)
   local var65 = {}
   var65.LayoutOrder = var3:getNextOrder()
   var65.Size = var1.ButtonsPaneSize
   var65.Layout = Enum.FillDirection.Horizontal
   var65.HorizontalAlignment = Enum.HorizontalAlignment.Center
   var65.Spacing = var1.ButtonsPaneSpacing
   var65.Padding = var1.ButtonsPanePadding
   local var73 = {}
   local var77 = {}
   var77.Size = var1.CancelButtonSize
   var77.Text = var2:getText("General", "Cancel")
   var77.OnClick = var0.Close
   var77.LayoutOrder = 1
   var77.Style = "Round"
   var73.Cancel = var1.createElement(var5, var77)
   local var90 = {}
   var90.Size = var1.SubmitButtonSize
   var90.LayoutOrder = 2
   var90.Text = var2:getText("General", "Apply")
   var90.Style = "RoundPrimary"
   var90.OnClick = var0.Save
   var73.Submit = var1.createElement(var5, var90)
   var45.Buttons = var1.createElement(var6, var65, var73)
   local var104 = {}
   var104.LayoutOrder = var3:getNextOrder()
   var104.Size = var1.ColorPaneSize
   var104.Layout = Enum.FillDirection.Horizontal
   var104.Spacing = var1.ColorPaneSpacing
   var104.Padding = var1.ColorPanePadding
   local var111 = {}
   local var115 = {}
   var115.TextXAlignment = Enum.TextXAlignment.Right
   var115.Text = var2:getText("Info", "SelectedColor")
   var115.Size = var1.PreviewTitleSize
   var115.LayoutOrder = 1
   var111.TitleText = var1.createElement(var7, var115)
   local var127 = {}
   var127.LayoutOrder = 2
   var127.Size = var1.ColorPreviewSize
   var127.BackgroundColor = var0.Color
   var111.Preview = var1.createElement(var6, var127)
   var45.ColorPane = var1.createElement(var6, var104, var111)
   return var1.createElement(var6, var40, var45)
end

function var9.render(arg1)
   local var0 = arg1.props
   local var1 = var0.Stylizer.ColorPickerTopControls
   local var2 = var0.Localization
   local var3 = var8.new()
   local var40 = {}
   var40.LayoutOrder = var0.LayoutOrder
   var40.Layout = Enum.FillDirection.Vertical
   var40.Size = var1.Size
   var40.Spacing = var1.Spacing
   local var45 = {}
   local var49 = {}
   var49.Text = var2:getText("Info", "ColorPickerTitle") ... " " ... var0.TagName
   var49.Size = var1.TitleTextSize
   var49.LayoutOrder = var3:getNextOrder()
   var45.TitleText = var1.createElement(var7, var49)
   local var65 = {}
   var65.LayoutOrder = var3:getNextOrder()
   var65.Size = var1.ButtonsPaneSize
   var65.Layout = Enum.FillDirection.Horizontal
   var65.HorizontalAlignment = Enum.HorizontalAlignment.Center
   var65.Spacing = var1.ButtonsPaneSpacing
   var65.Padding = var1.ButtonsPanePadding
   local var73 = {}
   local var77 = {}
   var77.Size = var1.CancelButtonSize
   var77.Text = var2:getText("General", "Cancel")
   var77.OnClick = var0.Close
   var77.LayoutOrder = 1
   var77.Style = "Round"
   var73.Cancel = var1.createElement(var5, var77)
   local var90 = {}
   var90.Size = var1.SubmitButtonSize
   var90.LayoutOrder = 2
   var90.Text = var2:getText("General", "Apply")
   var90.Style = "RoundPrimary"
   var90.OnClick = var0.Save
   var73.Submit = var1.createElement(var5, var90)
   var45.Buttons = var1.createElement(var6, var65, var73)
   local var104 = {}
   var104.LayoutOrder = var3:getNextOrder()
   var104.Size = var1.ColorPaneSize
   var104.Layout = Enum.FillDirection.Horizontal
   var104.Spacing = var1.ColorPaneSpacing
   var104.Padding = var1.ColorPanePadding
   local var111 = {}
   local var115 = {}
   var115.TextXAlignment = Enum.TextXAlignment.Right
   var115.Text = var2:getText("Info", "SelectedColor")
   var115.Size = var1.PreviewTitleSize
   var115.LayoutOrder = 1
   var111.TitleText = var1.createElement(var7, var115)
   local var127 = {}
   var127.LayoutOrder = 2
   var127.Size = var1.ColorPreviewSize
   var127.BackgroundColor = var0.Color
   var111.Preview = var1.createElement(var6, var127)
   var45.ColorPane = var1.createElement(var6, var104, var111)
   return var1.createElement(var6, var40, var45)
end

fun0 = var3.withContext
local var134 = {}
var134.Analytics = var3.Analytics
var134.Localization = var3.Localization
var134.Stylizer = var2.Style.Stylizer
var9 = fun0(var134)(var9)
return var9
