--[[
	Package link auto-generated by manage_libraries and Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index
local Package = require(PackageIndex["roblox_roact-fit-components"]["roact-fit-components"])
return Package
