--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["RoactNavigation-3dc2ef99-923e9108"]["RoactNavigation"])

return Package
