return  {
	Size_0 = "Global.Size_0",
	Size_25 = "Global.Size_25",
	Size_50 = "Global.Size_50",
	Size_75 = "Global.Size_75",
	Size_100 = "Global.Size_100",
	Size_150 = "Global.Size_150",
	Size_200 = "Global.Size_200",
	Size_250 = "Global.Size_250",
	Size_300 = "Global.Size_300",
	Size_350 = "Global.Size_350",
	Size_400 = "Global.Size_400",
	Size_450 = "Global.Size_450",
	Size_500 = "Global.Size_500",
	Size_600 = "Global.Size_600",
	Size_700 = "Global.Size_700",
	Size_800 = "Global.Size_800",
	Size_900 = "Global.Size_900",
	Size_1000 = "Global.Size_1000",
	Size_1100 = "Global.Size_1100",
	Size_1200 = "Global.Size_1200",
	Size_1300 = "Global.Size_1300",
	Size_1400 = "Global.Size_1400",
	Space_0 = "Global.Space_0",
	Space_25 = "Global.Space_25",
	Space_50 = "Global.Space_50",
	Space_75 = "Global.Space_75",
	Space_100 = "Global.Space_100",
	Space_150 = "Global.Space_150",
	Space_200 = "Global.Space_200",
	Space_250 = "Global.Space_250",
	Space_300 = "Global.Space_300",
	Space_400 = "Global.Space_400",
	Space_500 = "Global.Space_500",
	Space_600 = "Global.Space_600",
	Space_800 = "Global.Space_800",
	Space_1000 = "Global.Space_1000",
	FontSize_25 = "Global.FontSize_25",
	FontSize_50 = "Global.FontSize_50",
	FontSize_75 = "Global.FontSize_75",
	FontSize_100 = "Global.FontSize_100",
	FontSize_200 = "Global.FontSize_200",
	FontSize_300 = "Global.FontSize_300",
	FontSize_400 = "Global.FontSize_400",
	FontSize_500 = "Global.FontSize_500",
	FontSize_600 = "Global.FontSize_600",
	FontSize_700 = "Global.FontSize_700",
	FontSize_800 = "Global.FontSize_800",
	FontSize_900 = "Global.FontSize_900",
	FontSize_1000 = "Global.FontSize_1000",
	Family = {
		Standard = "Global.Family.Standard",
	},
	Weight_300 = "Global.Weight_300",
	Weight_400 = "Global.Weight_400",
	Weight_600 = "Global.Weight_600",
	Weight_700 = "Global.Weight_700",
	Weight_900 = "Global.Weight_900",
	LetterSpacing = {
		Default = "Global.LetterSpacing.Default",
	},
	LineHeight_100 = "Global.LineHeight_100",
	LineHeight_200 = "Global.LineHeight_200",
	LineHeight_300 = "Global.LineHeight_300",
	LineHeight_400 = "Global.LineHeight_400",
	Stroke_50 = "Global.Stroke_50",
	Stroke_100 = "Global.Stroke_100",
	Stroke_150 = "Global.Stroke_150",
	Stroke_200 = "Global.Stroke_200",
	Stroke_250 = "Global.Stroke_250",
	Stroke_300 = "Global.Stroke_300",
	Stroke_400 = "Global.Stroke_400",
	Opacity_0 = "Global.Opacity_0",
	Opacity_8 = "Global.Opacity_8",
	Opacity_12 = "Global.Opacity_12",
	Opacity_16 = "Global.Opacity_16",
	Opacity_32 = "Global.Opacity_32",
	Opacity_68 = "Global.Opacity_68",
	Opacity_84 = "Global.Opacity_84",
	Opacity_88 = "Global.Opacity_88",
	Opacity_92 = "Global.Opacity_92",
	Opacity_100 = "Global.Opacity_100",
	Color = {
		Black = {
			Color3 = "Global.Color.Black.Color3",
			Transparency = "Global.Color.Black.Transparency",
		},
		White = {
			Color3 = "Global.Color.White.Color3",
			Transparency = "Global.Color.White.Transparency",
		},
		Green = {
			Color3 = "Global.Color.Green.Color3",
			Transparency = "Global.Color.Green.Transparency",
		},
		Red = {
			Color3 = "Global.Color.Red.Color3",
			Transparency = "Global.Color.Red.Transparency",
		},
		Blue = {
			Color3 = "Global.Color.Blue.Color3",
			Transparency = "Global.Color.Blue.Transparency",
		},
		Carbon = {
			Color3 = "Global.Color.Carbon.Color3",
			Transparency = "Global.Color.Carbon.Transparency",
		},
		Flint = {
			Color3 = "Global.Color.Flint.Color3",
			Transparency = "Global.Color.Flint.Transparency",
		},
		Graphite = {
			Color3 = "Global.Color.Graphite.Color3",
			Transparency = "Global.Color.Graphite.Transparency",
		},
		Obsidian = {
			Color3 = "Global.Color.Obsidian.Color3",
			Transparency = "Global.Color.Obsidian.Transparency",
		},
		Pumice = {
			Color3 = "Global.Color.Pumice.Color3",
			Transparency = "Global.Color.Pumice.Transparency",
		},
		Slate = {
			Color3 = "Global.Color.Slate.Color3",
			Transparency = "Global.Color.Slate.Transparency",
		},
		Alabaster = {
			Color3 = "Global.Color.Alabaster.Color3",
			Transparency = "Global.Color.Alabaster.Transparency",
		},
		Ash = {
			Color3 = "Global.Color.Ash.Color3",
			Transparency = "Global.Color.Ash.Transparency",
		},
		Chalk = {
			Color3 = "Global.Color.Chalk.Color3",
			Transparency = "Global.Color.Chalk.Transparency",
		},
		Smoke = {
			Color3 = "Global.Color.Smoke.Color3",
			Transparency = "Global.Color.Smoke.Transparency",
		},
		None = {
			Color3 = "Global.Color.None.Color3",
			Transparency = "Global.Color.None.Transparency",
		},
	},
}
