--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["RoduxProfile-133cf2fb-0d245abc"]["RoduxProfile"])

return Package
