-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("Toolbox")
local var1 = var0.Packages
local var2 = require(var1.React)
local var3 = require(var1.Framework)
local var4 = var3.UI
local var5 = var3.UI.Pane
local var6 = var4.StyledDialog
local var7 = var4.TextLabel
local var8 = require(var0.Core.Components.PurchaseFlow.PurchaseDialog)
local var9 = var0.Core.Util
local var10 = require(var9.ContextHelper)
local var11 = require(var9.LayoutOrderIterator)
local var12 = require(var9.Constants).Dialog
local var13 = var3.ContextServices.Stylizer
local var14 = var3.ContextServices
local var15 = var14.withContext
local var16 = require(var0.Core.Types.MarketplaceFiatServiceTypes)
return function(arg1)
   local var0 = var14.Localization:use()
   local var1 = var11.new()
   local var81 = {}
   local var83 = {}
   var83.Key = false
   var83.Text = var0:getText("Purchase", "Cancel")
   local var89 = {}
   var89.Key = true
   var89.Style = "RoundPrimary"
   var89.Text = var0:getText("Purchase", "Buy")
   var81.Buttons = {}
   var83 = var12.IMAGE_SIZE.X.Offset + var12.PROMPT_SIZE.X.Offset
   var89 = var12.PROMPT_SIZE.Y.Offset + var12.BALANCE_SIZE.Y.Offset
   var81.MinContentSize = Vector2.new(var83, var89)
   var81.OnButtonPressed = arg1.OnButtonClicked
   var81.OnClose = arg1.OnClose
   var81.Title = var0:getText("Purchase", "BuyTitle")
   local var102 = {}
   local var106 = {}
   var106.AutomaticSize = Enum.AutomaticSize.XY
   var106.Layout = Enum.FillDirection.Horizontal
   var106.LayoutOrder = arg1.LayoutOrder
   var106.Spacing = 12
   var106.VerticalAlignment = Enum.VerticalAlignment.Top
   local var112 = {}
   local var116 = {}
   var116.BackgroundTransparency = 1
   var116.Image = arg1.Thumbnail
   var116.LayoutOrder = var1:getNextOrder()
   var116.Size = var12.IMAGE_SIZE
   var112.Thumbnail = var2.createElement("ImageLabel", var116)
   local var126 = {}
   var126.AutomaticSize = Enum.AutomaticSize.Y
   var126.Size = UDim2.new(0, var12.PROMPT_SIZE.X.Offset, 0, 0)
   var126.LayoutOrder = var1:getNextOrder()
   local var141 = {}
   var141.name = arg1.Name
   var141.creator = arg1.CreatorName
   var141.price = arg1.Price
   var126.Text = var0:getText("Purchase", "FiatBuyPrompt", var141)
   var126.TextColor = var13:use().purchaseDialog.promptText
   var126.TextWrapped = true
   var126.TextXAlignment = Enum.TextXAlignment.Left
   var126.TextYAlignment = Enum.TextYAlignment.Top
   var112.Prompt = var2.createElement(var7, var126)
   var102.Container = var2.createElement(var5, var106, var112)
   return var2.createElement(var6, var81, var102)
end
