-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("Toolbox")
local var1 = var0.Packages
local var2 = require(var1.React)
local var3 = require(var1.Framework)
local var4 = var3.UI
local var5 = var3.UI.Pane
local var6 = var4.StyledDialog
local var7 = var4.TextLabel
local var8 = require(var0.Core.Components.PurchaseFlow.PurchaseDialog)
local var9 = var0.Core.Util
local var10 = require(var9.LayoutOrderIterator)
local var11 = require(var9.Constants).Dialog
local var12 = var3.ContextServices.Stylizer
local var13 = var3.ContextServices
local var14 = var13.withContext
local var15 = require(var0.Core.Types.MarketplaceFiatServiceTypes)
return function(arg1)
   local var0 = var13.Localization:use()
   local var1 = var10.new()
   local var78 = {}
   local var80 = {}
   var80.Key = false
   var80.Text = var0:getText("Purchase", "Cancel")
   local var86 = {}
   var86.Key = true
   var86.Style = "RoundPrimary"
   var86.Text = var0:getText("Purchase", "Buy")
   var78.Buttons = {}
   var80 = var11.IMAGE_SIZE.X.Offset + var11.PROMPT_SIZE.X.Offset
   var86 = var11.PROMPT_SIZE.Y.Offset + var11.BALANCE_SIZE.Y.Offset
   var78.MinContentSize = Vector2.new(var80, var86)
   var78.OnButtonPressed = arg1.OnButtonClicked
   var78.OnClose = arg1.OnClose
   var78.Title = var0:getText("Purchase", "BuyTitle")
   local var99 = {}
   local var103 = {}
   var103.AutomaticSize = Enum.AutomaticSize.XY
   var103.Layout = Enum.FillDirection.Horizontal
   var103.LayoutOrder = arg1.LayoutOrder
   var103.Spacing = 12
   var103.VerticalAlignment = Enum.VerticalAlignment.Top
   local var109 = {}
   local var113 = {}
   var113.BackgroundTransparency = 1
   var113.Image = arg1.Thumbnail
   var113.LayoutOrder = var1:getNextOrder()
   var113.Size = var11.IMAGE_SIZE
   var109.Thumbnail = var2.createElement("ImageLabel", var113)
   local var123 = {}
   var123.AutomaticSize = Enum.AutomaticSize.Y
   var123.Size = UDim2.new(0, var11.PROMPT_SIZE.X.Offset, 0, 0)
   var123.LayoutOrder = var1:getNextOrder()
   local var138 = {}
   var138.name = arg1.Name
   var138.creator = arg1.CreatorName
   var138.price = arg1.Price
   var123.Text = var0:getText("Purchase", "FiatBuyPrompt", var138)
   var123.TextColor = var12:use().purchaseDialog.promptText
   var123.TextWrapped = true
   var123.TextXAlignment = Enum.TextXAlignment.Left
   var123.TextYAlignment = Enum.TextYAlignment.Top
   var109.Prompt = var2.createElement(var7, var123)
   var99.Container = var2.createElement(var5, var103, var109)
   return var2.createElement(var6, var78, var99)
end
