[package]
name = "ultimate-list"
version = "0.3.1"
readme = "README.md"
content_root = "src"
files = ["*"]
publish = true
[dependencies.React]
target = "https://github.com/roblox/roact-alignment"
version = "^17.3.7"
