--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["ExperienceChat-09990ed6-a147b962"]["ExperienceChat"])

return Package
