--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["ExperienceChat-0195bf64-20bb1a25"]["ExperienceChat"])

return Package
