--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["ExperienceChat-60e021cb-496bea09"]["ExperienceChat"])

return Package
