--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["ExperienceChat-2bd849d2-78d25f7e"]["ExperienceChat"])

return Package
