--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["MomentsCreationFlow"]["MomentsCreationFlow"])

export type CreationFlowLocalization = Package.CreationFlowLocalization
export type CreationFlowState = Package.CreationFlowState
export type MomentMetadata = Package.MomentMetadata
export type RecommendationRegistrationInfo = Package.RecommendationRegistrationInfo


return Package
