--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["Otter-7466d762-fff3ac76"].Packages["Otter"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package