--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["roblox_policy-provider"]["policy-provider"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package