--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["lua-promise-07b6e77b-1bb842c3"]["lua-promise"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package