--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["RegExp"]["RegExp"])

export type RegExp = Package.RegExp


return Package
