--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["UIBlox-f086ce57-5e12c3a0"].Packages["UIBlox"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package