--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local package = PackageIndex["UIBlox-1e1dafaa-e05b20d6"]["UIBlox"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package