--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = PackageIndex["RbxDesignFoundations-e7e73050-fd2e104b"]["RbxDesignFoundations"]

return Package
