--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["NetworkingUserInfo-b7341c74-5977b047"]["NetworkingUserInfo"])

return Package
