return {
	GRID_SIZE_MIN = 60,
	GRID_SIZE_MAX = 200,
	GRID_SIZE_SNAP_INCREMENT = 10,
	GRID_SIZE_VERTICAL_DRAG_TOLERANCE = 300,
	STUDS_PER_TILE_MIN = 0.1,
	STUDS_PER_TILE_MAX = 20,
	STUDS_PER_TILE_SNAP_INCREMENT = 0.1,
}
