
local List = {
	append = require(script.append),
	copy = require(script.copy),
	copyDeep = require(script.copyDeep),
	count = require(script.count),
	equals = require(script.equals),
	equalsDeep = require(script.equalsDeep),
	every = require(script.every),
	filter = require(script.filter),
	find = require(script.find),
	findLast = require(script.findLast),
	findWhere = require(script.findWhere),
	findWhereLast = require(script.findWhereLast),
	flatMap = require(script.flatMap),
	flatten = require(script.flatten),
	get = require(script.get),
	includes = require(script.includes),
	insert = require(script.insert),
	join = require(script.join),
	joinDeep = require(script.joinDeep),
	map = require(script.map),
	pop = require(script.pop),
	push = require(script.push),
	reduce = require(script.reduce),
	reduceRight = require(script.reduceRight),
	removeIndex = require(script.removeIndex),
	removeValue = require(script.removeValue),
	reverse = require(script.reverse),
	set = require(script.set),
	shift = require(script.shift),
	slice = require(script.slice),
	some = require(script.some),
	sort = require(script.sort),
	splice = require(script.splice),
	toSet = require(script.toSet),
	unshift = require(script.unshift),
	update = require(script.update),
	zip = require(script.zip),
	zipAll = require(script.zipAll),
}

return List