return function()
	local CorePackages = game:GetService("CorePackages")

	local getGameIconRequestSize = require(script.Parent.getGameIconRequestSize)

	local JestGlobals = require(CorePackages.JestGlobals)
	local expect = JestGlobals.expect
	describe("GetGameIconRequestSize()", function()
		it("required image size is close to 50 request size", function()
			local requestSize = getGameIconRequestSize(45)
			expect(requestSize).toBe(50)
		end)
		it("required image size of 50", function()
			local requestSize = getGameIconRequestSize(50)
			expect(requestSize).toBe(50)
		end)
		it("required image size is close to 128 request size", function()
			local requestSize = getGameIconRequestSize(125)
			expect(requestSize).toBe(128)
		end)
		it("required image size of 128", function()
			local requestSize = getGameIconRequestSize(128)
			expect(requestSize).toBe(128)
		end)
		it("required image size is close to 150 request size", function()
			local requestSize = getGameIconRequestSize(140)
			expect(requestSize).toBe(150)
		end)
		it("required image size of 150", function()
			local requestSize = getGameIconRequestSize(150)
			expect(requestSize).toBe(150)
		end)
		it("required image size is close to 256 request size", function()
			local requestSize = getGameIconRequestSize(250)
			expect(requestSize).toBe(256)
		end)
		it("required image size of 256", function()
			local requestSize = getGameIconRequestSize(256)
			expect(requestSize).toBe(256)
		end)
		it("required image size is close to 512 request size", function()
			local requestSize = getGameIconRequestSize(500)
			expect(requestSize).toBe(512)
		end)
		it("required image size of 512", function()
			local requestSize = getGameIconRequestSize(512)
			expect(requestSize).toBe(512)
		end)
		it("required image size is larger than the biggest request size available", function()
			local requestSize = getGameIconRequestSize(1024)
			expect(requestSize).toBe(512)
		end)
	end)
end
