-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = require(script.AssigningGroup)
local var1 = require(script.ColorPicker)
local var2 = require(script.GroupData)
local var3 = require(script.GroupMenu)
local var4 = require(script.HoveredIcon)
local var5 = require(script.IconPicker)
local var6 = require(script.IconSearch)
local var7 = require(script.MinimizedSettingsPane)
local var8 = require(script.RenamingGroup)
local var9 = require(script.RenamingTag)
local var10 = require(script.Search)
local var11 = require(script.TagData)
local var12 = require(script.TagMenu)
local var13 = require(script.UIGroupCollapseState)
local var14 = require(script.UnknownTags)
local var15 = require(script.WorldView)
return function(arg1, arg2)
   arg1 = arg1 or {}
   local var0 = {}
   var0.AssigningGroup = var0(arg1.AssigningGroup, arg2)
   var0.ColorPicker = var1(arg1.ColorPicker, arg2)
   var0.GroupData = var2(arg1.GroupData, arg2)
   var0.GroupMenu = var3(arg1.GroupMenu, arg2)
   var0.HoveredIcon = var4(arg1.HoveredIcon, arg2)
   var0.IconPicker = var5(arg1.IconPicker, arg2)
   var0.IconSearch = var6(arg1.IconSearch, arg2)
   var0.MinimizedSettingsPane = var7(arg1.MinimizedSettingsPane, arg2)
   var0.RenamingGroup = var8(arg1.RenamingGroup, arg2)
   var0.RenamingTag = var9(arg1.RenamingTag, arg2)
   var0.Search = var10(arg1.Search, arg2)
   var0.TagData = var11(arg1.TagData, arg2)
   var0.TagMenu = var12(arg1, arg2)
   var0.UIGroupCollapseState = var13(arg1.UIGroupCollapseState, arg2)
   var0.UnknownTags = var14(arg1.UnknownTags, arg2)
   var0.WorldView = var15(arg1.WorldView, arg2)
   return var0
end
