--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["DiscoveryMonolith"]["DiscoveryMonolith"])

export type GameSearchConfig = Package.GameSearchConfig


return Package
