--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["GameTile"]["GameTile"])

export type ExperienceFooterProps = Package.ExperienceFooterProps
export type GameTileLayoutType = Package.GameTileLayoutType


return Package
