--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["GameCollectionViews"]["GameCollectionViews"])

export type GameCollectionLayoutParams = Package.GameCollectionLayoutParams


return Package
