MAIN:
        0 PREPVARARGS                      0
        1 DUPTABLE                         R0 K34 [{[1] = "userId", ["UserName"] = "userName", ["GroupId"] = "groupId", ["GroupName"] = "groupName", ["RoleId"] = "rolesetId", ["RoleName"] = "rolesetName", ["RoleRank"] = "rank", ["Action"] = "action", ["AllowedPermissions"] = "allowedPermissions", ["PlayAction"] = "Play", ["EditAction"] = "Edit", ["AdminAction"] = "Admin", ["SubjectType"] = "subjectType", ["SubjectId"] = "subjectId", ["UserSubject"] = "User", ["GroupSubject"] = "Group", ["RoleSubject"] = "Roleset"}]
        2 DUPTABLE                         R1 K72 [{["default"] = "A1A2A5", ["Invalid"] = "A1A2A5", ["Blue"] = "00A2FF", ["LightBlue"] = "55C1FF", ["Green"] = "00B864", ["LightGreen"] = "26FF9C", ["Purple"] = "9E78EC", ["LightPurple"] = "B69AF1", ["Yellow"] = "D8A009", ["LightYellow"] = "F7C744", ["Orange"] = "EF7A36", ["LightOrange"] = "F29057", ["Red"] = "F2453D", ["LightRed"] = "F4645D", ["Pink"] = "E245CD", ["LightPink"] = "EC83DE", ["Teal"] = "00D0D0", ["LightTeal"] = "36FFFF", ["Standard"] = "FFFFFF"}]
        3 DUPTABLE                         R2 K98 [{["default"] = "202227", ["Invalid"] = "202227", ["Blue"] = "528BFF", ["Green"] = "01854B", ["Purple"] = "A766F5", ["Yellow"] = "976C00", ["Orange"] = "DC6423", ["Red"] = "DF281F", ["Magenta"] = "D540F5", ["Teal"] = "0494B2", ["Turquoise"] = "02353F", ["Rust"] = "A9430B", ["Pistachio"] = "0C9B5A", ["Midnight"] = "0027B8", ["Lavender"] = "5614A5", ["Pink"] = "E74E90", ["Crimson"] = "830F07", ["Plum"] = "8A0CA7"}]
        4 DUPTABLE                         R3 K115 [{["default"] = "F7F7F8", ["Invalid"] = "F7F7F8", ["Blue"] = "70A0FF", ["Green"] = "39C582", ["Purple"] = "B682F7", ["Yellow"] = "DBA61F", ["Orange"] = "FA945A", ["Red"] = "E75750", ["Magenta"] = "DF6AF7", ["Teal"] = "7EE5F8", ["Turquoise"] = "056C82", ["Rust"] = "DC6423", ["Pistachio"] = "B0F6D0", ["Midnight"] = "0035F5", ["Lavender"] = "822EE7", ["Pink"] = "F7ADCF", ["Crimson"] = "C5120A", ["Plum"] = "C00AE8"}]
        5 DUPTABLE                         R4 K120 [{"webKeys", "granularCollaboratorColorsMap", "granularCollaboratorUpdatedLightModeColorsMap", "granularCollaboratorUpdatedDarkModeColorsMap"}]
        6 SETTABLEKS                       R0 R4 K116 ["webKeys"]
        8 SETTABLEKS                       R1 R4 K117 ["granularCollaboratorColorsMap"]
       10 SETTABLEKS                       R2 R4 K118 ["granularCollaboratorUpdatedLightModeColorsMap"]
       12 SETTABLEKS                       R3 R4 K119 ["granularCollaboratorUpdatedDarkModeColorsMap"]
       14 RETURN                           R4 1
