-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = game:GetFastFlag("ToolboxEnableAudioGrantDialog")
local var1 = {}
var1.All = "All"
var1.UserId = "userId"
var1.UserName = "userName"
var1.GroupId = "groupId"
var1.GroupName = "groupName"
var1.RoleId = "rolesetId"
var1.RoleName = "rolesetName"
var1.RoleRank = "rank"
var1.UpToVersion = "upToVersion"
var1.Action = "action"
var1.UseViewAction = "UseView"
var1.EditAction = "Edit"
var1.RevokedAction = "Revoked"
var1.UseAction = "Use"
var1.GrantAssetPermissionsAction = "GrantAssetPermissions"
var1.SubjectType = "subjectType"
var1.SubjectId = "subjectId"
var1.PermissionLevel = "permissionLevel"
var1.PermissionSource = "permissionSource"
var1.UserSubject = "User"
var1.GroupSubject = "Group"
var1.RoleSubject = "Roleset"
var1.GroupRolesetSubject = "GroupRoleset"
var1.Requests = "requests"
var1.Universe = "Universe"
var1.UnknownError = "UnknownError"
var1.HasPermission = "HasPermission"
var1.NoPermission = "NoPermission"
var1.AssetNotFound = "AssetNotFound"
local var2 = {}
var2.AccountPermissionLevel = "Account"
var2.UniversePermissionLevel = "Universe"
var2.AssetPermissionLevel = "Asset"
var2.AssetPermissionSource = "AssetPermissions"
var2.GroupPermissionSource = "GroupRolesetPermissions"
local var3 = {}
var3.webKeys = var1
var3.webValues = var2
return var3
