MAIN:
        0 PREPVARARGS                      0
        1 GETIMPORT                        R0 K1 [require]
        3 GETIMPORT                        R3 K3 [script]
        5 GETTABLEKS                       R2 R3 K4 ["Parent"]
        7 GETTABLEKS                       R1 R2 K5 ["SkillDefinition"]
        9 CALL                             R0 1 1
       10 DUPTABLE                         R1 K9 [{"name", "description", "content"}]
       11 LOADK                            R2 K10 ["roblox_scripting"]
       12 SETTABLEKS                       R2 R1 K6 ["name"]
       14 LOADK                            R2 K11 ["Roblox Luau scripting best practices, common patterns, and API conventions. Use when writing, reviewing, or debugging Roblox scripts."]
       15 SETTABLEKS                       R2 R1 K7 ["description"]
       17 LOADK                            R2 K12 ["ROBLOX LUAU SCRIPTING GUIDE\n\nSCRIPT TYPES:\n- Script (ServerScript): Runs on the server. Place in ServerScriptService or ServerStorage.\n- LocalScript: Runs on the client. Place in StarterPlayerScripts, StarterCharacterScripts, or StarterGui.\n- ModuleScript: Shared code that can be required by any script. Returns a single value (usually a table).\n\nCOMMON SERVICES:\n- game:GetService(\"Players\") — Access player list and PlayerAdded/PlayerRemoving events\n- game:GetService(\"ReplicatedStorage\") — Shared storage visible to server and client\n- game:GetService(\"ServerStorage\") — Server-only storage, invisible to clients\n- game:GetService(\"ServerScriptService\") — Server-only scripts\n- game:GetService(\"Workspace\") — The 3D world; same as game.Workspace\n- game:GetService(\"RunService\") — Heartbeat, RenderStepped, Stepped events\n- game:GetService(\"UserInputService\") — Client-side input detection\n- game:GetService(\"TweenService\") — Smooth property animations\n- game:GetService(\"HttpService\") — HTTP requests and JSON encoding\n\nREMOTE EVENTS & FUNCTIONS (Client-Server Communication):\n- RemoteEvent: One-way communication. Server:FireClient(player, ...) / Client:FireServer(...)\n- RemoteFunction: Two-way with return value. Use sparingly; prefer RemoteEvents.\n- Place RemoteEvents/RemoteFunctions in ReplicatedStorage so both sides can access them.\n- NEVER trust client input. Always validate on the server.\n\nBEST PRACTICES:\n- Use task.wait() instead of wait() (deprecated)\n- Use task.spawn() instead of spawn() (deprecated)\n- Use task.delay() instead of delay() (deprecated)\n- Prefer :GetService() over direct game.ServiceName access\n- Use :FindFirstChild() with nil checks instead of direct dot access for dynamic instances\n- Clean up connections: store connection = event:Connect(...), then connection:Disconnect()\n- Use :Destroy() to clean up instances, not setting Parent = nil\n- Avoid polling; use events and signals whenever possible\n- Type annotate function parameters for clarity: function foo(player: Player, amount: number)\n\nERROR HANDLING:\n- Use pcall/xpcall for operations that can fail (HTTP requests, :FindFirstChild chains, etc.)\n- Pattern: local success, result = pcall(function() return riskyOperation() end)\n\nCOMMON PATTERNS:\n- Player setup: Players.PlayerAdded:Connect(function(player) ... end)\n- Character access: player.CharacterAdded:Connect(function(character) ... end)\n- Instance creation: local part = Instance.new(\"Part\"); part.Parent = workspace\n- Debounce: local debounce = false; if debounce then return end; debounce = true; task.delay(1, function() debounce = false end)\n- Module pattern: local M = {}; function M.foo() end; return M"]
       18 SETTABLEKS                       R2 R1 K8 ["content"]
       20 RETURN                           R1 1
