--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["ReactDevtoolsShared-d86ebb2a-ca453478"]["ReactDevtoolsShared"])

return Package
