-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("FileSync")
local var1 = require(var0.Packages.React)
local var2 = require(var0.Src.Util.Constants)
local var3 = require(var0.Src.Components.ActionButton)
local var4 = require(var0.Src.Util.ModernIcons)
local var5 = require(var0.Packages.Framework)
local var6 = var5.ContextServices.Localization
local var7 = var5.Util.LayoutOrderIterator
return function(arg1)
   local var0 = var6:use()
   local var1 = var7.new()
   local var230 = {}
   var230.BackgroundTransparency = 1
   var230.LayoutOrder = arg1.LayoutOrder
   var230.Name = "Buttons"
   var230.Size = arg1.Size or UDim2.new(1, var2.BUTTON_PADDING * 2, 0, var2.BUTTON_HEIGHT)
   local var234 = {}
   local var238 = {}
   var238.FillDirection = Enum.FillDirection.Horizontal
   var238.SortOrder = Enum.SortOrder.LayoutOrder
   var234.ButtonsListLayout = var1.createElement("UIListLayout", var238)
   local var245 = {}
   var245.PaddingBottom = UDim.new(var2.BUTTON_PADDING_VERTICAL, 0)
   var245.PaddingTop = UDim.new(var2.BUTTON_PADDING_VERTICAL, 0)
   var234.ButtonsUIPadding = var1.createElement("UIPadding", var245)
   local var260 = {}
   var260.BackgroundTransparency = 1
   var260.LayoutOrder = var1:getNextOrder()
   var260.Size = UDim2.new(var2.BUTTON_PADDING_HORIZONTAL, 0, 1, 0)
   var234.Spacer1 = var1.createElement("Frame", var260)
   local var275 = {}
   var275.Size = UDim2.new(var2.BUTTON_SIZE, 0, 1, 0)
   var275.Image = var4.getIconForCurrentTheme(var4.IconEnums.Export)
   var275.OnClick = arg1.OnExport
   var275.Text = var0:getText("Operations", "Export")
   var275.TextColor3 = Color3.new(0, 0, 0)
   var275.TextSize = 14
   var275.Font = Enum.Font.SourceSans
   var275.LayoutOrder = var1:getNextOrder()
   var275.HasChanges = arg1.ChangesInStudio
   var234.ExportButton = var1.createElement(var3, var275)
   local var308 = {}
   var308.BackgroundTransparency = 1
   var308.LayoutOrder = var1:getNextOrder()
   var308.Size = UDim2.new(var2.BUTTON_PADDING_CENTER, 0, 1, 0)
   var234.Spacer2 = var1.createElement("Frame", var308)
   local var323 = {}
   var323.Size = UDim2.new(var2.BUTTON_SIZE, 0, 1, 0)
   var323.Image = var4.getIconForCurrentTheme(var4.IconEnums.Import)
   var323.OnClick = arg1.OnImport
   var323.Text = var0:getText("Operations", "Import")
   var323.LayoutOrder = var1:getNextOrder()
   var323.HasChanges = arg1.ChangesInDisk
   var234.ImportButton = var1.createElement(var3, var323)
   local var349 = {}
   var349.BackgroundTransparency = 1
   var349.LayoutOrder = var1:getNextOrder()
   var349.Size = UDim2.new(var2.BUTTON_PADDING_HORIZONTAL, 0, 1, 0)
   var234.Spacer3 = var1.createElement("Frame", var349)
   return var1.createElement("Frame", var230, var234)
end
