-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("VisualizationModes")
local var1 = require(var0.Packages.React)
local var2 = require(var0.Src.Modes.SettingVisualizationMode)
local var3 = require(var0.Packages._Index.DeveloperFramework.DeveloperFramework.Types)
return function(arg1)
   local var0 = settings()
   local var1 = arg1.Localization
   local var33 = {}
   var33.Name = "Physics"
   var33.Title = var1:getText("VisualizationModeCategories", "Physics")
   local var43 = {}
   var43.Name = "DecompositionGeometry"
   var43.Title = var1:getText("StudioModes", "DecompositionGeometry")
   var43.Setting = var0.Physics
   var43.Property = "ShowDecompositionGeometry"
   local var51 = var1.createElement(var2, var43)
   local var55 = {}
   var55.Name = "ConstraintDetails"
   var55.Title = var1:getText("StudioModes", "ConstraintDetails")
   var55.Setting = game:GetService("StudioService")
   var55.Property = "ShowConstraintDetails"
   local var66 = var1.createElement(var2, var55)
   local var4 = var1.createElement("VisualizationModeCategory", var33, {})
   local var71 = {}
   var71.Name = "Rendering"
   var71.Title = var1:getText("VisualizationModeCategories", "Rendering")
   local var81 = {}
   var81.Name = "LightGuides"
   var81.Title = var1:getText("StudioModes", "LightGuides")
   var81.Setting = var0.Studio
   var81.Property = "Show Light Guides"
   local var89 = var1.createElement(var2, var81)
   local var7 = var1.createElement("VisualizationModeCategory", var71, {})
   local var94 = {}
   var94.Name = "Pathfinding"
   var94.Title = var1:getText("VisualizationModeCategories", "Pathfinding")
   local var104 = {}
   var104.Name = "PathfindingMesh"
   var104.Title = var1:getText("StudioModes", "PathfindingMesh")
   var104.Setting = var0.Studio
   var104.Property = "Show Navigation Mesh"
   local var112 = var1.createElement(var2, var104)
   local var116 = {}
   var116.Name = "PathfindingLabels"
   var116.Title = var1:getText("StudioModes", "PathfindingLabels")
   var116.Setting = var0.Studio
   var116.Property = "Show Navigation Mesh"
   local var124 = var1.createElement(var2, var116)
   local var128 = {}
   var128.Name = "PathfindingLinks"
   var128.Title = var1:getText("StudioModes", "PathfindingLinks")
   var128.Setting = var0.Studio
   var128.Property = "Show Pathfinding Links"
   local var136 = var1.createElement(var2, var128)
   local var13 = var1.createElement("VisualizationModeCategory", var94, {})
   local var141 = {}
   var141.Name = "PhysicsDebug"
   var141.Title = var1:getText("VisualizationModeCategories", "PhysicsDebug")
   local var151 = {}
   var151.Name = "NetworkOwner"
   var151.Title = var1:getText("StudioModes", "NetworkOwner")
   var151.Setting = var0.Physics
   var151.Property = "AreOwnersShown"
   local var15 = var1.createElement(var2, var151)
   local var163 = {}
   var163.Name = "Assemblies"
   var163.Title = var1:getText("StudioModes", "Assemblies")
   var163.Setting = var0.Physics
   var163.Property = "AreAssembliesShown"
   local var17 = var1.createElement(var2, var163)
   local var175 = {}
   var175.Name = "ContactPoints"
   var175.Title = var1:getText("StudioModes", "ContactPoints")
   var175.Setting = var0.Physics
   var175.Property = "AreContactPointsShown"
   local var19 = var1.createElement(var2, var175)
   local var187 = {}
   var187.Name = "AwakeParts"
   var187.Title = var1:getText("StudioModes", "AwakeParts")
   var187.Setting = var0.Physics
   var187.Property = "AreAwakePartsHighlighted"
   local var20 = var1.createElement(var2, var187)
   local var199 = {}
   var199.Name = "Mechanisms"
   var199.Title = var1:getText("StudioModes", "AreMechanismsShown")
   var199.Setting = var0.Physics
   var199.Property = "AreMechanismsShown"
   local var21 = var1.createElement(var2, var199)
   local var22 = var1.createElement("VisualizationModeCategory", var141, {})
   return var1.createElement(var1.Fragment, {}, {})
end
