-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("VisualizationModes")
local var1 = require(var0.Packages.React)
local var2 = require(var0.Src.Modes.SettingVisualizationMode)
local var3 = require(var0.Packages._Index.DeveloperFramework.DeveloperFramework.Types)
return function(arg1)
   local var0 = settings()
   local var1 = arg1.Localization
   local var69 = {}
   var69.Name = "Physics"
   var69.Title = var1:getText("VisualizationModeCategories", "Physics")
   local var79 = {}
   var79.Name = "DecompositionGeometry"
   var79.Title = var1:getText("StudioModes", "DecompositionGeometry")
   var79.Setting = var0.Physics
   var79.Property = "ShowDecompositionGeometry"
   local var87 = var1.createElement(var2, var79)
   local var91 = {}
   var91.Name = "ConstraintDetails"
   var91.Title = var1:getText("StudioModes", "ConstraintDetails")
   var91.Setting = game:GetService("StudioService")
   var91.Property = "ShowConstraintDetails"
   local var102 = var1.createElement(var2, var91)
   local var4 = var1.createElement("VisualizationModeCategory", var69, {})
   local var107 = {}
   var107.Name = "Rendering"
   var107.Title = var1:getText("VisualizationModeCategories", "Rendering")
   local var117 = {}
   var117.Name = "LightGuides"
   var117.Title = var1:getText("StudioModes", "LightGuides")
   var117.Setting = var0.Studio
   var117.Property = "Show Light Guides"
   local var125 = var1.createElement(var2, var117)
   local var7 = var1.createElement("VisualizationModeCategory", var107, {})
   local var130 = {}
   var130.Name = "Pathfinding"
   var130.Title = var1:getText("VisualizationModeCategories", "Pathfinding")
   local var140 = {}
   var140.Name = "PathfindingMesh"
   var140.Title = var1:getText("StudioModes", "PathfindingMesh")
   var140.Setting = var0.Studio
   var140.Property = "Show Navigation Mesh"
   local var148 = var1.createElement(var2, var140)
   local var152 = {}
   var152.Name = "PathfindingLabels"
   var152.Title = var1:getText("StudioModes", "PathfindingLabels")
   var152.Setting = var0.Studio
   var152.Property = "Show Navigation Mesh"
   local var160 = var1.createElement(var2, var152)
   local var164 = {}
   var164.Name = "PathfindingLinks"
   var164.Title = var1:getText("StudioModes", "PathfindingLinks")
   var164.Setting = var0.Studio
   var164.Property = "Show Pathfinding Links"
   local var172 = var1.createElement(var2, var164)
   local var13 = var1.createElement("VisualizationModeCategory", var130, {})
   local var177 = {}
   var177.Name = "PhysicsDebug"
   var177.Title = var1:getText("VisualizationModeCategories", "PhysicsDebug")
   local var187 = {}
   var187.Name = "NetworkOwner"
   var187.Title = var1:getText("StudioModes", "NetworkOwner")
   var187.Setting = var0.Physics
   var187.Property = "AreOwnersShown"
   local var15 = var1.createElement(var2, var187)
   local var199 = {}
   var199.Name = "Assemblies"
   var199.Title = var1:getText("StudioModes", "Assemblies")
   var199.Setting = var0.Physics
   var199.Property = "AreAssembliesShown"
   local var17 = var1.createElement(var2, var199)
   local var211 = {}
   var211.Name = "ContactPoints"
   var211.Title = var1:getText("StudioModes", "ContactPoints")
   var211.Setting = var0.Physics
   var211.Property = "AreContactPointsShown"
   local var19 = var1.createElement(var2, var211)
   local var223 = {}
   var223.Name = "AwakeParts"
   var223.Title = var1:getText("StudioModes", "AwakeParts")
   var223.Setting = var0.Physics
   var223.Property = "AreAwakePartsHighlighted"
   local var20 = var1.createElement(var2, var223)
   local var235 = {}
   var235.Name = "Mechanisms"
   var235.Title = var1:getText("StudioModes", "AreMechanismsShown")
   var235.Setting = var0.Physics
   var235.Property = "AreMechanismsShown"
   local var21 = var1.createElement(var2, var235)
   local var22 = var1.createElement("VisualizationModeCategory", var177, {})
   return var1.createElement(var1.Fragment, {}, {})
end
