local FriendsLanding = script:FindFirstAncestor("FriendsLanding")
local dependencies = require(FriendsLanding.dependencies)
local EnumPresenceType = dependencies.RoduxPresence.Enums.PresenceType

return {
	["OnlineFriend"] = {
		["displayName"] = "OnlineFriend",
		["gameId"] = "Game-OoooOO-Id",
		["id"] = "37",
		["lastLocation"] = "LastLocation",
		["lastOnline"] = "LastOnline-OOOoOO",
		["placeId"] = 123,
		["rootPlaceId"] = 234,
		["thumbnail"] = "rbxthumb://type=Avatar&id=37&w=150&h=150",
		["universeId"] = 345,
		["userId"] = 456,
		["userPresenceType"] = EnumPresenceType.Online,
		["username"] = "username37",
	},
	["DeletedFriend"] = {
		["displayName"] = "DeletedFriend",
		["gameId"] = "Game-OoooOO-Id",
		["id"] = "37",
		["lastLocation"] = "LastLocation",
		["lastOnline"] = "LastOnline-OOOoOO",
		["placeId"] = 123,
		["rootPlaceId"] = 234,
		["thumbnail"] = "rbxthumb://type=Avatar&id=37&w=150&h=150",
		["universeId"] = 345,
		["userId"] = 456,
		["userPresenceType"] = EnumPresenceType.Offline,
		["username"] = "username37",
		["isDeleted"] = true,
	},
	["OfflineFriend"] = {
		["displayName"] = "OfflineFriend",
		["gameId"] = "Game-OoooOO-Id",
		["id"] = "37",
		["lastLocation"] = "LastLocation",
		["lastOnline"] = "LastOnline-OOOoOO",
		["placeId"] = 123,
		["rootPlaceId"] = 234,
		["thumbnail"] = "rbxthumb://type=Avatar&id=37&w=150&h=150",
		["universeId"] = 345,
		["userId"] = 456,
		["userPresenceType"] = EnumPresenceType.Offline,
		["username"] = "username37",
	},
	["InGameFriend"] = {
		["displayName"] = "InGameFriend",
		["gameId"] = "Game-OoooOO-Id",
		["id"] = "37",
		["lastLocation"] = "LastLocation",
		["lastOnline"] = "LastOnline-OOOoOO",
		["placeId"] = 123,
		["rootPlaceId"] = 234,
		["thumbnail"] = "rbxthumb://type=Avatar&id=37&w=150&h=150",
		["universeId"] = 345,
		["userId"] = 456,
		["userPresenceType"] = EnumPresenceType.InGame,
		["username"] = "username37",
	},
	["InStudioFriend"] = {
		["displayName"] = "InStudioFriend",
		["gameId"] = "Game-OoooOO-Id",
		["id"] = "37",
		["lastLocation"] = "LastLocation",
		["lastOnline"] = "LastOnline-OOOoOO",
		["placeId"] = 123,
		["rootPlaceId"] = 234,
		["thumbnail"] = "rbxthumb://type=Avatar&id=37&w=150&h=150",
		["universeId"] = 345,
		["userId"] = 456,
		["userPresenceType"] = EnumPresenceType.InStudio,
		["username"] = "username37",
	},
	["InGameWithoutLastLocationFriend"] = {
		["displayName"] = "InGameWithoutLastLocationFriend",
		["gameId"] = "Game-OoooOO-Id",
		["id"] = "37",
		["lastLocation"] = "",
		["lastOnline"] = "LastOnline-OOOoOO",
		["placeId"] = 123,
		["rootPlaceId"] = 234,
		["thumbnail"] = "rbxthumb://type=Avatar&id=37&w=150&h=150",
		["universeId"] = 345,
		["userId"] = 456,
		["userPresenceType"] = EnumPresenceType.InGame,
		["username"] = "username37",
	},
	["InStudioWithoutLastLocationFriend"] = {
		["displayName"] = "InStudioWithoutLastLocationFriend",
		["gameId"] = "Game-OoooOO-Id",
		["id"] = "37",
		["lastLocation"] = "",
		["lastOnline"] = "LastOnline-OOOoOO",
		["placeId"] = 123,
		["rootPlaceId"] = 234,
		["thumbnail"] = "rbxthumb://type=Avatar&id=37&w=150&h=150",
		["universeId"] = 345,
		["userId"] = 456,
		["userPresenceType"] = EnumPresenceType.InStudio,
		["username"] = "username37",
	},
}
