-- Auto-generated by service-contracts. DO NOT EDIT MANUALLY.

local proto = require(script.Parent.Parent.Parent.Parent.proto)
export type Descriptor = proto.Descriptor
export type Message<T, Fields> = proto.Package<T, Fields>
export type CustomJson<T, Json> = proto.CustomJson<T, Json>
export type TypeRegistry = proto.TypeRegistry

local spotlight_collection_page = require(script.spotlight_collection_page)

-- Exported types
export type SpotlightCollectionPageRequest = spotlight_collection_page.SpotlightCollectionPageRequest
export type SpotlightCollectionPageResponse = spotlight_collection_page.SpotlightCollectionPageResponse

return {
	spotlight_collection_page = spotlight_collection_page,
}
