--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["ReactIs-85154ff2-6c194edd"]["ReactIs"])

return Package
