[package]
name = "MomentsCommon"
version = "0.1.5"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!**/*test*",
    "!**/*Test*",
    "!**/TestUtils/**",
]
publish = true
authors = ["sharing <sharing@roblox.com>"]
description = "Moments common module"
repository = "https://github.com/Roblox/moments"
keywords = ["moments"]
[dependencies.BuilderIcons]
version = "^0.1.9"

[dependencies.Cryo]
version = "^1.1.0"

[dependencies.Dash]
version = "^0.1.0"

[dependencies.Foundation]
version = "^1.67.0"

[dependencies.Promise]
version = "^3.5.0"

[dependencies.React]
version = "^17.1.7"

[dependencies.ReactOtter]
version = "^1.2.1"

[dependencies.ReactUtils]
version = "^1.9.0"

[dependencies.Roact]
package = "RoactCompat"
version = "^17.1.17"

[dependencies.RoactRodux]
version = "^0.5.1"
[dev_dependencies.Jest]
version = "^3.12.0"

[dev_dependencies.JestGlobals]
version = "^3.12.0"

[dev_dependencies.MomentsTestUtils]
package = "MomentsTestUtils"
version = "^0.1.0"

[dev_dependencies.ReactRoblox]
version = "^17.1.7"

[dev_dependencies.Rhodium]
version = "^0.5.0"
