-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("TerrainEditor")
local var1 = require(script.Arctic)
local var2 = require(script.Canyons)
local var3 = require(script.Dunes)
local var4 = require(script.Hills)
local var5 = require(script.Lavascape)
local var6 = require(script.Marsh)
local var7 = require(script.Mountains)
local var8 = require(script.Plains)
local var9 = require(script.Water)
local var10 = var0.Src.Util.Generation
local var11 = require(var10.NoisySeed)
local var12 = require(var10.Perlin)
local var13 = require(var0.Src.Types).Biomes
return function(arg1, arg2, arg3)
   var13.Arctic = var1(arg1, arg3)
   var13.Canyons = var2(arg1, arg2, arg3)
   var13.Dunes = var3(arg1, arg3)
   var13.Hills = var4(arg1, arg3)
   var13.Lavascape = var5(arg1, arg3)
   var13.Marsh = var6(arg1, arg3)
   var13.Mountains = var7(arg1, arg3)
   var13.Plains = var8(arg1, arg3)
   var13.Water = var9(arg1, arg3)
   return {}
end
