return function()
	local TrustAndSafety = script.Parent.Parent
	local OpenReportDialog = require(TrustAndSafety.Actions.OpenReportDialog)
	local CloseReportDialog = require(TrustAndSafety.Actions.CloseReportDialog)
	local OpenReportSentDialog = require(TrustAndSafety.Actions.OpenReportSentDialog)
	local CloseReportSentDialog = require(TrustAndSafety.Actions.CloseReportSentDialog)
	local OpenReportMenu = require(TrustAndSafety.Actions.OpenReportMenu)
	local CloseReportMenu = require(TrustAndSafety.Actions.CloseReportMenu)
	local Constants = require(TrustAndSafety.Resources.Constants)
	local report = require(script.Parent.report)

	describe("Initial state", function()
		it("should be closed by default", function()
			local defaultState = report(nil, {})
			expect(defaultState.isReportDialogOpen).to.equal(false)
			expect(defaultState.isReportSentOpen).to.equal(false)
			expect(defaultState.isReportMenuOpen).to.equal(false)
		end)
	end)

	describe("ReportDialog", function()
		local targetPlayer = {
			UserId = 123,
			Name = "testName",
			DisplayName = "testDisplay",
		}

		it("should open for a player", function()
			local oldState = report(nil, {})
			local newState = report(oldState, OpenReportDialog(Constants.ReportType.Player, targetPlayer))
			expect(oldState).to.never.equal(newState)
			expect(newState.isReportDialogOpen).to.equal(true)
			expect(newState.reportType).to.equal(Constants.ReportType.Player)
			expect(newState.targetPlayer).to.equal(targetPlayer)
		end)

		it("should open for a game", function()
			local oldState = report(nil, {})
			local newState = report(oldState, OpenReportDialog(Constants.ReportType.Game))
			expect(oldState).to.never.equal(newState)
			expect(newState.isReportDialogOpen).to.equal(true)
			expect(newState.reportType).to.equal(Constants.ReportType.Game)
		end)

		it("should clear targetPlayer for a game", function()
			local oldState = report(nil, {})
			oldState = report(oldState, OpenReportDialog(Constants.ReportType.Player, targetPlayer))
			oldState = report(oldState, CloseReportDialog())
			local newState = report(oldState, OpenReportDialog(Constants.ReportType.Game))
			expect(oldState).to.never.equal(newState)
			expect(newState.isReportDialogOpen).to.equal(true)
			expect(newState.reportType).to.equal(Constants.ReportType.Game)
			expect(newState.targetPlayer).to.equal(nil)
		end)

		it("should close", function()
			local oldState = report(nil, {})
			oldState = report(oldState, OpenReportDialog(Constants.ReportType.Game))
			local newState = report(oldState, CloseReportDialog())
			expect(oldState).to.never.equal(newState)
			expect(newState.isReportDialogOpen).to.equal(false)
		end)
	end)

	describe("ReportSentDialog", function()
		it("should open", function()
			local oldState = report(nil, {})
			local newState = report(oldState, OpenReportSentDialog(nil, nil))
			expect(oldState).to.never.equal(newState)
			expect(newState.isReportSentOpen).to.equal(true)
		end)

		it("should close", function()
			local oldState = report(nil, {})
			oldState = report(oldState, OpenReportSentDialog(nil, nil))
			
			local newState = report(oldState, CloseReportSentDialog())
			expect(oldState).to.never.equal(newState)
			expect(newState.isReportSentOpen).to.equal(false)
		end)
	end)

	describe("ReportMenu", function()
		it("should open", function()
			local oldState = report(nil, {})
			local newState = report(oldState, OpenReportMenu())
			expect(oldState).to.never.equal(newState)
			expect(newState.isReportMenuOpen).to.equal(true)
		end)

		it("should close", function()
			local oldState = report(nil, {})
			oldState = report(oldState, OpenReportMenu())
			
			local newState = report(oldState, CloseReportMenu())
			expect(oldState).to.never.equal(newState)
			expect(newState.isReportMenuOpen).to.equal(false)
		end)
	end)
end
