-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("TerrainEditor")
local var1 = require(var0.Packages.Framework)
local var2 = require(var0.Packages.ReactRoblox)
local var3 = require(var0.Packages.React)
local var4 = var1.ContextServices
local var5 = var4.Localization
local var6 = var4.Stylizer
local var7 = var1.UI
local var8 = var7.Pane
local var9 = var7.TextLabel
local var10 = game:GetService("CoreGui")
return function(arg1)
   local var0 = var5:use()
   local var1 = var6:use("Note")
   local var2 = arg1.Key
   local var37 = {}
   local var42 = {}
   local var46 = {}
   var46.AnchorPoint = Vector2.new(0.5, 0)
   var46.AutomaticSize = Enum.AutomaticSize.X
   var46.BackgroundColor = var1.Background
   var46.Layout = Enum.FillDirection.Horizontal
   var46.Spacing = var1.FramePadding
   var46.Padding = var1.FramePadding
   var46.Position = UDim2.new(0.5, 0, 0, var1.EdgePadding)
   var46.Size = UDim2.fromOffset(0, 25)
   local var66 = {}
   local var70 = {}
   var70.AutomaticSize = Enum.AutomaticSize.XY
   var70.BackgroundColor = var1.KeyBackground
   var70.Padding = var1.TextMargin
   var70.LayoutOrder = 1
   local var75 = {}
   local var79 = {}
   var79.CornerRadius = UDim.new(0, 4)
   var75.Corner = var3.createElement("UICorner", var79)
   local var88 = {}
   var88.Text = var0:getText("Note", `{var2}`)
   var75.Text = var3.createElement(var9, var88)
   var66.Key = var3.createElement(var8, var70, var75)
   local var102 = {}
   var102.AutomaticSize = Enum.AutomaticSize.XY
   var102.Padding = var1.TextMargin
   var102.LayoutOrder = 2
   local var106 = {}
   local var110 = {}
   var110.Text = var0:getText("Note", `{var2}`)
   var106.Text = var3.createElement(var9, var110)
   var66.Apply = var3.createElement(var8, var102, var106)
   var42.Frame = var3.createElement(var8, var46, var66)
   var37.Note = var3.createElement("ScreenGui", {}, var42)
   return var2.createPortal(var37, var10)
end
