--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["Timers"]["Timers"])

export type Timeout = Package.Timeout
export type Interval = Package.Interval


return Package
