--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["JestTestResult-edcba0e9-2.4.1"]["JestTestResult"])

export type AggregatedResult = Package.AggregatedResult
export type AssertionLocation = Package.AssertionLocation
export type AssertionResult = Package.AssertionResult
export type FailedAssertion = Package.FailedAssertion
export type FormattedTestResults = Package.FormattedTestResults
export type Milliseconds = Package.Milliseconds
export type RuntimeTransformResult = Package.RuntimeTransformResult
export type SerializableError = Package.SerializableError
export type Snapshot = Package.Snapshot
export type SnapshotSummary = Package.SnapshotSummary
export type Status = Package.Status
export type Suite = Package.Suite
export type Test = Package.Test
export type TestEvents = Package.TestEvents
export type TestFileEvent = Package.TestFileEvent
export type TestResult = Package.TestResult
export type TestResultsProcessor = Package.TestResultsProcessor
export type TestCaseResult = Package.TestCaseResult
export type V8CoverageResult = Package.V8CoverageResult


return Package
