-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("TerrainEditor")
local var1 = require(var0.Src.Types)
local var2 = var1.BuildSettings
local var3 = var1.Gizmo
local var20 = {}
local var23 = {}
var2.Offset = Vector2.new(0, 0)
var2.Seed = 0.123
var23.Children = {}
var2.AdvancedNoise = var23
var2.NoiseStrength = 0.4
var2.BlendingEdge = 0
var2.CliffSlope = 75
var2.NoiseScale = 0.4
local var41 = {}
var41.FallbackMaterial = Enum.Material.Sandstone
var41.Unit = var1.MaterialUnit.Percentage
var41.Min = 0
var41.Max = 1
var41.MaterialIndex = 1
local var48 = {}
var48.Material = Enum.Material.Sandstone
var48.MinHeight = 0
var48.MaxHeight = 1
var48.MinSlope = 0
var48.MaxSlope = 90
var48.Priority = 0
var41.MaterialList = {}
var2.Material = var41
var2.PlacementMode = true
var2.RimHeight = 0.4
var2.Size = Vector3.new(512, 128, 512)
var2.SnapToVoxels = true
var2.TopRadius = 0.5
var2.Transform = CFrame.new()
var20.Defaults = {}
var20.Id = var1.Category.BuildSettings
local var74 = {}
var74.Id = var3.Region
local var76 = {}
var76.Type = var3.Region
var76.Wireframe = false
var76.Rotation = false
var74.Schema = var76
local var7 = {}
var7.Id = var3.Placement
local var82 = {}
var82.Type = var3.Placement
var7.Schema = var82
return require(var0.Src.Tools.BaseTool):new(var1.TerrainType.Mesa, var1.Tab.None, {}, {})
