-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent.Parent
local var1 = require(var0.Src.Types)
local var2 = require(var0.Src.Flags)
local var3 = var2.getFFlagMSPhase02
local var4 = var2.getFFlagMSPhase02FixCategory
local var5 = {}
local var18 = "Materials"
local var19 = "Metal"
Enum.Material.Aluminum = {}
local var22 = "Materials"
local var23 = "Concrete"
Enum.Material.Asphalt = {}
local var26 = "Materials"
local var27 = "Rock"
Enum.Material.Basalt = {}
local var30 = "Materials"
local var31 = "Stone"
Enum.Material.Brick = {}
local var34 = "Materials"
local var35 = "Stone"
Enum.Material.Cobblestone = {}
local var38 = "Materials"
local var39 = "Concrete"
Enum.Material.Concrete = {}
local var42 = "Materials"
local var43 = "Metal"
Enum.Material.CorrodedMetal = {}
local var46 = "Materials"
local var47 = "Rock"
Enum.Material.CrackedLava = {}
local var50 = "Materials"
local var51 = "Metal"
Enum.Material.DiamondPlate = {}
local var54 = "Materials"
local var55 = "Fabric"
Enum.Material.Fabric = {}
local var58 = "Materials"
local var59 = "Special"
Enum.Material.ForceField = {}
local var62 = "Materials"
local var63 = "Organic"
Enum.Material.Glacier = {}
local var66 = "Materials"
local var67 = "Translucent"
Enum.Material.Glass = {}
local var70 = "Materials"
local var71 = "Rock"
Enum.Material.Granite = {}
local var74 = "Materials"
local var75 = "Ground"
Enum.Material.Grass = {}
local var78 = "Materials"
local var79 = "Ground"
Enum.Material.Ground = {}
local var82 = "Materials"
local var83 = "Organic"
Enum.Material.Ice = {}
local var86 = "Materials"
local var87 = "Ground"
Enum.Material.LeafyGrass = {}
local var90 = "Materials"
local var91 = "Rock"
Enum.Material.Limestone = {}
local var94 = "Materials"
local var95 = "Special"
Enum.Material.Neon = {}
local var98 = "Materials"
local var99 = "Rock"
Enum.Material.Marble = {}
local var102 = "Materials"
local var103 = "Metal"
Enum.Material.Metal = {}
local var106 = "Materials"
local var107 = "Ground"
Enum.Material.Mud = {}
local var110 = "Materials"
local var111 = "Concrete"
Enum.Material.Pavement = {}
local var114 = "Materials"
local var115 = "Rock"
Enum.Material.Pebble = {}
local var118 = "Materials"
local var119 = "Plastic"
Enum.Material.Plastic = {}
local var122 = "Materials"
local var123 = "Rock"
Enum.Material.Rock = {}
local var126 = "Materials"
local var127 = "Organic"
Enum.Material.Salt = {}
local var130 = "Materials"
local var131 = "Ground"
Enum.Material.Sand = {}
local var134 = "Materials"
local var135 = "Rock"
Enum.Material.Sandstone = {}
local var138 = "Materials"
local var139 = "Rock"
Enum.Material.Slate = {}
local var142 = "Materials"
local var143 = "Plastic"
Enum.Material.SmoothPlastic = {}
local var146 = "Materials"
local var147 = "Ground"
Enum.Material.Snow = {}
local var150 = "Materials"
local var151 = "Wood"
Enum.Material.Wood = {}
local var154 = "Materials"
local var155 = "Wood"
Enum.Material.WoodPlanks = {}
local var76 = {}
local var159 = "Materials"
local var160 = "Metal"
Enum.Material.Aluminum = {}
local var163 = "Materials"
local var164 = "Concrete"
Enum.Material.Asphalt = {}
local var167 = "Materials"
local var168 = "Rock"
Enum.Material.Basalt = {}
local var171 = "Materials"
local var172 = "Stone"
Enum.Material.Brick = {}
local var175 = "Materials"
local var176 = "Paper"
Enum.Material.Cardboard = {}
local var179 = "Materials"
local var180 = "Fabric"
Enum.Material.Carpet = {}
local var183 = "Materials"
local var184 = "Ceramic"
Enum.Material.CeramicTiles = {}
local var187 = "Materials"
local var188 = "Ceramic"
Enum.Material.ClayRoofTiles = {}
local var191 = "Materials"
local var192 = "Stone"
Enum.Material.Cobblestone = {}
local var195 = "Materials"
local var196 = "Concrete"
Enum.Material.Concrete = {}
local var199 = "Materials"
local var200 = "Metal"
Enum.Material.CorrodedMetal = {}
local var203 = "Materials"
local var204 = "Rock"
Enum.Material.CrackedLava = {}
local var207 = "Materials"
local var208 = "Metal"
Enum.Material.DiamondPlate = {}
local var211 = "Materials"
local var212 = "Fabric"
Enum.Material.Fabric = {}
local var215 = "Materials"
local var216 = "Special"
Enum.Material.ForceField = {}
local var219 = "Materials"
local var220 = "Organic"
Enum.Material.Glacier = {}
local var223 = "Materials"
local var224 = "Translucent"
Enum.Material.Glass = {}
local var227 = "Materials"
local var228 = "Rock"
Enum.Material.Granite = {}
local var231 = "Materials"
local var232 = "Ground"
Enum.Material.Grass = {}
local var235 = "Materials"
local var236 = "Ground"
Enum.Material.Ground = {}
local var239 = "Materials"
local var240 = "Organic"
Enum.Material.Ice = {}
local var243 = "Materials"
local var244 = "Ground"
Enum.Material.LeafyGrass = {}
local var247 = "Materials"
local var248 = "Leather"
Enum.Material.Leather = {}
local var251 = "Materials"
local var252 = "Rock"
Enum.Material.Limestone = {}
local var255 = "Materials"
local var256 = "Special"
Enum.Material.Neon = {}
local var259 = "Materials"
local var260 = "Rock"
Enum.Material.Marble = {}
local var263 = "Materials"
local var264 = "Metal"
Enum.Material.Metal = {}
local var267 = "Materials"
local var268 = "Ground"
Enum.Material.Mud = {}
local var271 = "Materials"
local var272 = "Concrete"
Enum.Material.Pavement = {}
local var275 = "Materials"
local var276 = "Rock"
Enum.Material.Pebble = {}
local var279 = "Materials"
local var280 = "Ceramic"
Enum.Material.Plaster = {}
local var283 = "Materials"
local var284 = "Plastic"
Enum.Material.Plastic = {}
local var287 = "Materials"
local var288 = "Rock"
Enum.Material.Rock = {}
local var291 = "Materials"
local var292 = "Synthetic"
Enum.Material.RoofShingles = {}
local var295 = "Materials"
local var296 = "Synthetic"
Enum.Material.Rubber = {}
local var299 = "Materials"
local var300 = "Organic"
Enum.Material.Salt = {}
local var303 = "Materials"
local var304 = "Ground"
Enum.Material.Sand = {}
local var307 = "Materials"
local var308 = "Rock"
Enum.Material.Sandstone = {}
local var311 = "Materials"
local var312 = "Rock"
Enum.Material.Slate = {}
local var315 = "Materials"
local var316 = "Plastic"
Enum.Material.SmoothPlastic = {}
local var319 = "Materials"
local var320 = "Ground"
Enum.Material.Snow = {}
local var323 = "Materials"
local var324 = "Wood"
Enum.Material.Wood = {}
local var327 = "Materials"
local var328 = "Wood"
Enum.Material.WoodPlanks = {}
local var163 = {}
local var332 = "Materials"
local var333 = "Metal"
Enum.Material.Aluminum = {}
local var336 = "Materials"
local var337 = "Concrete"
Enum.Material.Asphalt = {}
local var340 = "Materials"
local var341 = "Rock"
Enum.Material.Basalt = {}
local var344 = "Materials"
local var345 = "Stone"
Enum.Material.Brick = {}
local var348 = "Materials"
local var349 = "Paper"
Enum.Material.Cardboard = {}
local var352 = "Materials"
local var353 = "Fabric"
Enum.Material.Carpet = {}
local var356 = "Materials"
local var357 = "Ceramic"
Enum.Material.CeramicTiles = {}
local var360 = "Materials"
local var361 = "Ceramic"
Enum.Material.ClayRoofTiles = {}
local var364 = "Materials"
local var365 = "Stone"
Enum.Material.Cobblestone = {}
local var368 = "Materials"
local var369 = "Concrete"
Enum.Material.Concrete = {}
local var372 = "Materials"
local var373 = "Metal"
Enum.Material.CorrodedMetal = {}
local var376 = "Materials"
local var377 = "Rock"
Enum.Material.CrackedLava = {}
local var380 = "Materials"
local var381 = "Metal"
Enum.Material.DiamondPlate = {}
local var384 = "Materials"
local var385 = "Fabric"
Enum.Material.Fabric = {}
local var388 = "Materials"
local var389 = "Special"
Enum.Material.ForceField = {}
local var392 = "Materials"
local var393 = "Organic"
Enum.Material.Glacier = {}
local var396 = "Materials"
local var397 = "Translucent"
Enum.Material.Glass = {}
local var400 = "Materials"
local var401 = "Rock"
Enum.Material.Granite = {}
local var404 = "Materials"
local var405 = "Ground"
Enum.Material.Grass = {}
local var408 = "Materials"
local var409 = "Ground"
Enum.Material.Ground = {}
local var412 = "Materials"
local var413 = "Organic"
Enum.Material.Ice = {}
local var416 = "Materials"
local var417 = "Ground"
Enum.Material.LeafyGrass = {}
local var420 = "Materials"
local var421 = "Fabric"
Enum.Material.Leather = {}
local var424 = "Materials"
local var425 = "Rock"
Enum.Material.Limestone = {}
local var428 = "Materials"
local var429 = "Special"
Enum.Material.Neon = {}
local var432 = "Materials"
local var433 = "Rock"
Enum.Material.Marble = {}
local var436 = "Materials"
local var437 = "Metal"
Enum.Material.Metal = {}
local var440 = "Materials"
local var441 = "Ground"
Enum.Material.Mud = {}
local var444 = "Materials"
local var445 = "Concrete"
Enum.Material.Pavement = {}
local var448 = "Materials"
local var449 = "Rock"
Enum.Material.Pebble = {}
local var452 = "Materials"
local var453 = "Ceramic"
Enum.Material.Plaster = {}
local var456 = "Materials"
local var457 = "Plastic"
Enum.Material.Plastic = {}
local var460 = "Materials"
local var461 = "Rock"
Enum.Material.Rock = {}
local var464 = "Materials"
local var465 = "Synthetic"
Enum.Material.RoofShingles = {}
local var468 = "Materials"
local var469 = "Synthetic"
Enum.Material.Rubber = {}
local var472 = "Materials"
local var473 = "Organic"
Enum.Material.Salt = {}
local var476 = "Materials"
local var477 = "Ground"
Enum.Material.Sand = {}
local var480 = "Materials"
local var481 = "Rock"
Enum.Material.Sandstone = {}
local var484 = "Materials"
local var485 = "Rock"
Enum.Material.Slate = {}
local var488 = "Materials"
local var489 = "Plastic"
Enum.Material.SmoothPlastic = {}
local var492 = "Materials"
local var493 = "Ground"
Enum.Material.Snow = {}
local var496 = "Materials"
local var497 = "Wood"
Enum.Material.Wood = {}
local var248 = "Materials"
local var249 = "Wood"
Enum.Material.WoodPlanks = {}
return function(arg1)
   if var3() then
      if var4() then
         return var163[arg1]
      end
      return var76[arg1]
   end
   return var5[arg1]
end
