return {
	NORMAL_ICON_SIZE = 85,
	CONDENSED_ICON_SIZE = 65,
	-- 120 is the height of the components of the modal not including the customized content
	MODAL_HEIGHT_WITHOUT_CONTENT = 120,
	MODAL_NORMAL_SECTION_PADDING = 24,
	MODAL_NORMAL_CONTENT_PADDING = 15,
	MODAL_CONDENSED_CONTENT_PADDING = 8,
	MODAL_NORMAL_BUTTON_MARGIN = 12,
	MODAL_CONDENSED_BUTTON_MARGIN = 8,
	MODAL_NORMAL_BUTTON_HEIGHT = 36,
	CENTRAL_OVERLAY_TYPE_ANIMATOR = "IapExperienceAnimator",
	CLOSE_MODAL_ACTION = "IapCloseModal"
}
