local ImageSet = script.Parent
local IconSizeEnum = require(ImageSet.Enum.IconSize)

return function()
	local getIconSize = require(script.Parent.getIconSize)
	describe("getIconSize()", function()
		it("should return the number 16", function()
			local iconSize = getIconSize(IconSizeEnum.Small)
			expect(iconSize).to.equal(16)
		end)
		it("should return the number 36", function()
			local iconSize = getIconSize(IconSizeEnum.Medium)
			expect(iconSize).to.equal(36)
		end)
		it("should return the number 48", function()
			local iconSize = getIconSize(IconSizeEnum.Large)
			expect(iconSize).to.equal(48)
		end)
		it("should return the number 96", function()
			local iconSize = getIconSize(IconSizeEnum.XLarge)
			expect(iconSize).to.equal(96)
		end)
		it("should return the number 192", function()
			local iconSize = getIconSize(IconSizeEnum.XXLarge)
			expect(iconSize).to.equal(192)
		end)
		it("should error", function()
			expect(function()
				return getIconSize("ASD")
			end).to.throw()
		end)
	end)
end
