local Modules = game:GetService("CoreGui"):FindFirstChild("RobloxGui").Modules
local Flags = require(Modules.LuaApp.Legacy.AvatarEditor.Flags)

local SIMULATE_RESOLUTION_SCALE = nil

local sheetIds = {
	[1] = 'rbxasset://textures/AvatarEditorImages/Sheet.png'
}

local sprites = {
	["bar-empty-head"] = {
		name = "bar-empty-head",
		filename = "1x/bar-empty-head.png",
		imageRectSize = Vector2.new(3, 6),
		imageRectOffset = Vector2.new(18, 1),
		imageId = sheetIds[1],
	},
	["bar-empty-mid"] = {
		name = "bar-empty-mid",
		filename = "1x/bar-empty-mid.png",
		imageRectSize = Vector2.new(1, 6),
		imageRectOffset = Vector2.new(15, 1),
		imageId = sheetIds[1],
	},
	["bar-empty-tail"] = {
		name = "bar-empty-tail",
		filename = "1x/bar-empty-tail.png",
		imageRectSize = Vector2.new(3, 6),
		imageRectOffset = Vector2.new(1, 1),
		imageId = sheetIds[1],
	},
	["bar-full-head"] = {
		name = "bar-full-head",
		filename = "1x/bar-full-head.png",
		imageRectSize = Vector2.new(7, 14),
		imageRectOffset = Vector2.new(100, 1),
		imageId = sheetIds[1],
	},
	["bar-full-mid"] = {
		name = "bar-full-mid",
		filename = "1x/bar-full-mid.png",
		imageRectSize = Vector2.new(1, 14),
		imageRectOffset = Vector2.new(97, 1),
		imageId = sheetIds[1],
	},
	["bar-full-tail"] = {
		name = "bar-full-tail",
		filename = "1x/bar-full-tail.png",
		imageRectSize = Vector2.new(7, 14),
		imageRectOffset = Vector2.new(109, 1),
		imageId = sheetIds[1],
	},
	["btn-expand"] = {
		name = "btn-expand",
		filename = "1x/btn-expand.png",
		imageRectSize = Vector2.new(60, 24),
		imageRectOffset = Vector2.new(403, 1),
		imageId = sheetIds[1],
	},
	["dragger-highlight"] = {
		name = "dragger-highlight",
		filename = "1x/dragger-highlight.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(627, 69),
		imageId = sheetIds[1],
	},
	["dragger"] = {
		name = "dragger",
		filename = "1x/dragger.png",
		imageRectSize = Vector2.new(32, 32),
		imageRectOffset = Vector2.new(1968, 31),
		imageId = sheetIds[1],
	},
	["gr-box-shadow"] = {
		name = "gr-box-shadow",
		filename = "1x/gr-box-shadow.png",
		imageRectSize = Vector2.new(12, 12),
		imageRectOffset = Vector2.new(32, 1),
		imageId = sheetIds[1],
	},
	["gr-card corner"] = {
		name = "gr-card corner",
		filename = "1x/gr-card corner.png",
		imageRectSize = Vector2.new(13, 13),
		imageRectOffset = Vector2.new(82, 1),
		imageId = sheetIds[1],
	},
	["gr-category-selector"] = {
		name = "gr-category-selector",
		filename = "1x/gr-category-selector.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(913, 69),
		imageId = sheetIds[1],
	},
	["gr-circle-shadow"] = {
		name = "gr-circle-shadow",
		filename = "1x/gr-circle-shadow.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1351, 185),
		imageId = sheetIds[1],
	},
	["gr-circle-white"] = {
		name = "gr-circle-white",
		filename = "1x/gr-circle-white.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(477, 69),
		imageId = sheetIds[1],
	},
	["gr-corner"] = {
		name = "gr-corner",
		filename = "1x/gr-corner.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1467, 185),
		imageId = sheetIds[1],
	},
	["gr-half-circle"] = {
		name = "gr-half-circle",
		filename = "1x/gr-half-circle.png",
		imageRectSize = Vector2.new(34, 70),
		imageRectOffset = Vector2.new(1954, 243),
		imageId = sheetIds[1],
	},
	["gr-orange-circle"] = {
		name = "gr-orange-circle",
		filename = "1x/gr-orange-circle.png",
		imageRectSize = Vector2.new(52, 52),
		imageRectOffset = Vector2.new(1015, 69),
		imageId = sheetIds[1],
	},
	["gr-ring-selector"] = {
		name = "gr-ring-selector",
		filename = "1x/gr-ring-selector.png",
		imageRectSize = Vector2.new(54, 54),
		imageRectOffset = Vector2.new(1069, 69),
		imageId = sheetIds[1],
	},
	["gr-ring01"] = {
		name = "gr-ring01",
		filename = "1x/gr-ring01.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(527, 69),
		imageId = sheetIds[1],
	},
	["gr-tail"] = {
		name = "gr-tail",
		filename = "1x/gr-tail.png",
		imageRectSize = Vector2.new(1, 70),
		imageRectOffset = Vector2.new(1951, 243),
		imageId = sheetIds[1],
	},
	["gra-toggle-button"] = {
		name = "gra-toggle-button",
		filename = "1x/gra-toggle-button.png",
		imageRectSize = Vector2.new(30, 24),
		imageRectOffset = Vector2.new(344, 1),
		imageId = sheetIds[1],
	},
	["gra-toggle-frame"] = {
		name = "gra-toggle-frame",
		filename = "1x/gra-toggle-frame.png",
		imageRectSize = Vector2.new(64, 28),
		imageRectOffset = Vector2.new(571, 31),
		imageId = sheetIds[1],
	},
	["ic-avatar-animation-on"] = {
		name = "ic-avatar-animation-on",
		filename = "1x/ic-avatar-animation-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(728, 31),
		imageId = sheetIds[1],
	},
	["ic-avatar-animation"] = {
		name = "ic-avatar-animation",
		filename = "1x/ic-avatar-animation.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(818, 31),
		imageId = sheetIds[1],
	},
	["ic-back-white"] = {
		name = "ic-back-white",
		filename = "1x/ic-back-white.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(878, 31),
		imageId = sheetIds[1],
	},
	["ic-body-part-on"] = {
		name = "ic-body-part-on",
		filename = "1x/ic-body-part-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(848, 31),
		imageId = sheetIds[1],
	},
	["ic-body-part"] = {
		name = "ic-body-part",
		filename = "1x/ic-body-part.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(788, 31),
		imageId = sheetIds[1],
	},
	["ic-bundle-on"] = {
		name = "ic-bundle-on",
		filename = "1x/ic-bundle-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(758, 31),
		imageId = sheetIds[1],
	},
	["ic-bundle"] = {
		name = "ic-bundle",
		filename = "1x/ic-bundle.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(541, 31),
		imageId = sheetIds[1],
	},
	["ic-color-on"] = {
		name = "ic-color-on",
		filename = "1x/ic-color-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(211, 31),
		imageId = sheetIds[1],
	},
	["ic-color"] = {
		name = "ic-color",
		filename = "1x/ic-color.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(301, 31),
		imageId = sheetIds[1],
	},
	["ic-left-arm-on"] = {
		name = "ic-left-arm-on",
		filename = "1x/ic-left-arm-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(998, 31),
		imageId = sheetIds[1],
	},
	["ic-left-arm"] = {
		name = "ic-left-arm",
		filename = "1x/ic-left-arm.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1238, 31),
		imageId = sheetIds[1],
	},
	["ic-left-leg-on"] = {
		name = "ic-left-leg-on",
		filename = "1x/ic-left-leg-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1268, 31),
		imageId = sheetIds[1],
	},
	["ic-left-leg"] = {
		name = "ic-left-leg",
		filename = "1x/ic-left-leg.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1448, 31),
		imageId = sheetIds[1],
	},
	["ic-right-arm-on"] = {
		name = "ic-right-arm-on",
		filename = "1x/ic-right-arm-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1328, 31),
		imageId = sheetIds[1],
	},
	["ic-right-arm"] = {
		name = "ic-right-arm",
		filename = "1x/ic-right-arm.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(968, 31),
		imageId = sheetIds[1],
	},
	["ic-right-leg-on"] = {
		name = "ic-right-leg-on",
		filename = "1x/ic-right-leg-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1791, 1),
		imageId = sheetIds[1],
	},
	["ic-right-leg"] = {
		name = "ic-right-leg",
		filename = "1x/ic-right-leg.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1183, 1),
		imageId = sheetIds[1],
	},
	["ic-scaling-on"] = {
		name = "ic-scaling-on",
		filename = "1x/ic-scaling-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(943, 1),
		imageId = sheetIds[1],
	},
	["ic-scaling"] = {
		name = "ic-scaling",
		filename = "1x/ic-scaling.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(853, 1),
		imageId = sheetIds[1],
	},
	["ic-shirt-on"] = {
		name = "ic-shirt-on",
		filename = "1x/ic-shirt-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(793, 1),
		imageId = sheetIds[1],
	},
	["ic-shirt"] = {
		name = "ic-shirt",
		filename = "1x/ic-shirt.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(763, 1),
		imageId = sheetIds[1],
	},
	["ic-shoulder-on"] = {
		name = "ic-shoulder-on",
		filename = "1x/ic-shoulder-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(973, 1),
		imageId = sheetIds[1],
	},
	["ic-shoulder"] = {
		name = "ic-shoulder",
		filename = "1x/ic-shoulder.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1063, 1),
		imageId = sheetIds[1],
	},
	["ic-tshirt-on"] = {
		name = "ic-tshirt-on",
		filename = "1x/ic-tshirt-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1033, 1),
		imageId = sheetIds[1],
	},
	["ic-tshirt"] = {
		name = "ic-tshirt",
		filename = "1x/ic-tshirt.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1003, 1),
		imageId = sheetIds[1],
	},
	["ic-up-black"] = {
		name = "ic-up-black",
		filename = "1x/ic-up-black.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(523, 1),
		imageId = sheetIds[1],
	},
	["img-selector-box"] = {
		name = "img-selector-box",
		filename = "1x/img-selector-box.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1409, 185),
		imageId = sheetIds[1],
	},
	["bar-empty-head@2x"] = {
		name = "bar-empty-head@2x",
		filename = "2x/bar-empty-head@2x.png",
		imageRectSize = Vector2.new(6, 12),
		imageRectOffset = Vector2.new(46, 1),
		imageId = sheetIds[1],
	},
	["bar-empty-mid@2x"] = {
		name = "bar-empty-mid@2x",
		filename = "2x/bar-empty-mid@2x.png",
		imageRectSize = Vector2.new(2, 12),
		imageRectOffset = Vector2.new(78, 1),
		imageId = sheetIds[1],
	},
	["bar-empty-tail@2x"] = {
		name = "bar-empty-tail@2x",
		filename = "2x/bar-empty-tail@2x.png",
		imageRectSize = Vector2.new(6, 12),
		imageRectOffset = Vector2.new(54, 1),
		imageId = sheetIds[1],
	},
	["bar-full-head@2x"] = {
		name = "bar-full-head@2x",
		filename = "2x/bar-full-head@2x.png",
		imageRectSize = Vector2.new(14, 28),
		imageRectOffset = Vector2.new(1273, 1),
		imageId = sheetIds[1],
	},
	["bar-full-mid@2x"] = {
		name = "bar-full-mid@2x",
		filename = "2x/bar-full-mid@2x.png",
		imageRectSize = Vector2.new(2, 28),
		imageRectOffset = Vector2.new(1757, 1),
		imageId = sheetIds[1],
	},
	["bar-full-tail@2x"] = {
		name = "bar-full-tail@2x",
		filename = "2x/bar-full-tail@2x.png",
		imageRectSize = Vector2.new(14, 28),
		imageRectOffset = Vector2.new(1741, 1),
		imageId = sheetIds[1],
	},
	["btn-expand@2x"] = {
		name = "btn-expand@2x",
		filename = "2x/btn-expand@2x.png",
		imageRectSize = Vector2.new(120, 48),
		imageRectOffset = Vector2.new(677, 69),
		imageId = sheetIds[1],
	},
	["dragger-highlight@2x"] = {
		name = "dragger-highlight@2x",
		filename = "2x/dragger-highlight@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(799, 573),
		imageId = sheetIds[1],
	},
	["dragger@2x"] = {
		name = "dragger@2x",
		filename = "2x/dragger@2x.png",
		imageRectSize = Vector2.new(64, 64),
		imageRectOffset = Vector2.new(1885, 243),
		imageId = sheetIds[1],
	},
	["gr-box-shadow@2x"] = {
		name = "gr-box-shadow@2x",
		filename = "2x/gr-box-shadow@2x.png",
		imageRectSize = Vector2.new(24, 24),
		imageRectOffset = Vector2.new(318, 1),
		imageId = sheetIds[1],
	},
	["gr-card corner@2x"] = {
		name = "gr-card corner@2x",
		filename = "2x/gr-card corner@2x.png",
		imageRectSize = Vector2.new(26, 26),
		imageRectOffset = Vector2.new(465, 1),
		imageId = sheetIds[1],
	},
	["gr-category-selector@2x"] = {
		name = "gr-category-selector@2x",
		filename = "2x/gr-category-selector@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(603, 573),
		imageId = sheetIds[1],
	},
	["gr-circle-shadow@2x"] = {
		name = "gr-circle-shadow@2x",
		filename = "2x/gr-circle-shadow@2x.png",
		imageRectSize = Vector2.new(112, 112),
		imageRectOffset = Vector2.new(1903, 573),
		imageId = sheetIds[1],
	},
	["gr-circle-white@2x"] = {
		name = "gr-circle-white@2x",
		filename = "2x/gr-circle-white@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(897, 573),
		imageId = sheetIds[1],
	},
	["gr-corner@2x"] = {
		name = "gr-corner@2x",
		filename = "2x/gr-corner@2x.png",
		imageRectSize = Vector2.new(112, 112),
		imageRectOffset = Vector2.new(1, 687),
		imageId = sheetIds[1],
	},
	["gr-half-circle@2x"] = {
		name = "gr-half-circle@2x",
		filename = "2x/gr-half-circle@2x.png",
		imageRectSize = Vector2.new(68, 140),
		imageRectOffset = Vector2.new(839, 687),
		imageId = sheetIds[1],
	},
	["gr-orange-circle@2x"] = {
		name = "gr-orange-circle@2x",
		filename = "2x/gr-orange-circle@2x.png",
		imageRectSize = Vector2.new(104, 104),
		imageRectOffset = Vector2.new(1687, 573),
		imageId = sheetIds[1],
	},
	["gr-ring-selector@2x"] = {
		name = "gr-ring-selector@2x",
		filename = "2x/gr-ring-selector@2x.png",
		imageRectSize = Vector2.new(108, 108),
		imageRectOffset = Vector2.new(1793, 573),
		imageId = sheetIds[1],
	},
	["gr-ring01@2x"] = {
		name = "gr-ring01@2x",
		filename = "2x/gr-ring01@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(701, 573),
		imageId = sheetIds[1],
	},
	["gr-tail@2x"] = {
		name = "gr-tail@2x",
		filename = "2x/gr-tail@2x.png",
		imageRectSize = Vector2.new(2, 140),
		imageRectOffset = Vector2.new(909, 687),
		imageId = sheetIds[1],
	},
	["gra-toggle-button@2x"] = {
		name = "gra-toggle-button@2x",
		filename = "2x/gra-toggle-button@2x.png",
		imageRectSize = Vector2.new(60, 48),
		imageRectOffset = Vector2.new(799, 69),
		imageId = sheetIds[1],
	},
	["gra-toggle-frame@2x"] = {
		name = "gra-toggle-frame@2x",
		filename = "2x/gra-toggle-frame@2x.png",
		imageRectSize = Vector2.new(128, 56),
		imageRectOffset = Vector2.new(1161, 185),
		imageId = sheetIds[1],
	},
	["ic-avatar-animation-on@2x"] = {
		name = "ic-avatar-animation-on@2x",
		filename = "2x/ic-avatar-animation-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1045, 185),
		imageId = sheetIds[1],
	},
	["ic-avatar-animation@2x"] = {
		name = "ic-avatar-animation@2x",
		filename = "2x/ic-avatar-animation@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1525, 185),
		imageId = sheetIds[1],
	},
	["ic-back-white@2x"] = {
		name = "ic-back-white@2x",
		filename = "2x/ic-back-white@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1873, 185),
		imageId = sheetIds[1],
	},
	["ic-body-part-on@2x"] = {
		name = "ic-body-part-on@2x",
		filename = "2x/ic-body-part-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(59, 243),
		imageId = sheetIds[1],
	},
	["ic-body-part@2x"] = {
		name = "ic-body-part@2x",
		filename = "2x/ic-body-part@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1, 243),
		imageId = sheetIds[1],
	},
	["ic-bundle-on@2x"] = {
		name = "ic-bundle-on@2x",
		filename = "2x/ic-bundle-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1931, 185),
		imageId = sheetIds[1],
	},
	["ic-bundle@2x"] = {
		name = "ic-bundle@2x",
		filename = "2x/ic-bundle@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1815, 185),
		imageId = sheetIds[1],
	},
	["ic-color-on@2x"] = {
		name = "ic-color-on@2x",
		filename = "2x/ic-color-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(175, 185),
		imageId = sheetIds[1],
	},
	["ic-color@2x"] = {
		name = "ic-color@2x",
		filename = "2x/ic-color@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(117, 185),
		imageId = sheetIds[1],
	},
	["ic-left-arm-on@2x"] = {
		name = "ic-left-arm-on@2x",
		filename = "2x/ic-left-arm-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(233, 243),
		imageId = sheetIds[1],
	},
	["ic-left-arm@2x"] = {
		name = "ic-left-arm@2x",
		filename = "2x/ic-left-arm@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(581, 243),
		imageId = sheetIds[1],
	},
	["ic-left-leg-on@2x"] = {
		name = "ic-left-leg-on@2x",
		filename = "2x/ic-left-leg-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1161, 243),
		imageId = sheetIds[1],
	},
	["ic-left-leg@2x"] = {
		name = "ic-left-leg@2x",
		filename = "2x/ic-left-leg@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(755, 243),
		imageId = sheetIds[1],
	},
	["ic-right-arm-on@2x"] = {
		name = "ic-right-arm-on@2x",
		filename = "2x/ic-right-arm-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(291, 243),
		imageId = sheetIds[1],
	},
	["ic-right-arm@2x"] = {
		name = "ic-right-arm@2x",
		filename = "2x/ic-right-arm@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(465, 243),
		imageId = sheetIds[1],
	},
	["ic-right-leg-on@2x"] = {
		name = "ic-right-leg-on@2x",
		filename = "2x/ic-right-leg-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(349, 243),
		imageId = sheetIds[1],
	},
	["ic-right-leg@2x"] = {
		name = "ic-right-leg@2x",
		filename = "2x/ic-right-leg@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(407, 243),
		imageId = sheetIds[1],
	},
	["ic-scaling-on@2x"] = {
		name = "ic-scaling-on@2x",
		filename = "2x/ic-scaling-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1683, 127),
		imageId = sheetIds[1],
	},
	["ic-scaling@2x"] = {
		name = "ic-scaling@2x",
		filename = "2x/ic-scaling@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1219, 243),
		imageId = sheetIds[1],
	},
	["ic-shirt-on@2x"] = {
		name = "ic-shirt-on@2x",
		filename = "2x/ic-shirt-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1045, 243),
		imageId = sheetIds[1],
	},
	["ic-shirt@2x"] = {
		name = "ic-shirt@2x",
		filename = "2x/ic-shirt@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1393, 243),
		imageId = sheetIds[1],
	},
	["ic-shoulder-on@2x"] = {
		name = "ic-shoulder-on@2x",
		filename = "2x/ic-shoulder-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(117, 243),
		imageId = sheetIds[1],
	},
	["ic-shoulder@2x"] = {
		name = "ic-shoulder@2x",
		filename = "2x/ic-shoulder@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1589, 69),
		imageId = sheetIds[1],
	},
	["ic-tshirt-on@2x"] = {
		name = "ic-tshirt-on@2x",
		filename = "2x/ic-tshirt-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(117, 127),
		imageId = sheetIds[1],
	},
	["ic-tshirt@2x"] = {
		name = "ic-tshirt@2x",
		filename = "2x/ic-tshirt@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(233, 127),
		imageId = sheetIds[1],
	},
	["ic-up-black@2x"] = {
		name = "ic-up-black@2x",
		filename = "2x/ic-up-black@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(59, 127),
		imageId = sheetIds[1],
	},
	["img-selector-box@2x"] = {
		name = "img-selector-box@2x",
		filename = "2x/img-selector-box@2x.png",
		imageRectSize = Vector2.new(112, 112),
		imageRectOffset = Vector2.new(115, 687),
		imageId = sheetIds[1],
	},
	["bar-empty-head@3x"] = {
		name = "bar-empty-head@3x",
		filename = "3x/bar-empty-head@3x.png",
		imageRectSize = Vector2.new(9, 18),
		imageRectOffset = Vector2.new(284, 1),
		imageId = sheetIds[1],
	},
	["bar-empty-mid@3x"] = {
		name = "bar-empty-mid@3x",
		filename = "3x/bar-empty-mid@3x.png",
		imageRectSize = Vector2.new(3, 18),
		imageRectOffset = Vector2.new(279, 1),
		imageId = sheetIds[1],
	},
	["bar-empty-tail@3x"] = {
		name = "bar-empty-tail@3x",
		filename = "3x/bar-empty-tail@3x.png",
		imageRectSize = Vector2.new(9, 18),
		imageRectOffset = Vector2.new(245, 1),
		imageId = sheetIds[1],
	},
	["bar-full-head@3x"] = {
		name = "bar-full-head@3x",
		filename = "3x/bar-full-head@3x.png",
		imageRectSize = Vector2.new(21, 42),
		imageRectOffset = Vector2.new(29, 69),
		imageId = sheetIds[1],
	},
	["bar-full-mid@3x"] = {
		name = "bar-full-mid@3x",
		filename = "3x/bar-full-mid@3x.png",
		imageRectSize = Vector2.new(3, 42),
		imageRectOffset = Vector2.new(24, 69),
		imageId = sheetIds[1],
	},
	["bar-full-tail@3x"] = {
		name = "bar-full-tail@3x",
		filename = "3x/bar-full-tail@3x.png",
		imageRectSize = Vector2.new(21, 42),
		imageRectOffset = Vector2.new(1, 69),
		imageId = sheetIds[1],
	},
	["dragger-highlight@3x"] = {
		name = "dragger-highlight@3x",
		filename = "3x/dragger-highlight@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1497, 687),
		imageId = sheetIds[1],
	},
	["dragger@3x"] = {
		name = "dragger@3x",
		filename = "3x/dragger@3x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(1387, 573),
		imageId = sheetIds[1],
	},
	["gr-box-shadow@3x"] = {
		name = "gr-box-shadow@3x",
		filename = "3x/gr-box-shadow@3x.png",
		imageRectSize = Vector2.new(36, 36),
		imageRectOffset = Vector2.new(2002, 31),
		imageId = sheetIds[1],
	},
	["gr-circle-shadow@3x"] = {
		name = "gr-circle-shadow@3x",
		filename = "3x/gr-circle-shadow@3x.png",
		imageRectSize = Vector2.new(168, 168),
		imageRectOffset = Vector2.new(331, 839),
		imageId = sheetIds[1],
	},
	["gr-circle-white@3x"] = {
		name = "gr-circle-white@3x",
		filename = "3x/gr-circle-white@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1351, 687),
		imageId = sheetIds[1],
	},
	["gr-ring-selector@3x"] = {
		name = "gr-ring-selector@3x",
		filename = "3x/gr-ring-selector@3x.png",
		imageRectSize = Vector2.new(162, 162),
		imageRectOffset = Vector2.new(1, 839),
		imageId = sheetIds[1],
	},
	["ic-color-on@3x"] = {
		name = "ic-color-on@3x",
		filename = "3x/ic-color-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1, 487),
		imageId = sheetIds[1],
	},
	["ic-color@3x"] = {
		name = "ic-color@3x",
		filename = "3x/ic-color@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1463, 401),
		imageId = sheetIds[1],
	},
	["ctn-primary nav"] = {
		name = "ctn-primary nav",
		filename = "graphic/navigation/ctn-primary nav.png",
		imageRectSize = Vector2.new(98, 99),
		imageRectOffset = Vector2.new(1485, 573),
		imageId = sheetIds[1],
	},
	["ctn-primary nav@2x"] = {
		name = "ctn-primary nav@2x",
		filename = "graphic/navigation/ctn-primary nav@2x.png",
		imageRectSize = Vector2.new(196, 198),
		imageRectOffset = Vector2.new(1411, 839),
		imageId = sheetIds[1],
	},
	["ctn-primary nav@3x"] = {
		name = "ctn-primary nav@3x",
		filename = "graphic/navigation/ctn-primary nav@3x.png",
		imageRectSize = Vector2.new(294, 297),
		imageRectOffset = Vector2.new(249, 1057),
		imageId = sheetIds[1],
	},
	["ctn-secondary nav"] = {
		name = "ctn-secondary nav",
		filename = "graphic/navigation/ctn-secondary nav.png",
		imageRectSize = Vector2.new(92, 15),
		imageRectOffset = Vector2.new(151, 1),
		imageId = sheetIds[1],
	},
	["ctn-secondary nav@2x"] = {
		name = "ctn-secondary nav@2x",
		filename = "graphic/navigation/ctn-secondary nav@2x.png",
		imageRectSize = Vector2.new(184, 30),
		imageRectOffset = Vector2.new(1748, 31),
		imageId = sheetIds[1],
	},
	["ctn-secondary nav@3x"] = {
		name = "ctn-secondary nav@3x",
		filename = "graphic/navigation/ctn-secondary nav@3x.png",
		imageRectSize = Vector2.new(276, 45),
		imageRectOffset = Vector2.new(99, 69),
		imageId = sheetIds[1],
	},
	["ring1"] = {
		name = "ring1",
		filename = "graphic/ring/ring1.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1509, 243),
		imageId = sheetIds[1],
	},
	["ring1@2x"] = {
		name = "ring1@2x",
		filename = "graphic/ring/ring1@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(473, 687),
		imageId = sheetIds[1],
	},
	["ring1@3x"] = {
		name = "ring1@3x",
		filename = "graphic/ring/ring1@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(683, 839),
		imageId = sheetIds[1],
	},
	["ring2"] = {
		name = "ring2",
		filename = "graphic/ring/ring2.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1571, 243),
		imageId = sheetIds[1],
	},
	["ring2@2x"] = {
		name = "ring2@2x",
		filename = "graphic/ring/ring2@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(351, 687),
		imageId = sheetIds[1],
	},
	["ring2@3x"] = {
		name = "ring2@3x",
		filename = "graphic/ring/ring2@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(501, 839),
		imageId = sheetIds[1],
	},
	["ring3"] = {
		name = "ring3",
		filename = "graphic/ring/ring3.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1757, 243),
		imageId = sheetIds[1],
	},
	["ring3@2x"] = {
		name = "ring3@2x",
		filename = "graphic/ring/ring3@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(229, 687),
		imageId = sheetIds[1],
	},
	["ring3@3x"] = {
		name = "ring3@3x",
		filename = "graphic/ring/ring3@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(1229, 839),
		imageId = sheetIds[1],
	},
	["ring4"] = {
		name = "ring4",
		filename = "graphic/ring/ring4.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1633, 243),
		imageId = sheetIds[1],
	},
	["ring4@2x"] = {
		name = "ring4@2x",
		filename = "graphic/ring/ring4@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(717, 687),
		imageId = sheetIds[1],
	},
	["ring4@3x"] = {
		name = "ring4@3x",
		filename = "graphic/ring/ring4@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(1047, 839),
		imageId = sheetIds[1],
	},
	["ring5"] = {
		name = "ring5",
		filename = "graphic/ring/ring5.png",
		imageRectSize = Vector2.new(60, 60),
		imageRectOffset = Vector2.new(1695, 243),
		imageId = sheetIds[1],
	},
	["ring5@2x"] = {
		name = "ring5@2x",
		filename = "graphic/ring/ring5@2x.png",
		imageRectSize = Vector2.new(120, 120),
		imageRectOffset = Vector2.new(595, 687),
		imageId = sheetIds[1],
	},
	["ring5@3x"] = {
		name = "ring5@3x",
		filename = "graphic/ring/ring5@3x.png",
		imageRectSize = Vector2.new(180, 180),
		imageRectOffset = Vector2.new(865, 839),
		imageId = sheetIds[1],
	},
	["color circle-default"] = {
		name = "color circle-default",
		filename = "graphic/selector/color circle-default.png",
		imageRectSize = Vector2.new(72, 72),
		imageRectOffset = Vector2.new(78, 315),
		imageId = sheetIds[1],
	},
	["color circle-default@2x"] = {
		name = "color circle-default@2x",
		filename = "graphic/selector/color circle-default@2x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(913, 687),
		imageId = sheetIds[1],
	},
	["color circle-default@3x"] = {
		name = "color circle-default@3x",
		filename = "graphic/selector/color circle-default@3x.png",
		imageRectSize = Vector2.new(216, 216),
		imageRectOffset = Vector2.new(1609, 839),
		imageId = sheetIds[1],
	},
	["corner"] = {
		name = "corner",
		filename = "graphic/selector/corner.png",
		imageRectSize = Vector2.new(50, 50),
		imageRectOffset = Vector2.new(963, 69),
		imageId = sheetIds[1],
	},
	["corner@2x"] = {
		name = "corner@2x",
		filename = "graphic/selector/corner@2x.png",
		imageRectSize = Vector2.new(100, 100),
		imageRectOffset = Vector2.new(1585, 573),
		imageId = sheetIds[1],
	},
	["corner@3x"] = {
		name = "corner@3x",
		filename = "graphic/selector/corner@3x.png",
		imageRectSize = Vector2.new(150, 150),
		imageRectOffset = Vector2.new(1789, 687),
		imageId = sheetIds[1],
	},
	["icon-border-on"] = {
		name = "icon-border-on",
		filename = "graphic/selector/icon-border-on.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(427, 69),
		imageId = sheetIds[1],
	},
	["icon-border-on@2x"] = {
		name = "icon-border-on@2x",
		filename = "graphic/selector/icon-border-on@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(1191, 573),
		imageId = sheetIds[1],
	},
	["icon-border-on@3x"] = {
		name = "icon-border-on@3x",
		filename = "graphic/selector/icon-border-on@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1059, 687),
		imageId = sheetIds[1],
	},
	["icon-border"] = {
		name = "icon-border",
		filename = "graphic/selector/icon-border.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(577, 69),
		imageId = sheetIds[1],
	},
	["icon-border@2x"] = {
		name = "icon-border@2x",
		filename = "graphic/selector/icon-border@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(1289, 573),
		imageId = sheetIds[1],
	},
	["icon-border@3x"] = {
		name = "icon-border@3x",
		filename = "graphic/selector/icon-border@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1205, 687),
		imageId = sheetIds[1],
	},
	["selector-border"] = {
		name = "selector-border",
		filename = "graphic/selector/selector-border.png",
		imageRectSize = Vector2.new(7, 7),
		imageRectOffset = Vector2.new(23, 1),
		imageId = sheetIds[1],
	},
	["selector-border@2x"] = {
		name = "selector-border@2x",
		filename = "graphic/selector/selector-border@2x.png",
		imageRectSize = Vector2.new(14, 14),
		imageRectOffset = Vector2.new(118, 1),
		imageId = sheetIds[1],
	},
	["selector-border@3x"] = {
		name = "selector-border@3x",
		filename = "graphic/selector/selector-border@3x.png",
		imageRectSize = Vector2.new(21, 21),
		imageRectOffset = Vector2.new(295, 1),
		imageId = sheetIds[1],
	},
	["selector-color"] = {
		name = "selector-color",
		filename = "graphic/selector/selector-color.png",
		imageRectSize = Vector2.new(82, 82),
		imageRectOffset = Vector2.new(152, 315),
		imageId = sheetIds[1],
	},
	["selector-color@2x"] = {
		name = "selector-color@2x",
		filename = "graphic/selector/selector-color@2x.png",
		imageRectSize = Vector2.new(164, 164),
		imageRectOffset = Vector2.new(165, 839),
		imageId = sheetIds[1],
	},
	["selector-color@3x"] = {
		name = "selector-color@3x",
		filename = "graphic/selector/selector-color@3x.png",
		imageRectSize = Vector2.new(246, 246),
		imageRectOffset = Vector2.new(1, 1057),
		imageId = sheetIds[1],
	},
	["btn-slide pressed"] = {
		name = "btn-slide pressed",
		filename = "graphic/slider/btn-slide pressed.png",
		imageRectSize = Vector2.new(48, 48),
		imageRectOffset = Vector2.new(627, 69),
		imageId = sheetIds[1],
	},
	["btn-slide pressed@2x"] = {
		name = "btn-slide pressed@2x",
		filename = "graphic/slider/btn-slide pressed@2x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(799, 573),
		imageId = sheetIds[1],
	},
	["btn-slide pressed@3x"] = {
		name = "btn-slide pressed@3x",
		filename = "graphic/slider/btn-slide pressed@3x.png",
		imageRectSize = Vector2.new(144, 144),
		imageRectOffset = Vector2.new(1497, 687),
		imageId = sheetIds[1],
	},
	["btn-slider"] = {
		name = "btn-slider",
		filename = "graphic/slider/btn-slider.png",
		imageRectSize = Vector2.new(32, 32),
		imageRectOffset = Vector2.new(1934, 31),
		imageId = sheetIds[1],
	},
	["btn-slider@2x"] = {
		name = "btn-slider@2x",
		filename = "graphic/slider/btn-slider@2x.png",
		imageRectSize = Vector2.new(64, 64),
		imageRectOffset = Vector2.new(1819, 243),
		imageId = sheetIds[1],
	},
	["btn-slider@3x"] = {
		name = "btn-slider@3x",
		filename = "graphic/slider/btn-slider@3x.png",
		imageRectSize = Vector2.new(96, 96),
		imageRectOffset = Vector2.new(995, 573),
		imageId = sheetIds[1],
	},
	["slider bar-on"] = {
		name = "slider bar-on",
		filename = "graphic/slider/slider bar-on.png",
		imageRectSize = Vector2.new(15, 14),
		imageRectOffset = Vector2.new(134, 1),
		imageId = sheetIds[1],
	},
	["slider bar-on@2x"] = {
		name = "slider bar-on@2x",
		filename = "graphic/slider/slider bar-on@2x.png",
		imageRectSize = Vector2.new(30, 28),
		imageRectOffset = Vector2.new(1439, 1),
		imageId = sheetIds[1],
	},
	["slider bar-on@3x"] = {
		name = "slider bar-on@3x",
		filename = "graphic/slider/slider bar-on@3x.png",
		imageRectSize = Vector2.new(45, 42),
		imageRectOffset = Vector2.new(52, 69),
		imageId = sheetIds[1],
	},
	["slider bar"] = {
		name = "slider bar",
		filename = "graphic/slider/slider bar.png",
		imageRectSize = Vector2.new(7, 6),
		imageRectOffset = Vector2.new(6, 1),
		imageId = sheetIds[1],
	},
	["slider bar@2x"] = {
		name = "slider bar@2x",
		filename = "graphic/slider/slider bar@2x.png",
		imageRectSize = Vector2.new(14, 12),
		imageRectOffset = Vector2.new(62, 1),
		imageId = sheetIds[1],
	},
	["slider bar@3x"] = {
		name = "slider bar@3x",
		filename = "graphic/slider/slider bar@3x.png",
		imageRectSize = Vector2.new(21, 18),
		imageRectOffset = Vector2.new(256, 1),
		imageId = sheetIds[1],
	},
	["btn-toggle"] = {
		name = "btn-toggle",
		filename = "graphic/switch/btn-toggle.png",
		imageRectSize = Vector2.new(25, 24),
		imageRectOffset = Vector2.new(376, 1),
		imageId = sheetIds[1],
	},
	["btn-toggle@2x"] = {
		name = "btn-toggle@2x",
		filename = "graphic/switch/btn-toggle@2x.png",
		imageRectSize = Vector2.new(50, 48),
		imageRectOffset = Vector2.new(861, 69),
		imageId = sheetIds[1],
	},
	["btn-toggle@3x"] = {
		name = "btn-toggle@3x",
		filename = "graphic/switch/btn-toggle@3x.png",
		imageRectSize = Vector2.new(75, 72),
		imageRectOffset = Vector2.new(1, 315),
		imageId = sheetIds[1],
	},
	["ctn-toggle"] = {
		name = "ctn-toggle",
		filename = "graphic/switch/ctn-toggle.png",
		imageRectSize = Vector2.new(29, 28),
		imageRectOffset = Vector2.new(667, 31),
		imageId = sheetIds[1],
	},
	["ctn-toggle@2x"] = {
		name = "ctn-toggle@2x",
		filename = "graphic/switch/ctn-toggle@2x.png",
		imageRectSize = Vector2.new(58, 56),
		imageRectOffset = Vector2.new(1291, 185),
		imageId = sheetIds[1],
	},
	["ctn-toggle@3x"] = {
		name = "ctn-toggle@3x",
		filename = "graphic/switch/ctn-toggle@3x.png",
		imageRectSize = Vector2.new(87, 84),
		imageRectOffset = Vector2.new(1440, 315),
		imageId = sheetIds[1],
	},
	["ic-climb-on"] = {
		name = "ic-climb-on",
		filename = "Icon/Navigation/animations/ic-climb-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(451, 31),
		imageId = sheetIds[1],
	},
	["ic-climb-on@2x"] = {
		name = "ic-climb-on@2x",
		filename = "Icon/Navigation/animations/ic-climb-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1641, 185),
		imageId = sheetIds[1],
	},
	["ic-climb-on@3x"] = {
		name = "ic-climb-on@3x",
		filename = "Icon/Navigation/animations/ic-climb-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(173, 487),
		imageId = sheetIds[1],
	},
	["ic-climb"] = {
		name = "ic-climb",
		filename = "Icon/Navigation/animations/ic-climb.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(151, 31),
		imageId = sheetIds[1],
	},
	["ic-climb@2x"] = {
		name = "ic-climb@2x",
		filename = "Icon/Navigation/animations/ic-climb@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1757, 185),
		imageId = sheetIds[1],
	},
	["ic-climb@3x"] = {
		name = "ic-climb@3x",
		filename = "Icon/Navigation/animations/ic-climb@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(431, 487),
		imageId = sheetIds[1],
	},
	["ic-fall-on"] = {
		name = "ic-fall-on",
		filename = "Icon/Navigation/animations/ic-fall-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(241, 31),
		imageId = sheetIds[1],
	},
	["ic-fall-on@2x"] = {
		name = "ic-fall-on@2x",
		filename = "Icon/Navigation/animations/ic-fall-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(233, 185),
		imageId = sheetIds[1],
	},
	["ic-fall-on@3x"] = {
		name = "ic-fall-on@3x",
		filename = "Icon/Navigation/animations/ic-fall-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(517, 401),
		imageId = sheetIds[1],
	},
	["ic-fall"] = {
		name = "ic-fall",
		filename = "Icon/Navigation/animations/ic-fall.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(61, 31),
		imageId = sheetIds[1],
	},
	["ic-fall@2x"] = {
		name = "ic-fall@2x",
		filename = "Icon/Navigation/animations/ic-fall@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(291, 185),
		imageId = sheetIds[1],
	},
	["ic-fall@3x"] = {
		name = "ic-fall@3x",
		filename = "Icon/Navigation/animations/ic-fall@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(775, 401),
		imageId = sheetIds[1],
	},
	["ic-idle-on"] = {
		name = "ic-idle-on",
		filename = "Icon/Navigation/animations/ic-idle-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1501, 1),
		imageId = sheetIds[1],
	},
	["ic-idle-on@2x"] = {
		name = "ic-idle-on@2x",
		filename = "Icon/Navigation/animations/ic-idle-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1567, 127),
		imageId = sheetIds[1],
	},
	["ic-idle-on@3x"] = {
		name = "ic-idle-on@3x",
		filename = "Icon/Navigation/animations/ic-idle-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(259, 573),
		imageId = sheetIds[1],
	},
	["ic-idle"] = {
		name = "ic-idle",
		filename = "Icon/Navigation/animations/ic-idle.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1591, 1),
		imageId = sheetIds[1],
	},
	["ic-idle@2x"] = {
		name = "ic-idle@2x",
		filename = "Icon/Navigation/animations/ic-idle@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1509, 127),
		imageId = sheetIds[1],
	},
	["ic-idle@3x"] = {
		name = "ic-idle@3x",
		filename = "Icon/Navigation/animations/ic-idle@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(345, 573),
		imageId = sheetIds[1],
	},
	["ic-jump-on"] = {
		name = "ic-jump-on",
		filename = "Icon/Navigation/animations/ic-jump-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1088, 31),
		imageId = sheetIds[1],
	},
	["ic-jump-on@2x"] = {
		name = "ic-jump-on@2x",
		filename = "Icon/Navigation/animations/ic-jump-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1335, 243),
		imageId = sheetIds[1],
	},
	["ic-jump-on@3x"] = {
		name = "ic-jump-on@3x",
		filename = "Icon/Navigation/animations/ic-jump-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(87, 573),
		imageId = sheetIds[1],
	},
	["ic-jump"] = {
		name = "ic-jump",
		filename = "Icon/Navigation/animations/ic-jump.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1028, 31),
		imageId = sheetIds[1],
	},
	["ic-jump@2x"] = {
		name = "ic-jump@2x",
		filename = "Icon/Navigation/animations/ic-jump@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(639, 243),
		imageId = sheetIds[1],
	},
	["ic-jump@3x"] = {
		name = "ic-jump@3x",
		filename = "Icon/Navigation/animations/ic-jump@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(861, 487),
		imageId = sheetIds[1],
	},
	["ic-run-on"] = {
		name = "ic-run-on",
		filename = "Icon/Navigation/animations/ic-run-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(913, 1),
		imageId = sheetIds[1],
	},
	["ic-run-on@2x"] = {
		name = "ic-run-on@2x",
		filename = "Icon/Navigation/animations/ic-run-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1393, 127),
		imageId = sheetIds[1],
	},
	["ic-run-on@3x"] = {
		name = "ic-run-on@3x",
		filename = "Icon/Navigation/animations/ic-run-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1377, 487),
		imageId = sheetIds[1],
	},
	["ic-run"] = {
		name = "ic-run",
		filename = "Icon/Navigation/animations/ic-run.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(883, 1),
		imageId = sheetIds[1],
	},
	["ic-run@2x"] = {
		name = "ic-run@2x",
		filename = "Icon/Navigation/animations/ic-run@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1277, 243),
		imageId = sheetIds[1],
	},
	["ic-run@3x"] = {
		name = "ic-run@3x",
		filename = "Icon/Navigation/animations/ic-run@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1807, 401),
		imageId = sheetIds[1],
	},
	["ic-swim-on"] = {
		name = "ic-swim-on",
		filename = "Icon/Navigation/animations/ic-swim-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1531, 1),
		imageId = sheetIds[1],
	},
	["ic-swim-on@2x"] = {
		name = "ic-swim-on@2x",
		filename = "Icon/Navigation/animations/ic-swim-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(987, 127),
		imageId = sheetIds[1],
	},
	["ic-swim-on@3x"] = {
		name = "ic-swim-on@3x",
		filename = "Icon/Navigation/animations/ic-swim-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(322, 315),
		imageId = sheetIds[1],
	},
	["ic-swim"] = {
		name = "ic-swim",
		filename = "Icon/Navigation/animations/ic-swim.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1561, 1),
		imageId = sheetIds[1],
	},
	["ic-swim@2x"] = {
		name = "ic-swim@2x",
		filename = "Icon/Navigation/animations/ic-swim@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(581, 127),
		imageId = sheetIds[1],
	},
	["ic-swim@3x"] = {
		name = "ic-swim@3x",
		filename = "Icon/Navigation/animations/ic-swim@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(408, 315),
		imageId = sheetIds[1],
	},
	["ic-walk-on"] = {
		name = "ic-walk-on",
		filename = "Icon/Navigation/animations/ic-walk-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1471, 1),
		imageId = sheetIds[1],
	},
	["ic-walk-on@2x"] = {
		name = "ic-walk-on@2x",
		filename = "Icon/Navigation/animations/ic-walk-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(465, 127),
		imageId = sheetIds[1],
	},
	["ic-walk-on@3x"] = {
		name = "ic-walk-on@3x",
		filename = "Icon/Navigation/animations/ic-walk-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1701, 315),
		imageId = sheetIds[1],
	},
	["ic-walk"] = {
		name = "ic-walk",
		filename = "Icon/Navigation/animations/ic-walk.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1409, 1),
		imageId = sheetIds[1],
	},
	["ic-walk@2x"] = {
		name = "ic-walk@2x",
		filename = "Icon/Navigation/animations/ic-walk@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(755, 127),
		imageId = sheetIds[1],
	},
	["ic-walk@3x"] = {
		name = "ic-walk@3x",
		filename = "Icon/Navigation/animations/ic-walk@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1873, 315),
		imageId = sheetIds[1],
	},
	["ic-head-on"] = {
		name = "ic-head-on",
		filename = "Icon/Navigation/body/ic-head-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1243, 1),
		imageId = sheetIds[1],
	},
	["ic-head-on@2x"] = {
		name = "ic-head-on@2x",
		filename = "Icon/Navigation/body/ic-head-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(929, 127),
		imageId = sheetIds[1],
	},
	["ic-head-on@3x"] = {
		name = "ic-head-on@3x",
		filename = "Icon/Navigation/body/ic-head-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(431, 573),
		imageId = sheetIds[1],
	},
	["ic-head"] = {
		name = "ic-head",
		filename = "Icon/Navigation/body/ic-head.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1208, 31),
		imageId = sheetIds[1],
	},
	["ic-head@2x"] = {
		name = "ic-head@2x",
		filename = "Icon/Navigation/body/ic-head@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1741, 127),
		imageId = sheetIds[1],
	},
	["ic-head@3x"] = {
		name = "ic-head@3x",
		filename = "Icon/Navigation/body/ic-head@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(173, 573),
		imageId = sheetIds[1],
	},
	["ic-left-arms-on"] = {
		name = "ic-left-arms-on",
		filename = "Icon/Navigation/body/ic-left-arms-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1289, 1),
		imageId = sheetIds[1],
	},
	["ic-left-arms-on@2x"] = {
		name = "ic-left-arms-on@2x",
		filename = "Icon/Navigation/body/ic-left-arms-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(697, 127),
		imageId = sheetIds[1],
	},
	["ic-left-arms-on@3x"] = {
		name = "ic-left-arms-on@3x",
		filename = "Icon/Navigation/body/ic-left-arms-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1119, 487),
		imageId = sheetIds[1],
	},
	["ic-left-arms"] = {
		name = "ic-left-arms",
		filename = "Icon/Navigation/body/ic-left-arms.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1379, 1),
		imageId = sheetIds[1],
	},
	["ic-left-arms@2x"] = {
		name = "ic-left-arms@2x",
		filename = "Icon/Navigation/body/ic-left-arms@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(407, 127),
		imageId = sheetIds[1],
	},
	["ic-left-arms@3x"] = {
		name = "ic-left-arms@3x",
		filename = "Icon/Navigation/body/ic-left-arms@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1, 573),
		imageId = sheetIds[1],
	},
	["ic-left-legs-on"] = {
		name = "ic-left-legs-on",
		filename = "Icon/Navigation/body/ic-left-legs-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1319, 1),
		imageId = sheetIds[1],
	},
	["ic-left-legs-on@2x"] = {
		name = "ic-left-legs-on@2x",
		filename = "Icon/Navigation/body/ic-left-legs-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(639, 127),
		imageId = sheetIds[1],
	},
	["ic-left-legs-on@3x"] = {
		name = "ic-left-legs-on@3x",
		filename = "Icon/Navigation/body/ic-left-legs-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1033, 487),
		imageId = sheetIds[1],
	},
	["ic-left-legs"] = {
		name = "ic-left-legs",
		filename = "Icon/Navigation/body/ic-left-legs.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1448, 31),
		imageId = sheetIds[1],
	},
	["ic-left-legs@2x"] = {
		name = "ic-left-legs@2x",
		filename = "Icon/Navigation/body/ic-left-legs@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(755, 243),
		imageId = sheetIds[1],
	},
	["ic-left-legs@3x"] = {
		name = "ic-left-legs@3x",
		filename = "Icon/Navigation/body/ic-left-legs@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1205, 487),
		imageId = sheetIds[1],
	},
	["ic-right-arms-on"] = {
		name = "ic-right-arms-on",
		filename = "Icon/Navigation/body/ic-right-arms-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1349, 1),
		imageId = sheetIds[1],
	},
	["ic-right-arms-on@2x"] = {
		name = "ic-right-arms-on@2x",
		filename = "Icon/Navigation/body/ic-right-arms-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1451, 127),
		imageId = sheetIds[1],
	},
	["ic-right-arms-on@3x"] = {
		name = "ic-right-arms-on@3x",
		filename = "Icon/Navigation/body/ic-right-arms-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1721, 487),
		imageId = sheetIds[1],
	},
	["ic-right-arms"] = {
		name = "ic-right-arms",
		filename = "Icon/Navigation/body/ic-right-arms.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1621, 1),
		imageId = sheetIds[1],
	},
	["ic-right-arms@2x"] = {
		name = "ic-right-arms@2x",
		filename = "Icon/Navigation/body/ic-right-arms@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1045, 127),
		imageId = sheetIds[1],
	},
	["ic-right-arms@3x"] = {
		name = "ic-right-arms@3x",
		filename = "Icon/Navigation/body/ic-right-arms@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1893, 487),
		imageId = sheetIds[1],
	},
	["ic-right-legs-on"] = {
		name = "ic-right-legs-on",
		filename = "Icon/Navigation/body/ic-right-legs-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1681, 1),
		imageId = sheetIds[1],
	},
	["ic-right-legs-on@2x"] = {
		name = "ic-right-legs-on@2x",
		filename = "Icon/Navigation/body/ic-right-legs-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1161, 127),
		imageId = sheetIds[1],
	},
	["ic-right-legs-on@3x"] = {
		name = "ic-right-legs-on@3x",
		filename = "Icon/Navigation/body/ic-right-legs-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1635, 487),
		imageId = sheetIds[1],
	},
	["ic-right-legs"] = {
		name = "ic-right-legs",
		filename = "Icon/Navigation/body/ic-right-legs.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1183, 1),
		imageId = sheetIds[1],
	},
	["ic-right-legs@2x"] = {
		name = "ic-right-legs@2x",
		filename = "Icon/Navigation/body/ic-right-legs@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(407, 243),
		imageId = sheetIds[1],
	},
	["ic-right-legs@3x"] = {
		name = "ic-right-legs@3x",
		filename = "Icon/Navigation/body/ic-right-legs@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1463, 487),
		imageId = sheetIds[1],
	},
	["ic-scale-on"] = {
		name = "ic-scale-on",
		filename = "Icon/Navigation/body/ic-scale-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1821, 1),
		imageId = sheetIds[1],
	},
	["ic-scale-on@2x"] = {
		name = "ic-scale-on@2x",
		filename = "Icon/Navigation/body/ic-scale-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1219, 127),
		imageId = sheetIds[1],
	},
	["ic-scale-on@3x"] = {
		name = "ic-scale-on@3x",
		filename = "Icon/Navigation/body/ic-scale-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(603, 487),
		imageId = sheetIds[1],
	},
	["ic-scale"] = {
		name = "ic-scale",
		filename = "Icon/Navigation/body/ic-scale.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(853, 1),
		imageId = sheetIds[1],
	},
	["ic-scale@2x"] = {
		name = "ic-scale@2x",
		filename = "Icon/Navigation/body/ic-scale@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1219, 243),
		imageId = sheetIds[1],
	},
	["ic-scale@3x"] = {
		name = "ic-scale@3x",
		filename = "Icon/Navigation/body/ic-scale@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1615, 315),
		imageId = sheetIds[1],
	},
	["ic-skintone-on"] = {
		name = "ic-skintone-on",
		filename = "Icon/Navigation/body/ic-skintone-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(211, 31),
		imageId = sheetIds[1],
	},
	["ic-skintone-on@2x"] = {
		name = "ic-skintone-on@2x",
		filename = "Icon/Navigation/body/ic-skintone-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(175, 185),
		imageId = sheetIds[1],
	},
	["ic-skintone-on@3x"] = {
		name = "ic-skintone-on@3x",
		filename = "Icon/Navigation/body/ic-skintone-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1, 487),
		imageId = sheetIds[1],
	},
	["ic-skintone"] = {
		name = "ic-skintone",
		filename = "Icon/Navigation/body/ic-skintone.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(301, 31),
		imageId = sheetIds[1],
	},
	["ic-skintone@2x"] = {
		name = "ic-skintone@2x",
		filename = "Icon/Navigation/body/ic-skintone@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(117, 185),
		imageId = sheetIds[1],
	},
	["ic-skintone@3x"] = {
		name = "ic-skintone@3x",
		filename = "Icon/Navigation/body/ic-skintone@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1463, 401),
		imageId = sheetIds[1],
	},
	["ic-torso-on"] = {
		name = "ic-torso-on",
		filename = "Icon/Navigation/body/ic-torso-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1851, 1),
		imageId = sheetIds[1],
	},
	["ic-torso-on@2x"] = {
		name = "ic-torso-on@2x",
		filename = "Icon/Navigation/body/ic-torso-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(349, 127),
		imageId = sheetIds[1],
	},
	["ic-torso-on@3x"] = {
		name = "ic-torso-on@3x",
		filename = "Icon/Navigation/body/ic-torso-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(236, 315),
		imageId = sheetIds[1],
	},
	["ic-torso"] = {
		name = "ic-torso",
		filename = "Icon/Navigation/body/ic-torso.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1093, 1),
		imageId = sheetIds[1],
	},
	["ic-torso@2x"] = {
		name = "ic-torso@2x",
		filename = "Icon/Navigation/body/ic-torso@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1, 127),
		imageId = sheetIds[1],
	},
	["ic-torso@3x"] = {
		name = "ic-torso@3x",
		filename = "Icon/Navigation/body/ic-torso@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(494, 315),
		imageId = sheetIds[1],
	},
	["ic-back-on"] = {
		name = "ic-back-on",
		filename = "Icon/Navigation/clothing/ic-back-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1911, 1),
		imageId = sheetIds[1],
	},
	["ic-back-on@2x"] = {
		name = "ic-back-on@2x",
		filename = "Icon/Navigation/clothing/ic-back-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1299, 69),
		imageId = sheetIds[1],
	},
	["ic-back-on@3x"] = {
		name = "ic-back-on@3x",
		filename = "Icon/Navigation/clothing/ic-back-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1549, 401),
		imageId = sheetIds[1],
	},
	["ic-back"] = {
		name = "ic-back",
		filename = "Icon/Navigation/clothing/ic-back.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(938, 31),
		imageId = sheetIds[1],
	},
	["ic-back@2x"] = {
		name = "ic-back@2x",
		filename = "Icon/Navigation/clothing/ic-back@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1989, 185),
		imageId = sheetIds[1],
	},
	["ic-back@3x"] = {
		name = "ic-back@3x",
		filename = "Icon/Navigation/clothing/ic-back@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1377, 401),
		imageId = sheetIds[1],
	},
	["ic-face-accessories-on"] = {
		name = "ic-face-accessories-on",
		filename = "Icon/Navigation/clothing/ic-face-accessories-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(2001, 1),
		imageId = sheetIds[1],
	},
	["ic-face-accessories-on@2x"] = {
		name = "ic-face-accessories-on@2x",
		filename = "Icon/Navigation/clothing/ic-face-accessories-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1531, 69),
		imageId = sheetIds[1],
	},
	["ic-face-accessories-on@3x"] = {
		name = "ic-face-accessories-on@3x",
		filename = "Icon/Navigation/clothing/ic-face-accessories-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1268, 315),
		imageId = sheetIds[1],
	},
	["ic-face-accessories"] = {
		name = "ic-face-accessories",
		filename = "Icon/Navigation/clothing/ic-face-accessories.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1941, 1),
		imageId = sheetIds[1],
	},
	["ic-face-accessories@2x"] = {
		name = "ic-face-accessories@2x",
		filename = "Icon/Navigation/clothing/ic-face-accessories@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1647, 69),
		imageId = sheetIds[1],
	},
	["ic-face-accessories@3x"] = {
		name = "ic-face-accessories@3x",
		filename = "Icon/Navigation/clothing/ic-face-accessories@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1354, 315),
		imageId = sheetIds[1],
	},
	["ic-face-on"] = {
		name = "ic-face-on",
		filename = "Icon/Navigation/clothing/ic-face-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(331, 31),
		imageId = sheetIds[1],
	},
	["ic-face-on@2x"] = {
		name = "ic-face-on@2x",
		filename = "Icon/Navigation/clothing/ic-face-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1915, 127),
		imageId = sheetIds[1],
	},
	["ic-face-on@3x"] = {
		name = "ic-face-on@3x",
		filename = "Icon/Navigation/clothing/ic-face-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1, 401),
		imageId = sheetIds[1],
	},
	["ic-face"] = {
		name = "ic-face",
		filename = "Icon/Navigation/clothing/ic-face.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(271, 31),
		imageId = sheetIds[1],
	},
	["ic-face@2x"] = {
		name = "ic-face@2x",
		filename = "Icon/Navigation/clothing/ic-face@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1857, 127),
		imageId = sheetIds[1],
	},
	["ic-face@3x"] = {
		name = "ic-face@3x",
		filename = "Icon/Navigation/clothing/ic-face@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1959, 315),
		imageId = sheetIds[1],
	},
	["ic-front-on"] = {
		name = "ic-front-on",
		filename = "Icon/Navigation/clothing/ic-front-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1971, 1),
		imageId = sheetIds[1],
	},
	["ic-front-on@2x"] = {
		name = "ic-front-on@2x",
		filename = "Icon/Navigation/clothing/ic-front-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1473, 69),
		imageId = sheetIds[1],
	},
	["ic-front-on@3x"] = {
		name = "ic-front-on@3x",
		filename = "Icon/Navigation/clothing/ic-front-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1033, 401),
		imageId = sheetIds[1],
	},
	["ic-front"] = {
		name = "ic-front",
		filename = "Icon/Navigation/clothing/ic-front.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1628, 31),
		imageId = sheetIds[1],
	},
	["ic-front@2x"] = {
		name = "ic-front@2x",
		filename = "Icon/Navigation/clothing/ic-front@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(697, 185),
		imageId = sheetIds[1],
	},
	["ic-front@3x"] = {
		name = "ic-front@3x",
		filename = "Icon/Navigation/clothing/ic-front@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(947, 401),
		imageId = sheetIds[1],
	},
	["ic-gear-on"] = {
		name = "ic-gear-on",
		filename = "Icon/Navigation/clothing/ic-gear-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1881, 1),
		imageId = sheetIds[1],
	},
	["ic-gear-on@2x"] = {
		name = "ic-gear-on@2x",
		filename = "Icon/Navigation/clothing/ic-gear-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1125, 69),
		imageId = sheetIds[1],
	},
	["ic-gear-on@3x"] = {
		name = "ic-gear-on@3x",
		filename = "Icon/Navigation/clothing/ic-gear-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1119, 401),
		imageId = sheetIds[1],
	},
	["ic-gear"] = {
		name = "ic-gear",
		filename = "Icon/Navigation/clothing/ic-gear.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1658, 31),
		imageId = sheetIds[1],
	},
	["ic-gear@2x"] = {
		name = "ic-gear@2x",
		filename = "Icon/Navigation/clothing/ic-gear@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(755, 185),
		imageId = sheetIds[1],
	},
	["ic-gear@3x"] = {
		name = "ic-gear@3x",
		filename = "Icon/Navigation/clothing/ic-gear@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(861, 401),
		imageId = sheetIds[1],
	},
	["ic-hair-on"] = {
		name = "ic-hair-on",
		filename = "Icon/Navigation/clothing/ic-hair-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1213, 1),
		imageId = sheetIds[1],
	},
	["ic-hair-on@2x"] = {
		name = "ic-hair-on@2x",
		filename = "Icon/Navigation/clothing/ic-hair-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(523, 127),
		imageId = sheetIds[1],
	},
	["ic-hair-on@3x"] = {
		name = "ic-hair-on@3x",
		filename = "Icon/Navigation/clothing/ic-hair-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(689, 401),
		imageId = sheetIds[1],
	},
	["ic-hair"] = {
		name = "ic-hair",
		filename = "Icon/Navigation/clothing/ic-hair.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1688, 31),
		imageId = sheetIds[1],
	},
	["ic-hair@2x"] = {
		name = "ic-hair@2x",
		filename = "Icon/Navigation/clothing/ic-hair@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(523, 185),
		imageId = sheetIds[1],
	},
	["ic-hair@3x"] = {
		name = "ic-hair@3x",
		filename = "Icon/Navigation/clothing/ic-hair@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(603, 401),
		imageId = sheetIds[1],
	},
	["ic-hat-on"] = {
		name = "ic-hat-on",
		filename = "Icon/Navigation/clothing/ic-hat-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1718, 31),
		imageId = sheetIds[1],
	},
	["ic-hat-on@2x"] = {
		name = "ic-hat-on@2x",
		filename = "Icon/Navigation/clothing/ic-hat-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(349, 185),
		imageId = sheetIds[1],
	},
	["ic-hat-on@3x"] = {
		name = "ic-hat-on@3x",
		filename = "Icon/Navigation/clothing/ic-hat-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(87, 401),
		imageId = sheetIds[1],
	},
	["ic-hat"] = {
		name = "ic-hat",
		filename = "Icon/Navigation/clothing/ic-hat.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1058, 31),
		imageId = sheetIds[1],
	},
	["ic-hat@2x"] = {
		name = "ic-hat@2x",
		filename = "Icon/Navigation/clothing/ic-hat@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(465, 185),
		imageId = sheetIds[1],
	},
	["ic-hat@3x"] = {
		name = "ic-hat@3x",
		filename = "Icon/Navigation/clothing/ic-hat@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(517, 573),
		imageId = sheetIds[1],
	},
	["ic-neck-on"] = {
		name = "ic-neck-on",
		filename = "Icon/Navigation/clothing/ic-neck-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1651, 1),
		imageId = sheetIds[1],
	},
	["ic-neck-on@2x"] = {
		name = "ic-neck-on@2x",
		filename = "Icon/Navigation/clothing/ic-neck-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1357, 69),
		imageId = sheetIds[1],
	},
	["ic-neck-on@3x"] = {
		name = "ic-neck-on@3x",
		filename = "Icon/Navigation/clothing/ic-neck-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(947, 487),
		imageId = sheetIds[1],
	},
	["ic-neck"] = {
		name = "ic-neck",
		filename = "Icon/Navigation/clothing/ic-neck.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1478, 31),
		imageId = sheetIds[1],
	},
	["ic-neck@2x"] = {
		name = "ic-neck@2x",
		filename = "Icon/Navigation/clothing/ic-neck@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(813, 243),
		imageId = sheetIds[1],
	},
	["ic-neck@3x"] = {
		name = "ic-neck@3x",
		filename = "Icon/Navigation/clothing/ic-neck@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1182, 315),
		imageId = sheetIds[1],
	},
	["ic-pants-on"] = {
		name = "ic-pants-on",
		filename = "Icon/Navigation/clothing/ic-pants-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1711, 1),
		imageId = sheetIds[1],
	},
	["ic-pants-on@2x"] = {
		name = "ic-pants-on@2x",
		filename = "Icon/Navigation/clothing/ic-pants-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1415, 69),
		imageId = sheetIds[1],
	},
	["ic-pants-on@3x"] = {
		name = "ic-pants-on@3x",
		filename = "Icon/Navigation/clothing/ic-pants-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(689, 487),
		imageId = sheetIds[1],
	},
	["ic-pants"] = {
		name = "ic-pants",
		filename = "Icon/Navigation/clothing/ic-pants.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1388, 31),
		imageId = sheetIds[1],
	},
	["ic-pants@2x"] = {
		name = "ic-pants@2x",
		filename = "Icon/Navigation/clothing/ic-pants@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(697, 243),
		imageId = sheetIds[1],
	},
	["ic-pants@3x"] = {
		name = "ic-pants@3x",
		filename = "Icon/Navigation/clothing/ic-pants@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1291, 487),
		imageId = sheetIds[1],
	},
	["ic-shirts-on"] = {
		name = "ic-shirts-on",
		filename = "Icon/Navigation/clothing/ic-shirts-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(793, 1),
		imageId = sheetIds[1],
	},
	["ic-shirts-on@2x"] = {
		name = "ic-shirts-on@2x",
		filename = "Icon/Navigation/clothing/ic-shirts-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1045, 243),
		imageId = sheetIds[1],
	},
	["ic-shirts-on@3x"] = {
		name = "ic-shirts-on@3x",
		filename = "Icon/Navigation/clothing/ic-shirts-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(580, 315),
		imageId = sheetIds[1],
	},
	["ic-shirts"] = {
		name = "ic-shirts",
		filename = "Icon/Navigation/clothing/ic-shirts.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(763, 1),
		imageId = sheetIds[1],
	},
	["ic-shirts@2x"] = {
		name = "ic-shirts@2x",
		filename = "Icon/Navigation/clothing/ic-shirts@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1393, 243),
		imageId = sheetIds[1],
	},
	["ic-shirts@3x"] = {
		name = "ic-shirts@3x",
		filename = "Icon/Navigation/clothing/ic-shirts@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(752, 315),
		imageId = sheetIds[1],
	},
	["ic-shoulders-on"] = {
		name = "ic-shoulders-on",
		filename = "Icon/Navigation/clothing/ic-shoulders-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1761, 1),
		imageId = sheetIds[1],
	},
	["ic-shoulders-on@2x"] = {
		name = "ic-shoulders-on@2x",
		filename = "Icon/Navigation/clothing/ic-shoulders-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1277, 127),
		imageId = sheetIds[1],
	},
	["ic-shoulders-on@3x"] = {
		name = "ic-shoulders-on@3x",
		filename = "Icon/Navigation/clothing/ic-shoulders-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(924, 315),
		imageId = sheetIds[1],
	},
	["ic-shoulders"] = {
		name = "ic-shoulders",
		filename = "Icon/Navigation/clothing/ic-shoulders.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1063, 1),
		imageId = sheetIds[1],
	},
	["ic-shoulders@2x"] = {
		name = "ic-shoulders@2x",
		filename = "Icon/Navigation/clothing/ic-shoulders@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1589, 69),
		imageId = sheetIds[1],
	},
	["ic-shoulders@3x"] = {
		name = "ic-shoulders@3x",
		filename = "Icon/Navigation/clothing/ic-shoulders@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(838, 315),
		imageId = sheetIds[1],
	},
	["ic-tshirts-on"] = {
		name = "ic-tshirts-on",
		filename = "Icon/Navigation/clothing/ic-tshirts-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(823, 1),
		imageId = sheetIds[1],
	},
	["ic-tshirts-on@2x"] = {
		name = "ic-tshirts-on@2x",
		filename = "Icon/Navigation/clothing/ic-tshirts-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(291, 127),
		imageId = sheetIds[1],
	},
	["ic-tshirts-on@3x"] = {
		name = "ic-tshirts-on@3x",
		filename = "Icon/Navigation/clothing/ic-tshirts-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(666, 315),
		imageId = sheetIds[1],
	},
	["ic-tshirts"] = {
		name = "ic-tshirts",
		filename = "Icon/Navigation/clothing/ic-tshirts.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(703, 1),
		imageId = sheetIds[1],
	},
	["ic-tshirts@2x"] = {
		name = "ic-tshirts@2x",
		filename = "Icon/Navigation/clothing/ic-tshirts@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(175, 127),
		imageId = sheetIds[1],
	},
	["ic-tshirts@3x"] = {
		name = "ic-tshirts@3x",
		filename = "Icon/Navigation/clothing/ic-tshirts@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1096, 315),
		imageId = sheetIds[1],
	},
	["ic-waist-on"] = {
		name = "ic-waist-on",
		filename = "Icon/Navigation/clothing/ic-waist-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(613, 1),
		imageId = sheetIds[1],
	},
	["ic-waist-on@2x"] = {
		name = "ic-waist-on@2x",
		filename = "Icon/Navigation/clothing/ic-waist-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1625, 127),
		imageId = sheetIds[1],
	},
	["ic-waist-on@3x"] = {
		name = "ic-waist-on@3x",
		filename = "Icon/Navigation/clothing/ic-waist-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1010, 315),
		imageId = sheetIds[1],
	},
	["ic-waist"] = {
		name = "ic-waist",
		filename = "Icon/Navigation/clothing/ic-waist.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(643, 1),
		imageId = sheetIds[1],
	},
	["ic-waist@2x"] = {
		name = "ic-waist@2x",
		filename = "Icon/Navigation/clothing/ic-waist@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(813, 127),
		imageId = sheetIds[1],
	},
	["ic-waist@3x"] = {
		name = "ic-waist@3x",
		filename = "Icon/Navigation/clothing/ic-waist@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1787, 315),
		imageId = sheetIds[1],
	},
	["ic-all-on"] = {
		name = "ic-all-on",
		filename = "Icon/Navigation/primary/ic-all-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(673, 1),
		imageId = sheetIds[1],
	},
	["ic-all-on@2x"] = {
		name = "ic-all-on@2x",
		filename = "Icon/Navigation/primary/ic-all-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(871, 127),
		imageId = sheetIds[1],
	},
	["ic-all-on@3x"] = {
		name = "ic-all-on@3x",
		filename = "Icon/Navigation/primary/ic-all-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1529, 315),
		imageId = sheetIds[1],
	},
	["ic-all"] = {
		name = "ic-all",
		filename = "Icon/Navigation/primary/ic-all.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(481, 31),
		imageId = sheetIds[1],
	},
	["ic-all@2x"] = {
		name = "ic-all@2x",
		filename = "Icon/Navigation/primary/ic-all@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1103, 185),
		imageId = sheetIds[1],
	},
	["ic-all@3x"] = {
		name = "ic-all@3x",
		filename = "Icon/Navigation/primary/ic-all@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1721, 401),
		imageId = sheetIds[1],
	},
	["ic-animations-on"] = {
		name = "ic-animations-on",
		filename = "Icon/Navigation/primary/ic-animations-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(913, 1),
		imageId = sheetIds[1],
	},
	["ic-animations-on@2x"] = {
		name = "ic-animations-on@2x",
		filename = "Icon/Navigation/primary/ic-animations-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(987, 243),
		imageId = sheetIds[1],
	},
	["ic-animations-on@3x"] = {
		name = "ic-animations-on@3x",
		filename = "Icon/Navigation/primary/ic-animations-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1635, 401),
		imageId = sheetIds[1],
	},
	["ic-animations"] = {
		name = "ic-animations",
		filename = "Icon/Navigation/primary/ic-animations.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(883, 1),
		imageId = sheetIds[1],
	},
	["ic-animations@2x"] = {
		name = "ic-animations@2x",
		filename = "Icon/Navigation/primary/ic-animations@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1277, 243),
		imageId = sheetIds[1],
	},
	["ic-animations@3x"] = {
		name = "ic-animations@3x",
		filename = "Icon/Navigation/primary/ic-animations@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1807, 401),
		imageId = sheetIds[1],
	},
	["ic-body-on"] = {
		name = "ic-body-on",
		filename = "Icon/Navigation/primary/ic-body-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(848, 31),
		imageId = sheetIds[1],
	},
	["ic-body-on@2x"] = {
		name = "ic-body-on@2x",
		filename = "Icon/Navigation/primary/ic-body-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(59, 243),
		imageId = sheetIds[1],
	},
	["ic-body-on@3x"] = {
		name = "ic-body-on@3x",
		filename = "Icon/Navigation/primary/ic-body-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1291, 401),
		imageId = sheetIds[1],
	},
	["ic-body"] = {
		name = "ic-body",
		filename = "Icon/Navigation/primary/ic-body.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(788, 31),
		imageId = sheetIds[1],
	},
	["ic-body@2x"] = {
		name = "ic-body@2x",
		filename = "Icon/Navigation/primary/ic-body@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1, 243),
		imageId = sheetIds[1],
	},
	["ic-body@3x"] = {
		name = "ic-body@3x",
		filename = "Icon/Navigation/primary/ic-body@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1893, 401),
		imageId = sheetIds[1],
	},
	["ic-clothing-on"] = {
		name = "ic-clothing-on",
		filename = "Icon/Navigation/primary/ic-clothing-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(698, 31),
		imageId = sheetIds[1],
	},
	["ic-clothing-on@2x"] = {
		name = "ic-clothing-on@2x",
		filename = "Icon/Navigation/primary/ic-clothing-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1103, 127),
		imageId = sheetIds[1],
	},
	["ic-clothing-on@3x"] = {
		name = "ic-clothing-on@3x",
		filename = "Icon/Navigation/primary/ic-clothing-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(517, 487),
		imageId = sheetIds[1],
	},
	["ic-clothing"] = {
		name = "ic-clothing",
		filename = "Icon/Navigation/primary/ic-clothing.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(91, 31),
		imageId = sheetIds[1],
	},
	["ic-clothing@2x"] = {
		name = "ic-clothing@2x",
		filename = "Icon/Navigation/primary/ic-clothing@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(871, 185),
		imageId = sheetIds[1],
	},
	["ic-clothing@3x"] = {
		name = "ic-clothing@3x",
		filename = "Icon/Navigation/primary/ic-clothing@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(259, 487),
		imageId = sheetIds[1],
	},
	["ic-costumes-on"] = {
		name = "ic-costumes-on",
		filename = "Icon/Navigation/primary/ic-costumes-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(637, 31),
		imageId = sheetIds[1],
	},
	["ic-costumes-on@2x"] = {
		name = "ic-costumes-on@2x",
		filename = "Icon/Navigation/primary/ic-costumes-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1335, 127),
		imageId = sheetIds[1],
	},
	["ic-costumes-on@3x"] = {
		name = "ic-costumes-on@3x",
		filename = "Icon/Navigation/primary/ic-costumes-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1205, 401),
		imageId = sheetIds[1],
	},
	["ic-costumes"] = {
		name = "ic-costumes",
		filename = "Icon/Navigation/primary/ic-costumes.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(541, 31),
		imageId = sheetIds[1],
	},
	["ic-costumes@2x"] = {
		name = "ic-costumes@2x",
		filename = "Icon/Navigation/primary/ic-costumes@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1815, 185),
		imageId = sheetIds[1],
	},
	["ic-costumes@3x"] = {
		name = "ic-costumes@3x",
		filename = "Icon/Navigation/primary/ic-costumes@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(345, 401),
		imageId = sheetIds[1],
	},
	["ic-recent-on"] = {
		name = "ic-recent-on",
		filename = "Icon/Navigation/primary/ic-recent-on.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1298, 31),
		imageId = sheetIds[1],
	},
	["ic-recent-on@2x"] = {
		name = "ic-recent-on@2x",
		filename = "Icon/Navigation/primary/ic-recent-on@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(523, 243),
		imageId = sheetIds[1],
	},
	["ic-recent-on@3x"] = {
		name = "ic-recent-on@3x",
		filename = "Icon/Navigation/primary/ic-recent-on@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1549, 487),
		imageId = sheetIds[1],
	},
	["ic-recent"] = {
		name = "ic-recent",
		filename = "Icon/Navigation/primary/ic-recent.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(1358, 31),
		imageId = sheetIds[1],
	},
	["ic-recent@2x"] = {
		name = "ic-recent@2x",
		filename = "Icon/Navigation/primary/ic-recent@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(175, 243),
		imageId = sheetIds[1],
	},
	["ic-recent@3x"] = {
		name = "ic-recent@3x",
		filename = "Icon/Navigation/primary/ic-recent@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(1807, 487),
		imageId = sheetIds[1],
	},
	["ic-close"] = {
		name = "ic-close",
		filename = "Icon/others/ic-close.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(121, 31),
		imageId = sheetIds[1],
	},
	["ic-close@2x"] = {
		name = "ic-close@2x",
		filename = "Icon/others/ic-close@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1699, 185),
		imageId = sheetIds[1],
	},
	["ic-close@3x"] = {
		name = "ic-close@3x",
		filename = "Icon/others/ic-close@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(345, 487),
		imageId = sheetIds[1],
	},
	["ic-collapse"] = {
		name = "ic-collapse",
		filename = "Icon/others/ic-collapse.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(31, 31),
		imageId = sheetIds[1],
	},
	["ic-collapse@2x"] = {
		name = "ic-collapse@2x",
		filename = "Icon/others/ic-collapse@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(59, 185),
		imageId = sheetIds[1],
	},
	["ic-collapse@3x"] = {
		name = "ic-collapse@3x",
		filename = "Icon/others/ic-collapse@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(87, 487),
		imageId = sheetIds[1],
	},
	["ic-down-arrow-off"] = {
		name = "ic-down-arrow-off",
		filename = "Icon/others/ic-down-arrow-off.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(391, 31),
		imageId = sheetIds[1],
	},
	["ic-down-arrow-off@2x"] = {
		name = "ic-down-arrow-off@2x",
		filename = "Icon/others/ic-down-arrow-off@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1, 185),
		imageId = sheetIds[1],
	},
	["ic-down-arrow-off@3x"] = {
		name = "ic-down-arrow-off@3x",
		filename = "Icon/others/ic-down-arrow-off@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(259, 401),
		imageId = sheetIds[1],
	},
	["ic-down-arrow"] = {
		name = "ic-down-arrow",
		filename = "Icon/others/ic-down-arrow.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(361, 31),
		imageId = sheetIds[1],
	},
	["ic-down-arrow@2x"] = {
		name = "ic-down-arrow@2x",
		filename = "Icon/others/ic-down-arrow@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1973, 127),
		imageId = sheetIds[1],
	},
	["ic-down-arrow@3x"] = {
		name = "ic-down-arrow@3x",
		filename = "Icon/others/ic-down-arrow@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(431, 401),
		imageId = sheetIds[1],
	},
	["ic-expand"] = {
		name = "ic-expand",
		filename = "Icon/others/ic-expand.png",
		imageRectSize = Vector2.new(28, 28),
		imageRectOffset = Vector2.new(421, 31),
		imageId = sheetIds[1],
	},
	["ic-expand@2x"] = {
		name = "ic-expand@2x",
		filename = "Icon/others/ic-expand@2x.png",
		imageRectSize = Vector2.new(56, 56),
		imageRectOffset = Vector2.new(1799, 127),
		imageId = sheetIds[1],
	},
	["ic-expand@3x"] = {
		name = "ic-expand@3x",
		filename = "Icon/others/ic-expand@3x.png",
		imageRectSize = Vector2.new(84, 84),
		imageRectOffset = Vector2.new(173, 401),
		imageId = sheetIds[1],
	},

}

if Flags:GetFlag("AvatarEditorWhiteLineFix") then
	sprites["btn-toggle@3x"] = {
		name = "btn-toggle@3x",
		filename = "graphic/switch/btn-toggle@3x.png",
		imageRectSize = Vector2.new(74.9, 72),
		imageRectOffset = Vector2.new(1, 315),
		imageId = sheetIds[1],
	}
end

--
-- api
local guiService = game:GetService'GuiService'

local function getDescendants(obj, t)
	t = t or {}
	for _, v in next, obj:GetChildren() do
		table.insert(t, v)
		getDescendants(v, t)
	end
	return t
end

local this = {}
this.enabled = true
this.all = function()
	return sprites
end
this.info = function(name)
	return sprites[name]
end
this.getScale = function()
	return SIMULATE_RESOLUTION_SCALE or guiService:GetResolutionScale()
end
this.equipDescendants = function(gui, name)
	for _, obj in next, getDescendants(gui) do
		if obj.Name == 'SpriteName'
			and obj.ClassName == 'StringValue'
			and obj.Parent
			and not obj.Parent:FindFirstChild'DontMagicallyAssignToSpriteSheet' then
			this.equip(obj.Parent, obj.Value)

			if obj.Parent:FindFirstChild'SpriteIsReversed' then
				obj.Parent.ImageRectOffset = obj.Parent.ImageRectOffset + Vector2.new(obj.Parent.ImageRectSize.x, 0)
				obj.Parent.ImageRectSize = obj.Parent.ImageRectSize * Vector2.new(-1, 1)
			end
		end
	end
end
this.equip = function(gui, name, doNotMutateSprite)
	if not doNotMutateSprite and not gui:FindFirstChild'DoNotMutateSprite' then
		pcall(function()
			local tryMutation = function(n)
				local scaleName = name..'@'..n..'x'
				if sprites[scaleName] then
					if gui.SliceCenter ~= Rect.new() then
						gui.SliceCenter = Rect.new(
							gui.SliceCenter.Min.x*n, gui.SliceCenter.Min.y*n,
							gui.SliceCenter.Max.x*n, gui.SliceCenter.Max.y*n
						)
					end

					return scaleName
				end
			end

			local resScale = this.getScale()
			if resScale > 2 then
				name = tryMutation(3) or tryMutation(2) or name
			elseif resScale > 1 then
				name = tryMutation(2) or name
			end
		end)
	end

	if sprites[name] then
		local content = sprites[name].imageId

		gui.ImageRectSize = sprites[name].imageRectSize
		gui.ImageRectOffset = sprites[name].imageRectOffset
		gui.Image = content
	else
		warn('BAD SPRITE NAME: "'..tostring(name)..'".  Tried to equip to '..gui:GetFullName())
		gui.ImageRectSize = Vector2.new(0, 0)
		gui.ImageRectOffset = Vector2.new(0, 0)
		gui.Image = 'rbxasset://textures/ui/ErrorIcon.png'
	end
end

return this