--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["ReactDebugTools"]["ReactDebugTools"])

export type HooksNode = Package.HooksNode
export type HooksTree = Package.HooksTree
-- ROBLOX deviation END


return Package
