-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.Selection = require(script.Parent.Selection)
var0.TransformHandlesImplementation = require(script.Parent.TransformHandlesImplementation)
var0.getSelectionBoxComponent = require(script.Parent.getSelectionBoxComponent)
var0.HoverEscapeDetector = require(script.Parent.HoverEscapeDetector)
var0.getMouseTarget = require(script.Parent.getMouseTarget)
var0.setHover = require(script.Parent.setHover)
var0.setActivePoint = require(script.Parent.setActivePoint)
var0.isExclusiveSelectable = require(script.Parent.isExclusiveSelectable)
var0.dispatchWorldClick = require(script.Parent.dispatchWorldClick)
var0.getNextSelectables = require(script.Parent.getNextSelectables)
var0.getSelectableWithCache = require(script.Parent.getSelectableWithCache)
var0.beginBoxSelect = require(script.Parent.beginBoxSelect)
var0.endBoxSelect = require(script.Parent.endBoxSelect)
var0.BoundsChangedTracker = require(script.Parent.BoundsChangedTracker)
var0.SelectionInfo = require(script.Parent.SelectionInfo)
var0.addUndoWaypoint = require(script.Parent.addUndoWaypoint)
return var0
