--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["JestFakeTimers-edcba0e9-3.5.0"]["JestFakeTimers"])

export type FakeTimers = Package.FakeTimers


return Package
