--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["Otter-b29e22b0-fff3ac76"]["Otter"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package