-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("TerrainEditor")
local var15 = {}
var15.addUndoWaypoint = require(script.addUndoWaypoint)
var15.dispatchWorldClick = require(script.dispatchWorldClick)
var15.endBoxSelect = require(script.endBoxSelect)
var15.getNextSelectables = require(script.getNextSelectables)
var15.isExclusiveSelectable = require(script.isExclusiveSelectable)
var15.ExtrudeHandlesImplementation = require(script.ExtrudeHandlesImplementation)
var15.getMouseTarget = require(script.getMouseTarget)
var15.Selection = require(script.Selection)
var15.SelectionInfo = require(script.SelectionInfo)
var15.TransformHandlesImplementation = require(script.TransformHandlesImplementation)
var15.updateBoxSelect = require(script.updateBoxSelect)
return require(var0.Packages.Dash).join(require(var0.Packages.DraggerSchemaTemplate.DraggerSchema), var15)
