return {
	-- Common
	UIBlox = require(script.UIBlox),
	isSubjectToDesktopPolicies = require(script.isSubjectToDesktopPolicies),

	-- Ecosystems
	getFFlagUseVerifiedBadgeExperienceModal = require(script.getFFlagUseVerifiedBadgeExperienceModal),
	getFFlagVBDuarFix = require(script.getFFlagVBDuarFix),
	getFFlagVBXboxReducerFix = require(script.getFFlagVBXboxReducerFix),
	getFFlagDecoupleNavigationFromVerifiedBadgeModal = require(script.getFFlagDecoupleNavigationFromVerifiedBadgeModal),
	getFFlagFetchSponsoredEventsOnMorePage = require(script.getFFlagFetchSponsoredEventsOnMorePage),
	getFFlagEnableVirtualEvents = require(script.getFFlagEnableVirtualEvents),

	-- LuaApp
	getFFlagLuaProfileShareWithDesktopPolicy = require(script.getFFlagLuaProfileShareWithDesktopPolicy),
	GetFFlagEnableSwapToSourceButton = require(script.GetFFlagEnableSwapToSourceButton),
	FFlagDesktopLaunchLinksInExternalBrowser = require(script.FFlagDesktopLaunchLinksInExternalBrowser),
	GetFFlagLuaAppUseOmniRecDefaultPolicy = require(script.GetFFlagLuaAppUseOmniRecDefaultPolicy),
	ConvertUniverseIdToString = require(script.ConvertUniverseIdToString),

	-- VR
	GetFFlagDeactivateThrottleInVR = require(script.GetFFlagDeactivateThrottleInVR),
	GetFFlagRoundedCornersVR = require(script.GetFFlagRoundedCornersVR),
	GetFFlagAvatarEditorMaquettes = require(script.GetFFlagAvatarEditorMaquettes),

	-- Social
	GetRemoveLuaChatOpenGameDetailsPageThunkDep = require(script.GetRemoveLuaChatOpenGameDetailsPageThunkDep),

	-- Misc
	FFlagLuaAppFixMessageBusUnsubscribe = require(script.FFlagLuaAppFixMessageBusUnsubscribe),
	FFlagAXCatalogSearchSizeGamepad = require(script.FFlagAXCatalogSearchSizeGamepad),
	FFlagCatalogRecommendationsV2RolloutEnabledForAll = require(script.FFlagCatalogRecommendationsV2RolloutEnabledForAll),
	GetEnableCatalogRecommendationsV2 = require(script.GetEnableCatalogRecommendationsV2),
	GetFFlagEnableCatalogRecommendationsV2 = require(script.GetFFlagEnableCatalogRecommendationsV2),
	GetFFlagAvatarEditorServiceInUniversalApp = require(script.GetFFlagAvatarEditorServiceInUniversalApp),
	GetEngineFeatureIxpUserAppLayersPrefetchEnabled = require(script.GetEngineFeatureIxpUserAppLayersPrefetchEnabled),
	GetFFlagEnableUnifiedWebViews = require(script.GetFFlagEnableUnifiedWebViews),
	GetFFlagEnableVRWelcomePanel = require(script.GetFFlagEnableVRWelcomePanel),
	GetFFlagIsVRSkyboxStatic = require(script.GetFFlagIsVRSkyboxStatic),
	GetFFlagSkipRedundantVoiceCheck = require(script.GetFFlagSkipRedundantVoiceCheck),
	GetFFlagVRAppScreenSize = require(script.GetFFlagVRAppScreenSize),
	GetFStringLoadingScreenIxpLayer = require(script.GetFStringLoadingScreenIxpLayer),
	GetFStringRobuxUpsellIxpLayer = require(script.GetFStringRobuxUpsellIxpLayer),
	GetFStringLargerRobuxUpsellIxpLayer = require(script.GetFStringLargerRobuxUpsellIxpLayer),
	getFFlagAutoSyncForContactImporterDisabled = require(script.getFFlagAutoSyncForContactImporterDisabled),
	getFFlagChatUserDeepLinkEnabled = require(script.getFFlagChatUserDeepLinkEnabled),
	getFFlagContactImporterEnabledForDev = require(script.getFFlagContactImporterEnabledForDev),
	getFFlagContactImporterWithPhoneVerification = require(script.getFFlagContactImporterWithPhoneVerification),
	getFFlagFixLearnMoreLinkViaSocialTab = require(script.getFFlagFixLearnMoreLinkViaSocialTab),
	getFFlagFriendsCarouselDontUseIngestService = require(script.getFFlagFriendsCarouselDontUseIngestService),
	getFFlagOffNetworkAnalytics = require(script.getFFlagOffNetworkAnalytics),
	getFFlagOffNetworkFriendingEnabled = require(script.getFFlagOffNetworkFriendingEnabled),
	getFFlagPYMKDontUseIngestService = require(script.getFFlagPYMKDontUseIngestService),
	getFFlagProfileRecommendationId = require(script.getFFlagProfileRecommendationId),
	getFFlagPYMKCarouselRecommendationId = require(script.getFFlagPYMKCarouselRecommendationId),
	getFFlagShareLinkDeepLinkEnabled = require(script.getFFlagShareLinkDeepLinkEnabled),
	getFFlagSocialAddFriendshipRequestEvent = require(script.getFFlagSocialAddFriendshipRequestEvent),
	getFFlagSocialPanelIAEnabled = require(script.GetFFlagSocialPanelIAEnabled),
	getFFlagSocialAddMessageModal = require(script.getFFlagSocialAddMessageModal),
	getFFlagSocialPresenceEventReceiver = require(script.getFFlagSocialPresenceEventReceiver),
	getFFlagSocialProfileShareAnalyticsEnabled = require(script.getFFlagSocialProfileShareAnalyticsEnabled),
	getFFlagSocialTabRemoveIsEnabled = require(script.getFFlagSocialTabRemoveIsEnabled),
	getFFlagSoothsayerCheckForContactImporter = require(script.getFFlagSoothsayerCheckForContactImporter),
	getFStringSocialFriendsLayer = require(script.getFStringSocialFriendsLayer),
	getFFlagContactImporterOnFriendsCarousel = require(script.getFFlagContactImporterOnFriendsCarousel),
	getFFlagMigrateSocialNetworking = require(script.getFFlagMigrateSocialNetworking),
	GetEnableDesignSystemExperiment = require(script.GetEnableDesignSystemExperiment),
	GetFFlagDisableBubbleChatForExpChat = require(script.GetFFlagDisableBubbleChatForExpChat),
	GetFFlagShareGetPlatformTargetImpl = require(script.GetFFlagShareGetPlatformTargetImpl),
	GetFFlagUpgradeExpChatV3_3_1 = require(script.GetFFlagUpgradeExpChatV3_3_1),
	GetEnableFriendFooterOnHomePage = require(script.GetEnableFriendFooterOnHomePage),
	GetFFlagLuaAppAddSignalToFocusArea = require(script.GetFFlagLuaAppAddSignalToFocusArea),
	GetFFlagLuaAppUseUIBloxColorPalettes = require(script.GetFFlagLuaAppUseUIBloxColorPalettes),
	isNewFriendsEndpointsEnabled = require(script.isNewFriendsEndpointsEnabled),
	GetFFlagCleanUpIsSubjectToDesktopPolicies = require(script.GetFFlagCleanUpIsSubjectToDesktopPolicies),
	GetFFlagUseCorrectedFriendSortUtil = require(script.GetFFlagUseCorrectedFriendSortUtil),
	GetFFlagPeekViewDeprecateFitChildren = require(script.GetFFlagPeekViewDeprecateFitChildren),
	getFFlagPYMKCarouselRenameOmniSessionId = require(script.getFFlagPYMKCarouselRenameOmniSessionId)
}
