return {
	-- Ecosystems
	getFFlagUseVerifiedBadgeExperienceModal = require(script.getFFlagUseVerifiedBadgeExperienceModal),
	getFFlagVBDuarFix = require(script.getFFlagVBDuarFix),
	getFFlagVBXboxReducerFix = require(script.getFFlagVBXboxReducerFix),
	getFFlagDecoupleNavigationFromVerifiedBadgeModal = require(script.getFFlagDecoupleNavigationFromVerifiedBadgeModal),
	getFFlagFetchSponsoredEventsOnMorePage = require(script.getFFlagFetchSponsoredEventsOnMorePage),
	getFFlagEnableVirtualEvents = require(script.getFFlagEnableVirtualEvents),

	UIBlox = require(script.UIBlox),
	FFlagLuaAppFixMessageBusUnsubscribe = require(script.FFlagLuaAppFixMessageBusUnsubscribe),
	FFlagRoactGamepadFixDelayedRefFocusLost = require(script.FFlagRoactGamepadFixDelayedRefFocusLost),
	GetEngineFeatureIxpUserAppLayersPrefetchEnabled = require(script.GetEngineFeatureIxpUserAppLayersPrefetchEnabled),
	GetFFlagEnableUnifiedWebViews = require(script.GetFFlagEnableUnifiedWebViews),
	GetFFlagEnableVRWelcomePanel = require(script.GetFFlagEnableVRWelcomePanel),
	GetFFlagIsVRSkyboxStatic = require(script.GetFFlagIsVRSkyboxStatic),
	GetFFlagSkipRedundantVoiceCheck = require(script.GetFFlagSkipRedundantVoiceCheck),
	GetFFlagVRAppScreenSize = require(script.GetFFlagVRAppScreenSize),
	GetFStringLoadingScreenIxpLayer = require(script.GetFStringLoadingScreenIxpLayer),
	GetFStringRobuxUpsellIxpLayer = require(script.GetFStringRobuxUpsellIxpLayer),
	getFFlagAutoSyncForContactImporterDisabled = require(script.getFFlagAutoSyncForContactImporterDisabled),
	getFFlagChatUserDeepLinkEnabled = require(script.getFFlagChatUserDeepLinkEnabled),
	getFFlagContactImporterEnabledForDev = require(script.getFFlagContactImporterEnabledForDev),
	getFFlagContactImporterWithPhoneVerification = require(script.getFFlagContactImporterWithPhoneVerification),
	getFFlagFixLearnMoreLinkViaSocialTab = require(script.getFFlagFixLearnMoreLinkViaSocialTab),
	getFFlagFriendsCarouselDontUseIngestService = require(script.getFFlagFriendsCarouselDontUseIngestService),
	getFFlagFriendsCarouselLegacyCarouselReport = require(script.getFFlagFriendsCarouselLegacyCarouselReport),
	getFFlagOffNetworkAnalytics = require(script.getFFlagOffNetworkAnalytics),
	getFFlagOffNetworkFriendingEnabled = require(script.getFFlagOffNetworkFriendingEnabled),
	getFFlagPYMKDontUseIngestService = require(script.getFFlagPYMKDontUseIngestService),
	getFFlagProfileRecommendationId = require(script.getFFlagProfileRecommendationId),
	getFFlagPYMKCarouselRecommendationId = require(script.getFFlagPYMKCarouselRecommendationId),
	getFFlagShareLinkDeepLinkEnabled = require(script.getFFlagShareLinkDeepLinkEnabled),
	getFFlagSocialAddFriendshipRequestEvent = require(script.getFFlagSocialAddFriendshipRequestEvent),
	getFFlagSocialPanelIAEnabled = require(script.GetFFlagSocialPanelIAEnabled),
	getFFlagSocialAddMessageModal = require(script.getFFlagSocialAddMessageModal),
	getFFlagSocialPresenceEventReceiver = require(script.getFFlagSocialPresenceEventReceiver),
	getFFlagSocialProfileShareAnalyticsEnabled = require(script.getFFlagSocialProfileShareAnalyticsEnabled),
	getFFlagSocialTabRemoveIsEnabled = require(script.getFFlagSocialTabRemoveIsEnabled),
	getFFlagSoothsayerCheckForContactImporter = require(script.getFFlagSoothsayerCheckForContactImporter),
	getFStringSocialFriendsLayer = require(script.getFStringSocialFriendsLayer),
	getFFlagContactImporterOnFriendsCarousel = require(script.getFFlagContactImporterOnFriendsCarousel),
	GetEnableDesignSystemExperiment = require(script.GetEnableDesignSystemExperiment),
}
