-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("AnimationClipEditor")
local var1 = require(var0.Packages.Roact)
local var2 = require(var0.Packages.Framework)
local var3 = var2.UI.RadioButtonList
local var4 = var2.ContextServices
local var5 = require(var0.Src.Util.Constants)
local var6 = var1.PureComponent:extend("IKModeButtons")
local function fun0(arg1)
   local var0 = arg1.props.Localization
   local var1 = arg1.props
   local var2 = var1.Stylizer
   local var82 = {}
   var82.Size = UDim2.new(1, 0, 0, var1.Height)
   var82.BackgroundColor3 = var2.ikTheme.headerColor
   var82.BorderSizePixel = 1
   var82.BorderColor3 = var2.ikTheme.headerBorder
   var82.LayoutOrder = var1.LayoutOrder
   local var94 = {}
   local var98 = {}
   var98.AnchorPoint = Vector2.new(0, 0.5)
   var98.Position = UDim2.new(0, 0, 0.5, 0)
   var98.Size = UDim2.new(0, 64, 0, var5.TRACK_HEIGHT)
   var98.BackgroundTransparency = 1
   var98.TextSize = var2.ikTheme.textSize
   var98.Font = var2.font
   var98.TextColor3 = var2.ikTheme.textColor
   var98.TextXAlignment = Enum.TextXAlignment.Center
   var98.TextYAlignment = Enum.TextYAlignment.Center
   var98.Text = var0:getText("IKMenu", "IKMode")
   var98.LayoutOrder = 0
   var94.IKModeLabel = var1.createElement("TextLabel", var98)
   local var133 = {}
   var133.BackgroundTransparency = 1
   var133.AnchorPoint = Vector2.new(1, 0.5)
   var133.Position = UDim2.new(1, 0, 0.5, 0)
   var133.Size = UDim2.new(0, 186, 0.5, 0)
   var133.LayoutOrder = 1
   local var152 = {}
   local var156 = {}
   local var3 = {}
   var3.Key = var5.IK_MODE.BodyPart
   var3.Text = var0:getText("IKMenu", "BodyPart")
   local var4 = {}
   var4.Key = var5.IK_MODE.FullBody
   var4.Text = var0:getText("IKMenu", "FullBody")
   var156.Buttons = {}
   var156.SelectedKey = var1.IKMode
   var156.FillDirection = Enum.FillDirection.Horizontal
   var156.LayoutOrder = 1
   var156.OnClick = var1.SetIKMode
   var152.RadioButtons = var1.createElement(var3, var156)
   var94.RadioButtonsFrame = var1.createElement("Frame", var133, var152)
   return var1.createElement("Frame", var82, var94)
end

function var6.render(arg1)
   local var0 = arg1.props.Localization
   local var1 = arg1.props
   local var2 = var1.Stylizer
   local var82 = {}
   var82.Size = UDim2.new(1, 0, 0, var1.Height)
   var82.BackgroundColor3 = var2.ikTheme.headerColor
   var82.BorderSizePixel = 1
   var82.BorderColor3 = var2.ikTheme.headerBorder
   var82.LayoutOrder = var1.LayoutOrder
   local var94 = {}
   local var98 = {}
   var98.AnchorPoint = Vector2.new(0, 0.5)
   var98.Position = UDim2.new(0, 0, 0.5, 0)
   var98.Size = UDim2.new(0, 64, 0, var5.TRACK_HEIGHT)
   var98.BackgroundTransparency = 1
   var98.TextSize = var2.ikTheme.textSize
   var98.Font = var2.font
   var98.TextColor3 = var2.ikTheme.textColor
   var98.TextXAlignment = Enum.TextXAlignment.Center
   var98.TextYAlignment = Enum.TextYAlignment.Center
   var98.Text = var0:getText("IKMenu", "IKMode")
   var98.LayoutOrder = 0
   var94.IKModeLabel = var1.createElement("TextLabel", var98)
   local var133 = {}
   var133.BackgroundTransparency = 1
   var133.AnchorPoint = Vector2.new(1, 0.5)
   var133.Position = UDim2.new(1, 0, 0.5, 0)
   var133.Size = UDim2.new(0, 186, 0.5, 0)
   var133.LayoutOrder = 1
   local var152 = {}
   local var156 = {}
   local var3 = {}
   var3.Key = var5.IK_MODE.BodyPart
   var3.Text = var0:getText("IKMenu", "BodyPart")
   local var4 = {}
   var4.Key = var5.IK_MODE.FullBody
   var4.Text = var0:getText("IKMenu", "FullBody")
   var156.Buttons = {}
   var156.SelectedKey = var1.IKMode
   var156.FillDirection = Enum.FillDirection.Horizontal
   var156.LayoutOrder = 1
   var156.OnClick = var1.SetIKMode
   var152.RadioButtons = var1.createElement(var3, var156)
   var94.RadioButtonsFrame = var1.createElement("Frame", var133, var152)
   return var1.createElement("Frame", var82, var94)
end

fun0 = var4.withContext
local var179 = {}
var179.Stylizer = var4.Stylizer
var179.Localization = var4.Localization
var6 = fun0(var179)(var6)
return var6
