local OverflowScrollContainer = require(script.OverflowScrollContainer)

export type OverflowScrollContainerProps = OverflowScrollContainer.OverflowScrollContainerProps

return OverflowScrollContainer
