#version 150
#extension GL_ARB_compute_shader : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

#extension GL_ARB_shading_language_include : require
#include <ElementData.h>
layout(std430) readonly buffer DstIndices
{
    uint _data[];
} DstIndicesc0;

layout(std430) buffer DstData
{
    ElementData _data[];
} DstDatac0;

layout(std430) readonly buffer SrcData
{
    ElementData _data[];
} SrcDatac0;

void main()
{
    if (DstIndicesc0._data[gl_GlobalInvocationID.x] != 4294967295u)
    {
        DstDatac0._data[DstIndicesc0._data[gl_GlobalInvocationID.x]] = SrcDatac0._data[gl_GlobalInvocationID.x];
    }
}

