local FFlagInspectAndBuyLayeredClothingSupport = require(script.Parent.FFlagInspectAndBuyLayeredClothingSupport)

return FFlagInspectAndBuyLayeredClothingSupport and game:DefineFastFlag("InspectAndBuyLayeredClothingR6Support", false)