--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["ES7Types"]["ES7Types"])

export type Object = Package.Object
export type Array<T> = Package.Array<T> 
export type Function = Package.Function
export type Table<T, V> = Package.Table<T, V> 
export type Tuple<T, V> = Package.Tuple<T, V> 
export type mapCallbackFn<K, V> = Package.mapCallbackFn<K, V> 
export type mapCallbackFnWithThisArg<K, V> = Package.mapCallbackFnWithThisArg<K, V> 
export type Map<K, V> = Package.Map<K, V> 
export type WeakMap<K, V> = Package.WeakMap<K, V> 
export type setCallbackFn<T> = Package.setCallbackFn<T> 
export type setCallbackFnWithThisArg<T> = Package.setCallbackFnWithThisArg<T> 
export type Set<T> = Package.Set<T> 


return Package
