--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["Path-3.8.0"]["Path"])

export type Path = Package.Path


return Package
