-- Auto-generated by service-contracts. DO NOT EDIT MANUALLY.

local proto = require(script.Parent.Parent.Parent.Parent.proto)
export type Descriptor = proto.Descriptor
export type Message<T, Fields> = proto.Package<T, Fields>
export type CustomJson<T, Json> = proto.CustomJson<T, Json>
export type TypeRegistry = proto.TypeRegistry

local template_api_messages = require(script.template_api_messages)

-- Exported types
export type DisplayLocationTemplateMapping = template_api_messages.DisplayLocationTemplateMapping
export type GetTemplatesRequest = template_api_messages.GetTemplatesRequest
export type GetTemplatesResponse = template_api_messages.GetTemplatesResponse

return {
	template_api_messages = template_api_messages,
}
