-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.TESTING = true
var0.UNIMPLEMENTED_WARNING = "Unfortunately this feature is not active yet!"
var0.OPERATION_SUCCESSFUL = "This operation was successful!"
local var4 = {}
var4.Navigation = 1
var4.NameBox = 2
var4.View = 3
var4.ConfirmationButtons = 5
var0.INPUT_PANE_LAYOUT = var4
local var9 = {}
var9.Warning = 1
var9.Namespace = 2
var9.Detail = 3
var9.DetailType = 4
var0.RBXEVENT_ORDER = var9
local var14 = {}
var14.Switch = 1
var14.Key = 2
var14.Value = 3
var0.MEM_STORAGE_ORDER = var14
local var18 = {}
var18.RBXEvent = 1
var18.Theme = 2
var18.MemStorage = 3
var0.VIEW_ORDER = var18
local var22 = {}
var22.InputPane = 1
var22.History = 2
var0.APP_ORDER = var22
local var25 = {}
var25.RBXEvent = "RBXEvent"
var25.MemStorage = "MemStorage"
var0.VIEW_ID = var25
local var7 = {}
local var8 = {}
var8.GetValue = "Get Value"
var8.SetValue = "Set Value"
var8.NewEntry = "New Entry"
var7.MemStorage = var8
var0.ROUTES = var7
return var0
