--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["Fetch"]["Fetch"])

export type Headers = Package.Headers
export type HeadersInit = Package.HeadersInit
export type Request = Package.Request
export type RequestInit = Package.RequestInit
export type Response = Package.Response
export type ResponseInit = Package.ResponseInit
export type Body = Package.Body
export type BodyInit = Package.BodyInit
export type AbortSignal = Package.AbortSignal


return Package
