return {
	GetFFlagUIBloxEnableGenericButtonHoverBackgroundFix = require(
		script.GetFFlagUIBloxEnableGenericButtonHoverBackgroundFix
	),
	GetFFlagUIBloxUseNewGenericTextLabelProps = require(script.GetFFlagUIBloxUseNewGenericTextLabelProps),
	GetUIBloxUseNewThemeColorPalettes = require(script.GetUIBloxUseNewThemeColorPalettes),
	GetFFlagUIBloxBindAllLaserPointerButtons = require(script.GetFFlagUIBloxBindAllLaserPointerButtons),
	GetFFlagUIBloxRemovePreviewAnchor = require(script.GetFFlagUIBloxRemovePreviewAnchor),
	GetFFlagUIBloxEnableMediaGalleryUpdate = require(script.GetFFlagUIBloxEnableMediaGalleryUpdate),
	GetFFlagUIBloxEnableCollectibleItemRestriction = require(script.GetFFlagUIBloxEnableCollectibleItemRestriction),
	GetFFlagUIBloxUseRightSideGadget = require(script.GetFFlagUIBloxUseRightSideGadget),
	GetFFlagUIBloxPillGroupAutomaticSize = require(script.GetFFlagUIBloxPillGroupAutomaticSize),
	GetFFlagUIBloxLoadableImageResponsiveThumbnails = require(script.GetFFlagUIBloxLoadableImageResponsiveThumbnails),
	GetFFlagUIBloxVRAlignPanel3DUnderInGamePanel = require(script.GetFFlagUIBloxVRAlignPanel3DUnderInGamePanel),
	GetFFlagUIBloxEnableRoDSDesignTokenSupport = require(script.GetFFlagUIBloxEnableRoDSDesignTokenSupport),
	GetFFlagUIBloxEnableTileOverlayFix = require(script.GetFFlagUIBloxEnableTileOverlayFix),
	GetFFlagUIBloxPillGroupUseSelectedPills = require(script.GetFFlagUIBloxPillGroupUseSelectedPills),
}
