[package]
name = "RoduxNetworking"
version = "3.4.1"
readme = "README.md"
content_root = "src"
files = ["*"]
publish = true
authors = ["Benjamin Brimeyer"]
[dependencies.Cryo]
target = "https://github.com/roblox/cryo"
version = "^1.0"

[dependencies.Promise]
target = "https://github.com/roblox/roblox-lua-promise"
version = "^3.2.1"

[dependencies.Rodux]
target = "https://github.com/roblox/rodux"
version = "^3.2.0"

[dependencies.tutils]
target = "https://github.com/roblox/tutils"
version = "^0.1.2"
[dev_dependencies.Mock]
git = "https://github.com/roblox/mock"
rev = "master"

[dev_dependencies.TestEZ]
target = "https://github.com/roblox/testez"
version = "^0.4.0"
