[package]
name = "RbxDesignFoundations"
version = "4.0.11"
readme = "README.md"
content_root = "lib"
files = ["*"]
publish = true
authors = ["Roblox"]
[dev_dependencies.Jest]
version = "^3.12.0"

[dev_dependencies.JestGlobals]
version = "^3.12.0"
