-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
local var1 = {}
var1.Cancel = "Cancel"
var1.Pause = "Pause"
var1.Resume = "Resume"
var0.DialogOption = var1
local var2 = {}
var2.Gizmo = "Gizmo"
var2.History = "History"
var0.OperationSource = var2
local var3 = {}
var3.Apply = "Apply"
var3.CopySelected = "CopySelected"
var3.CutSelected = "CutSelected"
var3.DeleteSelected = "DeleteSelected"
var3.DuplicateSelected = "DuplicateSelected"
var3.EditPlane = "EditPlane"
var3.PasteSelected = "PasteSelected"
var3.Quit = "Quit"
var0.PluginAction = var3
local var4 = {}
var4.Duplicate = "Duplicate"
var4.Import = "Import"
var4.Move = "Move"
var4.Paste = "Paste"
var4.Stamp = "Stamp"
var0.TransformMode = var4
return var0
