-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
local var1 = {}
local var2 = {}
var2.Add = "Add"
var2.Subtract = "Subtract"
var1.BrushMode = "BrushMode"
var0.BrushMode = var2
local var3 = {}
var3.Sphere = "Sphere"
var3.Cube = "Cube"
var3.Cylinder = "Cylinder"
var1.BrushShape = "BrushShape"
var0.BrushShape = var3
local var4 = {}
var4.Fill = "Fill"
var4.Replace = "Replace"
var1.FillMode = "FillMode"
var0.FillMode = var4
local var5 = {}
var5.Erode = "Erode"
var5.Grow = "Grow"
var5.Both = "Both"
var1.FlattenMode = "FlattenMode"
var0.FlattenMode = var5
local var6 = {}
var6.Auto = "Auto"
var6.Fixed = "Fixed"
var1.FlattenPlane = "FlattenPlane"
var0.FlattenPlane = var6
local var7 = {}
var7.Bottom = "Bottom"
var7.Center = "Center"
var7.Top = "Top"
var1.PivotPosition = "PivotPosition"
var0.PivotPosition = var7
local var8 = {}
var8.Auto = "Auto"
var8.Off = "Off"
var8.Manual = "Manual"
var1.PlaneLock = "PlaneLock"
var0.PlaneLock = var8
local var9 = {}
var9.Paint = "Paint"
var9.Replace = "Replace"
var1.MaterialMode = "MaterialMode"
var0.MaterialMode = var9
local var10 = {}
var10.BrushSize = "BrushSize"
var10.Off = "Off"
var10.Voxel = "Voxel"
var1.Snapping = "Snapping"
var0.Snapping = var10
local var11 = {}
local var55 = var2.Add
local var56 = var2.Subtract
var1.BrushMode = {}
local var59 = var3.Sphere
local var60 = var3.Cube
local var61 = var3.Cylinder
var1.BrushShape = {}
local var64 = var4.Fill
local var65 = var4.Replace
var1.FillMode = {}
local var68 = var6.Auto
local var69 = var6.Fixed
var1.FlattenPlane = {}
local var72 = var5.Erode
local var73 = var5.Grow
local var74 = var5.Both
var1.FlattenMode = {}
local var77 = var7.Bottom
local var78 = var7.Center
local var79 = var7.Top
var1.PivotPosition = {}
local var82 = var8.Off
local var83 = var8.Auto
local var84 = var8.Manual
var1.PlaneLock = {}
local var87 = var9.Paint
local var88 = var9.Replace
var1.MaterialMode = {}
local var89 = var1.Snapping
local var91 = var10.Off
local var34 = var10.Voxel
var1.Snapping = {}
var89 = require(script:FindFirstAncestor("TerrainEditor").Src.Flags.getFFlagTerrainEditorBrushSizeSnapping)
local var35 = var89()
if var35 then
   table.insert(var11[var1.Snapping], var10.BrushSize)
end
var35 = var0
local var36 = nil
local var37 = nil
assert(var11[var34], `Expected editor enum index for {var34}`)
local var38 = var10.BrushSize
local var39 = nil
local var40 = nil
assert(table.find(var11[var34], var113), `Expected index for enum value {var34}`)
var0.EnumTypeIndices = var11
var0.EnumType = var1
return var0
