-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
local var1 = {}
local var2 = {}
var2.Add = "Add"
var2.Subtract = "Subtract"
var1.BrushMode = "BrushMode"
var0.BrushMode = var2
local var3 = {}
var3.Sphere = "Sphere"
var3.Cube = "Cube"
var3.Cylinder = "Cylinder"
var1.BrushShape = "BrushShape"
var0.BrushShape = var3
local var4 = {}
var4.Fill = "Fill"
var4.Replace = "Replace"
var1.FillMode = "FillMode"
var0.FillMode = var4
local var5 = {}
var5.Erode = "Erode"
var5.Grow = "Grow"
var5.Both = "Both"
var1.FlattenMode = "FlattenMode"
var0.FlattenMode = var5
local var6 = {}
var6.Auto = "Auto"
var6.Fixed = "Fixed"
var1.FlattenPlane = "FlattenPlane"
var0.FlattenPlane = var6
local var7 = {}
var7.Bottom = "Bottom"
var7.Center = "Center"
var7.Top = "Top"
var1.PivotPosition = "PivotPosition"
var0.PivotPosition = var7
local var8 = {}
var8.Auto = "Auto"
var8.Off = "Off"
var8.Manual = "Manual"
var1.PlaneLock = "PlaneLock"
var0.PlaneLock = var8
local var9 = {}
var9.Paint = "Paint"
var9.Replace = "Replace"
var1.MaterialMode = "MaterialMode"
var0.MaterialMode = var9
local var10 = {}
var10.Stud = "Stud"
var10.Percentage = "Percentage"
var1.MaterialUnit = "MaterialUnit"
var0.MaterialUnit = var10
local var11 = {}
var11.Off = "Off"
var11.Voxel = "Voxel"
var1.Snapping = "Snapping"
var0.Snapping = var11
local var12 = {}
var12.Arctic = "Arctic"
var12.Crater = "Crater"
var12.Desert = "Desert"
var12.Lake = "Lake"
var12.Mesa = "Mesa"
var12.Mountain = "Mountain"
var12.Plain = "Plain"
var12.Volcano = "Volcano"
var12.None = "None"
var1.TerrainType = "TerrainType"
var0.TerrainType = var12
local var13 = {}
local var60 = var2.Add
local var61 = var2.Subtract
var1.BrushMode = {}
local var64 = var3.Sphere
local var65 = var3.Cube
local var66 = var3.Cylinder
var1.BrushShape = {}
local var69 = var4.Fill
local var70 = var4.Replace
var1.FillMode = {}
local var73 = var6.Auto
local var74 = var6.Fixed
var1.FlattenPlane = {}
local var77 = var5.Erode
local var78 = var5.Grow
local var79 = var5.Both
var1.FlattenMode = {}
local var82 = var7.Bottom
local var83 = var7.Center
local var84 = var7.Top
var1.PivotPosition = {}
local var87 = var8.Off
local var88 = var8.Auto
local var89 = var8.Manual
var1.PlaneLock = {}
local var92 = var9.Paint
local var93 = var9.Replace
var1.MaterialMode = {}
local var96 = var10.Stud
local var97 = var10.Percentage
var1.MaterialUnit = {}
local var100 = var11.Off
local var101 = var11.Voxel
var1.Snapping = {}
local var38 = var1.TerrainType
local var104 = var12.Plain
local var40 = var12.Arctic
local var107 = var12.Mountain
local var108 = var12.Volcano
local var109 = var12.Mesa
local var110 = var12.Crater
local var112 = var12.None
var1.TerrainType = {}
var38 = var0
local var46 = nil
local var47 = nil
var112 = var40
var109 = `Expected editor enum index for {var12.Lake}`
assert(var13[var40], var109)
local var48 = var12.Desert
local var49 = nil
local var50 = nil
assert(table.find(var13[var40], var125), `Expected index for enum value {var40}`)
var0.EnumTypeIndices = var13
var0.EnumType = var1
return var0
