-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("TerrainEditor")
local var1 = require(var0.Src.Types.Generation)
local var2 = require(var0.Src.Types.PublicEnums)
local var3 = require(var0.Src.Types.PrivateEnums)
local var4 = require(var0.Src.Types.Tools)
local var5 = {}
local var6 = {}
var5.Category = var6
local var7 = {}
var7.Biomes = "Biomes"
var7.BiomeBlending = "BiomeBlending"
var7.BiomeSize = "BiomeSize"
var7.Caves = "Caves"
var7.Seed = "Seed"
var7.Generate = "Generate"
var5.BiomeSettings = var7
var6.BiomeSettings = "BiomeSettings"
local var8 = {}
var8.BrushMode = "BrushMode"
var8.BrushSize = "BrushSize"
var8.BrushShape = "BrushShape"
var8.FixedYPlane = "FixedYPlane"
var8.FixedYPlanePosition = "FixedYPlanePosition"
var8.FlattenMode = "FlattenMode"
var8.FlattenPlane = "FlattenPlane"
var8.IgnoreParts = "IgnoreParts"
var8.IgnoreWater = "IgnoreWater"
var8.ManualPlaneLock = "ManualPlaneLock"
var8.PivotPosition = "PivotPosition"
var8.PlaneLock = "PlaneLock"
var8.PlanePosition = "PlanePosition"
var8.PlaneRotation = "PlaneRotation"
var8.PlaneTransform = "PlaneTransform"
var8.PullTerrain = "PullTerrain"
var8.Snapping = "Snapping"
var8.State = "State"
var8.Strength = "Strength"
var8.TemporarySmooth = "TemporarySmooth"
var8.WaterAutofill = "WaterAutofill"
var5.BrushSettings = var8
var6.BrushSettings = "BrushSettings"
local var9 = {}
var9.Unit = "Unit"
var9.Elevation = "Elevation"
var9.Material = "Material"
var9.Slope = "Slope"
var9.FillMaterial = "FillMaterial"
var5.MaterialPresetSettings = var9
var6.MaterialPresetSettings = "MaterialPresetSettings"
local var10 = {}
var10.AdvancedNoise = "AdvancedNoise"
var10.Amplitude = "Amplitude"
var10.BankSize = "BankSize"
var10.BlendingEdge = "BlendingEdge"
var10.Commit = "Commit"
var10.CraterDepth = "CraterDepth"
var10.CraterRadius = "CraterRadius"
var10.FillBottom = "FillBottom"
var10.Frequency = "Frequency"
var10.Material = "Material"
var10.Offset = "Offset"
var10.OperationSource = "OperationSource"
var10.Position = "Position"
var10.RimHeight = "RimHeight"
var10.Seed = "Seed"
var10.Size = "Size"
var10.SnapToVoxels = "SnapToVoxels"
var10.TerrainType = "TerrainType"
var10.TopRadius = "TopRadius"
var10.Transform = "Transform"
var10.WaterLevel = "WaterLevel"
var10.MaterialLUT = "MaterialLUT"
var5.BuildSettings = var10
var6.BuildSettings = "BuildSettings"
local var11 = {}
var11.Clear = "Clear"
var5.ClearSettings = var11
var6.ClearSettings = "ClearSettings"
local var12 = {}
var12.Heightmap = "Heightmap"
var12.Colormap = "Colormap"
var12.DefaultMaterial = "DefaultMaterial"
var12.Import = "Import"
var5.HeightmapSettings = var12
var6.HeightmapSettings = "HeightmapSettings"
local var13 = {}
var13.Apply = "Apply"
var13.AutoMaterial = "AutoMaterial"
var13.FillMode = "FillMode"
var13.MaterialMode = "MaterialMode"
var13.SourceMaterial = "SourceMaterial"
var13.TargetMaterial = "TargetMaterial"
var5.MaterialSettings = var13
var6.MaterialSettings = "MaterialSettings"
local var14 = {}
var14.Create = "Create"
var14.Evaporate = "Evaporate"
var14.OperationSource = "OperationSource"
var14.Position = "Position"
var14.Size = "Size"
var14.SnapToVoxels = "SnapToVoxels"
var14.Transform = "Transform"
var5.SeaLevelSettings = var14
var6.SeaLevelSettings = "SeaLevelSettings"
local var15 = {}
var15.OperationSource = "OperationSource"
var15.Position = "Position"
var15.Rotation = "Rotation"
var15.Size = "Size"
var15.SnapToVoxels = "SnapToVoxels"
var15.Transform = "Transform"
var15.TransformMode = "TransformMode"
var5.SelectionSettings = var15
var6.SelectionSettings = "SelectionSettings"
local var16 = {}
var16.Apply = "Apply"
var16.ForcePreview = "ForcePreview"
var16.LiveEdit = "LiveEdit"
var16.MergeEmpty = "MergeEmpty"
var16.OperationSource = "OperationSource"
var16.Position = "Position"
var16.Rotation = "Rotation"
var16.Size = "Size"
var16.SnapToVoxels = "SnapToVoxels"
var16.TerrainRegion = "TerrainRegion"
var16.TerrainRegionSize = "TerrainRegionSize"
var16.TerrainRegionTransform = "TerrainRegionTransform"
var16.TerrainRegionBuffer = "TerrainRegionBuffer"
var16.TerrainRegionBufferSize = "TerrainRegionBufferSize"
var16.TerrainRegionBufferTransform = "TerrainRegionBufferTransform"
var16.Transform = "Transform"
var16.TransformMode = "TransformMode"
var5.TransformSettings = var16
var6.TransformSettings = "TransformSettings"
local var17 = {}
var17.Shorelines = "Shorelines"
var5.UpgradeSettings = var17
var6.UpgradeSettings = "UpgradeSettings"
local var18 = {}
var18.Brush = "Brush"
var18.Note = "Note"
var18.Plane = "Plane"
var18.Region = "Region"
var5.Gizmo = var18
local var19 = {}
var19.Transform = "Transform"
var5.Note = var19
local var20 = {}
var20.Global = "Global"
var20.LocalPersistent = "LocalPersistent"
var20.LocalSession = "LocalSession"
var5.Storage = var20
return var5
