-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("TerrainEditor")
local var1 = require(var0.Src.Types.Generation)
local var2 = require(var0.Src.Types.PublicEnums)
local var3 = require(var0.Src.Types.PrivateEnums)
local var4 = require(var0.Src.Types.Tools)
local var5 = {}
local var6 = {}
var5.Category = var6
local var7 = {}
var7.Biomes = "Biomes"
var7.BiomeBlending = "BiomeBlending"
var7.BiomeSize = "BiomeSize"
var7.Caves = "Caves"
var7.Seed = "Seed"
var7.Generate = "Generate"
var5.BiomeSettings = var7
var6.BiomeSettings = "BiomeSettings"
local var8 = {}
var8.BrushMode = "BrushMode"
var8.BrushSize = "BrushSize"
var8.BrushShape = "BrushShape"
var8.FixedYPlane = "FixedYPlane"
var8.FixedYPlanePosition = "FixedYPlanePosition"
var8.FlattenMode = "FlattenMode"
var8.FlattenPlane = "FlattenPlane"
var8.IgnoreParts = "IgnoreParts"
var8.IgnoreWater = "IgnoreWater"
var8.ManualPlaneLock = "ManualPlaneLock"
var8.PivotPosition = "PivotPosition"
var8.PlaneLock = "PlaneLock"
var8.PlanePosition = "PlanePosition"
var8.PlaneRotation = "PlaneRotation"
var8.PlaneTransform = "PlaneTransform"
var8.PullTerrain = "PullTerrain"
var8.Snapping = "Snapping"
var8.State = "State"
var8.Strength = "Strength"
var8.TemporarySmooth = "TemporarySmooth"
var8.WaterAutofill = "WaterAutofill"
var5.BrushSettings = var8
var6.BrushSettings = "BrushSettings"
local var9 = {}
var9.Clear = "Clear"
var5.ClearSettings = var9
var6.ClearSettings = "ClearSettings"
local var10 = {}
var10.Heightmap = "Heightmap"
var10.Colormap = "Colormap"
var10.DefaultMaterial = "DefaultMaterial"
var10.Import = "Import"
var5.HeightmapSettings = var10
var6.HeightmapSettings = "HeightmapSettings"
local var11 = {}
var11.Apply = "Apply"
var11.AutoMaterial = "AutoMaterial"
var11.FillMode = "FillMode"
var11.MaterialMode = "MaterialMode"
var11.SourceMaterial = "SourceMaterial"
var11.TargetMaterial = "TargetMaterial"
var5.MaterialSettings = var11
var6.MaterialSettings = "MaterialSettings"
local var12 = {}
var12.Create = "Create"
var12.Evaporate = "Evaporate"
var12.OperationSource = "OperationSource"
var12.Position = "Position"
var12.Size = "Size"
var12.SnapToVoxels = "SnapToVoxels"
var12.Transform = "Transform"
var5.SeaLevelSettings = var12
var6.SeaLevelSettings = "SeaLevelSettings"
local var13 = {}
var13.OperationSource = "OperationSource"
var13.Position = "Position"
var13.Rotation = "Rotation"
var13.Size = "Size"
var13.SnapToVoxels = "SnapToVoxels"
var13.Transform = "Transform"
var13.TransformMode = "TransformMode"
var5.SelectionSettings = var13
var6.SelectionSettings = "SelectionSettings"
local var14 = {}
var14.Apply = "Apply"
var14.ForcePreview = "ForcePreview"
var14.LiveEdit = "LiveEdit"
var14.MergeEmpty = "MergeEmpty"
var14.OperationSource = "OperationSource"
var14.Position = "Position"
var14.Rotation = "Rotation"
var14.Size = "Size"
var14.SnapToVoxels = "SnapToVoxels"
var14.TerrainRegion = "TerrainRegion"
var14.TerrainRegionSize = "TerrainRegionSize"
var14.TerrainRegionTransform = "TerrainRegionTransform"
var14.TerrainRegionBuffer = "TerrainRegionBuffer"
var14.TerrainRegionBufferSize = "TerrainRegionBufferSize"
var14.TerrainRegionBufferTransform = "TerrainRegionBufferTransform"
var14.Transform = "Transform"
var14.TransformMode = "TransformMode"
var5.TransformSettings = var14
var6.TransformSettings = "TransformSettings"
local var15 = {}
var15.Shorelines = "Shorelines"
var5.UpgradeSettings = var15
var6.UpgradeSettings = "UpgradeSettings"
local var16 = {}
var16.Brush = "Brush"
var16.Note = "Note"
var16.Plane = "Plane"
var16.Region = "Region"
var5.Gizmo = var16
local var17 = {}
var17.Transform = "Transform"
var5.Note = var17
local var18 = {}
var18.Global = "Global"
var18.LocalPersistent = "LocalPersistent"
var18.LocalSession = "LocalSession"
var5.Storage = var18
return var5
