-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("TerrainEditor")
local var1 = require(var0.Src.Types.Generation)
local var2 = require(var0.Src.Types.PublicEnums)
local var3 = require(var0.Src.Types.PrivateEnums)
local var4 = require(var0.Src.Types.Tools)
local var5 = {}
local var6 = {}
var5.Category = var6
local var7 = {}
var7.Biomes = "Biomes"
var7.BiomeBlending = "BiomeBlending"
var7.BiomeSize = "BiomeSize"
var7.Caves = "Caves"
var7.Seed = "Seed"
var7.Generate = "Generate"
var5.BiomeSettings = var7
var6.BiomeSettings = "BiomeSettings"
local var8 = {}
var8.BrushMode = "BrushMode"
var8.BrushSize = "BrushSize"
var8.BrushShape = "BrushShape"
var8.FixedYPlane = "FixedYPlane"
var8.FixedYPlanePosition = "FixedYPlanePosition"
var8.FlattenMode = "FlattenMode"
var8.FlattenPlane = "FlattenPlane"
var8.IgnoreParts = "IgnoreParts"
var8.IgnoreWater = "IgnoreWater"
var8.ManualPlaneLock = "ManualPlaneLock"
var8.PivotPosition = "PivotPosition"
var8.PlaneLock = "PlaneLock"
var8.PlanePosition = "PlanePosition"
var8.PlaneRotation = "PlaneRotation"
var8.PlaneTransform = "PlaneTransform"
var8.PullTerrain = "PullTerrain"
var8.Snapping = "Snapping"
var8.State = "State"
var8.Strength = "Strength"
var8.TemporarySmooth = "TemporarySmooth"
var8.WaterAutofill = "WaterAutofill"
var5.BrushSettings = var8
var6.BrushSettings = "BrushSettings"
local var9 = {}
var9.Unit = "Unit"
var9.Elevation = "Elevation"
var9.Material = "Material"
var9.Slope = "Slope"
var9.FillMaterial = "FillMaterial"
var5.ElevationSettings = var9
var6.ElevationSettings = "ElevationSettings"
local var10 = {}
var10.FallbackMaterial = "FallbackMaterial"
var5.AdditionalSettings = var10
var6.AdditionalSettings = "AdditionalSettings"
local var11 = {}
var11.AdvancedNoise = "AdvancedNoise"
var11.BankSize = "BankSize"
var11.BlendingEdge = "BlendingEdge"
var11.CliffSlope = "CliffSlope"
var11.Confirm = "Confirm"
var11.CraterDepth = "CraterDepth"
var11.CraterRadius = "CraterRadius"
var11.FillBottom = "FillBottom"
var11.Material = "Material"
var11.MaterialLUT = "MaterialLUT"
var11.NoiseScale = "NoiseScale"
var11.NoiseStrength = "NoiseStrength"
var11.Offset = "Offset"
var11.OperationSource = "OperationSource"
var11.PlacementMode = "PlacementMode"
var11.Position = "Position"
var11.RimHeight = "RimHeight"
var11.Seed = "Seed"
var11.Size = "Size"
var11.SnapToVoxels = "SnapToVoxels"
var11.TerrainType = "TerrainType"
var11.TopRadius = "TopRadius"
var11.Transform = "Transform"
var11.WaterLevel = "WaterLevel"
var5.BuildSettings = var11
var6.BuildSettings = "BuildSettings"
local var12 = {}
var12.Clear = "Clear"
var5.ClearSettings = var12
var6.ClearSettings = "ClearSettings"
local var13 = {}
var13.Heightmap = "Heightmap"
var13.Colormap = "Colormap"
var13.DefaultMaterial = "DefaultMaterial"
var13.Import = "Import"
var5.HeightmapSettings = var13
var6.HeightmapSettings = "HeightmapSettings"
local var14 = {}
var14.Apply = "Apply"
var14.AutoMaterial = "AutoMaterial"
var14.FillMode = "FillMode"
var14.MaterialMode = "MaterialMode"
var14.SourceMaterial = "SourceMaterial"
var14.TargetMaterial = "TargetMaterial"
var5.MaterialSettings = var14
var6.MaterialSettings = "MaterialSettings"
local var15 = {}
var15.Create = "Create"
var15.Evaporate = "Evaporate"
var15.OperationSource = "OperationSource"
var15.Position = "Position"
var15.Size = "Size"
var15.SnapToVoxels = "SnapToVoxels"
var15.Transform = "Transform"
var5.SeaLevelSettings = var15
var6.SeaLevelSettings = "SeaLevelSettings"
local var16 = {}
var16.OperationSource = "OperationSource"
var16.Position = "Position"
var16.Rotation = "Rotation"
var16.Size = "Size"
var16.SnapToVoxels = "SnapToVoxels"
var16.Transform = "Transform"
var16.TransformMode = "TransformMode"
var5.SelectionSettings = var16
var6.SelectionSettings = "SelectionSettings"
local var17 = {}
var17.Apply = "Apply"
var17.ForcePreview = "ForcePreview"
var17.LiveEdit = "LiveEdit"
var17.MergeEmpty = "MergeEmpty"
var17.OperationSource = "OperationSource"
var17.Position = "Position"
var17.Rotation = "Rotation"
var17.Size = "Size"
var17.SnapToVoxels = "SnapToVoxels"
var17.TerrainRegion = "TerrainRegion"
var17.TerrainRegionSize = "TerrainRegionSize"
var17.TerrainRegionTransform = "TerrainRegionTransform"
var17.TerrainRegionBuffer = "TerrainRegionBuffer"
var17.TerrainRegionBufferSize = "TerrainRegionBufferSize"
var17.TerrainRegionBufferTransform = "TerrainRegionBufferTransform"
var17.Transform = "Transform"
var17.TransformMode = "TransformMode"
var5.TransformSettings = var17
var6.TransformSettings = "TransformSettings"
local var18 = {}
var18.Shorelines = "Shorelines"
var5.UpgradeSettings = var18
var6.UpgradeSettings = "UpgradeSettings"
local var19 = {}
var19.Brush = "Brush"
var19.Note = "Note"
var19.Placement = "Placement"
var19.Plane = "Plane"
var19.Region = "Region"
var5.Gizmo = var19
local var20 = {}
var20.Transform = "Transform"
var5.Note = var20
local var21 = {}
var21.Global = "Global"
var21.LocalPersistent = "LocalPersistent"
var21.LocalSession = "LocalSession"
var5.Storage = var21
return var5
