-- Generated with Unluau (https://github.com/valencefun/unluau)
local var46 = require(script.Parent.Parent.Parent.Parent.Packages.Framework).Styling
local var1 = var46.createStyleRule
var46 = var1
local var49 = {}
var49.Size = UDim2.new(1, 0, 1, 0)
var49.BackgroundColor3 = "$BackgroundDefault"
var49.BorderSizePixel = 0
local var61 = {}
var61.FillDirection = Enum.FillDirection.Vertical
var61.HorizontalAlignment = Enum.HorizontalAlignment.Left
var61.SortOrder = Enum.SortOrder.LayoutOrder
var61.VerticalAlignment = Enum.VerticalAlignment.Top
local var3 = var1("::UIListLayout", var61)
local var69 = {}
var69.Size = UDim2.new(1, 65531, 1, 65493)
var69.CanvasSize = UDim2.new(1, 65531, 1, 65493)
var69.AutomaticCanvasSize = Enum.AutomaticSize.Y
var69.BackgroundTransparency = 1
var69.BorderSizePixel = 0
var69.ScrollBarThickness = 6
var69.ScrollBarImageColor3 = "$NotificationScrollBarColor"
var69.VerticalScrollBarInset = Enum.ScrollBarInset.ScrollBar
var69.ScrollingDirection = Enum.ScrollingDirection.Y
local var92 = {}
var92.FillDirection = Enum.FillDirection.Vertical
var92.HorizontalAlignment = Enum.HorizontalAlignment.Left
var92.SortOrder = Enum.SortOrder.LayoutOrder
var92.VerticalAlignment = Enum.VerticalAlignment.Top
var92.Padding = UDim.new(0, 6)
local var101 = var1("::UIListLayout", var92)
local var4 = var1(">> .Component-NotificationTrayScrollingFrame", var69, {})
local var105 = {}
var105.Size = UDim2.new(1, 0, 0, 0)
var105.AutomaticSize = Enum.AutomaticSize.Y
var105.BackgroundTransparency = 1
local var117 = {}
var117.PaddingTop = UDim.new(0, 12)
var117.PaddingBottom = UDim.new(0, 12)
local var5 = var1("::UIPadding", var117)
local var6 = var1(">> .Component-NotificationTrayLoading", var105, {})
return var46(".Component-NotificationTray", var49, {})
