-- Generated with Unluau (https://github.com/valencefun/unluau)
local var9 = require(script.Parent.Parent.Parent.Parent.Packages.Framework).Styling
local var1 = var9.createStyleRule
var9 = var1
local var12 = {}
var12.Size = UDim2.new(1, 0, 1, 0)
var12.BackgroundColor3 = "$BackgroundDefault"
var12.BorderSizePixel = 0
local var24 = {}
var24.FillDirection = Enum.FillDirection.Vertical
var24.HorizontalAlignment = Enum.HorizontalAlignment.Left
var24.SortOrder = Enum.SortOrder.LayoutOrder
var24.VerticalAlignment = Enum.VerticalAlignment.Top
local var3 = var1("::UIListLayout", var24)
local var32 = {}
var32.Size = UDim2.new(1, 65531, 1, 65493)
var32.CanvasSize = UDim2.new(1, 65531, 1, 65493)
var32.AutomaticCanvasSize = Enum.AutomaticSize.Y
var32.BackgroundTransparency = 1
var32.BorderSizePixel = 0
var32.ScrollBarThickness = 6
var32.ScrollBarImageColor3 = "$NotificationScrollBarColor"
var32.VerticalScrollBarInset = Enum.ScrollBarInset.ScrollBar
var32.ScrollingDirection = Enum.ScrollingDirection.Y
local var55 = {}
var55.FillDirection = Enum.FillDirection.Vertical
var55.HorizontalAlignment = Enum.HorizontalAlignment.Left
var55.SortOrder = Enum.SortOrder.LayoutOrder
var55.VerticalAlignment = Enum.VerticalAlignment.Top
var55.Padding = UDim.new(0, 6)
local var64 = var1("::UIListLayout", var55)
local var4 = var1(">> .Component-NotificationTrayScrollingFrame", var32, {})
local var68 = {}
var68.Size = UDim2.new(1, 0, 0, 0)
var68.AutomaticSize = Enum.AutomaticSize.Y
var68.BackgroundTransparency = 1
local var80 = {}
var80.PaddingTop = UDim.new(0, 12)
var80.PaddingBottom = UDim.new(0, 12)
local var5 = var1("::UIPadding", var80)
local var6 = var1(">> .Component-NotificationTrayLoading", var68, {})
return var9(".Component-NotificationTray", var12, {})
