-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script.Parent.Parent.Parent
local var1 = require(var0.Packages.Framework)
local var2 = require(var0.Packages.MaterialFramework)
local var3 = var1.ContextServices.Analytics
local var4 = var1.ContextServices.Localization
local var5 = var1.TestHelpers.Instances.MockPlugin
local var6 = require(var0.Src.Resources.MakeTheme)
local var7 = require(var0.Src.Controllers.PluginController)
local var8 = require(var0.Src.Controllers.ShortcutController)
local var9 = require(var0.Src.Controllers.ToolController)
local var10 = require(var0.Src.Util.mockResourceTable)
local var11 = var2.Context.StudioServices
local var12 = {}
local var50 = {}
var50.stringResourceTable = var10
var50.translationResourceTable = var10
var2.Resources.LOCALIZATION_PROJECT_NAME = var50
local var14 = {}
var14.stringResourceTable = var10
var14.translationResourceTable = var10
var1.Resources.LOCALIZATION_PROJECT_NAME = var14
var12.libraries = {}
return function()
   local var0 = var5.new("TerrainEditor")
   var0:GetMouse().UnitRay = Ray.new(Vector3.zero, Vector3.xAxis)
   var0:GetMouse().X = 0
   var0:GetMouse().Y = 0
   local var70 = var7
   var70 = var0
   local var2 = var70.mock(var70)
   local var3 = var4.mock(var12)
   local var4 = var3.mock()
   local var80 = var8
   var80 = var0
   local var6 = var80.new(var80, var3)
   local var7 = var6(true)
   local var90 = var9
   var90 = var2
   local var9 = {}
   var9.Analytics = var4
   var9.Localization = var3
   var9.PluginController = var2
   var9.ShortcutController = var6
   var9.StudioServices = var11.mock()
   var9.Stylizer = var7
   var9.ToolController = var90.mock(var90, var6, var4, var3, var7)
   return var9
end
