[package]
name = "ReactDebugTools"
version = "17.0.4"
content_root = "src"
files = ["*"]
publish = true
authors = [
    "Paul Doyle <pdoyle@roblox.com>",
    "Matt Hargett <mhargett@roblox.com>",
    "Max Mines <mmines@roblox.com>",
    "Carlo Conte <cconte@roblox.com>",
    "Henry Allen <hallen@roblox.com>",
    "Olivier Trepanier <otrepanier@roblox.com>",
    "Hugh Collins <hcollins@roblox.com>",
]
[dependencies.LuauPolyfill]
version = "^1"

[dependencies.ReactReconciler]
package = "ReactReconciler"
version = "^17.0.4"

[dependencies.Shared]
package = "Shared"
version = "^17.0.4"
