PROTO_0:
        0 NEWTABLE                         R1 0 0
        2 GETUPVAL                         R2 0
        3 LOADNIL                          R3
        4 LOADNIL                          R4
        5 FORGPREP                         R2
        6 GETTABLE                         R7 R0 R6
        7 JUMPIFNOT                        R7 ; [+1]
        8 SETTABLE                         R7 R1 R5
        9 FORGLOOP                         R2 2 ; [-4]
       11 RETURN                           R1 1

PROTO_1:
        0 GETTABLEKS                       R1 R0 K0 ["responseBody"]
        2 FASTCALL1                        TYPE R1 ; [+3]
        3 MOVE                             R4 R1
        4 GETIMPORT                        R3 K2 [type]
        6 CALL                             R3 1 1
        7 JUMPIFNOTEQKS                    R3 K3 ["table"] ; [+4]
        9 GETTABLEKS                       R2 R1 K4 ["data"]
       11 JUMP                             ; [+1]
       12 LOADNIL                          R2
       13 NEWTABLE                         R3 0 0
       15 NEWTABLE                         R4 0 0
       17 FASTCALL1                        TYPE R2 ; [+3]
       18 MOVE                             R6 R2
       19 GETIMPORT                        R5 K2 [type]
       21 CALL                             R5 1 1
       22 JUMPIFNOTEQKS                    R5 K3 ["table"] ; [+44]
       24 GETIMPORT                        R5 K6 [ipairs]
       26 MOVE                             R6 R2
       27 CALL                             R5 1 3
       28 FORGPREP_INEXT                   R5
       29 FASTCALL1                        TYPE R9 ; [+3]
       30 MOVE                             R11 R9
       31 GETIMPORT                        R10 K2 [type]
       33 CALL                             R10 1 1
       34 JUMPIFNOTEQKS                    R10 K3 ["table"] ; [+30]
       36 GETTABLEKS                       R11 R9 K7 ["targetId"]
       38 FASTCALL1                        TYPE R11 ; [+2]
       39 GETIMPORT                        R10 K2 [type]
       41 CALL                             R10 1 1
       42 JUMPIFNOTEQKS                    R10 K8 ["number"] ; [+22]
       44 GETTABLEKS                       R11 R9 K9 ["imageUrl"]
       46 FASTCALL1                        TYPE R11 ; [+2]
       47 GETIMPORT                        R10 K2 [type]
       49 CALL                             R10 1 1
       50 JUMPIFNOTEQKS                    R10 K10 ["string"] ; [+14]
       52 GETTABLEKS                       R10 R9 K7 ["targetId"]
       54 GETTABLEKS                       R11 R9 K9 ["imageUrl"]
       56 SETTABLE                         R11 R3 R10
       57 GETTABLEKS                       R12 R9 K9 ["imageUrl"]
       59 FASTCALL2                        TABLE_INSERT R4 R12 ; [+4]
       61 MOVE                             R11 R4
       62 GETIMPORT                        R10 K12 [table.insert]
       64 CALL                             R10 2 0
       65 FORGLOOP                         R5 2 [inext] ; [-37]
       67 GETUPVAL                         R5 0
       68 MOVE                             R6 R4
       69 CALL                             R5 1 1
       70 NEWCLOSURE                       R7 P0
       71 CAPTURE                          VAL R3
       72 NAMECALL                         R5 R5 K13 ["andThen"]
       74 CALL                             R5 2 -1
       75 RETURN                           R5 -1

PROTO_2:
        0 GETUPVAL                         R1 0
        1 GETTABLEKS                       R1 R1 K0 ["new"]
        3 CALL                             R1 0 1
        4 GETTABLEKS                       R2 R1 K1 ["composeUrl"]
        6 GETUPVAL                         R3 1
        7 GETTABLEKS                       R3 R3 K2 ["UNIVERSE_ICON_URL"]
        9 GETTABLEKS                       R3 R3 K3 ["Prefix"]
       11 GETUPVAL                         R4 1
       12 GETTABLEKS                       R4 R4 K2 ["UNIVERSE_ICON_URL"]
       14 GETTABLEKS                       R4 R4 K4 ["Url"]
       16 DUPTABLE                         R5 K12 [{["returnPolicy"] = "AutoGenerated", ["size"] = "150x150", ["format"] = "png", ["universeIds"]}]
       17 SETTABLEKS                       R0 R5 K11 ["universeIds"]
       19 CALL                             R2 3 1
       20 GETUPVAL                         R3 2
       21 GETUPVAL                         R5 2
       22 MOVE                             R7 R2
       23 LOADNIL                          R8
       24 NAMECALL                         R5 R5 K13 ["get"]
       26 CALL                             R5 3 -1
       27 NAMECALL                         R3 R3 K14 ["parseJson"]
       29 CALL                             R3 -1 1
       30 DUPCLOSURE                       R5 K15 [PROTO_1]
       31 CAPTURE                          UPVAL U3
       32 NAMECALL                         R3 R3 K16 ["andThen"]
       34 CALL                             R3 2 -1
       35 RETURN                           R3 -1

MAIN:
        0 PREPVARARGS                      0
        1 GETIMPORT                        R0 K1 [script]
        3 LOADK                            R2 K2 ["CreatorConfig"]
        4 NAMECALL                         R0 R0 K3 ["FindFirstAncestor"]
        6 CALL                             R0 2 1
        7 GETIMPORT                        R1 K5 [require]
        9 GETTABLEKS                       R2 R0 K6 ["Packages"]
       11 GETTABLEKS                       R2 R2 K7 ["Framework"]
       13 CALL                             R1 1 1
       14 GETTABLEKS                       R2 R1 K8 ["RobloxAPI"]
       16 GETTABLEKS                       R2 R2 K9 ["Url"]
       18 GETIMPORT                        R3 K5 [require]
       20 GETTABLEKS                       R4 R0 K10 ["Src"]
       22 GETTABLEKS                       R4 R4 K11 ["Network"]
       24 GETTABLEKS                       R4 R4 K12 ["Urls"]
       26 CALL                             R3 1 1
       27 GETIMPORT                        R4 K5 [require]
       29 GETTABLEKS                       R5 R0 K10 ["Src"]
       31 GETTABLEKS                       R5 R5 K11 ["Network"]
       33 GETTABLEKS                       R5 R5 K13 ["ResolveIconUrls"]
       35 CALL                             R4 1 1
       36 GETTABLEKS                       R5 R1 K14 ["Http"]
       38 GETTABLEKS                       R5 R5 K15 ["Networking"]
       40 GETTABLEKS                       R5 R5 K16 ["new"]
       42 DUPTABLE                         R6 K19 [{["isInternal"] = True}]
       43 CALL                             R5 1 1
       44 DUPCLOSURE                       R6 K20 [PROTO_2]
       45 CAPTURE                          VAL R2
       46 CAPTURE                          VAL R3
       47 CAPTURE                          VAL R5
       48 CAPTURE                          VAL R4
       49 RETURN                           R6 1
