--[[
	Package link auto-generated by manage_libraries and Rotriever
]]
local FFlagPlayerEmulatorDeduplicatePackages = game:GetFastFlag("PlayerEmulatorDeduplicatePackages")
if FFlagPlayerEmulatorDeduplicatePackages then
	local PackageIndex = script.Parent.Parent.Parent._Index
	local Package = require(PackageIndex["RoactRodux"]["RoactRodux"])
	return Package
else
	local PackageIndex = script.Parent.Parent.Parent._Old

	if game:GetFastFlag("PlayerEmulatorUseRoactv14") then
		return require(PackageIndex["roblox_roact-rodux"]["roact-rodux"])
	end

	return require(PackageIndex["RoactRodux-d65ac2db2841-f36097a9ef27"].packages["RoactRodux"])
end
