--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent

local package = PackageIndex["t-558c5873-74411073"].Packages["t"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package