--!strict

-- TODO remove this linting exception once we have an actual styling system
--# selene: allow(roblox_internal_custom_color)

local COLOR_WHITE = Color3.fromRGB(255, 255, 255)
local COLOR_GRAY = Color3.fromRGB(155, 155, 155)
local COLOR_DARK = Color3.fromRGB(25, 25, 25)
local COLOR_RED = Color3.fromRGB(255, 100, 100)
local COLOR_BLUE = Color3.fromRGB(100, 100, 255)
local COLOR_BUTTON = Color3.fromRGB(100, 100, 100)
local COLOR_MAGENTA = Color3.fromRGB(255, 0, 255)

local StyleUtil = {
	CANVAS_BACKGROUND_COLOR3 = COLOR_DARK,
	CANVAS_BACKGROUND_TRANSPARENCY = 1,
	CURVE_COLOR3 = COLOR_RED,
	CURVE_THICKNESS = 2,
	DEBUG_COLOR3 = COLOR_MAGENTA,
	GRID_COLOR3 = COLOR_GRAY,
	GRID_COLOR3_MINOR = COLOR_GRAY,
	GRID_THICKNESS = 2,
	GRID_THICKNESS_MINOR = 1,
	GRID_TRANSPARENCY = 0.6,
	GRID_TRANSPARENCY_MINOR = 0.8,
	GRID_BOX_BACKGROUND_COLOR3 = COLOR_BLUE,
	GRID_BOX_BACKGROUND_TRANSPARENCY = 0.7,
	GRID_BOX_BORDER_COLOR3 = COLOR_BLUE,
	GRID_BOX_BORDER_THICKNESS = 0,
	GRID_LABEL_COLOR3 = COLOR_WHITE,
	GRID_LABEL_FONT_SIZE = 10,
	GRID_LINE_COLOR3 = COLOR_WHITE,
	GRID_LINE_THICKNESS = 2,
	GRID_LINE_TRANSPARENCY = 0,
	POINT_HANDLE_COLOR3 = COLOR_RED,
	POINT_HANDLE_IMAGE = "rbxasset://textures/smallWhiteCircle.png",
	POINT_HANDLE_OUTLINE_COLOR3 = COLOR_WHITE,
	POINT_HANDLE_OUTLINE_THICKNESS = 0,
	POINT_HANDLE_SIZE = 10,
	SCALE_BACKGROUND_COLOR3 = COLOR_DARK,
	SCALE_BACKGROUND_TRANSPARENCY = 1,
	SCALE_DISTANCE = UDim.new(0, 0),
	SCALE_SIZE = UDim.new(0, 25),
	SCALE_TICK_COLOR3 = COLOR_GRAY,
	SCALE_TICK_LABEL_COLOR3 = COLOR_GRAY,
	SCALE_TICK_LABEL_PADDING = 4,
	SCALE_TICK_LABEL_SIZE = 8,
	SCALE_TICK_LENGTH = 10,
	SCALE_TICK_LENGTH_MINOR = 5,
	SCALE_TICK_THICKNESS = 2,
	SCROLLBAR_COLOR3 = COLOR_DARK,
	SCROLLBAR_DISTANCE = UDim.new(0, 30),
	SCROLLBAR_LEFT_SCROLL_BUTTON_IMAGE = "rbxasset://textures/AnimationEditor/button_control_reverseplay.png",
	SCROLLBAR_LEFT_ZOOM_BUTTON_IMAGE = "rbxasset://textures/AnimationEditor/button_zoom.png",
	SCROLLBAR_OUTLINE_COLOR3 = COLOR_DARK,
	SCROLLBAR_OUTLINE_THICKNESS = 1,
	SCROLLBAR_RIGHT_SCROLL_BUTTON_IMAGE = "rbxasset://textures/AnimationEditor/button_control_play.png",
	SCROLLBAR_RIGHT_ZOOM_BUTTON_IMAGE = "rbxasset://textures/AnimationEditor/button_zoom.png",
	SCROLLBAR_SCROLL_BUTTON_SIZE = 15,
	SCROLLBAR_SIZE = UDim.new(0, 15),
	SCROLLBAR_ZOOM_BUTTON_SIZE = 15,
	SCROLLBAR_BUTTON_COLOR3 = COLOR_BUTTON,
	VIEWPORT_BACKGROUND_COLOR3 = COLOR_DARK,
	VIEWPORT_BACKGROUND_TRANSPARENCY = 0,
}

return StyleUtil
