--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["PluginLoader"]["PluginLoader"])

export type Args = Package.Args
export type PluginLoaderContext = Package.PluginLoaderContext
export type ButtonInfo = Package.ButtonInfo


return Package
