--[[
	Package link auto-generated by manage_libraries and Rotriever
]]
local FFlagDeveloperStorybookDeduplicatePackages = game:GetFastFlag("DeveloperStorybookDeduplicatePackages")
if FFlagDeveloperStorybookDeduplicatePackages then
	local PackageIndex = script.Parent._Index
	local Package = require(PackageIndex["RoactRodux"]["RoactRodux"])
	return Package
else
	local PackageIndex = script.Parent._IndexOld
	return require(PackageIndex["RoactRodux"]["RoactRodux"])
end

