local OperationHelper = require(script.Parent.OperationHelper)

return function()
	describe("clampDownToVoxel", function()
		it("should return the expected results", function()
			expect(OperationHelper.clampDownToVoxel(0)).to.equal(0)
			expect(OperationHelper.clampDownToVoxel(1)).to.equal(0)
			expect(OperationHelper.clampDownToVoxel(3.9)).to.equal(0)
			expect(OperationHelper.clampDownToVoxel(4)).to.equal(4)
			expect(OperationHelper.clampDownToVoxel(5)).to.equal(4)
			expect(OperationHelper.clampDownToVoxel(-1)).to.equal(-4)
			expect(OperationHelper.clampDownToVoxel(17)).to.equal(16)
			expect(OperationHelper.clampDownToVoxel(-17)).to.equal(-20)
		end)
	end)

	describe("clampUpToVoxel", function()
		it("should return the expected results", function()
			expect(OperationHelper.clampUpToVoxel(0)).to.equal(0)
			expect(OperationHelper.clampUpToVoxel(1)).to.equal(4)
			expect(OperationHelper.clampUpToVoxel(3.9)).to.equal(4)
			expect(OperationHelper.clampUpToVoxel(4)).to.equal(4)
			expect(OperationHelper.clampUpToVoxel(5)).to.equal(8)
			expect(OperationHelper.clampUpToVoxel(-1)).to.equal(-0)
			expect(OperationHelper.clampUpToVoxel(17)).to.equal(20)
			expect(OperationHelper.clampUpToVoxel(-17)).to.equal(-16)
		end)
	end)

	describe("getWaterHeightAndAirFillerMaterial", function()
	end)
end
