-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = require(script:FindFirstAncestor("Toolbox").Core.Util.DebugFlags)
local var1 = {}
var1[0] = "Unknown"
local var12 = "InvalidTargetType"
local var13 = "FailedToFetchPublishingFee"
local var14 = "ServiceUnavailable"
local var15 = "InvalidArgument"
local var16 = "NotFound"
local var17 = "FailedToGetCollectibleItemId"
local var18 = "FailedToGetCommissionRates"
local var19 = "NullParameterRequest"
local var20 = "PublishLimitExceeded"
local var21 = "AssetIsPendingValidation"
local var22 = "AssetContainsInvalidContent"
local var23 = "UserDoesNotHavePermissionsForGroupAsset"
local var24 = "AssetTypeCannotBeReleased"
local var25 = "AssetIsPendingReview"
local var26 = "AssetIsModerated"
local var27 = "ItemIsReleased"
local var28 = "UserDoesNotHavePermissionToRelease"
local var29 = "UserDoesNotOwnTheItem"
local var30 = "ItemPriceTooLow"
local var31 = "ItemPriceTooHigh"
local var32 = "InvalidAssetId"
local var33 = "InvalidAgent"
local var34 = "NoExperiencesListed"
local var35 = "NameIsModerated"
local var36 = "DescriptionIsModerated"
local var37 = "TextIsModerated"
local var38 = "FailedToFilterText"
local var39 = "AssetAlreadyReleasedAsUnlimited"
local var40 = "AssetInDelayedRelease"
local var41 = "InvalidIdempotencyToken"
local var42 = "InvalidAgreedPublishingFee"
local var43 = "GatewayCouldNotPublishItem"
local var44 = "GroupAssetNotSupported"
local var45 = "CouldNotFindInitialUserAsset"
local var46 = "InvalidQuantity"
local var47 = "SaleLocationCurrentlyNotSupported"
local var48 = "InvalidCollectibleItemId"
local var49 = "FailedToGetCollectibleItemInformation"
local var50 = "GroupItemsNotSupported"
local var51 = "FailedToUpdateCollectibleItem"
local var52 = "PublishQuotaUnavailable"
local var53 = "FailedToFetchMarketplaceFee"
local var54 = "QuantityLimitCurrentlyNotSupported"
local var55 = "InvalidQuantityLimit"
local var56 = "ExactCopyOfAssetHasBeenPublished"
local var57 = "ItemIsInBundle"
local var58 = "ResaleRestrictionCurrentlyNotSupported"
local var59 = "InvalidResaleRestriction"
local var60 = "FailedToUpdateCollectibleDescription"
local var61 = "InvalidBundleId"
local var62 = "BundleTypeCannotBeReleased"
local var63 = "BundleIsModerated"
local var64 = "BundleAlreadyReleasedAsUnlimited"
local var65 = "BundlesGatewayUnexpectedErrorCode"
local var66 = "CissUnexpectedException"
local var67 = "PublishingGatewayUnexpectedException"
local var68 = "NonLimitedPublishingNotSupported"
local var69 = "InvalidPublishingType"
local var70 = "InvalidPriceOffset"
local var71 = "InvalidMinimumPrice"
local var72 = "InvalidSaleStatus"
local var73 = "InvalidPriceConfiguration"
local var74 = "FailedToGetPriceConfiguration"
local var75 = "CannotBeFree"
local var76 = "UnexpectedPlaceIds"
local var77 = "MissingAuthenticatedUser"
local var78 = "InvalidCreatorType"
local var79 = "PermissionProviderNotEnabled"
local var80 = "InvalidGroupId"
local var81 = "InsufficientRobux"
local var82 = "ItemNotFound"
local var83 = "ItemIsModerated"
local var84 = "ItemModerationUnknown"
local var85 = "InvalidItemType"
local var86 = "CalendarQuotaExceeded"
local var87 = "CalendarQuotaUnavailable"
local var88 = "PublishingGatewayMissingReason"
local var89 = "PublishingGatewayUnexpectedReason"
local var90 = "PublishingGatewayUnexpectedAccessStatus"
local var91 = "MissingIdVerification"
local var92 = "CreationAccessBlocked"
local var93 = "MissingPremiumSubscriptionTier"
local var94 = "GroupOwnerMissingPremiumSubscriptionTier"
local var95 = "MissingCicRoleset"
return function(arg1, arg2, arg3)
   return arg1:getUploadPermissionStatus(arg2, arg3):andThen(function(arg1)
      local var0 = arg1.responseBody
      if var0.isAllowed then
         local var0 = {}
         var0.type = "allowed"
         return var0
      end
      local var1 = {}
      var1.type = "notAllowed"
      var1.denyReason = var1[var0.deniedReason] or var0.deniedReason
      return var1
   end):catch(function(arg1)
      local var0 = {}
      var0.type = "error"
      var0.message = tostring(arg1)
      return var0
   end)
end
