[package]
name = "ReactUtils"
version = "1.3.1"
content_root = "src"
files = [
    "*",
    "!**/*.spec.lua",
]
publish = true
authors = ["Roblox"]
[dependencies.LuauPolyfill]
version = "^1.2.3"

[dependencies.React]
version = "^17.0.1"

[dependencies.ReactRoblox]
version = "^17.0.1"

[dependencies.SafeFlags]
version = "^0.1.1"
