-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.Clear = "Clear"
var0.Draw = "Draw"
var0.Empty = "Empty"
var0.Fill = "Fill"
var0.Flatten = "Flatten"
var0.Generate = "Generate"
var0.Import = "Import"
var0.Mock = "Mock"
var0.Paint = "Paint"
var0.SeaLevel = "SeaLevel"
var0.Select = "Select"
var0.Sculpt = "Sculpt"
var0.Smooth = "Smooth"
var0.Transform = "Transform"
local var1 = {}
var1.Create = "Create"
var1.Edit = "Edit"
var1.None = "None"
local var2 = {}
var2.Add = "Add"
var2.Subtract = "Subtract"
local var3 = {}
var3.Sphere = "Sphere"
var3.Cube = "Cube"
var3.Cylinder = "Cylinder"
local var4 = {}
var4.Fill = "Fill"
var4.Replace = "Replace"
local var5 = {}
var5.Erode = "Erode"
var5.Grow = "Grow"
var5.Both = "Both"
local var6 = {}
var6.Auto = "Auto"
var6.Fixed = "Fixed"
local var7 = {}
var7.Bottom = "Bottom"
var7.Center = "Center"
var7.Top = "Top"
local var8 = {}
var8.Auto = "Auto"
var8.Off = "Off"
var8.Manual = "Manual"
local var9 = {}
var9.Paint = "Paint"
var9.Replace = "Replace"
local var10 = {}
var10.BrushSize = "BrushSize"
var10.Off = "Off"
var10.Voxel = "Voxel"
local var11 = {}
var11.Arctic = "Arctic"
var11.Canyons = "Canyons"
var11.Dunes = "Dunes"
var11.Hills = "Hills"
var11.Lavascape = "Lavascape"
var11.Marsh = "Marsh"
var11.Mountains = "Mountains"
var11.Plains = "Plains"
var11.Water = "Water"
local var12 = {}
var12.BrushMode = "BrushMode"
var12.BrushShape = "BrushShape"
var12.FillMode = "FillMode"
var12.FlattenPlane = "FlattenPlane"
var12.FlattenMode = "FlattenMode"
var12.PivotPosition = "PivotPosition"
var12.PlaneLock = "PlaneLock"
var12.MaterialMode = "MaterialMode"
var12.Snapping = "Snapping"
local var13 = {}
local var83 = var2.Add
local var84 = var2.Subtract
var12.BrushMode = {}
local var87 = var3.Sphere
local var88 = var3.Cube
local var89 = var3.Cylinder
var12.BrushShape = {}
local var92 = var4.Fill
local var93 = var4.Replace
var12.FillMode = {}
local var96 = var6.Auto
local var97 = var6.Fixed
var12.FlattenPlane = {}
local var100 = var5.Erode
local var101 = var5.Grow
local var102 = var5.Both
var12.FlattenMode = {}
local var105 = var7.Bottom
local var106 = var7.Center
local var107 = var7.Top
var12.PivotPosition = {}
local var110 = var8.Off
local var111 = var8.Auto
local var112 = var8.Manual
var12.PlaneLock = {}
local var115 = var9.Paint
local var116 = var9.Replace
var12.MaterialMode = {}
local var117 = var12.Snapping
local var119 = var10.Off
local var120 = var10.Voxel
var12.Snapping = {}
var117 = require(script:FindFirstAncestor("TerrainEditor").Src.Flags.getFFlagTerrainEditorBrushSizeSnapping)
if var117() then
   table.insert(var13[var12.Snapping], var10.BrushSize)
end
local var37 = {}
var37.Duplicate = "Duplicate"
var37.Import = "Import"
var37.Move = "Move"
var37.Paste = "Paste"
var37.Stamp = "Stamp"
local var38 = {}
var38.Gizmo = "Gizmo"
var38.History = "History"
local var39 = {}
var39.Apply = "Apply"
var39.CopySelected = "CopySelected"
var39.CutSelected = "CutSelected"
var39.DeleteSelected = "DeleteSelected"
var39.DuplicateSelected = "DuplicateSelected"
var39.EditPlane = "EditPlane"
var39.PasteSelected = "PasteSelected"
var39.Quit = "Quit"
local var40 = {}
var40.Biomes = "Biomes"
var40.BiomeBlending = "BiomeBlending"
var40.BiomeSize = "BiomeSize"
var40.Caves = "Caves"
var40.Seed = "Seed"
var40.Generate = "Generate"
local var41 = {}
var41.Height = "Height"
var41.Size = "Size"
local var42 = {}
var42.BrushMode = "BrushMode"
var42.BrushSize = "BrushSize"
var42.BrushShape = "BrushShape"
var42.FixedPlane = "FixedPlane"
var42.FlattenMode = "FlattenMode"
var42.FlattenPlane = "FlattenPlane"
var42.IgnoreParts = "IgnoreParts"
var42.IgnoreWater = "IgnoreWater"
var42.ManualPlaneLock = "ManualPlaneLock"
var42.PivotPosition = "PivotPosition"
var42.PlaneLock = "PlaneLock"
var42.PlanePosition = "PlanePosition"
var42.PlaneRotation = "PlaneRotation"
var42.PlaneTransform = "PlaneTransform"
var42.PullTerrain = "PullTerrain"
var42.Snapping = "Snapping"
var42.State = "State"
var42.Strength = "Strength"
var42.TemporarySmooth = "TemporarySmooth"
var42.WaterAutofill = "WaterAutofill"
local var43 = {}
var43.Clear = "Clear"
local var44 = {}
var44.Heightmap = "Heightmap"
var44.Colormap = "Colormap"
var44.DefaultMaterial = "DefaultMaterial"
var44.Import = "Import"
local var45 = {}
var45.Apply = "Apply"
var45.AutoMaterial = "AutoMaterial"
var45.FillMode = "FillMode"
var45.MaterialMode = "MaterialMode"
var45.SourceMaterial = "SourceMaterial"
var45.TargetMaterial = "TargetMaterial"
local var46 = {}
var46.Create = "Create"
var46.Evaporate = "Evaporate"
var46.OperationSource = "OperationSource"
var46.Position = "Position"
var46.Size = "Size"
var46.SnapToVoxels = "SnapToVoxels"
var46.Transform = "Transform"
local var47 = {}
var47.OperationSource = "OperationSource"
var47.Position = "Position"
var47.Rotation = "Rotation"
var47.Size = "Size"
var47.SnapToVoxels = "SnapToVoxels"
var47.Transform = "Transform"
var47.TransformMode = "TransformMode"
local var48 = {}
var48.Apply = "Apply"
var48.ForcePreview = "ForcePreview"
var48.LiveEdit = "LiveEdit"
var48.MergeEmpty = "MergeEmpty"
var48.OperationSource = "OperationSource"
var48.Position = "Position"
var48.Rotation = "Rotation"
var48.Size = "Size"
var48.SnapToVoxels = "SnapToVoxels"
var48.TerrainRegion = "TerrainRegion"
var48.TerrainRegionSize = "TerrainRegionSize"
var48.TerrainRegionTransform = "TerrainRegionTransform"
var48.TerrainRegionBuffer = "TerrainRegionBuffer"
var48.TerrainRegionBufferSize = "TerrainRegionBufferSize"
var48.TerrainRegionBufferTransform = "TerrainRegionBufferTransform"
var48.Transform = "Transform"
var48.TransformMode = "TransformMode"
local var49 = {}
var49.Shorelines = "Shorelines"
local var50 = {}
var50.BiomeSettings = "BiomeSettings"
var50.BrushSettings = "BrushSettings"
var50.ClearSettings = "ClearSettings"
var50.HeightmapSettings = "HeightmapSettings"
var50.MaterialSettings = "MaterialSettings"
var50.SeaLevelSettings = "SeaLevelSettings"
var50.SelectionSettings = "SelectionSettings"
var50.TransformSettings = "TransformSettings"
var50.Upgrades = "Upgrades"
local var51 = {}
var51.Global = "Global"
var51.LocalPersistent = "LocalPersistent"
var51.LocalSession = "LocalSession"
local var52 = {}
var52.Brush = "Brush"
var52.Note = "Note"
var52.Plane = "Plane"
var52.Region = "Region"
local var53 = {}
var53.Dimensions = "Dimensions"
var53.Filename = "Filename"
local var54 = {}
var54.Cancel = "Cancel"
var54.Pause = "Pause"
var54.Resume = "Resume"
local var55 = {}
var55.Transform = "Transform"
local var56 = {}
var56.Biomes = var11
var56.BiomeSettings = var40
var56.BrushMode = var2
var56.BrushSettings = var42
var56.BrushShape = var3
var56.BrushSizeType = var41
var56.Categories = var50
var56.ClearSettings = var43
var56.DialogOption = var54
var56.EditorEnum = var12
var56.EditorEnumIndeces = var13
var56.FillMode = var4
var56.FlattenMode = var5
var56.FlattenPlane = var6
var56.Gizmo = var52
var56.HeightmapSettings = var44
var56.Note = var55
var56.MaterialMode = var9
var56.MaterialSettings = var45
var56.MetadataItem = var53
var56.OperationSource = var38
var56.PivotPosition = var7
var56.PlaneLock = var8
var56.PluginAction = var39
var56.SeaLevelSettings = var46
var56.SelectionSettings = var47
var56.Snapping = var10
var56.Storage = var51
var56.ToolCategories = var1
var56.Tools = var0
var56.TransformMode = var37
var56.TransformSettings = var48
var56.Upgrades = var49
return var56
