-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.Clear = "Clear"
var0.Draw = "Draw"
var0.Empty = "Empty"
var0.Fill = "Fill"
var0.Flatten = "Flatten"
var0.Generate = "Generate"
var0.Import = "Import"
var0.Mock = "Mock"
var0.Paint = "Paint"
var0.Ramp = "Ramp"
var0.SeaLevel = "SeaLevel"
var0.Select = "Select"
var0.Sculpt = "Sculpt"
var0.Smooth = "Smooth"
var0.Transform = "Transform"
var0.Upgrade = "Upgrade"
local var1 = {}
var1.Create = "Create"
var1.Edit = "Edit"
var1.None = "None"
local var2 = {}
var2.Add = "Add"
var2.Subtract = "Subtract"
local var3 = {}
var3.Sphere = "Sphere"
var3.Cube = "Cube"
var3.Cylinder = "Cylinder"
local var4 = {}
var4.Fill = "Fill"
var4.Replace = "Replace"
local var5 = {}
var5.Erode = "Erode"
var5.Grow = "Grow"
var5.Both = "Both"
local var6 = {}
var6.Bottom = "Bottom"
var6.Center = "Center"
var6.Top = "Top"
local var7 = {}
var7.Off = "Off"
var7.Auto = "Auto"
var7.Manual = "Manual"
local var8 = {}
var8.Paint = "Paint"
var8.Replace = "Replace"
local var9 = {}
var9.BrushSize = "BrushSize"
var9.Off = "Off"
var9.Voxel = "Voxel"
local var10 = {}
var10.Arctic = "Arctic"
var10.Canyons = "Canyons"
var10.Dunes = "Dunes"
var10.Hills = "Hills"
var10.Lavascape = "Lavascape"
var10.Marsh = "Marsh"
var10.Mountains = "Mountains"
var10.Plains = "Plains"
var10.Water = "Water"
local var11 = {}
var11.BrushMode = "BrushMode"
var11.BrushShape = "BrushShape"
var11.FillMode = "FillMode"
var11.FlattenMode = "FlattenMode"
var11.PivotPosition = "PivotPosition"
var11.PlaneLock = "PlaneLock"
var11.MaterialMode = "MaterialMode"
var11.Snapping = "Snapping"
local var72 = var2.Add
local var73 = var2.Subtract
var11.BrushMode = {}
local var76 = var3.Sphere
local var77 = var3.Cube
local var78 = var3.Cylinder
var11.BrushShape = {}
local var81 = var4.Fill
local var82 = var4.Replace
var11.FillMode = {}
local var85 = var5.Erode
local var86 = var5.Grow
local var87 = var5.Both
var11.FlattenMode = {}
local var90 = var6.Bottom
local var91 = var6.Center
local var92 = var6.Top
var11.PivotPosition = {}
local var95 = var7.Off
local var96 = var7.Auto
local var97 = var7.Manual
var11.PlaneLock = {}
local var100 = var8.Paint
local var101 = var8.Replace
var11.MaterialMode = {}
local var104 = var9.Off
local var105 = var9.Voxel
local var106 = var9.BrushSize
var11.Snapping = {}
local var33 = {}
var33.Duplicate = "Duplicate"
var33.Import = "Import"
var33.Move = "Move"
var33.Paste = "Paste"
var33.Stamp = "Stamp"
local var34 = {}
var34.Gizmo = "Gizmo"
var34.History = "History"
local var35 = {}
var35.Apply = "Apply"
var35.CopySelected = "CopySelected"
var35.CutSelected = "CutSelected"
var35.DeleteSelected = "DeleteSelected"
var35.DuplicateSelected = "DuplicateSelected"
var35.EditPlane = "EditPlane"
var35.PasteSelected = "PasteSelected"
var35.Quit = "Quit"
local var36 = {}
var36.Biomes = "Biomes"
var36.BiomeBlending = "BiomeBlending"
var36.BiomeSize = "BiomeSize"
var36.Caves = "Caves"
var36.Seed = "Seed"
var36.Generate = "Generate"
local var37 = {}
var37.BrushMode = "BrushMode"
var37.BaseHeight = "BaseHeight"
var37.BaseSize = "BaseSize"
var37.BrushShape = "BrushShape"
var37.FixedPlane = "FixedPlane"
var37.FixedPlanePosition = "FixedPlanePosition"
var37.FlattenMode = "FlattenMode"
var37.IgnoreParts = "IgnoreParts"
var37.IgnoreWater = "IgnoreWater"
var37.ManualPlaneLock = "ManualPlaneLock"
var37.PivotPosition = "PivotPosition"
var37.PlaneLock = "PlaneLock"
var37.PlanePosition = "PlanePosition"
var37.PlaneRotation = "PlaneRotation"
var37.PlaneTransform = "PlaneTransform"
var37.PullTerrain = "PullTerrain"
var37.Snapping = "Snapping"
var37.State = "State"
var37.Strength = "Strength"
var37.TemporarySmooth = "TemporarySmooth"
var37.WaterAutofill = "WaterAutofill"
local var38 = {}
var38.Clear = "Clear"
local var39 = {}
var39.Heightmap = "Heightmap"
var39.Colormap = "Colormap"
var39.DefaultMaterial = "DefaultMaterial"
var39.Import = "Import"
local var40 = {}
var40.Apply = "Apply"
var40.AutoMaterial = "AutoMaterial"
var40.FillMode = "FillMode"
var40.MaterialMode = "MaterialMode"
var40.SourceMaterial = "SourceMaterial"
var40.TargetMaterial = "TargetMaterial"
local var41 = {}
var41.Create = "Create"
var41.Evaporate = "Evaporate"
var41.OperationSource = "OperationSource"
var41.Position = "Position"
var41.Size = "Size"
var41.SnapToVoxels = "SnapToVoxels"
var41.Transform = "Transform"
local var42 = {}
var42.OperationSource = "OperationSource"
var42.Position = "Position"
var42.Rotation = "Rotation"
var42.Size = "Size"
var42.SnapToVoxels = "SnapToVoxels"
var42.Transform = "Transform"
var42.TransformMode = "TransformMode"
local var43 = {}
var43.Apply = "Apply"
var43.ForcePreview = "ForcePreview"
var43.LiveEdit = "LiveEdit"
var43.MergeEmpty = "MergeEmpty"
var43.OperationSource = "OperationSource"
var43.Position = "Position"
var43.Rotation = "Rotation"
var43.Size = "Size"
var43.SnapToVoxels = "SnapToVoxels"
var43.TerrainRegion = "TerrainRegion"
var43.TerrainRegionSize = "TerrainRegionSize"
var43.TerrainRegionTransform = "TerrainRegionTransform"
var43.TerrainRegionBuffer = "TerrainRegionBuffer"
var43.TerrainRegionBufferSize = "TerrainRegionBufferSize"
var43.TerrainRegionBufferTransform = "TerrainRegionBufferTransform"
var43.Transform = "Transform"
var43.TransformMode = "TransformMode"
local var44 = {}
var44.Shorelines = "Shorelines"
local var45 = {}
var45.BiomeSettings = "BiomeSettings"
var45.BrushSettings = "BrushSettings"
var45.ClearSettings = "ClearSettings"
var45.HeightmapSettings = "HeightmapSettings"
var45.MaterialSettings = "MaterialSettings"
var45.SeaLevelSettings = "SeaLevelSettings"
var45.SelectionSettings = "SelectionSettings"
var45.TransformSettings = "TransformSettings"
var45.Upgrades = "Upgrades"
local var46 = {}
var46.Global = "Global"
var46.LocalPersistent = "LocalPersistent"
var46.LocalSession = "LocalSession"
local var47 = {}
var47.Brush = "Brush"
var47.Plane = "Plane"
var47.Region = "Region"
local var48 = {}
var48.Dimensions = "Dimensions"
var48.Filename = "Filename"
local var49 = {}
var49.Cancel = "Cancel"
var49.Pause = "Pause"
var49.Resume = "Resume"
local var50 = {}
var50.Biomes = var10
var50.BiomeSettings = var36
var50.BrushMode = var2
var50.BrushSettings = var37
var50.BrushShape = var3
var50.Categories = var45
var50.ClearSettings = var38
var50.DialogOption = var49
var50.EditorEnum = var11
var50.EditorEnumIndeces = {}
var50.FillMode = var4
var50.FlattenMode = var5
var50.Gizmo = var47
var50.HeightmapSettings = var39
var50.MaterialMode = var8
var50.MaterialSettings = var40
var50.MetadataItem = var48
var50.OperationSource = var34
var50.PivotPosition = var6
var50.PlaneLock = var7
var50.PluginAction = var35
var50.SeaLevelSettings = var41
var50.SelectionSettings = var42
var50.Snapping = var9
var50.Storage = var46
var50.ToolCategories = var1
var50.Tools = var0
var50.TransformMode = var33
var50.TransformSettings = var43
var50.Upgrades = var44
return var50
