--[[
	Package link auto-generated by manage_libraries and Rotriever
]]
local FFlagDeveloperStorybookDeduplicatePackages = game:GetFastFlag("DeveloperStorybookDeduplicatePackages")
if FFlagDeveloperStorybookDeduplicatePackages then
	local PackageIndex = script.Parent.Parent.Parent._Index
	local Package = require(PackageIndex["roblox_cryo"]["cryo"])
	return Package
else
	local PackageIndex = script.Parent.Parent.Parent._IndexOld
	return require(PackageIndex["roblox_cryo"]["cryo"])
end

