-- Generated with Unluau (https://github.com/valencefun/unluau)
local var9 = require(script.Parent.Parent.Parent.Parent.Packages.Framework).Styling
local var1 = var9.createStyleRule
var9 = var1
local var12 = {}
var12.AutomaticSize = Enum.AutomaticSize.Y
var12.BackgroundTransparency = 1
var12.BorderSizePixel = 0
local var19 = {}
var19.RichText = true
var19.Size = UDim2.new(1, 0, 0, 0)
var19.AutomaticSize = Enum.AutomaticSize.Y
var19.BackgroundTransparency = 1
var19.TextColor3 = "$TextPrimary"
var19.TextSize = 18
var19.Font = Enum.Font.SourceSans
var19.TextWrapped = true
var19.TextTruncate = Enum.TextTruncate.AtEnd
var19.TextXAlignment = Enum.TextXAlignment.Left
var19.TextYAlignment = Enum.TextYAlignment.Top
local var39 = {}
var39.MaxSize = Vector2.new(10000, 36)
var39.MinSize = Vector2.new(0, 18)
local var48 = var1("::UISizeConstraint", var39)
local var3 = var1("> #Subject", var19, {})
local var52 = {}
var52.Size = UDim2.new(1, 0, 0, 0)
var52.AutomaticSize = Enum.AutomaticSize.Y
var52.BackgroundTransparency = 1
var52.TextColor3 = "$TextSecondary"
var52.TextSize = 18
var52.Font = Enum.Font.SourceSans
var52.TextWrapped = true
var52.TextTruncate = Enum.TextTruncate.AtEnd
var52.TextXAlignment = Enum.TextXAlignment.Left
var52.TextYAlignment = Enum.TextYAlignment.Top
local var71 = {}
var71.MaxSize = Vector2.new(10000, 36)
var71.MinSize = Vector2.new(0, 18)
local var80 = var1("::UISizeConstraint", var71)
local var5 = var1("> #Subline", var52, {})
local var84 = {}
var84.Size = UDim2.new(1, 0, 0, 0)
var84.AutomaticSize = Enum.AutomaticSize.Y
var84.BackgroundTransparency = 1
var84.TextColor3 = "$TextSecondary"
var84.TextSize = 15
var84.Font = Enum.Font.SourceSans
var84.TextTruncate = Enum.TextTruncate.AtEnd
var84.TextXAlignment = Enum.TextXAlignment.Left
var84.TextYAlignment = Enum.TextYAlignment.Top
local var6 = var1("> #ElapsedTime", var84)
return var9(".Component-NotificationText", var12, {})
