-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("MaterialGenerator")
local var1 = require(var0.Packages.React)
local var2 = require(var0.Src.Controllers.MaterialsController)
return function()
   local var0 = var2:use()
   return var1.useCallback(function()
      var0:removeAllMaterials()
   end, {})
end
