--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["NetworkingContacts-31ab8d40-0.4.2"]["NetworkingContacts"])

return Package
