--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["ChalkLua-31ab8d40-0.2.0"]["ChalkLua"])

return Package
