return {
	WHITESPACE = {
		[0x0009] = true, -- Tab (HT)
		[0x000A] = true, -- Line Feed (LF)
		[0x000C] = true, -- Form Feed (FF)
		[0x000D] = true, -- Carriage Return (CR)
		[0x0020] = true, -- Space (SP)
		[0x00A0] = true, -- No-Break Space (NBSP)
		[0x1680] = true, -- Ogham Space Mark
		[0x2000] = true, -- En Quad
		[0x2001] = true, -- Em Quad
		[0x2002] = true, -- En Space
		[0x2003] = true, -- Em Space
		[0x2004] = true, -- Three-Per-Em Space
		[0x2005] = true, -- Four-Per-Em Space
		[0x2006] = true, -- Six-Per-Em Space
		[0x2007] = true, -- Figure Space
		[0x2008] = true, -- Punctuation Space
		[0x2009] = true, -- Thin Space
		[0x200A] = true, -- Hair Space
		[0x202F] = true, -- Narrow No-Break Space (NNBSP)
		[0x205F] = true, -- Medium Mathematical Space (MMSP)
		[0x3000] = true, -- Ideographic Space
	},
	PUNCTUATION = {
		[0x005F] = true, -- Low Line
		[0x203F] = true, -- Undertie
		[0x2040] = true, -- Character Tie
		[0x2054] = true, -- Inverted Undertie
		[0xFE33] = true, -- Presentation Form For Vertical Low Line
		[0xFE34] = true, -- Presentation Form For Vertical Wavy Low Line
		[0xFE4D] = true, -- Dashed Low Line
		[0xFE4E] = true, -- Centreline Low Line
		[0xFE4F] = true, -- Wavy Low Line
		[0xFF3F] = true, -- Fullwidth Low Line
		[0x002D] = true, -- Hyphen-Minus
		[0x058A] = true, -- Armenian Hyphen
		[0x05BE] = true, -- Hebrew Punctuation Maqaf
		[0x1400] = true, -- Canadian Syllabics Hyphen
		[0x1806] = true, -- Mongolian Todo Soft Hyphen
		[0x2010] = true, -- Hyphen
		[0x2011] = true, -- Non-Breaking Hyphen
		[0x2012] = true, -- Figure Dash
		[0x2013] = true, -- En Dash
		[0x2014] = true, -- Em Dash
		[0x2015] = true, -- Horizontal Bar
		[0x2E17] = true, -- Double Oblique Hyphen
		[0x2E1A] = true, -- Hyphen with Diaeresis
		[0x2E3A] = true, -- Two-Em Dash
		[0x2E3B] = true, -- Three-Em Dash
		[0x2E40] = true, -- Double Hyphen
		[0x301C] = true, -- Wave Dash
		[0x3030] = true, -- Wavy Dash
		[0x30A0] = true, -- Katakana-Hiragana Double Hyphen
		[0xFE31] = true, -- Presentation Form For Vertical Em Dash
		[0xFE32] = true, -- Presentation Form For Vertical En Dash
		[0xFE58] = true, -- Small Em Dash
		[0xFE63] = true, -- Small Hyphen-Minus
		[0xFF0D] = true, -- Fullwidth Hyphen-Minus
		[0x10EAD] = true, -- Yezidi Hyphenation Mark
		[0x0029] = true, -- Right Parenthesis
		[0x005D] = true, -- Right Square Bracket
		[0x007D] = true, -- Right Curly Bracket
		[0x0F3B] = true, -- Tibetan Mark Gug Rtags Gyas
		[0x0F3D] = true, -- Tibetan Mark Ang Khang Gyas
		[0x169C] = true, -- Ogham Reversed Feather Mark
		[0x2046] = true, -- Right Square Bracket with Quill
		[0x207E] = true, -- Superscript Right Parenthesis
		[0x208E] = true, -- Subscript Right Parenthesis
		[0x2309] = true, -- Right Ceiling
		[0x230B] = true, -- Right Floor
		[0x232A] = true, -- Right-Pointing Angle Bracket
		[0x2769] = true, -- Medium Right Parenthesis Ornament
		[0x276B] = true, -- Medium Flattened Right Parenthesis Ornament
		[0x276D] = true, -- Medium Right-Pointing Angle Bracket Ornament
		[0x276F] = true, -- Heavy Right-Pointing Angle Quotation Mark Ornament
		[0x2771] = true, -- Heavy Right-Pointing Angle Bracket Ornament
		[0x2773] = true, -- Light Right Tortoise Shell Bracket Ornament
		[0x2775] = true, -- Medium Right Curly Bracket Ornament
		[0x27C6] = true, -- Right S-Shaped Bag Delimiter
		[0x27E7] = true, -- Mathematical Right White Square Bracket
		[0x27E9] = true, -- Mathematical Right Angle Bracket
		[0x27EB] = true, -- Mathematical Right Double Angle Bracket
		[0x27ED] = true, -- Mathematical Right White Tortoise Shell Bracket
		[0x27EF] = true, -- Mathematical Right Flattened Parenthesis
		[0x2984] = true, -- Right White Curly Bracket
		[0x2986] = true, -- Right White Parenthesis
		[0x2988] = true, -- Z Notation Right Image Bracket
		[0x298A] = true, -- Z Notation Right Binding Bracket
		[0x298C] = true, -- Right Square Bracket with Underbar
		[0x298E] = true, -- Right Square Bracket with Tick In Bottom Corner
		[0x2990] = true, -- Right Square Bracket with Tick In Top Corner
		[0x2992] = true, -- Right Angle Bracket with Dot
		[0x2994] = true, -- Right Arc Greater-Than Bracket
		[0x2996] = true, -- Double Right Arc Less-Than Bracket
		[0x2998] = true, -- Right Black Tortoise Shell Bracket
		[0x29D9] = true, -- Right Wiggly Fence
		[0x29DB] = true, -- Right Double Wiggly Fence
		[0x29FD] = true, -- Right-Pointing Curved Angle Bracket
		[0x2E23] = true, -- Top Right Half Bracket
		[0x2E25] = true, -- Bottom Right Half Bracket
		[0x2E27] = true, -- Right Sideways U Bracket
		[0x2E29] = true, -- Right Double Parenthesis
		[0x3009] = true, -- Right Angle Bracket
		[0x300B] = true, -- Right Double Angle Bracket
		[0x300D] = true, -- Right Corner Bracket
		[0x300F] = true, -- Right White Corner Bracket
		[0x3011] = true, -- Right Black Lenticular Bracket
		[0x3015] = true, -- Right Tortoise Shell Bracket
		[0x3017] = true, -- Right White Lenticular Bracket
		[0x3019] = true, -- Right White Tortoise Shell Bracket
		[0x301B] = true, -- Right White Square Bracket
		[0x301E] = true, -- Double Prime Quotation Mark
		[0x301F] = true, -- Low Double Prime Quotation Mark
		[0xFD3E] = true, -- Ornate Left Parenthesis
		[0xFE18] = true, -- Presentation Form For Vertical Right White Lenticular Brakcet
		[0xFE36] = true, -- Presentation Form For Vertical Right Parenthesis
		[0xFE38] = true, -- Presentation Form For Vertical Right Curly Bracket
		[0xFE3A] = true, -- Presentation Form For Vertical Right Tortoise Shell Bracket
		[0xFE3C] = true, -- Presentation Form For Vertical Right Black Lenticular Bracket
		[0xFE3E] = true, -- Presentation Form For Vertical Right Double Angle Bracket
		[0xFE40] = true, -- Presentation Form For Vertical Right Angle Bracket
		[0xFE42] = true, -- Presentation Form For Vertical Right Corner Bracket
		[0xFE44] = true, -- Presentation Form For Vertical Right White Corner Bracket
		[0xFE48] = true, -- Presentation Form For Vertical Right Square Bracket
		[0xFE5A] = true, -- Small Right Parenthesis
		[0xFE5C] = true, -- Small Right Curly Bracket
		[0xFE5E] = true, -- Small Right Tortoise Shell Bracket
		[0xFF09] = true, -- Fullwidth Right Parenthesis
		[0xFF3D] = true, -- Fullwidth Right Square Bracket
		[0xFF5D] = true, -- Fullwidth Right Curly Bracket
		[0xFF60] = true, -- Fullwidth Right White Parenthesis
		[0xFF63] = true, -- Halfwidth Right Corner Bracket
		[0x00BB] = true, -- Right-Pointing Double Angle Quotation Mark
		[0x2019] = true, -- Right Single Quotation Mark
		[0x201D] = true, -- Right Double Quotation Mark
		[0x203A] = true, -- Single Right-Pointing Angle Quotation Mark
		[0x2E03] = true, -- Right Substitution Bracket
		[0x2E05] = true, -- Right Dotted Substitution Bracket
		[0x2E0A] = true, -- Right Transposition Bracket
		[0x2E0D] = true, -- Right Raised Omission Bracket
		[0x2E1D] = true, -- Right Low Paraphrase Bracket
		[0x2E21] = true, -- Right Vertical Bar with Quill
		[0x00AB] = true, -- Left-Pointing Double Angle Quotation Mark
		[0x2018] = true, -- Left Single Quotation Mark
		[0x201B] = true, -- Single High-Reversed-9 Quotation Mark
		[0x201C] = true, -- Left Double Quotation Mark
		[0x201F] = true, -- Double High-Reversed-9 Quotation Mark
		[0x2039] = true, -- Single Left-Pointing Angle Quotation Mark
		[0x2E02] = true, -- Left Substitution Bracket
		[0x2E04] = true, -- Left Dotted Substitution Bracket
		[0x2E09] = true, -- Left Transposition Bracket
		[0x2E0C] = true, -- Left Raised Omission Bracket
		[0x2E1C] = true, -- Left Low Paraphrase Bracket
		[0x2E20] = true, -- Left Vertical Bar with Quill
		[0x0021] = true, -- Exclamation Mark
		[0x0022] = true, -- Quotation Mark
		[0x0023] = true, -- Number Sign
		[0x0025] = true, -- Percent Sign
		[0x0026] = true, -- Ampersand
		[0x0027] = true, -- Apostrophe
		[0x002A] = true, -- Asterisk
		[0x002C] = true, -- Comma
		[0x002E] = true, -- Full Stop
		[0x002F] = true, -- Solidus
		[0x003A] = true, -- Colon
		[0x003B] = true, -- Semicolon
		[0x003F] = true, -- Question Mark
		[0x0040] = true, -- Commercial At
		[0x005C] = true, -- Reverse Solidus
		[0x00A1] = true, -- Inverted Exclamation Mark
		[0x00A7] = true, -- Section Sign
		[0x00B6] = true, -- Pilcrow Sign
		[0x00B7] = true, -- Middle Dot
		[0x00BF] = true, -- Inverted Question Mark
		[0x037E] = true, -- Greek Question Mark
		[0x0387] = true, -- Greek Ano Teleia
		[0x055A] = true, -- Armenian Apostrophe
		[0x055B] = true, -- Armenian Emphasis Mark
		[0x055C] = true, -- Armenian Exclamation Mark
		[0x055D] = true, -- Armenian Comma
		[0x055E] = true, -- Armenian Question Mark
		[0x055F] = true, -- Armenian Abbreviation Mark
		[0x0589] = true, -- Armenian Full Stop
		[0x05C0] = true, -- Hebrew Punctuation Paseq
		[0x05C3] = true, -- Hebrew Punctuation Sof Pasuq
		[0x05C6] = true, -- Hebrew Punctuation Nun Hafukha
		[0x05F3] = true, -- Hebrew Punctuation Geresh
		[0x05F4] = true, -- Hebrew Punctuation Gershayim
		[0x0609] = true, -- Arabic-Indic Per Mille Sign
		[0x060A] = true, -- Arabic-Indic Per Ten Thousand Sign
		[0x060C] = true, -- Arabic Comma
		[0x060D] = true, -- Arabic Date Separator
		[0x061B] = true, -- Arabic Semicolon
		[0x061E] = true, -- Arabic Triple Dot Punctuation Mark
		[0x061F] = true, -- Arabic Question Mark
		[0x066A] = true, -- Arabic Percent Sign
		[0x066B] = true, -- Arabic Decimal Separator
		[0x066C] = true, -- Arabic Thousands Separator
		[0x066D] = true, -- Arabic Five Pointed Star
		[0x06D4] = true, -- Arabic Full Stop
		[0x0700] = true, -- Syriac End of Paragraph
		[0x0701] = true, -- Syriac Supralinear Full Stop
		[0x0702] = true, -- Syriac Sublinear Full Stop
		[0x0703] = true, -- Syriac Supralinear Colon
		[0x0704] = true, -- Syriac Sublinear Colon
		[0x0705] = true, -- Syriac Horizontal Colon
		[0x0706] = true, -- Syriac Colon Skewed Left
		[0x0707] = true, -- Syriac Colon Skewed Right
		[0x0708] = true, -- Syriac Supralinear Colon Skewed Left
		[0x0709] = true, -- Syriac Sublinear Colon Skewed Right
		[0x070A] = true, -- Syriac Contraction
		[0x070B] = true, -- Syriac Harklean Obelus
		[0x070C] = true, -- Syriac Harklean Metobelus
		[0x070D] = true, -- Syriac Harklean Asteriscus
		[0x07F7] = true, -- Nko Symbol Gbakurunen
		[0x07F8] = true, -- Nko Comma
		[0x07F9] = true, -- Nko Exclamation Mark
		[0x0830] = true, -- Samaritan Punctuation Nequdaa
		[0x0831] = true, -- Samaritan Punctuation Afsaaq
		[0x0832] = true, -- Samaritan Punctuation Anged
		[0x0833] = true, -- Samaritan Punctuation Bau
		[0x0834] = true, -- Samaritan Punctuation Atmaau
		[0x0835] = true, -- Samaritan Punctuation Shiyyaalaa
		[0x0836] = true, -- Samaritan Abbreviation Mark
		[0x0837] = true, -- Samaritan Punctuation Melodic Qitsa
		[0x0838] = true, -- Samaritan Punctuation Ziqaa
		[0x0839] = true, -- Samaritan Punctuation Qitsa
		[0x083A] = true, -- Samaritan Punctuation Zaef
		[0x083B] = true, -- Samaritan Punctuation Turu
		[0x083C] = true, -- Samaritan Punctuation Arkaanu
		[0x083D] = true, -- Samaritan Punctuation Sof Mashfaat
		[0x083E] = true, -- Samaritan Punctuation Annaau
		[0x085E] = true, -- Mandaic Punctuation
		[0x0964] = true, -- Devanagari Danda
		[0x0965] = true, -- Devanagari Double Danda
		[0x0970] = true, -- Devanagari Abbreviation Sign
		[0x09FD] = true, -- Bengali Abbreviation Sign
		[0x0A76] = true, -- Gurmukhi Abbreviation Sign
		[0x0AF0] = true, -- Gujarati Abbreviation Sign
		[0x0C77] = true, -- Telugu Sign Siddham
		[0x0C84] = true, -- Kannada Sign Siddham
		[0x0DF4] = true, -- Sinhala Punctuation Kunddaliya
		[0x0E4F] = true, -- Thai Character Fongman
		[0x0E5A] = true, -- Thai Character Angkhankhu
		[0x0E5B] = true, -- Thai Character Khomut
		[0x0F04] = true, -- Tibetan Mark Initial Yig Mgo Mdun Ma
		[0x0F05] = true, -- Tibetan Mark Closing Yig Mgo Sgab Ma
		[0x0F06] = true, -- Tibetan Mark Caret Yig Mgo Phur Shad Ma
		[0x0F07] = true, -- Tibetan Mark Yig Mgo Tsheg Shad Ma
		[0x0F08] = true, -- Tibetan Mark Sbrul Shad
		[0x0F09] = true, -- Tibetan Mark Bskur Yig Mgo
		[0x0F0A] = true, -- Tibetan Mark Bka-undefined Shog Yig Mgo
		[0x0F0B] = true, -- Tibetan Mark Intersyllabic Tsheg
		[0x0F0C] = true, -- Tibetan Mark Delimiter Tsheg Bstar
		[0x0F0D] = true, -- Tibetan Mark Shad
		[0x0F0E] = true, -- Tibetan Mark Nyis Shad
		[0x0F0F] = true, -- Tibetan Mark Tsheg Shad
		[0x0F10] = true, -- Tibetan Mark Nyis Tsheg Shad
		[0x0F11] = true, -- Tibetan Mark Rin Chen Spungs Shad
		[0x0F12] = true, -- Tibetan Mark Rgya Gram Shad
		[0x0F14] = true, -- Tibetan Mark Gter Tsheg
		[0x0F85] = true, -- Tibetan Mark Paluta
		[0x0FD0] = true, -- Tibetan Mark Bska-undefined Shog Gi Mgo Rgyan
		[0x0FD1] = true, -- Tibetan Mark Mnyam Yig Gi Mgo Rgyan
		[0x0FD2] = true, -- Tibetan Mark Nyis Tsheg
		[0x0FD3] = true, -- Tibetan Mark Initial Brda Rnying Yig Mgo Mdun Ma
		[0x0FD4] = true, -- Tibetan Mark Closing Brda Rnying Yig Mgo Sgab Ma
		[0x0FD9] = true, -- Tibetan Mark Leading Mchan Rtags
		[0x0FDA] = true, -- Tibetan Mark Trailing Mchan Rtags
		[0x104A] = true, -- Myanmar Sign Little Section
		[0x104B] = true, -- Myanmar Sign Section
		[0x104C] = true, -- Myanmar Symbol Locative
		[0x104D] = true, -- Myanmar Symbol Completed
		[0x104E] = true, -- Myanmar Symbol Aforementioned
		[0x104F] = true, -- Myanmar Symbol Genitive
		[0x10FB] = true, -- Georgian Paragraph Separator
		[0x1360] = true, -- Ethiopic Section Mark
		[0x1361] = true, -- Ethiopic Wordspace
		[0x1362] = true, -- Ethiopic Full Stop
		[0x1363] = true, -- Ethiopic Comma
		[0x1364] = true, -- Ethiopic Semicolon
		[0x1365] = true, -- Ethiopic Colon
		[0x1366] = true, -- Ethiopic Preface Colon
		[0x1367] = true, -- Ethiopic Question Mark
		[0x1368] = true, -- Ethiopic Paragraph Separator
		[0x166E] = true, -- Canadian Syllabics Full Stop
		[0x16EB] = true, -- Runic Single Punctuation
		[0x16EC] = true, -- Runic Multiple Punctuation
		[0x16ED] = true, -- Runic Cross Punctuation
		[0x1735] = true, -- Philippine Single Punctuation
		[0x1736] = true, -- Philippine Double Punctuation
		[0x17D4] = true, -- Khmer Sign Khan
		[0x17D5] = true, -- Khmer Sign Bariyoosan
		[0x17D6] = true, -- Khmer Sign Camnuc Pii Kuuh
		[0x17D8] = true, -- Khmer Sign Beyyal
		[0x17D9] = true, -- Khmer Sign Phnaek Muan
		[0x17DA] = true, -- Khmer Sign Koomuut
		[0x1800] = true, -- Mongolian Birga
		[0x1801] = true, -- Mongolian Ellipsis
		[0x1802] = true, -- Mongolian Comma
		[0x1803] = true, -- Mongolian Full Stop
		[0x1804] = true, -- Mongolian Colon
		[0x1805] = true, -- Mongolian Four Dots
		[0x1807] = true, -- Mongolian Sibe Syllable Boundary Marker
		[0x1808] = true, -- Mongolian Manchu Comma
		[0x1809] = true, -- Mongolian Manchu Full Stop
		[0x180A] = true, -- Mongolian Nirugu
		[0x1944] = true, -- Limbu Exclamation Mark
		[0x1945] = true, -- Limbu Question Mark
		[0x1A1E] = true, -- Buginese Pallawa
		[0x1A1F] = true, -- Buginese End of Section
		[0x1AA0] = true, -- Tai Tham Sign Wiang
		[0x1AA1] = true, -- Tai Tham Sign Wiangwaak
		[0x1AA2] = true, -- Tai Tham Sign Sawan
		[0x1AA3] = true, -- Tai Tham Sign Keow
		[0x1AA4] = true, -- Tai Tham Sign Hoy
		[0x1AA5] = true, -- Tai Tham Sign Dokmai
		[0x1AA6] = true, -- Tai Tham Sign Reversed Rotated Rana
		[0x1AA8] = true, -- Tai Tham Sign Kaan
		[0x1AA9] = true, -- Tai Tham Sign Kaankuu
		[0x1AAA] = true, -- Tai Tham Sign Satkaan
		[0x1AAB] = true, -- Tai Tham Sign Satkaankuu
		[0x1AAC] = true, -- Tai Tham Sign Hang
		[0x1AAD] = true, -- Tai Tham Sign Caang
		[0x1B5A] = true, -- Balinese Panti
		[0x1B5B] = true, -- Balinese Pamada
		[0x1B5C] = true, -- Balinese Windu
		[0x1B5D] = true, -- Balinese Carik Pamungkah
		[0x1B5E] = true, -- Balinese Carik Siki
		[0x1B5F] = true, -- Balinese Carik Pareren
		[0x1B60] = true, -- Balinese Pameneng
		[0x1BFC] = true, -- Batak Symbol Bindu Na Metek
		[0x1BFD] = true, -- Batak Symbol Bindu Pinarboras
		[0x1BFE] = true, -- Batak Symbol Bindu Judul
		[0x1BFF] = true, -- Batak Symbol Bindu Pangolat
		[0x1C3B] = true, -- Lepcha Punctuation Ta-Rol
		[0x1C3C] = true, -- Lepcha Punctuation Nyet Thyoom Ta-Rol
		[0x1C3D] = true, -- Lepcha Punctuation Cer-Wa
		[0x1C3E] = true, -- Lepcha Punctuation Tshook Cer-Wa
		[0x1C3F] = true, -- Lepcha Punctuation Tshook
		[0x1C7E] = true, -- Ol Chiki Punctuation Mucaad
		[0x1C7F] = true, -- Ol Chiki Punctuation Double Mucaad
		[0x1CC0] = true, -- Sundanese Punctuation Bindu Surya
		[0x1CC1] = true, -- Sundanese Punctuation Bindu Panglong
		[0x1CC2] = true, -- Sundanese Punctuation Bindu Purnama
		[0x1CC3] = true, -- Sundanese Punctuation Bindu Cakra
		[0x1CC4] = true, -- Sundanese Punctuation Bindu Leu Satanga
		[0x1CC5] = true, -- Sundanese Punctuation Bindu Ka Satanga
		[0x1CC6] = true, -- Sundanese Punctuation Bindu Da Satanga
		[0x1CC7] = true, -- Sundanese Punctuation Bindu Ba Satanga
		[0x1CD3] = true, -- Vedic Sign Nihshvasa
		[0x2016] = true, -- Double Vertical Line
		[0x2017] = true, -- Double Low Line
		[0x2020] = true, -- Dagger
		[0x2021] = true, -- Double Dagger
		[0x2022] = true, -- Bullet
		[0x2023] = true, -- Triangular Bullet
		[0x2024] = true, -- One Dot Leader
		[0x2025] = true, -- Two Dot Leader
		[0x2026] = true, -- Horizontal Ellipsis
		[0x2027] = true, -- Hyphenation Point
		[0x2030] = true, -- Per Mille Sign
		[0x2031] = true, -- Per Ten Thousand Sign
		[0x2032] = true, -- Prime
		[0x2033] = true, -- Double Prime
		[0x2034] = true, -- Triple Prime
		[0x2035] = true, -- Reversed Prime
		[0x2036] = true, -- Reversed Double Prime
		[0x2037] = true, -- Reversed Triple Prime
		[0x2038] = true, -- Caret
		[0x203B] = true, -- Reference Mark
		[0x203C] = true, -- Double Exclamation Mark
		[0x203D] = true, -- Interrobang
		[0x203E] = true, -- Overline
		[0x2041] = true, -- Caret Insertion Point
		[0x2042] = true, -- Asterism
		[0x2043] = true, -- Hyphen Bullet
		[0x2047] = true, -- Double Question Mark
		[0x2048] = true, -- Question Exclamation Mark
		[0x2049] = true, -- Exclamation Question Mark
		[0x204A] = true, -- Tironian Sign Et
		[0x204B] = true, -- Reversed Pilcrow Sign
		[0x204C] = true, -- Black Leftwards Bullet
		[0x204D] = true, -- Black Rightwards Bullet
		[0x204E] = true, -- Low Asterisk
		[0x204F] = true, -- Reversed Semicolon
		[0x2050] = true, -- Close Up
		[0x2051] = true, -- Two Asterisks Aligned Vertically
		[0x2053] = true, -- Swung Dash
		[0x2055] = true, -- Flower Punctuation Mark
		[0x2056] = true, -- Three Dot Punctuation
		[0x2057] = true, -- Quadruple Prime
		[0x2058] = true, -- Four Dot Punctuation
		[0x2059] = true, -- Five Dot Punctuation
		[0x205A] = true, -- Two Dot Punctuation
		[0x205B] = true, -- Four Dot Mark
		[0x205C] = true, -- Dotted Cross
		[0x205D] = true, -- Tricolon
		[0x205E] = true, -- Vertical Four Dots
		[0x2CF9] = true, -- Coptic Old Nubian Full Stop
		[0x2CFA] = true, -- Coptic Old Nubian Direct Question Mark
		[0x2CFB] = true, -- Coptic Old Nubian Indirect Question Mark
		[0x2CFC] = true, -- Coptic Old Nubian Verse Divider
		[0x2CFE] = true, -- Coptic Full Stop
		[0x2CFF] = true, -- Coptic Morphological Divider
		[0x2D70] = true, -- Tifinagh Separator Mark
		[0x2E00] = true, -- Right Angle Substitution Marker
		[0x2E01] = true, -- Right Angle Dotted Substitution Marker
		[0x2E06] = true, -- Raised Interpolation Marker
		[0x2E07] = true, -- Raised Dotted Interpolation Marker
		[0x2E08] = true, -- Dotted Transposition Marker
		[0x2E0B] = true, -- Raised Square
		[0x2E0E] = true, -- Editorial Coronis
		[0x2E0F] = true, -- Paragraphos
		[0x2E10] = true, -- Forked Paragraphos
		[0x2E11] = true, -- Reversed Forked Paragraphos
		[0x2E12] = true, -- Hypodiastole
		[0x2E13] = true, -- Dotted Obelos
		[0x2E14] = true, -- Downwards Ancora
		[0x2E15] = true, -- Upwards Ancora
		[0x2E16] = true, -- Dotted Right-Pointing Angle
		[0x2E18] = true, -- Inverted Interrobang
		[0x2E19] = true, -- Palm Branch
		[0x2E1B] = true, -- Tilde with Ring Above
		[0x2E1E] = true, -- Tilde with Dot Above
		[0x2E1F] = true, -- Tilde with Dot Below
		[0x2E2A] = true, -- Two Dots Over One Dot Punctuation
		[0x2E2B] = true, -- One Dot Over Two Dots Punctuation
		[0x2E2C] = true, -- Squared Four Dot Punctuation
		[0x2E2D] = true, -- Five Dot Mark
		[0x2E2E] = true, -- Reversed Question Mark
		[0x2E30] = true, -- Ring Point
		[0x2E31] = true, -- Word Separator Middle Dot
		[0x2E32] = true, -- Turned Comma
		[0x2E33] = true, -- Raised Dot
		[0x2E34] = true, -- Raised Comma
		[0x2E35] = true, -- Turned Semicolon
		[0x2E36] = true, -- Dagger with Left Guard
		[0x2E37] = true, -- Dagger with Right Guard
		[0x2E38] = true, -- Turned Dagger
		[0x2E39] = true, -- Top Half Section Sign
		[0x2E3C] = true, -- Stenographic Full Stop
		[0x2E3D] = true, -- Vertical Six Dots
		[0x2E3E] = true, -- Wiggly Vertical Line
		[0x2E3F] = true, -- Capitulum
		[0x2E41] = true, -- Reversed Comma
		[0x2E43] = true, -- Dash with Left Upturn
		[0x2E44] = true, -- Double Suspension Mark
		[0x2E45] = true, -- Inverted Low Kavyka
		[0x2E46] = true, -- Inverted Low Kavyka with Kavyka Above
		[0x2E47] = true, -- Low Kavyka
		[0x2E48] = true, -- Low Kavyka with Dot
		[0x2E49] = true, -- Double Stacked Comma
		[0x2E4A] = true, -- Dotted Solidus
		[0x2E4B] = true, -- Triple Dagger
		[0x2E4C] = true, -- Medieval Comma
		[0x2E4D] = true, -- Paragraphus Mark
		[0x2E4E] = true, -- Punctus Elevatus Mark
		[0x2E4F] = true, -- Cornish Verse Divider
		[0x2E52] = true, -- Tironian Sign Capital Et
		[0x3001] = true, -- Ideographic Comma
		[0x3002] = true, -- Ideographic Full Stop
		[0x3003] = true, -- Ditto Mark
		[0x303D] = true, -- Part Alternation Mark
		[0x30FB] = true, -- Katakana Middle Dot
		[0xA4FE] = true, -- Lisu Punctuation Comma
		[0xA4FF] = true, -- Lisu Punctuation Full Stop
		[0xA60D] = true, -- Vai Comma
		[0xA60E] = true, -- Vai Full Stop
		[0xA60F] = true, -- Vai Question Mark
		[0xA673] = true, -- Slavonic Asterisk
		[0xA67E] = true, -- Cyrillic Kavyka
		[0xA6F2] = true, -- Bamum Njaemli
		[0xA6F3] = true, -- Bamum Full Stop
		[0xA6F4] = true, -- Bamum Colon
		[0xA6F5] = true, -- Bamum Comma
		[0xA6F6] = true, -- Bamum Semicolon
		[0xA6F7] = true, -- Bamum Question Mark
		[0xA874] = true, -- Phags-Pa Single Head Mark
		[0xA875] = true, -- Phags-Pa Double Head Mark
		[0xA876] = true, -- Phags-Pa Mark Shad
		[0xA877] = true, -- Phags-Pa Mark Double Shad
		[0xA8CE] = true, -- Saurashtra Danda
		[0xA8CF] = true, -- Saurashtra Double Danda
		[0xA8F8] = true, -- Devanagari Sign Pushpika
		[0xA8F9] = true, -- Devanagari Gap Filler
		[0xA8FA] = true, -- Devanagari Caret
		[0xA8FC] = true, -- Devanagari Sign Siddham
		[0xA92E] = true, -- Kayah Li Sign Cwi
		[0xA92F] = true, -- Kayah Li Sign Shya
		[0xA95F] = true, -- Rejang Section Mark
		[0xA9C1] = true, -- Javanese Left Rerenggan
		[0xA9C2] = true, -- Javanese Right Rerenggan
		[0xA9C3] = true, -- Javanese Pada Andap
		[0xA9C4] = true, -- Javanese Pada Madya
		[0xA9C5] = true, -- Javanese Pada Luhur
		[0xA9C6] = true, -- Javanese Pada Windu
		[0xA9C7] = true, -- Javanese Pada Pangkat
		[0xA9C8] = true, -- Javanese Pada Lingsa
		[0xA9C9] = true, -- Javanese Pada Lungsi
		[0xA9CA] = true, -- Javanese Pada Adeg
		[0xA9CB] = true, -- Javanese Pada Adeg Adeg
		[0xA9CC] = true, -- Javanese Pada Piseleh
		[0xA9CD] = true, -- Javanese Turned Pada Piseleh
		[0xA9DE] = true, -- Javanese Pada Tirta Tumetes
		[0xA9DF] = true, -- Javanese Pada Isen-Isen
		[0xAA5C] = true, -- Cham Punctuation Spiral
		[0xAA5D] = true, -- Cham Punctuation Danda
		[0xAA5E] = true, -- Cham Punctuation Double Danda
		[0xAA5F] = true, -- Cham Punctuation Triple Danda
		[0xAADE] = true, -- Tai Viet Symbol Ho Hoi
		[0xAADF] = true, -- Tai Viet Symbol Koi Koi
		[0xAAF0] = true, -- Meetei Mayek Cheikhan
		[0xAAF1] = true, -- Meetei Mayek Ahang Khudam
		[0xABEB] = true, -- Meetei Mayek Cheikhei
		[0xFE10] = true, -- Presentation Form For Vertical Comma
		[0xFE11] = true, -- Presentation Form For Vertical Ideographic Comma
		[0xFE12] = true, -- Presentation Form For Vertical Ideographic Full Stop
		[0xFE13] = true, -- Presentation Form For Vertical Colon
		[0xFE14] = true, -- Presentation Form For Vertical Semicolon
		[0xFE15] = true, -- Presentation Form For Vertical Exclamation Mark
		[0xFE16] = true, -- Presentation Form For Vertical Question Mark
		[0xFE19] = true, -- Presentation Form For Vertical Horizontal Ellipsis
		[0xFE30] = true, -- Presentation Form For Vertical Two Dot Leader
		[0xFE45] = true, -- Sesame Dot
		[0xFE46] = true, -- White Sesame Dot
		[0xFE49] = true, -- Dashed Overline
		[0xFE4A] = true, -- Centreline Overline
		[0xFE4B] = true, -- Wavy Overline
		[0xFE4C] = true, -- Double Wavy Overline
		[0xFE50] = true, -- Small Comma
		[0xFE51] = true, -- Small Ideographic Comma
		[0xFE52] = true, -- Small Full Stop
		[0xFE54] = true, -- Small Semicolon
		[0xFE55] = true, -- Small Colon
		[0xFE56] = true, -- Small Question Mark
		[0xFE57] = true, -- Small Exclamation Mark
		[0xFE5F] = true, -- Small Number Sign
		[0xFE60] = true, -- Small Ampersand
		[0xFE61] = true, -- Small Asterisk
		[0xFE68] = true, -- Small Reverse Solidus
		[0xFE6A] = true, -- Small Percent Sign
		[0xFE6B] = true, -- Small Commercial At
		[0xFF01] = true, -- Fullwidth Exclamation Mark
		[0xFF02] = true, -- Fullwidth Quotation Mark
		[0xFF03] = true, -- Fullwidth Number Sign
		[0xFF05] = true, -- Fullwidth Percent Sign
		[0xFF06] = true, -- Fullwidth Ampersand
		[0xFF07] = true, -- Fullwidth Apostrophe
		[0xFF0A] = true, -- Fullwidth Asterisk
		[0xFF0C] = true, -- Fullwidth Comma
		[0xFF0E] = true, -- Fullwidth Full Stop
		[0xFF0F] = true, -- Fullwidth Solidus
		[0xFF1A] = true, -- Fullwidth Colon
		[0xFF1B] = true, -- Fullwidth Semicolon
		[0xFF1F] = true, -- Fullwidth Question Mark
		[0xFF20] = true, -- Fullwidth Commercial At
		[0xFF3C] = true, -- Fullwidth Reverse Solidus
		[0xFF61] = true, -- Halfwidth Ideographic Full Stop
		[0xFF64] = true, -- Halfwidth Ideographic Comma
		[0xFF65] = true, -- Halfwidth Katakana Middle Dot
		[0x10100] = true, -- Aegean Word Separator Line
		[0x10101] = true, -- Aegean Word Separator Dot
		[0x10102] = true, -- Aegean Check Mark
		[0x1039F] = true, -- Ugaritic Word Divider
		[0x103D0] = true, -- Old Persian Word Divider
		[0x1056F] = true, -- Caucasian Albanian Citation Mark
		[0x10857] = true, -- Imperial Aramaic Section Sign
		[0x1091F] = true, -- Phoenician Word Separator
		[0x1093F] = true, -- Lydian Triangular Mark
		[0x10A50] = true, -- Kharoshthi Punctuation Dot
		[0x10A51] = true, -- Kharoshthi Punctuation Small Circle
		[0x10A52] = true, -- Kharoshthi Punctuation Circle
		[0x10A53] = true, -- Kharoshthi Punctuation Crescent Bar
		[0x10A54] = true, -- Kharoshthi Punctuation Mangalam
		[0x10A55] = true, -- Kharoshthi Punctuation Lotus
		[0x10A56] = true, -- Kharoshthi Punctuation Danda
		[0x10A57] = true, -- Kharoshthi Punctuation Double Danda
		[0x10A58] = true, -- Kharoshthi Punctuation Lines
		[0x10A7F] = true, -- Old South Arabian Numeric Indicator
		[0x10AF0] = true, -- Manichaean Punctuation Star
		[0x10AF1] = true, -- Manichaean Punctuation Fleuron
		[0x10AF2] = true, -- Manichaean Punctuation Double Dot Within Dot
		[0x10AF3] = true, -- Manichaean Punctuation Dot Within Dot
		[0x10AF4] = true, -- Manichaean Punctuation Dot
		[0x10AF5] = true, -- Manichaean Punctuation Two Dots
		[0x10AF6] = true, -- Manichaean Punctuation Line Filler
		[0x10B39] = true, -- Avestan Abbreviation Mark
		[0x10B3A] = true, -- Tiny Two Dots Over One Dot Punctuation
		[0x10B3B] = true, -- Small Two Dots Over One Dot Punctuation
		[0x10B3C] = true, -- Large Two Dots Over One Dot Punctuation
		[0x10B3D] = true, -- Large One Dot Over Two Dots Punctuation
		[0x10B3E] = true, -- Large Two Rings Over One Ring Punctuation
		[0x10B3F] = true, -- Large One Ring Over Two Rings Punctuation
		[0x10B99] = true, -- Psalter Pahlavi Section Mark
		[0x10B9A] = true, -- Psalter Pahlavi Turned Section Mark
		[0x10B9B] = true, -- Psalter Pahlavi Four Dots with Cross
		[0x10B9C] = true, -- Psalter Pahlavi Four Dots with Dot
		[0x10F55] = true, -- Sogdian Punctuation Two Vertical Bars
		[0x10F56] = true, -- Sogdian Punctuation Two Vertical Bars with Dots
		[0x10F57] = true, -- Sogdian Punctuation Circle with Dot
		[0x10F58] = true, -- Sogdian Punctuation Two Circles with Dots
		[0x10F59] = true, -- Sogdian Punctuation Half Circle with Dot
		[0x11047] = true, -- Brahmi Danda
		[0x11048] = true, -- Brahmi Double Danda
		[0x11049] = true, -- Brahmi Punctuation Dot
		[0x1104A] = true, -- Brahmi Punctuation Double Dot
		[0x1104B] = true, -- Brahmi Punctuation Line
		[0x1104C] = true, -- Brahmi Punctuation Crescent Bar
		[0x1104D] = true, -- Brahmi Punctuation Lotus
		[0x110BB] = true, -- Kaithi Abbreviation Sign
		[0x110BC] = true, -- Kaithi Enumeration Sign
		[0x110BE] = true, -- Kaithi Section Mark
		[0x110BF] = true, -- Kaithi Double Section Mark
		[0x110C0] = true, -- Kaithi Danda
		[0x110C1] = true, -- Kaithi Double Danda
		[0x11140] = true, -- Chakma Section Mark
		[0x11141] = true, -- Chakma Danda
		[0x11142] = true, -- Chakma Double Danda
		[0x11143] = true, -- Chakma Question Mark
		[0x11174] = true, -- Mahajani Abbreviation Sign
		[0x11175] = true, -- Mahajani Section Mark
		[0x111C5] = true, -- Sharada Danda
		[0x111C6] = true, -- Sharada Double Danda
		[0x111C7] = true, -- Sharada Abbreviation Sign
		[0x111C8] = true, -- Sharada Separator
		[0x111CD] = true, -- Sharada Sutra Mark
		[0x111DB] = true, -- Sharada Sign Siddham
		[0x111DD] = true, -- Sharada Continuation Sign
		[0x111DE] = true, -- Sharada Section Mark-1
		[0x111DF] = true, -- Sharada Section Mark-2
		[0x11238] = true, -- Khojki Danda
		[0x11239] = true, -- Khojki Double Danda
		[0x1123A] = true, -- Khojki Word Separator
		[0x1123B] = true, -- Khojki Section Mark
		[0x1123C] = true, -- Khojki Double Section Mark
		[0x1123D] = true, -- Khojki Abbreviation Sign
		[0x112A9] = true, -- Multani Section Mark
		[0x1144B] = true, -- Newa Danda
		[0x1144C] = true, -- Newa Double Danda
		[0x1144D] = true, -- Newa Comma
		[0x1144E] = true, -- Newa Gap Filler
		[0x1144F] = true, -- Newa Abbreviation Sign
		[0x1145A] = true, -- Newa Double Comma
		[0x1145B] = true, -- Newa Placeholder Mark
		[0x1145D] = true, -- Newa Insertion Sign
		[0x114C6] = true, -- Tirhuta Abbreviation Sign
		[0x115C1] = true, -- Siddham Sign Siddham
		[0x115C2] = true, -- Siddham Danda
		[0x115C3] = true, -- Siddham Double Danda
		[0x115C4] = true, -- Siddham Separator Dot
		[0x115C5] = true, -- Siddham Separator Bar
		[0x115C6] = true, -- Siddham Repetition Mark-1
		[0x115C7] = true, -- Siddham Repetition Mark-2
		[0x115C8] = true, -- Siddham Repetition Mark-3
		[0x115C9] = true, -- Siddham End of Text Mark
		[0x115CA] = true, -- Siddham Section Mark with Trident and U-Shaped Ornaments
		[0x115CB] = true, -- Siddham Section Mark with Trident and Dotted Crescents
		[0x115CC] = true, -- Siddham Section Mark with Rays and Dotted Crescents
		[0x115CD] = true, -- Siddham Section Mark with Rays and Dotted Double Crescents
		[0x115CE] = true, -- Siddham Section Mark with Rays and Dotted Triple Crescents
		[0x115CF] = true, -- Siddham Section Mark Double Ring
		[0x115D0] = true, -- Siddham Section Mark Double Ring with Rays
		[0x115D1] = true, -- Siddham Section Mark with Double Crescents
		[0x115D2] = true, -- Siddham Section Mark with Triple Crescents
		[0x115D3] = true, -- Siddham Section Mark with Quadruple Crescents
		[0x115D4] = true, -- Siddham Section Mark with Septuple Crescents
		[0x115D5] = true, -- Siddham Section Mark with Circles and Rays
		[0x115D6] = true, -- Siddham Section Mark with Circles and Two Enclosures
		[0x115D7] = true, -- Siddham Section Mark with Circles and Four Enclosures
		[0x11641] = true, -- Modi Danda
		[0x11642] = true, -- Modi Double Danda
		[0x11643] = true, -- Modi Abbreviation Sign
		[0x11660] = true, -- Mongolian Birga with Ornament
		[0x11661] = true, -- Mongolian Rotated Birga
		[0x11662] = true, -- Mongolian Double Birga with Ornament
		[0x11663] = true, -- Mongolian Triple Birga with Ornament
		[0x11664] = true, -- Mongolian Birga with Double Ornament
		[0x11665] = true, -- Mongolian Rotated Birga with Ornament
		[0x11666] = true, -- Mongolian Rotated Birga with Double Ornament
		[0x11667] = true, -- Mongolian Inverted Birga
		[0x11668] = true, -- Mongolian Inverted Birga with Double Ornament
		[0x11669] = true, -- Mongolian Swirl Birga
		[0x1166A] = true, -- Mongolian Swirl Birga with Ornament
		[0x1166B] = true, -- Mongolian Swirl Birga with Double Ornament
		[0x1166C] = true, -- Mongolian Turned Swirl Birga with Double Ornament
		[0x1173C] = true, -- Ahom Sign Small Section
		[0x1173D] = true, -- Ahom Sign Section
		[0x1173E] = true, -- Ahom Sign Rulai
		[0x1183B] = true, -- Dogra Abbreviation Sign
		[0x11944] = true, -- Dives Akuru Double Danda
		[0x11945] = true, -- Dives Akuru Gap Filler
		[0x11946] = true, -- Dives Akuru End of Text Mark
		[0x119E2] = true, -- Nandinagari Sign Siddham
		[0x11A3F] = true, -- Zanabazar Square Initial Head Mark
		[0x11A40] = true, -- Zanabazar Square Closing Head Mark
		[0x11A41] = true, -- Zanabazar Square Mark Tsheg
		[0x11A42] = true, -- Zanabazar Square Mark Shad
		[0x11A43] = true, -- Zanabazar Square Mark Double Shad
		[0x11A44] = true, -- Zanabazar Square Mark Long Tsheg
		[0x11A45] = true, -- Zanabazar Square Initial Double-Lined Head Mark
		[0x11A46] = true, -- Zanabazar Square Closing Double-Lined Head Mark
		[0x11A9A] = true, -- Soyombo Mark Tsheg
		[0x11A9B] = true, -- Soyombo Mark Shad
		[0x11A9C] = true, -- Soyombo Mark Double Shad
		[0x11A9E] = true, -- Soyombo Head Mark with Moon and Sun and Triple Flame
		[0x11A9F] = true, -- Soyombo Head Mark with Moon and Sun and Flame
		[0x11AA0] = true, -- Soyombo Head Mark with Moon and Sun
		[0x11AA1] = true, -- Soyombo Terminal Mark-1
		[0x11AA2] = true, -- Soyombo Terminal Mark-2
		[0x11C41] = true, -- Bhaiksuki Danda
		[0x11C42] = true, -- Bhaiksuki Double Danda
		[0x11C43] = true, -- Bhaiksuki Word Separator
		[0x11C44] = true, -- Bhaiksuki Gap Filler-1
		[0x11C45] = true, -- Bhaiksuki Gap Filler-2
		[0x11C70] = true, -- Marchen Head Mark
		[0x11C71] = true, -- Marchen Mark Shad
		[0x11EF7] = true, -- Makasar Passimbang
		[0x11EF8] = true, -- Makasar End of Section
		[0x11FFF] = true, -- Tamil Punctuation End of Text
		[0x12470] = true, -- Cuneiform Punctuation Sign Old Assyrian Word Divider
		[0x12471] = true, -- Cuneiform Punctuation Sign Vertical Colon
		[0x12472] = true, -- Cuneiform Punctuation Sign Diagonal Colon
		[0x12473] = true, -- Cuneiform Punctuation Sign Diagonal Tricolon
		[0x12474] = true, -- Cuneiform Punctuation Sign Diagonal Quadcolon
		[0x16A6E] = true, -- Mro Danda
		[0x16A6F] = true, -- Mro Double Danda
		[0x16AF5] = true, -- Bassa Vah Full Stop
		[0x16B37] = true, -- Pahawh Hmong Sign Vos Thom
		[0x16B38] = true, -- Pahawh Hmong Sign Vos Tshab Ceeb
		[0x16B39] = true, -- Pahawh Hmong Sign Cim Cheem
		[0x16B3A] = true, -- Pahawh Hmong Sign Vos Thiab
		[0x16B3B] = true, -- Pahawh Hmong Sign Vos Feem
		[0x16B44] = true, -- Pahawh Hmong Sign Xaus
		[0x16E97] = true, -- Medefaidrin Comma
		[0x16E98] = true, -- Medefaidrin Full Stop
		[0x16E99] = true, -- Medefaidrin Symbol Aiva
		[0x16E9A] = true, -- Medefaidrin Exclamation Oh
		[0x16FE2] = true, -- Old Chinese Hook Mark
		[0x1BC9F] = true, -- Duployan Punctuation Chinook Full Stop
		[0x1DA87] = true, -- Signwriting Comma
		[0x1DA88] = true, -- Signwriting Full Stop
		[0x1DA89] = true, -- Signwriting Semicolon
		[0x1DA8A] = true, -- Signwriting Colon
		[0x1DA8B] = true, -- Signwriting Parenthesis
		[0x1E95E] = true, -- Adlam Initial Exclamation Mark
		[0x1E95F] = true, -- Adlam Initial Question Mark
		[0x0028] = true, -- Left Parenthesis
		[0x005B] = true, -- Left Square Bracket
		[0x007B] = true, -- Left Curly Bracket
		[0x0F3A] = true, -- Tibetan Mark Gug Rtags Gyon
		[0x0F3C] = true, -- Tibetan Mark Ang Khang Gyon
		[0x169B] = true, -- Ogham Feather Mark
		[0x201A] = true, -- Single Low-9 Quotation Mark
		[0x201E] = true, -- Double Low-9 Quotation Mark
		[0x2045] = true, -- Left Square Bracket with Quill
		[0x207D] = true, -- Superscript Left Parenthesis
		[0x208D] = true, -- Subscript Left Parenthesis
		[0x2308] = true, -- Left Ceiling
		[0x230A] = true, -- Left Floor
		[0x2329] = true, -- Left-Pointing Angle Bracket
		[0x2768] = true, -- Medium Left Parenthesis Ornament
		[0x276A] = true, -- Medium Flattened Left Parenthesis Ornament
		[0x276C] = true, -- Medium Left-Pointing Angle Bracket Ornament
		[0x276E] = true, -- Heavy Left-Pointing Angle Quotation Mark Ornament
		[0x2770] = true, -- Heavy Left-Pointing Angle Bracket Ornament
		[0x2772] = true, -- Light Left Tortoise Shell Bracket Ornament
		[0x2774] = true, -- Medium Left Curly Bracket Ornament
		[0x27C5] = true, -- Left S-Shaped Bag Delimiter
		[0x27E6] = true, -- Mathematical Left White Square Bracket
		[0x27E8] = true, -- Mathematical Left Angle Bracket
		[0x27EA] = true, -- Mathematical Left Double Angle Bracket
		[0x27EC] = true, -- Mathematical Left White Tortoise Shell Bracket
		[0x27EE] = true, -- Mathematical Left Flattened Parenthesis
		[0x2983] = true, -- Left White Curly Bracket
		[0x2985] = true, -- Left White Parenthesis
		[0x2987] = true, -- Z Notation Left Image Bracket
		[0x2989] = true, -- Z Notation Left Binding Bracket
		[0x298B] = true, -- Left Square Bracket with Underbar
		[0x298D] = true, -- Left Square Bracket with Tick In Top Corner
		[0x298F] = true, -- Left Square Bracket with Tick In Bottom Corner
		[0x2991] = true, -- Left Angle Bracket with Dot
		[0x2993] = true, -- Left Arc Less-Than Bracket
		[0x2995] = true, -- Double Left Arc Greater-Than Bracket
		[0x2997] = true, -- Left Black Tortoise Shell Bracket
		[0x29D8] = true, -- Left Wiggly Fence
		[0x29DA] = true, -- Left Double Wiggly Fence
		[0x29FC] = true, -- Left-Pointing Curved Angle Bracket
		[0x2E22] = true, -- Top Left Half Bracket
		[0x2E24] = true, -- Bottom Left Half Bracket
		[0x2E26] = true, -- Left Sideways U Bracket
		[0x2E28] = true, -- Left Double Parenthesis
		[0x2E42] = true, -- Double Low-Reversed-9 Quotation Mark
		[0x3008] = true, -- Left Angle Bracket
		[0x300A] = true, -- Left Double Angle Bracket
		[0x300C] = true, -- Left Corner Bracket
		[0x300E] = true, -- Left White Corner Bracket
		[0x3010] = true, -- Left Black Lenticular Bracket
		[0x3014] = true, -- Left Tortoise Shell Bracket
		[0x3016] = true, -- Left White Lenticular Bracket
		[0x3018] = true, -- Left White Tortoise Shell Bracket
		[0x301A] = true, -- Left White Square Bracket
		[0x301D] = true, -- Reversed Double Prime Quotation Mark
		[0xFD3F] = true, -- Ornate Right Parenthesis
		[0xFE17] = true, -- Presentation Form For Vertical Left White Lenticular Bracket
		[0xFE35] = true, -- Presentation Form For Vertical Left Parenthesis
		[0xFE37] = true, -- Presentation Form For Vertical Left Curly Bracket
		[0xFE39] = true, -- Presentation Form For Vertical Left Tortoise Shell Bracket
		[0xFE3B] = true, -- Presentation Form For Vertical Left Black Lenticular Bracket
		[0xFE3D] = true, -- Presentation Form For Vertical Left Double Angle Bracket
		[0xFE3F] = true, -- Presentation Form For Vertical Left Angle Bracket
		[0xFE41] = true, -- Presentation Form For Vertical Left Corner Bracket
		[0xFE43] = true, -- Presentation Form For Vertical Left White Corner Bracket
		[0xFE47] = true, -- Presentation Form For Vertical Left Square Bracket
		[0xFE59] = true, -- Small Left Parenthesis
		[0xFE5B] = true, -- Small Left Curly Bracket
		[0xFE5D] = true, -- Small Left Tortoise Shell Bracket
		[0xFF08] = true, -- Fullwidth Left Parenthesis
		[0xFF3B] = true, -- Fullwidth Left Square Bracket
		[0xFF5B] = true, -- Fullwidth Left Curly Bracket
		[0xFF5F] = true, -- Fullwidth Left White Parenthesis
		[0xFF62] = true, -- Halfwidth Left Corner Bracket
		[0x0024] = true, -- Dollar Sign
		[0x00A2] = true, -- Cent Sign
		[0x00A3] = true, -- Pound Sign
		[0x00A4] = true, -- Currency Sign
		[0x00A5] = true, -- Yen Sign
		[0x058F] = true, -- Armenian Dram Sign
		[0x060B] = true, -- Afghani Sign
		[0x07FE] = true, -- Nko Dorome Sign
		[0x07FF] = true, -- Nko Taman Sign
		[0x09F2] = true, -- Bengali Rupee Mark
		[0x09F3] = true, -- Bengali Rupee Sign
		[0x09FB] = true, -- Bengali Ganda Mark
		[0x0AF1] = true, -- Gujarati Rupee Sign
		[0x0BF9] = true, -- Tamil Rupee Sign
		[0x0E3F] = true, -- Thai Currency Symbol Baht
		[0x17DB] = true, -- Khmer Currency Symbol Riel
		[0x20A0] = true, -- Euro-Currency Sign
		[0x20A1] = true, -- Colon Sign
		[0x20A2] = true, -- Cruzeiro Sign
		[0x20A3] = true, -- French Franc Sign
		[0x20A4] = true, -- Lira Sign
		[0x20A5] = true, -- Mill Sign
		[0x20A6] = true, -- Naira Sign
		[0x20A7] = true, -- Peseta Sign
		[0x20A8] = true, -- Rupee Sign
		[0x20A9] = true, -- Won Sign
		[0x20AA] = true, -- New Sheqel Sign
		[0x20AB] = true, -- Dong Sign
		[0x20AC] = true, -- Euro Sign
		[0x20AD] = true, -- Kip Sign
		[0x20AE] = true, -- Tugrik Sign
		[0x20AF] = true, -- Drachma Sign
		[0x20B0] = true, -- German Penny Sign
		[0x20B1] = true, -- Peso Sign
		[0x20B2] = true, -- Guarani Sign
		[0x20B3] = true, -- Austral Sign
		[0x20B4] = true, -- Hryvnia Sign
		[0x20B5] = true, -- Cedi Sign
		[0x20B6] = true, -- Livre Tournois Sign
		[0x20B7] = true, -- Spesmilo Sign
		[0x20B8] = true, -- Tenge Sign
		[0x20B9] = true, -- Indian Rupee Sign
		[0x20BA] = true, -- Turkish Lira Sign
		[0x20BB] = true, -- Nordic Mark Sign
		[0x20BC] = true, -- Manat Sign
		[0x20BD] = true, -- Ruble Sign
		[0x20BE] = true, -- Lari Sign
		[0x20BF] = true, -- Bitcoin Sign
		[0xA838] = true, -- North Indic Rupee Mark
		[0xFDFC] = true, -- Rial Sign
		[0xFE69] = true, -- Small Dollar Sign
		[0xFF04] = true, -- Fullwidth Dollar Sign
		[0xFFE0] = true, -- Fullwidth Cent Sign
		[0xFFE1] = true, -- Fullwidth Pound Sign
		[0xFFE5] = true, -- Fullwidth Yen Sign
		[0xFFE6] = true, -- Fullwidth Won Sign
		[0x11FDD] = true, -- Tamil Sign Kaacu
		[0x11FDE] = true, -- Tamil Sign Panam
		[0x11FDF] = true, -- Tamil Sign Pon
		[0x11FE0] = true, -- Tamil Sign Varaakan
		[0x1E2FF] = true, -- Wancho Ngun Sign
		[0x1ECB0] = true, -- Indic Siyaq Rupee Mark
		[0x005E] = true, -- Circumflex Accent
		[0x0060] = true, -- Grave Accent
		[0x00A8] = true, -- Diaeresis
		[0x00AF] = true, -- Macron
		[0x00B4] = true, -- Acute Accent
		[0x00B8] = true, -- Cedilla
		[0x02C2] = true, -- Modifier Letter Left Arrowhead
		[0x02C3] = true, -- Modifier Letter Right Arrowhead
		[0x02C4] = true, -- Modifier Letter Up Arrowhead
		[0x02C5] = true, -- Modifier Letter Down Arrowhead
		[0x02D2] = true, -- Modifier Letter Centred Right Half Ring
		[0x02D3] = true, -- Modifier Letter Centred Left Half Ring
		[0x02D4] = true, -- Modifier Letter Up Tack
		[0x02D5] = true, -- Modifier Letter Down Tack
		[0x02D6] = true, -- Modifier Letter Plus Sign
		[0x02D7] = true, -- Modifier Letter Minus Sign
		[0x02D8] = true, -- Breve
		[0x02D9] = true, -- Dot Above
		[0x02DA] = true, -- Ring Above
		[0x02DB] = true, -- Ogonek
		[0x02DC] = true, -- Small Tilde
		[0x02DD] = true, -- Double Acute Accent
		[0x02DE] = true, -- Modifier Letter Rhotic Hook
		[0x02DF] = true, -- Modifier Letter Cross Accent
		[0x02E5] = true, -- Modifier Letter Extra-High Tone Bar
		[0x02E6] = true, -- Modifier Letter High Tone Bar
		[0x02E7] = true, -- Modifier Letter Mid Tone Bar
		[0x02E8] = true, -- Modifier Letter Low Tone Bar
		[0x02E9] = true, -- Modifier Letter Extra-Low Tone Bar
		[0x02EA] = true, -- Modifier Letter Yin Departing Tone Mark
		[0x02EB] = true, -- Modifier Letter Yang Departing Tone Mark
		[0x02ED] = true, -- Modifier Letter Unaspirated
		[0x02EF] = true, -- Modifier Letter Low Down Arrowhead
		[0x02F0] = true, -- Modifier Letter Low Up Arrowhead
		[0x02F1] = true, -- Modifier Letter Low Left Arrowhead
		[0x02F2] = true, -- Modifier Letter Low Right Arrowhead
		[0x02F3] = true, -- Modifier Letter Low Ring
		[0x02F4] = true, -- Modifier Letter Middle Grave Accent
		[0x02F5] = true, -- Modifier Letter Middle Double Grave Accent
		[0x02F6] = true, -- Modifier Letter Middle Double Acute Accent
		[0x02F7] = true, -- Modifier Letter Low Tilde
		[0x02F8] = true, -- Modifier Letter Raised Colon
		[0x02F9] = true, -- Modifier Letter Begin High Tone
		[0x02FA] = true, -- Modifier Letter End High Tone
		[0x02FB] = true, -- Modifier Letter Begin Low Tone
		[0x02FC] = true, -- Modifier Letter End Low Tone
		[0x02FD] = true, -- Modifier Letter Shelf
		[0x02FE] = true, -- Modifier Letter Open Shelf
		[0x02FF] = true, -- Modifier Letter Low Left Arrow
		[0x0375] = true, -- Greek Lower Numeral Sign
		[0x0384] = true, -- Greek Tonos
		[0x0385] = true, -- Greek Dialytika Tonos
		[0x1FBD] = true, -- Greek Koronis
		[0x1FBF] = true, -- Greek Psili
		[0x1FC0] = true, -- Greek Perispomeni
		[0x1FC1] = true, -- Greek Dialytika and Perispomeni
		[0x1FCD] = true, -- Greek Psili and Varia
		[0x1FCE] = true, -- Greek Psili and Oxia
		[0x1FCF] = true, -- Greek Psili and Perispomeni
		[0x1FDD] = true, -- Greek Dasia and Varia
		[0x1FDE] = true, -- Greek Dasia and Oxia
		[0x1FDF] = true, -- Greek Dasia and Perispomeni
		[0x1FED] = true, -- Greek Dialytika and Varia
		[0x1FEE] = true, -- Greek Dialytika and Oxia
		[0x1FEF] = true, -- Greek Varia
		[0x1FFD] = true, -- Greek Oxia
		[0x1FFE] = true, -- Greek Dasia
		[0x309B] = true, -- Katakana-Hiragana Voiced Sound Mark
		[0x309C] = true, -- Katakana-Hiragana Semi-Voiced Sound Mark
		[0xA700] = true, -- Modifier Letter Chinese Tone Yin Ping
		[0xA701] = true, -- Modifier Letter Chinese Tone Yang Ping
		[0xA702] = true, -- Modifier Letter Chinese Tone Yin Shang
		[0xA703] = true, -- Modifier Letter Chinese Tone Yang Shang
		[0xA704] = true, -- Modifier Letter Chinese Tone Yin Qu
		[0xA705] = true, -- Modifier Letter Chinese Tone Yang Qu
		[0xA706] = true, -- Modifier Letter Chinese Tone Yin Ru
		[0xA707] = true, -- Modifier Letter Chinese Tone Yang Ru
		[0xA708] = true, -- Modifier Letter Extra-High Dotted Tone Bar
		[0xA709] = true, -- Modifier Letter High Dotted Tone Bar
		[0xA70A] = true, -- Modifier Letter Mid Dotted Tone Bar
		[0xA70B] = true, -- Modifier Letter Low Dotted Tone Bar
		[0xA70C] = true, -- Modifier Letter Extra-Low Dotted Tone Bar
		[0xA70D] = true, -- Modifier Letter Extra-High Dotted Left-Stem Tone Bar
		[0xA70E] = true, -- Modifier Letter High Dotted Left-Stem Tone Bar
		[0xA70F] = true, -- Modifier Letter Mid Dotted Left-Stem Tone Bar
		[0xA710] = true, -- Modifier Letter Low Dotted Left-Stem Tone Bar
		[0xA711] = true, -- Modifier Letter Extra-Low Dotted Left-Stem Tone Bar
		[0xA712] = true, -- Modifier Letter Extra-High Left-Stem Tone Bar
		[0xA713] = true, -- Modifier Letter High Left-Stem Tone Bar
		[0xA714] = true, -- Modifier Letter Mid Left-Stem Tone Bar
		[0xA715] = true, -- Modifier Letter Low Left-Stem Tone Bar
		[0xA716] = true, -- Modifier Letter Extra-Low Left-Stem Tone Bar
		[0xA720] = true, -- Modifier Letter Stress and High Tone
		[0xA721] = true, -- Modifier Letter Stress and Low Tone
		[0xA789] = true, -- Modifier Letter Colon
		[0xA78A] = true, -- Modifier Letter Short Equals Sign
		[0xAB5B] = true, -- Modifier Breve with Inverted Breve
		[0xAB6A] = true, -- Modifier Letter Left Tack
		[0xAB6B] = true, -- Modifier Letter Right Tack
		[0xFBB2] = true, -- Arabic Symbol Dot Above
		[0xFBB3] = true, -- Arabic Symbol Dot Below
		[0xFBB4] = true, -- Arabic Symbol Two Dots Above
		[0xFBB5] = true, -- Arabic Symbol Two Dots Below
		[0xFBB6] = true, -- Arabic Symbol Three Dots Above
		[0xFBB7] = true, -- Arabic Symbol Three Dots Below
		[0xFBB8] = true, -- Arabic Symbol Three Dots Pointing Downwards Above
		[0xFBB9] = true, -- Arabic Symbol Three Dots Pointing Downwards Below
		[0xFBBA] = true, -- Arabic Symbol Four Dots Above
		[0xFBBB] = true, -- Arabic Symbol Four Dots Below
		[0xFBBC] = true, -- Arabic Symbol Double Vertical Bar Below
		[0xFBBD] = true, -- Arabic Symbol Two Dots Vertically Above
		[0xFBBE] = true, -- Arabic Symbol Two Dots Vertically Below
		[0xFBBF] = true, -- Arabic Symbol Ring
		[0xFBC0] = true, -- Arabic Symbol Small Tah Above
		[0xFBC1] = true, -- Arabic Symbol Small Tah Below
		[0xFF3E] = true, -- Fullwidth Circumflex Accent
		[0xFF40] = true, -- Fullwidth Grave Accent
		[0xFFE3] = true, -- Fullwidth Macron
		[0x1F3FB] = true, -- Emoji Modifier Fitzpatrick Type-1-2
		[0x1F3FC] = true, -- Emoji Modifier Fitzpatrick Type-3
		[0x1F3FD] = true, -- Emoji Modifier Fitzpatrick Type-4
		[0x1F3FE] = true, -- Emoji Modifier Fitzpatrick Type-5
		[0x1F3FF] = true, -- Emoji Modifier Fitzpatrick Type-6
		[0x002B] = true, -- Plus Sign
		[0x003C] = true, -- Less-Than Sign
		[0x003D] = true, -- Equals Sign
		[0x003E] = true, -- Greater-Than Sign
		[0x007C] = true, -- Vertical Line
		[0x007E] = true, -- Tilde
		[0x00AC] = true, -- Not Sign
		[0x00B1] = true, -- Plus-Minus Sign
		[0x00D7] = true, -- Multiplication Sign
		[0x00F7] = true, -- Division Sign
		[0x03F6] = true, -- Greek Reversed Lunate Epsilon Symbol
		[0x0606] = true, -- Arabic-Indic Cube Root
		[0x0607] = true, -- Arabic-Indic Fourth Root
		[0x0608] = true, -- Arabic Ray
		[0x2044] = true, -- Fraction Slash
		[0x2052] = true, -- Commercial Minus Sign
		[0x207A] = true, -- Superscript Plus Sign
		[0x207B] = true, -- Superscript Minus
		[0x207C] = true, -- Superscript Equals Sign
		[0x208A] = true, -- Subscript Plus Sign
		[0x208B] = true, -- Subscript Minus
		[0x208C] = true, -- Subscript Equals Sign
		[0x2118] = true, -- Script Capital P
		[0x2140] = true, -- Double-Struck N-Ary Summation
		[0x2141] = true, -- Turned Sans-Serif Capital G
		[0x2142] = true, -- Turned Sans-Serif Capital L
		[0x2143] = true, -- Reversed Sans-Serif Capital L
		[0x2144] = true, -- Turned Sans-Serif Capital Y
		[0x214B] = true, -- Turned Ampersand
		[0x2190] = true, -- Leftwards Arrow
		[0x2191] = true, -- Upwards Arrow
		[0x2192] = true, -- Rightwards Arrow
		[0x2193] = true, -- Downwards Arrow
		[0x2194] = true, -- Left Right Arrow
		[0x219A] = true, -- Leftwards Arrow with Stroke
		[0x219B] = true, -- Rightwards Arrow with Stroke
		[0x21A0] = true, -- Rightwards Two Headed Arrow
		[0x21A3] = true, -- Rightwards Arrow with Tail
		[0x21A6] = true, -- Rightwards Arrow from Bar
		[0x21AE] = true, -- Left Right Arrow with Stroke
		[0x21CE] = true, -- Left Right Double Arrow with Stroke
		[0x21CF] = true, -- Rightwards Double Arrow with Stroke
		[0x21D2] = true, -- Rightwards Double Arrow
		[0x21D4] = true, -- Left Right Double Arrow
		[0x21F4] = true, -- Right Arrow with Small Circle
		[0x21F5] = true, -- Downwards Arrow Leftwards of Upwards Arrow
		[0x21F6] = true, -- Three Rightwards Arrows
		[0x21F7] = true, -- Leftwards Arrow with Vertical Stroke
		[0x21F8] = true, -- Rightwards Arrow with Vertical Stroke
		[0x21F9] = true, -- Left Right Arrow with Vertical Stroke
		[0x21FA] = true, -- Leftwards Arrow with Double Vertical Stroke
		[0x21FB] = true, -- Rightwards Arrow with Double Vertical Stroke
		[0x21FC] = true, -- Left Right Arrow with Double Vertical Stroke
		[0x21FD] = true, -- Leftwards Open-Headed Arrow
		[0x21FE] = true, -- Rightwards Open-Headed Arrow
		[0x21FF] = true, -- Left Right Open-Headed Arrow
		[0x2200] = true, -- For All
		[0x2201] = true, -- Complement
		[0x2202] = true, -- Partial Differential
		[0x2203] = true, -- There Exists
		[0x2204] = true, -- There Does Not Exist
		[0x2205] = true, -- Empty Set
		[0x2206] = true, -- Increment
		[0x2207] = true, -- Nabla
		[0x2208] = true, -- Element Of
		[0x2209] = true, -- Not An Element Of
		[0x220A] = true, -- Small Element Of
		[0x220B] = true, -- Contains as Member
		[0x220C] = true, -- Does Not Contain as Member
		[0x220D] = true, -- Small Contains as Member
		[0x220E] = true, -- End of Proof
		[0x220F] = true, -- N-Ary Product
		[0x2210] = true, -- N-Ary Coproduct
		[0x2211] = true, -- N-Ary Summation
		[0x2212] = true, -- Minus Sign
		[0x2213] = true, -- Minus-or-Plus Sign
		[0x2214] = true, -- Dot Plus
		[0x2215] = true, -- Division Slash
		[0x2216] = true, -- Set Minus
		[0x2217] = true, -- Asterisk Operator
		[0x2218] = true, -- Ring Operator
		[0x2219] = true, -- Bullet Operator
		[0x221A] = true, -- Square Root
		[0x221B] = true, -- Cube Root
		[0x221C] = true, -- Fourth Root
		[0x221D] = true, -- Proportional To
		[0x221E] = true, -- Infinity
		[0x221F] = true, -- Right Angle
		[0x2220] = true, -- Angle
		[0x2221] = true, -- Measured Angle
		[0x2222] = true, -- Spherical Angle
		[0x2223] = true, -- Divides
		[0x2224] = true, -- Does Not Divide
		[0x2225] = true, -- Parallel To
		[0x2226] = true, -- Not Parallel To
		[0x2227] = true, -- Logical And
		[0x2228] = true, -- Logical Or
		[0x2229] = true, -- Intersection
		[0x222A] = true, -- Union
		[0x222B] = true, -- Integral
		[0x222C] = true, -- Double Integral
		[0x222D] = true, -- Triple Integral
		[0x222E] = true, -- Contour Integral
		[0x222F] = true, -- Surface Integral
		[0x2230] = true, -- Volume Integral
		[0x2231] = true, -- Clockwise Integral
		[0x2232] = true, -- Clockwise Contour Integral
		[0x2233] = true, -- Anticlockwise Contour Integral
		[0x2234] = true, -- Therefore
		[0x2235] = true, -- Because
		[0x2236] = true, -- Ratio
		[0x2237] = true, -- Proportion
		[0x2238] = true, -- Dot Minus
		[0x2239] = true, -- Excess
		[0x223A] = true, -- Geometric Proportion
		[0x223B] = true, -- Homothetic
		[0x223C] = true, -- Tilde Operator
		[0x223D] = true, -- Reversed Tilde
		[0x223E] = true, -- Inverted Lazy S
		[0x223F] = true, -- Sine Wave
		[0x2240] = true, -- Wreath Product
		[0x2241] = true, -- Not Tilde
		[0x2242] = true, -- Minus Tilde
		[0x2243] = true, -- Asymptotically Equal To
		[0x2244] = true, -- Not Asymptotically Equal To
		[0x2245] = true, -- Approximately Equal To
		[0x2246] = true, -- Approximately But Not Actually Equal To
		[0x2247] = true, -- Neither Approximately Nor Actually Equal To
		[0x2248] = true, -- Almost Equal To
		[0x2249] = true, -- Not Almost Equal To
		[0x224A] = true, -- Almost Equal or Equal To
		[0x224B] = true, -- Triple Tilde
		[0x224C] = true, -- All Equal To
		[0x224D] = true, -- Equivalent To
		[0x224E] = true, -- Geometrically Equivalent To
		[0x224F] = true, -- Difference Between
		[0x2250] = true, -- Approaches the Limit
		[0x2251] = true, -- Geometrically Equal To
		[0x2252] = true, -- Approximately Equal to or the Image Of
		[0x2253] = true, -- Image of or Approximately Equal To
		[0x2254] = true, -- Colon Equals
		[0x2255] = true, -- Equals Colon
		[0x2256] = true, -- Ring In Equal To
		[0x2257] = true, -- Ring Equal To
		[0x2258] = true, -- Corresponds To
		[0x2259] = true, -- Estimates
		[0x225A] = true, -- Equiangular To
		[0x225B] = true, -- Star Equals
		[0x225C] = true, -- Delta Equal To
		[0x225D] = true, -- Equal to By Definition
		[0x225E] = true, -- Measured By
		[0x225F] = true, -- Questioned Equal To
		[0x2260] = true, -- Not Equal To
		[0x2261] = true, -- Identical To
		[0x2262] = true, -- Not Identical To
		[0x2263] = true, -- Strictly Equivalent To
		[0x2264] = true, -- Less-Than or Equal To
		[0x2265] = true, -- Greater-Than or Equal To
		[0x2266] = true, -- Less-Than Over Equal To
		[0x2267] = true, -- Greater-Than Over Equal To
		[0x2268] = true, -- Less-Than But Not Equal To
		[0x2269] = true, -- Greater-Than But Not Equal To
		[0x226A] = true, -- Much Less-Than
		[0x226B] = true, -- Much Greater-Than
		[0x226C] = true, -- Between
		[0x226D] = true, -- Not Equivalent To
		[0x226E] = true, -- Not Less-Than
		[0x226F] = true, -- Not Greater-Than
		[0x2270] = true, -- Neither Less-Than Nor Equal To
		[0x2271] = true, -- Neither Greater-Than Nor Equal To
		[0x2272] = true, -- Less-Than or Equivalent To
		[0x2273] = true, -- Greater-Than or Equivalent To
		[0x2274] = true, -- Neither Less-Than Nor Equivalent To
		[0x2275] = true, -- Neither Greater-Than Nor Equivalent To
		[0x2276] = true, -- Less-Than or Greater-Than
		[0x2277] = true, -- Greater-Than or Less-Than
		[0x2278] = true, -- Neither Less-Than Nor Greater-Than
		[0x2279] = true, -- Neither Greater-Than Nor Less-Than
		[0x227A] = true, -- Precedes
		[0x227B] = true, -- Succeeds
		[0x227C] = true, -- Precedes or Equal To
		[0x227D] = true, -- Succeeds or Equal To
		[0x227E] = true, -- Precedes or Equivalent To
		[0x227F] = true, -- Succeeds or Equivalent To
		[0x2280] = true, -- Does Not Precede
		[0x2281] = true, -- Does Not Succeed
		[0x2282] = true, -- Subset Of
		[0x2283] = true, -- Superset Of
		[0x2284] = true, -- Not A Subset Of
		[0x2285] = true, -- Not A Superset Of
		[0x2286] = true, -- Subset of or Equal To
		[0x2287] = true, -- Superset of or Equal To
		[0x2288] = true, -- Neither A Subset of Nor Equal To
		[0x2289] = true, -- Neither A Superset of Nor Equal To
		[0x228A] = true, -- Subset of with Not Equal To
		[0x228B] = true, -- Superset of with Not Equal To
		[0x228C] = true, -- Multiset
		[0x228D] = true, -- Multiset Multiplication
		[0x228E] = true, -- Multiset Union
		[0x228F] = true, -- Square Image Of
		[0x2290] = true, -- Square Original Of
		[0x2291] = true, -- Square Image of or Equal To
		[0x2292] = true, -- Square Original of or Equal To
		[0x2293] = true, -- Square Cap
		[0x2294] = true, -- Square Cup
		[0x2295] = true, -- Circled Plus
		[0x2296] = true, -- Circled Minus
		[0x2297] = true, -- Circled Times
		[0x2298] = true, -- Circled Division Slash
		[0x2299] = true, -- Circled Dot Operator
		[0x229A] = true, -- Circled Ring Operator
		[0x229B] = true, -- Circled Asterisk Operator
		[0x229C] = true, -- Circled Equals
		[0x229D] = true, -- Circled Dash
		[0x229E] = true, -- Squared Plus
		[0x229F] = true, -- Squared Minus
		[0x22A0] = true, -- Squared Times
		[0x22A1] = true, -- Squared Dot Operator
		[0x22A2] = true, -- Right Tack
		[0x22A3] = true, -- Left Tack
		[0x22A4] = true, -- Down Tack
		[0x22A5] = true, -- Up Tack
		[0x22A6] = true, -- Assertion
		[0x22A7] = true, -- Models
		[0x22A8] = true, -- True
		[0x22A9] = true, -- Forces
		[0x22AA] = true, -- Triple Vertical Bar Right Turnstile
		[0x22AB] = true, -- Double Vertical Bar Double Right Turnstile
		[0x22AC] = true, -- Does Not Prove
		[0x22AD] = true, -- Not True
		[0x22AE] = true, -- Does Not Force
		[0x22AF] = true, -- Negated Double Vertical Bar Double Right Turnstile
		[0x22B0] = true, -- Precedes Under Relation
		[0x22B1] = true, -- Succeeds Under Relation
		[0x22B2] = true, -- Normal Subgroup Of
		[0x22B3] = true, -- Contains as Normal Subgroup
		[0x22B4] = true, -- Normal Subgroup of or Equal To
		[0x22B5] = true, -- Contains as Normal Subgroup or Equal To
		[0x22B6] = true, -- Original Of
		[0x22B7] = true, -- Image Of
		[0x22B8] = true, -- Multimap
		[0x22B9] = true, -- Hermitian Conjugate Matrix
		[0x22BA] = true, -- Intercalate
		[0x22BB] = true, -- Xor
		[0x22BC] = true, -- Nand
		[0x22BD] = true, -- Nor
		[0x22BE] = true, -- Right Angle with Arc
		[0x22BF] = true, -- Right Triangle
		[0x22C0] = true, -- N-Ary Logical And
		[0x22C1] = true, -- N-Ary Logical Or
		[0x22C2] = true, -- N-Ary Intersection
		[0x22C3] = true, -- N-Ary Union
		[0x22C4] = true, -- Diamond Operator
		[0x22C5] = true, -- Dot Operator
		[0x22C6] = true, -- Star Operator
		[0x22C7] = true, -- Division Times
		[0x22C8] = true, -- Bowtie
		[0x22C9] = true, -- Left Normal Factor Semidirect Product
		[0x22CA] = true, -- Right Normal Factor Semidirect Product
		[0x22CB] = true, -- Left Semidirect Product
		[0x22CC] = true, -- Right Semidirect Product
		[0x22CD] = true, -- Reversed Tilde Equals
		[0x22CE] = true, -- Curly Logical Or
		[0x22CF] = true, -- Curly Logical And
		[0x22D0] = true, -- Double Subset
		[0x22D1] = true, -- Double Superset
		[0x22D2] = true, -- Double Intersection
		[0x22D3] = true, -- Double Union
		[0x22D4] = true, -- Pitchfork
		[0x22D5] = true, -- Equal and Parallel To
		[0x22D6] = true, -- Less-Than with Dot
		[0x22D7] = true, -- Greater-Than with Dot
		[0x22D8] = true, -- Very Much Less-Than
		[0x22D9] = true, -- Very Much Greater-Than
		[0x22DA] = true, -- Less-Than Equal to or Greater-Than
		[0x22DB] = true, -- Greater-Than Equal to or Less-Than
		[0x22DC] = true, -- Equal to or Less-Than
		[0x22DD] = true, -- Equal to or Greater-Than
		[0x22DE] = true, -- Equal to or Precedes
		[0x22DF] = true, -- Equal to or Succeeds
		[0x22E0] = true, -- Does Not Precede or Equal
		[0x22E1] = true, -- Does Not Succeed or Equal
		[0x22E2] = true, -- Not Square Image of or Equal To
		[0x22E3] = true, -- Not Square Original of or Equal To
		[0x22E4] = true, -- Square Image of or Not Equal To
		[0x22E5] = true, -- Square Original of or Not Equal To
		[0x22E6] = true, -- Less-Than But Not Equivalent To
		[0x22E7] = true, -- Greater-Than But Not Equivalent To
		[0x22E8] = true, -- Precedes But Not Equivalent To
		[0x22E9] = true, -- Succeeds But Not Equivalent To
		[0x22EA] = true, -- Not Normal Subgroup Of
		[0x22EB] = true, -- Does Not Contain as Normal Subgroup
		[0x22EC] = true, -- Not Normal Subgroup of or Equal To
		[0x22ED] = true, -- Does Not Contain as Normal Subgroup or Equal
		[0x22EE] = true, -- Vertical Ellipsis
		[0x22EF] = true, -- Midline Horizontal Ellipsis
		[0x22F0] = true, -- Up Right Diagonal Ellipsis
		[0x22F1] = true, -- Down Right Diagonal Ellipsis
		[0x22F2] = true, -- Element of with Long Horizontal Stroke
		[0x22F3] = true, -- Element of with Vertical Bar at End of Horizontal Stroke
		[0x22F4] = true, -- Small Element of with Vertical Bar at End of Horizontal Stroke
		[0x22F5] = true, -- Element of with Dot Above
		[0x22F6] = true, -- Element of with Overbar
		[0x22F7] = true, -- Small Element of with Overbar
		[0x22F8] = true, -- Element of with Underbar
		[0x22F9] = true, -- Element of with Two Horizontal Strokes
		[0x22FA] = true, -- Contains with Long Horizontal Stroke
		[0x22FB] = true, -- Contains with Vertical Bar at End of Horizontal Stroke
		[0x22FC] = true, -- Small Contains with Vertical Bar at End of Horizontal Stroke
		[0x22FD] = true, -- Contains with Overbar
		[0x22FE] = true, -- Small Contains with Overbar
		[0x22FF] = true, -- Z Notation Bag Membership
		[0x2320] = true, -- Top Half Integral
		[0x2321] = true, -- Bottom Half Integral
		[0x237C] = true, -- Right Angle with Downwards Zigzag Arrow
		[0x239B] = true, -- Left Parenthesis Upper Hook
		[0x239C] = true, -- Left Parenthesis Extension
		[0x239D] = true, -- Left Parenthesis Lower Hook
		[0x239E] = true, -- Right Parenthesis Upper Hook
		[0x239F] = true, -- Right Parenthesis Extension
		[0x23A0] = true, -- Right Parenthesis Lower Hook
		[0x23A1] = true, -- Left Square Bracket Upper Corner
		[0x23A2] = true, -- Left Square Bracket Extension
		[0x23A3] = true, -- Left Square Bracket Lower Corner
		[0x23A4] = true, -- Right Square Bracket Upper Corner
		[0x23A5] = true, -- Right Square Bracket Extension
		[0x23A6] = true, -- Right Square Bracket Lower Corner
		[0x23A7] = true, -- Left Curly Bracket Upper Hook
		[0x23A8] = true, -- Left Curly Bracket Middle Piece
		[0x23A9] = true, -- Left Curly Bracket Lower Hook
		[0x23AA] = true, -- Curly Bracket Extension
		[0x23AB] = true, -- Right Curly Bracket Upper Hook
		[0x23AC] = true, -- Right Curly Bracket Middle Piece
		[0x23AD] = true, -- Right Curly Bracket Lower Hook
		[0x23AE] = true, -- Integral Extension
		[0x23AF] = true, -- Horizontal Line Extension
		[0x23B0] = true, -- Upper Left or Lower Right Curly Bracket Section
		[0x23B1] = true, -- Upper Right or Lower Left Curly Bracket Section
		[0x23B2] = true, -- Summation Top
		[0x23B3] = true, -- Summation Bottom
		[0x23DC] = true, -- Top Parenthesis
		[0x23DD] = true, -- Bottom Parenthesis
		[0x23DE] = true, -- Top Curly Bracket
		[0x23DF] = true, -- Bottom Curly Bracket
		[0x23E0] = true, -- Top Tortoise Shell Bracket
		[0x23E1] = true, -- Bottom Tortoise Shell Bracket
		[0x25B7] = true, -- White Right-Pointing Triangle
		[0x25C1] = true, -- White Left-Pointing Triangle
		[0x25F8] = true, -- Upper Left Triangle
		[0x25F9] = true, -- Upper Right Triangle
		[0x25FA] = true, -- Lower Left Triangle
		[0x25FB] = true, -- White Medium Square
		[0x25FC] = true, -- Black Medium Square
		[0x25FD] = true, -- White Medium Small Square
		[0x25FE] = true, -- Black Medium Small Square
		[0x25FF] = true, -- Lower Right Triangle
		[0x266F] = true, -- Music Sharp Sign
		[0x27C0] = true, -- Three Dimensional Angle
		[0x27C1] = true, -- White Triangle Containing Small White Triangle
		[0x27C2] = true, -- Perpendicular
		[0x27C3] = true, -- Open Subset
		[0x27C4] = true, -- Open Superset
		[0x27C7] = true, -- or with Dot Inside
		[0x27C8] = true, -- Reverse Solidus Preceding Subset
		[0x27C9] = true, -- Superset Preceding Solidus
		[0x27CA] = true, -- Vertical Bar with Horizontal Stroke
		[0x27CB] = true, -- Mathematical Rising Diagonal
		[0x27CC] = true, -- Long Division
		[0x27CD] = true, -- Mathematical Falling Diagonal
		[0x27CE] = true, -- Squared Logical And
		[0x27CF] = true, -- Squared Logical Or
		[0x27D0] = true, -- White Diamond with Centred Dot
		[0x27D1] = true, -- and with Dot
		[0x27D2] = true, -- Element of Opening Upwards
		[0x27D3] = true, -- Lower Right Corner with Dot
		[0x27D4] = true, -- Upper Left Corner with Dot
		[0x27D5] = true, -- Left Outer Join
		[0x27D6] = true, -- Right Outer Join
		[0x27D7] = true, -- Full Outer Join
		[0x27D8] = true, -- Large Up Tack
		[0x27D9] = true, -- Large Down Tack
		[0x27DA] = true, -- Left and Right Double Turnstile
		[0x27DB] = true, -- Left and Right Tack
		[0x27DC] = true, -- Left Multimap
		[0x27DD] = true, -- Long Right Tack
		[0x27DE] = true, -- Long Left Tack
		[0x27DF] = true, -- Up Tack with Circle Above
		[0x27E0] = true, -- Lozenge Divided By Horizontal Rule
		[0x27E1] = true, -- White Concave-Sided Diamond
		[0x27E2] = true, -- White Concave-Sided Diamond with Leftwards Tick
		[0x27E3] = true, -- White Concave-Sided Diamond with Rightwards Tick
		[0x27E4] = true, -- White Square with Leftwards Tick
		[0x27E5] = true, -- White Square with Rightwards Tick
		[0x27F0] = true, -- Upwards Quadruple Arrow
		[0x27F1] = true, -- Downwards Quadruple Arrow
		[0x27F2] = true, -- Anticlockwise Gapped Circle Arrow
		[0x27F3] = true, -- Clockwise Gapped Circle Arrow
		[0x27F4] = true, -- Right Arrow with Circled Plus
		[0x27F5] = true, -- Long Leftwards Arrow
		[0x27F6] = true, -- Long Rightwards Arrow
		[0x27F7] = true, -- Long Left Right Arrow
		[0x27F8] = true, -- Long Leftwards Double Arrow
		[0x27F9] = true, -- Long Rightwards Double Arrow
		[0x27FA] = true, -- Long Left Right Double Arrow
		[0x27FB] = true, -- Long Leftwards Arrow from Bar
		[0x27FC] = true, -- Long Rightwards Arrow from Bar
		[0x27FD] = true, -- Long Leftwards Double Arrow from Bar
		[0x27FE] = true, -- Long Rightwards Double Arrow from Bar
		[0x27FF] = true, -- Long Rightwards Squiggle Arrow
		[0x2900] = true, -- Rightwards Two-Headed Arrow with Vertical Stroke
		[0x2901] = true, -- Rightwards Two-Headed Arrow with Double Vertical Stroke
		[0x2902] = true, -- Leftwards Double Arrow with Vertical Stroke
		[0x2903] = true, -- Rightwards Double Arrow with Vertical Stroke
		[0x2904] = true, -- Left Right Double Arrow with Vertical Stroke
		[0x2905] = true, -- Rightwards Two-Headed Arrow from Bar
		[0x2906] = true, -- Leftwards Double Arrow from Bar
		[0x2907] = true, -- Rightwards Double Arrow from Bar
		[0x2908] = true, -- Downwards Arrow with Horizontal Stroke
		[0x2909] = true, -- Upwards Arrow with Horizontal Stroke
		[0x290A] = true, -- Upwards Triple Arrow
		[0x290B] = true, -- Downwards Triple Arrow
		[0x290C] = true, -- Leftwards Double Dash Arrow
		[0x290D] = true, -- Rightwards Double Dash Arrow
		[0x290E] = true, -- Leftwards Triple Dash Arrow
		[0x290F] = true, -- Rightwards Triple Dash Arrow
		[0x2910] = true, -- Rightwards Two-Headed Triple Dash Arrow
		[0x2911] = true, -- Rightwards Arrow with Dotted Stem
		[0x2912] = true, -- Upwards Arrow to Bar
		[0x2913] = true, -- Downwards Arrow to Bar
		[0x2914] = true, -- Rightwards Arrow with Tail with Vertical Stroke
		[0x2915] = true, -- Rightwards Arrow with Tail with Double Vertical Stroke
		[0x2916] = true, -- Rightwards Two-Headed Arrow with Tail
		[0x2917] = true, -- Rightwards Two-Headed Arrow with Tail with Vertical Stroke
		[0x2918] = true, -- Rightwards Two-Headed Arrow with Tail with Double Vertical Stroke
		[0x2919] = true, -- Leftwards Arrow-Tail
		[0x291A] = true, -- Rightwards Arrow-Tail
		[0x291B] = true, -- Leftwards Double Arrow-Tail
		[0x291C] = true, -- Rightwards Double Arrow-Tail
		[0x291D] = true, -- Leftwards Arrow to Black Diamond
		[0x291E] = true, -- Rightwards Arrow to Black Diamond
		[0x291F] = true, -- Leftwards Arrow from Bar to Black Diamond
		[0x2920] = true, -- Rightwards Arrow from Bar to Black Diamond
		[0x2921] = true, -- North West and South East Arrow
		[0x2922] = true, -- North East and South West Arrow
		[0x2923] = true, -- North West Arrow with Hook
		[0x2924] = true, -- North East Arrow with Hook
		[0x2925] = true, -- South East Arrow with Hook
		[0x2926] = true, -- South West Arrow with Hook
		[0x2927] = true, -- North West Arrow and North East Arrow
		[0x2928] = true, -- North East Arrow and South East Arrow
		[0x2929] = true, -- South East Arrow and South West Arrow
		[0x292A] = true, -- South West Arrow and North West Arrow
		[0x292B] = true, -- Rising Diagonal Crossing Falling Diagonal
		[0x292C] = true, -- Falling Diagonal Crossing Rising Diagonal
		[0x292D] = true, -- South East Arrow Crossing North East Arrow
		[0x292E] = true, -- North East Arrow Crossing South East Arrow
		[0x292F] = true, -- Falling Diagonal Crossing North East Arrow
		[0x2930] = true, -- Rising Diagonal Crossing South East Arrow
		[0x2931] = true, -- North East Arrow Crossing North West Arrow
		[0x2932] = true, -- North West Arrow Crossing North East Arrow
		[0x2933] = true, -- Wave Arrow Pointing Directly Right
		[0x2934] = true, -- Arrow Pointing Rightwards Then Curving Upwards
		[0x2935] = true, -- Arrow Pointing Rightwards Then Curving Downwards
		[0x2936] = true, -- Arrow Pointing Downwards Then Curving Leftwards
		[0x2937] = true, -- Arrow Pointing Downwards Then Curving Rightwards
		[0x2938] = true, -- Right-Side Arc Clockwise Arrow
		[0x2939] = true, -- Left-Side Arc Anticlockwise Arrow
		[0x293A] = true, -- Top Arc Anticlockwise Arrow
		[0x293B] = true, -- Bottom Arc Anticlockwise Arrow
		[0x293C] = true, -- Top Arc Clockwise Arrow with Minus
		[0x293D] = true, -- Top Arc Anticlockwise Arrow with Plus
		[0x293E] = true, -- Lower Right Semicircular Clockwise Arrow
		[0x293F] = true, -- Lower Left Semicircular Anticlockwise Arrow
		[0x2940] = true, -- Anticlockwise Closed Circle Arrow
		[0x2941] = true, -- Clockwise Closed Circle Arrow
		[0x2942] = true, -- Rightwards Arrow Above Short Leftwards Arrow
		[0x2943] = true, -- Leftwards Arrow Above Short Rightwards Arrow
		[0x2944] = true, -- Short Rightwards Arrow Above Leftwards Arrow
		[0x2945] = true, -- Rightwards Arrow with Plus Below
		[0x2946] = true, -- Leftwards Arrow with Plus Below
		[0x2947] = true, -- Rightwards Arrow Through X
		[0x2948] = true, -- Left Right Arrow Through Small Circle
		[0x2949] = true, -- Upwards Two-Headed Arrow from Small Circle
		[0x294A] = true, -- Left Barb Up Right Barb Down Harpoon
		[0x294B] = true, -- Left Barb Down Right Barb Up Harpoon
		[0x294C] = true, -- Up Barb Right Down Barb Left Harpoon
		[0x294D] = true, -- Up Barb Left Down Barb Right Harpoon
		[0x294E] = true, -- Left Barb Up Right Barb Up Harpoon
		[0x294F] = true, -- Up Barb Right Down Barb Right Harpoon
		[0x2950] = true, -- Left Barb Down Right Barb Down Harpoon
		[0x2951] = true, -- Up Barb Left Down Barb Left Harpoon
		[0x2952] = true, -- Leftwards Harpoon with Barb Up to Bar
		[0x2953] = true, -- Rightwards Harpoon with Barb Up to Bar
		[0x2954] = true, -- Upwards Harpoon with Barb Right to Bar
		[0x2955] = true, -- Downwards Harpoon with Barb Right to Bar
		[0x2956] = true, -- Leftwards Harpoon with Barb Down to Bar
		[0x2957] = true, -- Rightwards Harpoon with Barb Down to Bar
		[0x2958] = true, -- Upwards Harpoon with Barb Left to Bar
		[0x2959] = true, -- Downwards Harpoon with Barb Left to Bar
		[0x295A] = true, -- Leftwards Harpoon with Barb Up from Bar
		[0x295B] = true, -- Rightwards Harpoon with Barb Up from Bar
		[0x295C] = true, -- Upwards Harpoon with Barb Right from Bar
		[0x295D] = true, -- Downwards Harpoon with Barb Right from Bar
		[0x295E] = true, -- Leftwards Harpoon with Barb Down from Bar
		[0x295F] = true, -- Rightwards Harpoon with Barb Down from Bar
		[0x2960] = true, -- Upwards Harpoon with Barb Left from Bar
		[0x2961] = true, -- Downwards Harpoon with Barb Left from Bar
		[0x2962] = true, -- Leftwards Harpoon with Barb Up Above Leftwards Harpoon with Barb Down
		[0x2963] = true, -- Upwards Harpoon with Barb Left Beside Upwards Harpoon with Barb Right
		[0x2964] = true, -- Rightwards Harpoon with Barb Up Above Rightwards Harpoon with Barb Down
		[0x2965] = true, -- Downwards Harpoon with Barb Left Beside Downwards Harpoon with Barb Right
		[0x2966] = true, -- Leftwards Harpoon with Barb Up Above Rightwards Harpoon with Barb Up
		[0x2967] = true, -- Leftwards Harpoon with Barb Down Above Rightwards Harpoon with Barb Down
		[0x2968] = true, -- Rightwards Harpoon with Barb Up Above Leftwards Harpoon with Barb Up
		[0x2969] = true, -- Rightwards Harpoon with Barb Down Above Leftwards Harpoon with Barb Down
		[0x296A] = true, -- Leftwards Harpoon with Barb Up Above Long Dash
		[0x296B] = true, -- Leftwards Harpoon with Barb Down Below Long Dash
		[0x296C] = true, -- Rightwards Harpoon with Barb Up Above Long Dash
		[0x296D] = true, -- Rightwards Harpoon with Barb Down Below Long Dash
		[0x296E] = true, -- Upwards Harpoon with Barb Left Beside Downwards Harpoon with Barb Right
		[0x296F] = true, -- Downwards Harpoon with Barb Left Beside Upwards Harpoon with Barb Right
		[0x2970] = true, -- Right Double Arrow with Rounded Head
		[0x2971] = true, -- Equals Sign Above Rightwards Arrow
		[0x2972] = true, -- Tilde Operator Above Rightwards Arrow
		[0x2973] = true, -- Leftwards Arrow Above Tilde Operator
		[0x2974] = true, -- Rightwards Arrow Above Tilde Operator
		[0x2975] = true, -- Rightwards Arrow Above Almost Equal To
		[0x2976] = true, -- Less-Than Above Leftwards Arrow
		[0x2977] = true, -- Leftwards Arrow Through Less-Than
		[0x2978] = true, -- Greater-Than Above Rightwards Arrow
		[0x2979] = true, -- Subset Above Rightwards Arrow
		[0x297A] = true, -- Leftwards Arrow Through Subset
		[0x297B] = true, -- Superset Above Leftwards Arrow
		[0x297C] = true, -- Left Fish Tail
		[0x297D] = true, -- Right Fish Tail
		[0x297E] = true, -- Up Fish Tail
		[0x297F] = true, -- Down Fish Tail
		[0x2980] = true, -- Triple Vertical Bar Delimiter
		[0x2981] = true, -- Z Notation Spot
		[0x2982] = true, -- Z Notation Type Colon
		[0x2999] = true, -- Dotted Fence
		[0x299A] = true, -- Vertical Zigzag Line
		[0x299B] = true, -- Measured Angle Opening Left
		[0x299C] = true, -- Right Angle Variant with Square
		[0x299D] = true, -- Measured Right Angle with Dot
		[0x299E] = true, -- Angle with S Inside
		[0x299F] = true, -- Acute Angle
		[0x29A0] = true, -- Spherical Angle Opening Left
		[0x29A1] = true, -- Spherical Angle Opening Up
		[0x29A2] = true, -- Turned Angle
		[0x29A3] = true, -- Reversed Angle
		[0x29A4] = true, -- Angle with Underbar
		[0x29A5] = true, -- Reversed Angle with Underbar
		[0x29A6] = true, -- Oblique Angle Opening Up
		[0x29A7] = true, -- Oblique Angle Opening Down
		[0x29A8] = true, -- Measured Angle with Open Arm Ending In Arrow Pointing Up and Right
		[0x29A9] = true, -- Measured Angle with Open Arm Ending In Arrow Pointing Up and Left
		[0x29AA] = true, -- Measured Angle with Open Arm Ending In Arrow Pointing Down and Right
		[0x29AB] = true, -- Measured Angle with Open Arm Ending In Arrow Pointing Down and Left
		[0x29AC] = true, -- Measured Angle with Open Arm Ending In Arrow Pointing Right and Up
		[0x29AD] = true, -- Measured Angle with Open Arm Ending In Arrow Pointing Left and Up
		[0x29AE] = true, -- Measured Angle with Open Arm Ending In Arrow Pointing Right and Down
		[0x29AF] = true, -- Measured Angle with Open Arm Ending In Arrow Pointing Left and Down
		[0x29B0] = true, -- Reversed Empty Set
		[0x29B1] = true, -- Empty Set with Overbar
		[0x29B2] = true, -- Empty Set with Small Circle Above
		[0x29B3] = true, -- Empty Set with Right Arrow Above
		[0x29B4] = true, -- Empty Set with Left Arrow Above
		[0x29B5] = true, -- Circle with Horizontal Bar
		[0x29B6] = true, -- Circled Vertical Bar
		[0x29B7] = true, -- Circled Parallel
		[0x29B8] = true, -- Circled Reverse Solidus
		[0x29B9] = true, -- Circled Perpendicular
		[0x29BA] = true, -- Circle Divided By Horizontal Bar and Top Half Divided By Vertical Bar
		[0x29BB] = true, -- Circle with Superimposed X
		[0x29BC] = true, -- Circled Anticlockwise-Rotated Division Sign
		[0x29BD] = true, -- Up Arrow Through Circle
		[0x29BE] = true, -- Circled White Bullet
		[0x29BF] = true, -- Circled Bullet
		[0x29C0] = true, -- Circled Less-Than
		[0x29C1] = true, -- Circled Greater-Than
		[0x29C2] = true, -- Circle with Small Circle to the Right
		[0x29C3] = true, -- Circle with Two Horizontal Strokes to the Right
		[0x29C4] = true, -- Squared Rising Diagonal Slash
		[0x29C5] = true, -- Squared Falling Diagonal Slash
		[0x29C6] = true, -- Squared Asterisk
		[0x29C7] = true, -- Squared Small Circle
		[0x29C8] = true, -- Squared Square
		[0x29C9] = true, -- Two Joined Squares
		[0x29CA] = true, -- Triangle with Dot Above
		[0x29CB] = true, -- Triangle with Underbar
		[0x29CC] = true, -- S In Triangle
		[0x29CD] = true, -- Triangle with Serifs at Bottom
		[0x29CE] = true, -- Right Triangle Above Left Triangle
		[0x29CF] = true, -- Left Triangle Beside Vertical Bar
		[0x29D0] = true, -- Vertical Bar Beside Right Triangle
		[0x29D1] = true, -- Bowtie with Left Half Black
		[0x29D2] = true, -- Bowtie with Right Half Black
		[0x29D3] = true, -- Black Bowtie
		[0x29D4] = true, -- Times with Left Half Black
		[0x29D5] = true, -- Times with Right Half Black
		[0x29D6] = true, -- White Hourglass
		[0x29D7] = true, -- Black Hourglass
		[0x29DC] = true, -- Incomplete Infinity
		[0x29DD] = true, -- Tie Over Infinity
		[0x29DE] = true, -- Infinity Negated with Vertical Bar
		[0x29DF] = true, -- Double-Ended Multimap
		[0x29E0] = true, -- Square with Contoured Outline
		[0x29E1] = true, -- Increases As
		[0x29E2] = true, -- Shuffle Product
		[0x29E3] = true, -- Equals Sign and Slanted Parallel
		[0x29E4] = true, -- Equals Sign and Slanted Parallel with Tilde Above
		[0x29E5] = true, -- Identical to and Slanted Parallel
		[0x29E6] = true, -- Gleich Stark
		[0x29E7] = true, -- Thermodynamic
		[0x29E8] = true, -- Down-Pointing Triangle with Left Half Black
		[0x29E9] = true, -- Down-Pointing Triangle with Right Half Black
		[0x29EA] = true, -- Black Diamond with Down Arrow
		[0x29EB] = true, -- Black Lozenge
		[0x29EC] = true, -- White Circle with Down Arrow
		[0x29ED] = true, -- Black Circle with Down Arrow
		[0x29EE] = true, -- Error-Barred White Square
		[0x29EF] = true, -- Error-Barred Black Square
		[0x29F0] = true, -- Error-Barred White Diamond
		[0x29F1] = true, -- Error-Barred Black Diamond
		[0x29F2] = true, -- Error-Barred White Circle
		[0x29F3] = true, -- Error-Barred Black Circle
		[0x29F4] = true, -- Rule-Delayed
		[0x29F5] = true, -- Reverse Solidus Operator
		[0x29F6] = true, -- Solidus with Overbar
		[0x29F7] = true, -- Reverse Solidus with Horizontal Stroke
		[0x29F8] = true, -- Big Solidus
		[0x29F9] = true, -- Big Reverse Solidus
		[0x29FA] = true, -- Double Plus
		[0x29FB] = true, -- Triple Plus
		[0x29FE] = true, -- Tiny
		[0x29FF] = true, -- Miny
		[0x2A00] = true, -- N-Ary Circled Dot Operator
		[0x2A01] = true, -- N-Ary Circled Plus Operator
		[0x2A02] = true, -- N-Ary Circled Times Operator
		[0x2A03] = true, -- N-Ary Union Operator with Dot
		[0x2A04] = true, -- N-Ary Union Operator with Plus
		[0x2A05] = true, -- N-Ary Square Intersection Operator
		[0x2A06] = true, -- N-Ary Square Union Operator
		[0x2A07] = true, -- Two Logical and Operator
		[0x2A08] = true, -- Two Logical or Operator
		[0x2A09] = true, -- N-Ary Times Operator
		[0x2A0A] = true, -- Modulo Two Sum
		[0x2A0B] = true, -- Summation with Integral
		[0x2A0C] = true, -- Quadruple Integral Operator
		[0x2A0D] = true, -- Finite Part Integral
		[0x2A0E] = true, -- Integral with Double Stroke
		[0x2A0F] = true, -- Integral Average with Slash
		[0x2A10] = true, -- Circulation Function
		[0x2A11] = true, -- Anticlockwise Integration
		[0x2A12] = true, -- Line Integration with Rectangular Path Around Pole
		[0x2A13] = true, -- Line Integration with Semicircular Path Around Pole
		[0x2A14] = true, -- Line Integration Not Including the Pole
		[0x2A15] = true, -- Integral Around A Point Operator
		[0x2A16] = true, -- Quaternion Integral Operator
		[0x2A17] = true, -- Integral with Leftwards Arrow with Hook
		[0x2A18] = true, -- Integral with Times Sign
		[0x2A19] = true, -- Integral with Intersection
		[0x2A1A] = true, -- Integral with Union
		[0x2A1B] = true, -- Integral with Overbar
		[0x2A1C] = true, -- Integral with Underbar
		[0x2A1D] = true, -- Join
		[0x2A1E] = true, -- Large Left Triangle Operator
		[0x2A1F] = true, -- Z Notation Schema Composition
		[0x2A20] = true, -- Z Notation Schema Piping
		[0x2A21] = true, -- Z Notation Schema Projection
		[0x2A22] = true, -- Plus Sign with Small Circle Above
		[0x2A23] = true, -- Plus Sign with Circumflex Accent Above
		[0x2A24] = true, -- Plus Sign with Tilde Above
		[0x2A25] = true, -- Plus Sign with Dot Below
		[0x2A26] = true, -- Plus Sign with Tilde Below
		[0x2A27] = true, -- Plus Sign with Subscript Two
		[0x2A28] = true, -- Plus Sign with Black Triangle
		[0x2A29] = true, -- Minus Sign with Comma Above
		[0x2A2A] = true, -- Minus Sign with Dot Below
		[0x2A2B] = true, -- Minus Sign with Falling Dots
		[0x2A2C] = true, -- Minus Sign with Rising Dots
		[0x2A2D] = true, -- Plus Sign In Left Half Circle
		[0x2A2E] = true, -- Plus Sign In Right Half Circle
		[0x2A2F] = true, -- Vector or Cross Product
		[0x2A30] = true, -- Multiplication Sign with Dot Above
		[0x2A31] = true, -- Multiplication Sign with Underbar
		[0x2A32] = true, -- Semidirect Product with Bottom Closed
		[0x2A33] = true, -- Smash Product
		[0x2A34] = true, -- Multiplication Sign In Left Half Circle
		[0x2A35] = true, -- Multiplication Sign In Right Half Circle
		[0x2A36] = true, -- Circled Multiplication Sign with Circumflex Accent
		[0x2A37] = true, -- Multiplication Sign In Double Circle
		[0x2A38] = true, -- Circled Division Sign
		[0x2A39] = true, -- Plus Sign In Triangle
		[0x2A3A] = true, -- Minus Sign In Triangle
		[0x2A3B] = true, -- Multiplication Sign In Triangle
		[0x2A3C] = true, -- Interior Product
		[0x2A3D] = true, -- Righthand Interior Product
		[0x2A3E] = true, -- Z Notation Relational Composition
		[0x2A3F] = true, -- Amalgamation or Coproduct
		[0x2A40] = true, -- Intersection with Dot
		[0x2A41] = true, -- Union with Minus Sign
		[0x2A42] = true, -- Union with Overbar
		[0x2A43] = true, -- Intersection with Overbar
		[0x2A44] = true, -- Intersection with Logical And
		[0x2A45] = true, -- Union with Logical Or
		[0x2A46] = true, -- Union Above Intersection
		[0x2A47] = true, -- Intersection Above Union
		[0x2A48] = true, -- Union Above Bar Above Intersection
		[0x2A49] = true, -- Intersection Above Bar Above Union
		[0x2A4A] = true, -- Union Beside and Joined with Union
		[0x2A4B] = true, -- Intersection Beside and Joined with Intersection
		[0x2A4C] = true, -- Closed Union with Serifs
		[0x2A4D] = true, -- Closed Intersection with Serifs
		[0x2A4E] = true, -- Double Square Intersection
		[0x2A4F] = true, -- Double Square Union
		[0x2A50] = true, -- Closed Union with Serifs and Smash Product
		[0x2A51] = true, -- Logical and with Dot Above
		[0x2A52] = true, -- Logical or with Dot Above
		[0x2A53] = true, -- Double Logical And
		[0x2A54] = true, -- Double Logical Or
		[0x2A55] = true, -- Two Intersecting Logical And
		[0x2A56] = true, -- Two Intersecting Logical Or
		[0x2A57] = true, -- Sloping Large Or
		[0x2A58] = true, -- Sloping Large And
		[0x2A59] = true, -- Logical or Overlapping Logical And
		[0x2A5A] = true, -- Logical and with Middle Stem
		[0x2A5B] = true, -- Logical or with Middle Stem
		[0x2A5C] = true, -- Logical and with Horizontal Dash
		[0x2A5D] = true, -- Logical or with Horizontal Dash
		[0x2A5E] = true, -- Logical and with Double Overbar
		[0x2A5F] = true, -- Logical and with Underbar
		[0x2A60] = true, -- Logical and with Double Underbar
		[0x2A61] = true, -- Small Vee with Underbar
		[0x2A62] = true, -- Logical or with Double Overbar
		[0x2A63] = true, -- Logical or with Double Underbar
		[0x2A64] = true, -- Z Notation Domain Antirestriction
		[0x2A65] = true, -- Z Notation Range Antirestriction
		[0x2A66] = true, -- Equals Sign with Dot Below
		[0x2A67] = true, -- Identical with Dot Above
		[0x2A68] = true, -- Triple Horizontal Bar with Double Vertical Stroke
		[0x2A69] = true, -- Triple Horizontal Bar with Triple Vertical Stroke
		[0x2A6A] = true, -- Tilde Operator with Dot Above
		[0x2A6B] = true, -- Tilde Operator with Rising Dots
		[0x2A6C] = true, -- Similar Minus Similar
		[0x2A6D] = true, -- Congruent with Dot Above
		[0x2A6E] = true, -- Equals with Asterisk
		[0x2A6F] = true, -- Almost Equal to with Circumflex Accent
		[0x2A70] = true, -- Approximately Equal or Equal To
		[0x2A71] = true, -- Equals Sign Above Plus Sign
		[0x2A72] = true, -- Plus Sign Above Equals Sign
		[0x2A73] = true, -- Equals Sign Above Tilde Operator
		[0x2A74] = true, -- Double Colon Equal
		[0x2A75] = true, -- Two Consecutive Equals Signs
		[0x2A76] = true, -- Three Consecutive Equals Signs
		[0x2A77] = true, -- Equals Sign with Two Dots Above and Two Dots Below
		[0x2A78] = true, -- Equivalent with Four Dots Above
		[0x2A79] = true, -- Less-Than with Circle Inside
		[0x2A7A] = true, -- Greater-Than with Circle Inside
		[0x2A7B] = true, -- Less-Than with Question Mark Above
		[0x2A7C] = true, -- Greater-Than with Question Mark Above
		[0x2A7D] = true, -- Less-Than or Slanted Equal To
		[0x2A7E] = true, -- Greater-Than or Slanted Equal To
		[0x2A7F] = true, -- Less-Than or Slanted Equal to with Dot Inside
		[0x2A80] = true, -- Greater-Than or Slanted Equal to with Dot Inside
		[0x2A81] = true, -- Less-Than or Slanted Equal to with Dot Above
		[0x2A82] = true, -- Greater-Than or Slanted Equal to with Dot Above
		[0x2A83] = true, -- Less-Than or Slanted Equal to with Dot Above Right
		[0x2A84] = true, -- Greater-Than or Slanted Equal to with Dot Above Left
		[0x2A85] = true, -- Less-Than or Approximate
		[0x2A86] = true, -- Greater-Than or Approximate
		[0x2A87] = true, -- Less-Than and Single-Line Not Equal To
		[0x2A88] = true, -- Greater-Than and Single-Line Not Equal To
		[0x2A89] = true, -- Less-Than and Not Approximate
		[0x2A8A] = true, -- Greater-Than and Not Approximate
		[0x2A8B] = true, -- Less-Than Above Double-Line Equal Above Greater-Than
		[0x2A8C] = true, -- Greater-Than Above Double-Line Equal Above Less-Than
		[0x2A8D] = true, -- Less-Than Above Similar or Equal
		[0x2A8E] = true, -- Greater-Than Above Similar or Equal
		[0x2A8F] = true, -- Less-Than Above Similar Above Greater-Than
		[0x2A90] = true, -- Greater-Than Above Similar Above Less-Than
		[0x2A91] = true, -- Less-Than Above Greater-Than Above Double-Line Equal
		[0x2A92] = true, -- Greater-Than Above Less-Than Above Double-Line Equal
		[0x2A93] = true, -- Less-Than Above Slanted Equal Above Greater-Than Above Slanted Equal
		[0x2A94] = true, -- Greater-Than Above Slanted Equal Above Less-Than Above Slanted Equal
		[0x2A95] = true, -- Slanted Equal to or Less-Than
		[0x2A96] = true, -- Slanted Equal to or Greater-Than
		[0x2A97] = true, -- Slanted Equal to or Less-Than with Dot Inside
		[0x2A98] = true, -- Slanted Equal to or Greater-Than with Dot Inside
		[0x2A99] = true, -- Double-Line Equal to or Less-Than
		[0x2A9A] = true, -- Double-Line Equal to or Greater-Than
		[0x2A9B] = true, -- Double-Line Slanted Equal to or Less-Than
		[0x2A9C] = true, -- Double-Line Slanted Equal to or Greater-Than
		[0x2A9D] = true, -- Similar or Less-Than
		[0x2A9E] = true, -- Similar or Greater-Than
		[0x2A9F] = true, -- Similar Above Less-Than Above Equals Sign
		[0x2AA0] = true, -- Similar Above Greater-Than Above Equals Sign
		[0x2AA1] = true, -- Double Nested Less-Than
		[0x2AA2] = true, -- Double Nested Greater-Than
		[0x2AA3] = true, -- Double Nested Less-Than with Underbar
		[0x2AA4] = true, -- Greater-Than Overlapping Less-Than
		[0x2AA5] = true, -- Greater-Than Beside Less-Than
		[0x2AA6] = true, -- Less-Than Closed By Curve
		[0x2AA7] = true, -- Greater-Than Closed By Curve
		[0x2AA8] = true, -- Less-Than Closed By Curve Above Slanted Equal
		[0x2AA9] = true, -- Greater-Than Closed By Curve Above Slanted Equal
		[0x2AAA] = true, -- Smaller Than
		[0x2AAB] = true, -- Larger Than
		[0x2AAC] = true, -- Smaller Than or Equal To
		[0x2AAD] = true, -- Larger Than or Equal To
		[0x2AAE] = true, -- Equals Sign with Bumpy Above
		[0x2AAF] = true, -- Precedes Above Single-Line Equals Sign
		[0x2AB0] = true, -- Succeeds Above Single-Line Equals Sign
		[0x2AB1] = true, -- Precedes Above Single-Line Not Equal To
		[0x2AB2] = true, -- Succeeds Above Single-Line Not Equal To
		[0x2AB3] = true, -- Precedes Above Equals Sign
		[0x2AB4] = true, -- Succeeds Above Equals Sign
		[0x2AB5] = true, -- Precedes Above Not Equal To
		[0x2AB6] = true, -- Succeeds Above Not Equal To
		[0x2AB7] = true, -- Precedes Above Almost Equal To
		[0x2AB8] = true, -- Succeeds Above Almost Equal To
		[0x2AB9] = true, -- Precedes Above Not Almost Equal To
		[0x2ABA] = true, -- Succeeds Above Not Almost Equal To
		[0x2ABB] = true, -- Double Precedes
		[0x2ABC] = true, -- Double Succeeds
		[0x2ABD] = true, -- Subset with Dot
		[0x2ABE] = true, -- Superset with Dot
		[0x2ABF] = true, -- Subset with Plus Sign Below
		[0x2AC0] = true, -- Superset with Plus Sign Below
		[0x2AC1] = true, -- Subset with Multiplication Sign Below
		[0x2AC2] = true, -- Superset with Multiplication Sign Below
		[0x2AC3] = true, -- Subset of or Equal to with Dot Above
		[0x2AC4] = true, -- Superset of or Equal to with Dot Above
		[0x2AC5] = true, -- Subset of Above Equals Sign
		[0x2AC6] = true, -- Superset of Above Equals Sign
		[0x2AC7] = true, -- Subset of Above Tilde Operator
		[0x2AC8] = true, -- Superset of Above Tilde Operator
		[0x2AC9] = true, -- Subset of Above Almost Equal To
		[0x2ACA] = true, -- Superset of Above Almost Equal To
		[0x2ACB] = true, -- Subset of Above Not Equal To
		[0x2ACC] = true, -- Superset of Above Not Equal To
		[0x2ACD] = true, -- Square Left Open Box Operator
		[0x2ACE] = true, -- Square Right Open Box Operator
		[0x2ACF] = true, -- Closed Subset
		[0x2AD0] = true, -- Closed Superset
		[0x2AD1] = true, -- Closed Subset or Equal To
		[0x2AD2] = true, -- Closed Superset or Equal To
		[0x2AD3] = true, -- Subset Above Superset
		[0x2AD4] = true, -- Superset Above Subset
		[0x2AD5] = true, -- Subset Above Subset
		[0x2AD6] = true, -- Superset Above Superset
		[0x2AD7] = true, -- Superset Beside Subset
		[0x2AD8] = true, -- Superset Beside and Joined By Dash with Subset
		[0x2AD9] = true, -- Element of Opening Downwards
		[0x2ADA] = true, -- Pitchfork with Tee Top
		[0x2ADB] = true, -- Transversal Intersection
		[0x2ADC] = true, -- Forking
		[0x2ADD] = true, -- Nonforking
		[0x2ADE] = true, -- Short Left Tack
		[0x2ADF] = true, -- Short Down Tack
		[0x2AE0] = true, -- Short Up Tack
		[0x2AE1] = true, -- Perpendicular with S
		[0x2AE2] = true, -- Vertical Bar Triple Right Turnstile
		[0x2AE3] = true, -- Double Vertical Bar Left Turnstile
		[0x2AE4] = true, -- Vertical Bar Double Left Turnstile
		[0x2AE5] = true, -- Double Vertical Bar Double Left Turnstile
		[0x2AE6] = true, -- Long Dash from Left Member of Double Vertical
		[0x2AE7] = true, -- Short Down Tack with Overbar
		[0x2AE8] = true, -- Short Up Tack with Underbar
		[0x2AE9] = true, -- Short Up Tack Above Short Down Tack
		[0x2AEA] = true, -- Double Down Tack
		[0x2AEB] = true, -- Double Up Tack
		[0x2AEC] = true, -- Double Stroke Not Sign
		[0x2AED] = true, -- Reversed Double Stroke Not Sign
		[0x2AEE] = true, -- Does Not Divide with Reversed Negation Slash
		[0x2AEF] = true, -- Vertical Line with Circle Above
		[0x2AF0] = true, -- Vertical Line with Circle Below
		[0x2AF1] = true, -- Down Tack with Circle Below
		[0x2AF2] = true, -- Parallel with Horizontal Stroke
		[0x2AF3] = true, -- Parallel with Tilde Operator
		[0x2AF4] = true, -- Triple Vertical Bar Binary Relation
		[0x2AF5] = true, -- Triple Vertical Bar with Horizontal Stroke
		[0x2AF6] = true, -- Triple Colon Operator
		[0x2AF7] = true, -- Triple Nested Less-Than
		[0x2AF8] = true, -- Triple Nested Greater-Than
		[0x2AF9] = true, -- Double-Line Slanted Less-Than or Equal To
		[0x2AFA] = true, -- Double-Line Slanted Greater-Than or Equal To
		[0x2AFB] = true, -- Triple Solidus Binary Relation
		[0x2AFC] = true, -- Large Triple Vertical Bar Operator
		[0x2AFD] = true, -- Double Solidus Operator
		[0x2AFE] = true, -- White Vertical Bar
		[0x2AFF] = true, -- N-Ary White Vertical Bar
		[0x2B30] = true, -- Left Arrow with Small Circle
		[0x2B31] = true, -- Three Leftwards Arrows
		[0x2B32] = true, -- Left Arrow with Circled Plus
		[0x2B33] = true, -- Long Leftwards Squiggle Arrow
		[0x2B34] = true, -- Leftwards Two-Headed Arrow with Vertical Stroke
		[0x2B35] = true, -- Leftwards Two-Headed Arrow with Double Vertical Stroke
		[0x2B36] = true, -- Leftwards Two-Headed Arrow from Bar
		[0x2B37] = true, -- Leftwards Two-Headed Triple Dash Arrow
		[0x2B38] = true, -- Leftwards Arrow with Dotted Stem
		[0x2B39] = true, -- Leftwards Arrow with Tail with Vertical Stroke
		[0x2B3A] = true, -- Leftwards Arrow with Tail with Double Vertical Stroke
		[0x2B3B] = true, -- Leftwards Two-Headed Arrow with Tail
		[0x2B3C] = true, -- Leftwards Two-Headed Arrow with Tail with Vertical Stroke
		[0x2B3D] = true, -- Leftwards Two-Headed Arrow with Tail with Double Vertical Stroke
		[0x2B3E] = true, -- Leftwards Arrow Through X
		[0x2B3F] = true, -- Wave Arrow Pointing Directly Left
		[0x2B40] = true, -- Equals Sign Above Leftwards Arrow
		[0x2B41] = true, -- Reverse Tilde Operator Above Leftwards Arrow
		[0x2B42] = true, -- Leftwards Arrow Above Reverse Almost Equal To
		[0x2B43] = true, -- Rightwards Arrow Through Greater-Than
		[0x2B44] = true, -- Rightwards Arrow Through Superset
		[0x2B47] = true, -- Reverse Tilde Operator Above Rightwards Arrow
		[0x2B48] = true, -- Rightwards Arrow Above Reverse Almost Equal To
		[0x2B49] = true, -- Tilde Operator Above Leftwards Arrow
		[0x2B4A] = true, -- Leftwards Arrow Above Almost Equal To
		[0x2B4B] = true, -- Leftwards Arrow Above Reverse Tilde Operator
		[0x2B4C] = true, -- Rightwards Arrow Above Reverse Tilde Operator
		[0xFB29] = true, -- Hebrew Letter Alternative Plus Sign
		[0xFE62] = true, -- Small Plus Sign
		[0xFE64] = true, -- Small Less-Than Sign
		[0xFE65] = true, -- Small Greater-Than Sign
		[0xFE66] = true, -- Small Equals Sign
		[0xFF0B] = true, -- Fullwidth Plus Sign
		[0xFF1C] = true, -- Fullwidth Less-Than Sign
		[0xFF1D] = true, -- Fullwidth Equals Sign
		[0xFF1E] = true, -- Fullwidth Greater-Than Sign
		[0xFF5C] = true, -- Fullwidth Vertical Line
		[0xFF5E] = true, -- Fullwidth Tilde
		[0xFFE2] = true, -- Fullwidth Not Sign
		[0xFFE9] = true, -- Halfwidth Leftwards Arrow
		[0xFFEA] = true, -- Halfwidth Upwards Arrow
		[0xFFEB] = true, -- Halfwidth Rightwards Arrow
		[0xFFEC] = true, -- Halfwidth Downwards Arrow
		[0x1D6C1] = true, -- Mathematical Bold Nabla
		[0x1D6DB] = true, -- Mathematical Bold Partial Differential
		[0x1D6FB] = true, -- Mathematical Italic Nabla
		[0x1D715] = true, -- Mathematical Italic Partial Differential
		[0x1D735] = true, -- Mathematical Bold Italic Nabla
		[0x1D74F] = true, -- Mathematical Bold Italic Partial Differential
		[0x1D76F] = true, -- Mathematical Sans-Serif Bold Nabla
		[0x1D789] = true, -- Mathematical Sans-Serif Bold Partial Differential
		[0x1D7A9] = true, -- Mathematical Sans-Serif Bold Italic Nabla
		[0x1D7C3] = true, -- Mathematical Sans-Serif Bold Italic Partial Differential
		[0x1EEF0] = true, -- Arabic Mathematical Operator Meem with Hah with Tatweel
		[0x1EEF1] = true, -- Arabic Mathematical Operator Hah with Dal
	},
}
