--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["Utils-4396b9b2-1.3.0"]["Utils"])

export type Signal<T> = Package.Signal<T> 
export type FireSignal<T> = Package.FireSignal<T> 
export type Subscription = Package.Subscription


return Package
