[package]
name = "JestEnvironmentLuau"
version = "3.8.1"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
license = "MIT"
[dependencies.JestEnvironment]
package = "JestEnvironment"
version = "^3.8.1"

[dependencies.JestFakeTimers]
package = "JestFakeTimers"
version = "^3.8.1"

[dependencies.JestMock]
package = "JestMock"
version = "^3.8.1"

[dependencies.JestTypes]
package = "JestTypes"
version = "^3.8.1"

[dependencies.LuauPolyfill]
version = "^1"

[dependencies.Promise]
version = "^3.3.0"
