-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = game:GetService("AssetImportService")
local var1 = script.Parent.Parent.Parent
local var2 = require(var1.Src.Actions.SetAssetImportSession)
local var3 = require(var1.Src.Actions.SetImportTree)
local var4 = require(var1.Src.Actions.SetFilename)
local var5 = require(var1.Src.Actions.SetSelectedImportItem)
local var6 = require(var1.Src.Actions.SetImportStatuses)
local var7 = require(var1.Src.Thunks.UpdatePreviewInstance)
local var8 = require(var1.Src.Thunks.LoadManagedGroups)
local var9 = require(var1.Src.Actions.ResetState)
local var10 = require(var1.Src.Thunks.UpdateChecked)
local var11 = require(var1.Src.Thunks.ShowImportPreview)
local var12 = require(var1.Src.Flags.getFFlagAssetImportEnableMultipleFiles)
local var13 = require(var1.Src.Flags.getFFlagAssetImportUseUploadId)
local var14 = require(var1.Src.Flags.getFFlagCinPreviewInstances)
return function(arg1)
   return function(arg1, arg2)
   end
end
