-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = require(script.Parent.Parent.Parent.Src.Util.TerrainEnums)
local var1 = var0.Biome
local var2 = var0.ToolId
local var3 = {}
var2.Generate = "rbxasset://textures/TerrainTools/" ... "mt_generate.png"
var2.ImportLocal = "rbxasset://textures/TerrainTools/" ... "mt_terrain_import.png"
var2.SeaLevel = "rbxasset://textures/TerrainTools/" ... "mt_sea_level.png"
var2.Replace = "rbxasset://textures/TerrainTools/" ... "mt_replace.png"
var2.Clear = "rbxasset://textures/TerrainTools/" ... "mt_terrain_clear.png"
var2.Select = "rbxasset://textures/TerrainTools/" ... "icon_regions_select.png"
var2.Transform = "rbxasset://textures/TerrainTools/" ... "icon_regions_move.png"
var2.Material = "rbxasset://textures/TerrainTools/" ... "icon_regions_fill.png"
var2.Move = "rbxasset://textures/TerrainTools/" ... "icon_regions_move.png"
var2.Resize = "rbxasset://textures/TerrainTools/" ... "icon_regions_resize.png"
var2.Rotate = "rbxasset://textures/TerrainTools/" ... "icon_regions_rotate.png"
var2.Copy = "rbxasset://textures/TerrainTools/" ... "icon_regions_copy.png"
var2.Paste = "rbxasset://textures/TerrainTools/" ... "icon_regions_paste.png"
var2.Delete = "rbxasset://textures/TerrainTools/" ... "icon_regions_delete.png"
var2.Fill = "rbxasset://textures/TerrainTools/" ... "icon_regions_fill.png"
var2.Add = "rbxasset://textures/TerrainTools/" ... "mt_add.png"
var2.Draw = "rbxasset://textures/TerrainTools/" ... "mt_add.png"
var2.Subtract = "rbxasset://textures/TerrainTools/" ... "mt_subtract.png"
var2.Sculpt = "rbxasset://textures/TerrainTools/" ... "mt_grow.png"
var2.Grow = "rbxasset://textures/TerrainTools/" ... "mt_grow.png"
var2.Erode = "rbxasset://textures/TerrainTools/" ... "mt_erode.png"
var2.Smooth = "rbxasset://textures/TerrainTools/" ... "mt_smooth.png"
var2.Flatten = "rbxasset://textures/TerrainTools/" ... "mt_flatten.png"
var2.Paint = "rbxasset://textures/TerrainTools/" ... "mt_paint.png"
var3.ToolIcons = {}
var3.INITIAL_BRUSH_SIZE = 6
var3.MIN_BRUSH_SIZE = 1
var3.MAX_BRUSH_SIZE = 64
var3.INITIAL_BRUSH_STRENGTH = 1
var3.INITIAL_PLANE_POSITION_Y = 30
var3.VOXEL_RESOLUTION = 4
var3.MIN_BIOME_SIZE = 16
var3.MAX_BIOME_SIZE = 4096
var3.BIOME_SNAP_INCREMENT = 4
var3.FLATTEN_PLANE_TOLERANCE = 0.05
var2.Select = true
var2.Transform = true
var2.Material = true
var2.Move = true
var2.Resize = true
var2.Rotate = true
var2.Copy = true
var2.Paste = true
var2.Delete = true
var2.Fill = true
var2.Add = true
var2.Subtract = true
var2.Draw = true
var2.Grow = true
var2.Erode = true
var2.Sculpt = true
var2.Smooth = true
var2.Flatten = true
var2.Paint = true
var2.SeaLevel = true
var2.Generate = true
var2.ImportLocal = true
var2.Replace = true
var3.ToolActivatesPlugin = {}
var1.Water = "BiomeWater"
var1.Marsh = "BiomeMarsh"
var1.Plains = "BiomePlains"
var1.Hills = "BiomeHills"
var1.Dunes = "BiomeDunes"
var1.Canyons = "BiomeCanyons"
var1.Mountains = "BiomeMountains"
var1.Lavascape = "BiomeLavascape"
var1.Arctic = "BiomeArctic"
var3.BiomeToLocalizationKey = {}
var2.Add = true
var2.Subtract = true
var2.Draw = true
var2.Grow = true
var2.Erode = true
var2.Sculpt = true
var2.Smooth = true
var2.Paint = true
var2.Replace = true
var3.ToolUsesPlaneLock = {}
var2.Transform = true
var2.Select = true
var2.Generate = true
var2.ImportLocal = true
var3.ToolUsesRegion = {}
var3.FIRST_COLUMN_WIDTH = 90
var3.MIDDLE_PADDING = 8
var3.SIDE_PADDING = 20
var3.SECOND_COLUMN_START = var3.SIDE_PADDING + var3.FIRST_COLUMN_WIDTH + var3.MIDDLE_PADDING
var3.SECOND_COLUMN_WIDTH = 136
var3.GRID_LINE_WIDTH = 20
var3.GRID_SIZE = 4
var3.DISABLED_GRID_SIZE = 0.01
var3.RAY_CAST_LENGTH = 4096
var3.MIN_WIDGET_SIZE = Vector2.new(var3.SIDE_PADDING + var3.FIRST_COLUMN_WIDTH + var3.MIDDLE_PADDING + var3.SECOND_COLUMN_WIDTH + var3.SIDE_PADDING, 256)
var3.TERRAIN_BRUSH_TRANSPARENCY = 0.9
var3.TERRAIN_BRUSH_TRANSPARENCY_MOUSE_DOWN = 0.97
var3.FILENAME_ELLIPSIZE_MIDDLE_SUFFIX_LENGTH = 7
var3.REGION_MIN_SIZE = 4
var3.REGION_MAX_SIZE = 16384
var3.SCROLL_WHEEL_SPEED = 10
return var3
