-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
local var1 = {}
var1.Generate = "Generate"
var1.Import = "Import"
var1.ImportLocal = "ImportLocal"
var1.SeaLevel = "SeaLevel"
var1.Replace = "Replace"
var1.Clear = "Clear"
var1.Select = "Select"
var1.Transform = "Transform"
var1.Move = "Move"
var1.Resize = "Resize"
var1.Rotate = "Rotate"
var1.Copy = "Copy"
var1.Paste = "Paste"
var1.Delete = "Delete"
var1.Fill = "Fill"
var1.Material = "Material"
var1.Add = "Add"
var1.Subtract = "Subtract"
var1.Grow = "Grow"
var1.Erode = "Erode"
var1.Smooth = "Smooth"
var1.Flatten = "Flatten"
var1.Draw = "Draw"
var1.Sculpt = "Sculpt"
var1.Paint = "Paint"
var1.None = "None"
var0.ToolId = var1
local var28 = {}
var28.Create = "Create"
var28.Build = "Build"
var28.Region = "Region"
var28.Sculpt = "Sculpt"
var28.Paint = "Paint"
var28.Edit = "Edit"
var0.TabId = var28
local var35 = {}
var35.Top = "Top"
var35.Center = "Cen"
var35.Bottom = "Bot"
var0.PivotType = var35
local var39 = {}
var39.Off = "Off"
var39.Auto = "Auto"
var39.Manual = "Manual"
var0.PlaneLockType = var39
local var43 = {}
var43.Erode = "Erode"
var43.Both = "Both"
var43.Grow = "Grow"
var0.FlattenMode = var43
local var47 = {}
var47.Sphere = "Sphere"
var47.Cube = "Cube"
var47.Cylinder = "Cylinder"
var0.BrushShape = var47
local var51 = {}
var51.Water = "Water"
var51.Plains = "Plains"
var51.Dunes = "Dunes"
var51.Mountains = "Mountains"
var51.Arctic = "Arctic"
var51.Marsh = "Marsh"
var51.Hills = "Hills"
var51.Canyons = "Canyons"
var51.Lavascape = "Lavascape"
var0.Biome = var51
local var61 = {}
var61.Block = "Block"
var61.Cylinder = "Cylinder"
var61.CylinderRotate = "CylinderRotate"
var61.Ball = "Ball"
var61.Wedge = "Wedge"
var0.Shape = var61
local var67 = {}
var67.Box = "Box"
var67.Brush = "Brush"
var0.ReplaceMode = var67
local var70 = {}
var70.Duplicate = "Duplicate"
var70.Move = "Move"
var70.Paste = "Paste"
var0.TransformMode = var70
local var74 = {}
var74.DefaultMaterial = "DefaultMaterial"
var74.Colormap = "Colormap"
var0.ImportMaterialMode = var74
local var12 = {}
var12.Add = "Add"
var12.Subtract = "Subtract"
var0.BrushMode = var12
return var0
