[package]
name = "JestDiff"
version = "3.8.1"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
license = "MIT"
[dependencies.ChalkLua]
version = "^0.2.0"

[dependencies.DiffSequences]
package = "DiffSequences"
version = "^3.8.1"

[dependencies.JestGetType]
package = "JestGetType"
version = "^3.8.1"

[dependencies.JestTypes]
package = "JestTypes"
version = "^3.8.1"

[dependencies.LuauPolyfill]
version = "^1"

[dependencies.PrettyFormat]
package = "PrettyFormat"
version = "^3.8.1"
