--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["NetworkingUserInfo-18e47610-e46c2dfc"]["NetworkingUserInfo"])

return Package
