--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["Navigation"]["Navigation"])

export type Action = Package.Action
export type RouteState = Package.RouteState
export type NavigationState = Package.NavigationState
export type NavigationObject = Package.NavigationObject


return Package
