--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Workspace

local Package = require(PackageIndex["ReactOtter"]["ReactOtter"])

export type Goal = Package.Goal
export type SpringOptions = Package.SpringOptions


return Package
