-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
local var1 = {}
local var3 = {}
local var5 = {}
local var7 = {}
var7.Children = {}
{}.LineNo = 2
var7.Lines = {}
var7.Variables = {}
var5.Children = {}
{}.LineNo = 2
{}.LineNo = 2
var5.Lines = {}
local var18 = {}
var18.func = {}
var5.Variables = var18
local var20 = {}
local var22 = {}
var22.Children = {}
{}.LineNo = 2
var22.Lines = {}
local var27 = {}
var27.s = {}
var22.Variables = var27
local var29 = {}
var29.Children = {}
{}.LineNo = 2
var29.Lines = {}
local var34 = {}
var34.s = {}
var29.Variables = var34
local var36 = {}
var36.Children = {}
{}.LineNo = 2
var36.Lines = {}
local var41 = {}
var41.s = {}
var36.Variables = var41
var20.Children = {}
{}.LineNo = 2
{}.LineNo = 2
{}.LineNo = 2
{}.LineNo = 2
var20.Lines = {}
var20.Variables = {}
local var53 = {}
local var55 = {}
var55.Children = {}
{}.LineNo = 2
var55.Lines = {}
var55.Variables = {}
var53.Children = {}
{}.LineNo = 2
{}.LineNo = 2
var53.Lines = {}
var53.Variables = {}
var3.Children = {}
{}.LineNo = 2
{}.LineNo = 2
{}.LineNo = 2
{}.LineNo = 2
{}.LineNo = 3
var3.Lines = {}
local var78 = {}
var78.c = {}
var78.x = {}
var78.y = {}
var3.Variables = var78
var1.Children = {}
{}.LineNo = 1
{}.LineNo = 2
var1.Lines = {}
local var16 = {}
var16.a = {}
var16.b = {}
var1.Variables = var16
var0._root = var1
return var0
