-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
local var1 = {}
local var2 = {}
var2.Name = "R15MigratorHasAdapter"
var2.Mask = 1
var1.AdapterTagging = var2
local var5 = {}
var5.Name = "R15MigratorUnconvertedCharacter"
var5.Mask = 2
var1.CharacterTagging = var5
local var8 = {}
var8.Name = "R15MigratorUnconvertedAnimation"
var8.Mask = 4
var1.AnimationTagging = var8
local var11 = {}
var11.Name = "R15MigratorUnconvertedScript"
var11.Mask = 8
var1.ScriptTagging = var11
var0.PublishTags = var1
local var6 = {}
var6.CharactersConvertedToR15Tag = "R15MigratorCharactersConvertedToR15"
var0.NonePublishTags = var6
local var7 = {}
var7.TempId = "R15MigratorTempId"
var7.OriginalId = "OriginalId"
var0.Attributes = var7
local var8 = {}
var8.TEXT_COLUMN_INDEX = 1
var8.STATUS_COLUMN_INDEX = 2
var0.StatusTableData = var8
var0.CrossPluginCommunicationName = "R15Migrator"
local var9 = {}
var9.Open = "Open"
var9.Published = "Published"
var0.CrossPluginCommunicationInstructions = var9
return var0
