
local Constants = {}

Constants.DOCKWIDGET_MIN_WIDTH = 600
Constants.DOCKWIDGET_MIN_HEIGHT = 180

Constants.HEADER_HEIGHT = 70
Constants.HEADER_TITLE_WIDTH = 250
Constants.HEADER_UPDATE_WIDTH = 100
Constants.HEADER_LEFT_PADDING = 20
Constants.HEADER_RIGHT_PADDING = -20
Constants.HEADER_TOP_PADDING = 20
Constants.HEADER_BUTTON_SIZE = 30


Constants.PLUGIN_VERTICAL_PADDING = 5
Constants.PLUGIN_HORIZONTAL_PADDING = 30
Constants.THUMBNAIL_SIZE = 60
Constants.PLUGIN_ENTRY_HEIGHT = 120
Constants.PLUGIN_NAME_HEIGHT = 30
Constants.PLUGIN_CREATOR_HEIGHT = 20
Constants.PLUGIN_DESCRIPTION_HEIGHT = 60
Constants.PLUGIN_ENABLE_WIDTH = 40
Constants.PLUGIN_CONTEXT_WIDTH = 28

return Constants