-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("Toolbox")
local var1 = var0.Packages
local var2 = require(var1.Roact)
local var3 = require(var1.Framework)
local var4 = require(var0.Core.Util.Images)
local var5 = var3.UI.Checkbox
local var6 = var3.UI
local var7 = var6.Image
local var8 = var6.TextLabel
local var9 = var3.Util.LayoutOrderIterator
local var10 = var6.Pane
local var11 = var6.Tooltip
local var12 = var3.ContextServices
local var13 = var2.PureComponent:extend("VerfifiedCreatorCheckbox")
local function fun0(arg1)
   local var0 = arg1.props
   local var1 = var0.Localization
   local var2 = var9.new()
   local var54 = {}
   var54.AutomaticSize = Enum.AutomaticSize.XY
   var54.HorizontalAlignment = Enum.HorizontalAlignment.Left
   var54.Layout = Enum.FillDirection.Vertical
   var54.LayoutOrder = var0.LayoutOrder
   var54.Spacing = 3
   local var60 = {}
   local var64 = {}
   var64.Checked = var0.IsChecked
   var64.LayoutOrder = var2:getNextOrder()
   var64.OnClick = var0.OnClick
   var64.Text = var1:getText("General", "SearchOptionsIncludeUnverifiedHeader")
   var64.TextWrapped = true
   var60.IncludeUnverifiedToggle = var2.createElement(var5, var64)
   local var74 = {}
   var74.AutomaticSize = Enum.AutomaticSize.XY
   var74.HorizontalAlignment = Enum.HorizontalAlignment.Left
   var74.Layout = Enum.FillDirection.Horizontal
   var74.LayoutOrder = var2:getNextOrder()
   local var80 = {}
   var80.Left = 24
   var74.Padding = var80
   var74.Spacing = 6
   var74.VerticalAlignment = Enum.VerticalAlignment.Top
   local var84 = {}
   local var88 = {}
   var88.AnchorPoint = Vector2.new(0, 0.5)
   var88.Image = var4.WARNING_ICON_SMALL
   var88.ImageColor3 = var0.Stylizer.searchOptions.warningIconColor
   var88.LayoutOrder = var2:getNextOrder()
   var88.Size = UDim2.fromOffset(16, 16)
   local var102 = {}
   local var106 = {}
   var106.Text = var1:getText("General", "SearchOptionsIncludeUnverifiedTooltip")
   var106.Priority = 11
   var102.Tooltip = var2.createElement(var11, var106)
   var84.Image = var2.createElement(var7, var88, var102)
   local var113 = {}
   var113.AutomaticSize = Enum.AutomaticSize.XY
   var113.LayoutOrder = var2:getNextOrder()
   var113.Style = "SubText"
   var113.Text = var1:getText("General", "SearchOptionsIncludeUnverifiedDescription")
   var113.TextSize = 14
   var113.TextWrapped = true
   var113.TextXAlignment = Enum.TextXAlignment.Left
   var84.VerifiedDescription = var2.createElement(var8, var113)
   var60.VerifiedDescriptionContainer = var2.createElement(var10, var74, var84)
   return var2.createElement(var10, var54, var60)
end

function var13.render(arg1)
   local var0 = arg1.props
   local var1 = var0.Localization
   local var2 = var9.new()
   local var54 = {}
   var54.AutomaticSize = Enum.AutomaticSize.XY
   var54.HorizontalAlignment = Enum.HorizontalAlignment.Left
   var54.Layout = Enum.FillDirection.Vertical
   var54.LayoutOrder = var0.LayoutOrder
   var54.Spacing = 3
   local var60 = {}
   local var64 = {}
   var64.Checked = var0.IsChecked
   var64.LayoutOrder = var2:getNextOrder()
   var64.OnClick = var0.OnClick
   var64.Text = var1:getText("General", "SearchOptionsIncludeUnverifiedHeader")
   var64.TextWrapped = true
   var60.IncludeUnverifiedToggle = var2.createElement(var5, var64)
   local var74 = {}
   var74.AutomaticSize = Enum.AutomaticSize.XY
   var74.HorizontalAlignment = Enum.HorizontalAlignment.Left
   var74.Layout = Enum.FillDirection.Horizontal
   var74.LayoutOrder = var2:getNextOrder()
   local var80 = {}
   var80.Left = 24
   var74.Padding = var80
   var74.Spacing = 6
   var74.VerticalAlignment = Enum.VerticalAlignment.Top
   local var84 = {}
   local var88 = {}
   var88.AnchorPoint = Vector2.new(0, 0.5)
   var88.Image = var4.WARNING_ICON_SMALL
   var88.ImageColor3 = var0.Stylizer.searchOptions.warningIconColor
   var88.LayoutOrder = var2:getNextOrder()
   var88.Size = UDim2.fromOffset(16, 16)
   local var102 = {}
   local var106 = {}
   var106.Text = var1:getText("General", "SearchOptionsIncludeUnverifiedTooltip")
   var106.Priority = 11
   var102.Tooltip = var2.createElement(var11, var106)
   var84.Image = var2.createElement(var7, var88, var102)
   local var113 = {}
   var113.AutomaticSize = Enum.AutomaticSize.XY
   var113.LayoutOrder = var2:getNextOrder()
   var113.Style = "SubText"
   var113.Text = var1:getText("General", "SearchOptionsIncludeUnverifiedDescription")
   var113.TextSize = 14
   var113.TextWrapped = true
   var113.TextXAlignment = Enum.TextXAlignment.Left
   var84.VerifiedDescription = var2.createElement(var8, var113)
   var60.VerifiedDescriptionContainer = var2.createElement(var10, var74, var84)
   return var2.createElement(var10, var54, var60)
end

fun0 = var12.withContext
local var124 = {}
var124.Localization = var12.Localization
var124.Stylizer = var12.Stylizer
var13 = fun0(var124)(var13)
return var13
