--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["NetworkingCurrentlyWearing-668767d0-dd87276c"]["NetworkingCurrentlyWearing"])

return Package
