--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["roblox_rodux-friends-1a8a251d-e7dec272"]["rodux-friends"])

return Package
