--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["JestUtil-edcba0e9-3.5.0"]["JestUtil"])

export type ErrorWithStack = Package.ErrorWithStack


return Package
