--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["JestMock-3.5.0"]["JestMock"])

export type MaybeMockedDeep<T> = Package.MaybeMockedDeep<T> 
export type MaybeMocked<T> = Package.MaybeMocked<T> 
export type ModuleMocker = Package.ModuleMocker


return Package
