return {
	None = "None",
	User = "User",
	Place = "Place",
	NotAudible = "NotAudible",
	Permission = "Permission",
	Retry = "Retry",
	VoiceChatSuspendedTemporary = "VoiceChatSuspendedTemporary",
	VoiceChatSuspendedTemporaryAvatarChat = "VoiceChatSuspendedTemporaryAvatarChat",
	VoiceChatSuspendedPermanent = "VoiceChatSuspendedPermanent",
	VoiceLoading = "VoiceLoading",
	VoiceToxicityModal = "VoiceToxicityModal",
	VoiceToxicityToast = "VoiceToxicityToast",
	VoiceToxicityFeedbackToast = "VoiceToxicityFeedbackToast",
}
