local LuaSocialLibrariesDeps = script.Parent

return {
	GenericPagination = require(LuaSocialLibrariesDeps.GenericPagination),
	RoactFitComponents = require(LuaSocialLibrariesDeps.RoactFitComponents),
	Mock = require(LuaSocialLibrariesDeps.Mock),
	RoduxNetworking = require(LuaSocialLibrariesDeps.RoduxNetworking),
	llama = require(LuaSocialLibrariesDeps.llama),
	RoduxAliases = require(LuaSocialLibrariesDeps.RoduxAliases),
	RoduxUsers = require(LuaSocialLibrariesDeps.RoduxUsers),
	RoduxFriends = require(LuaSocialLibrariesDeps.RoduxFriends),
	RoduxFriends_v220 = require(LuaSocialLibrariesDeps.RoduxFriends_v220),
	RoduxPresence = require(LuaSocialLibrariesDeps.RoduxPresence),
	RoduxPresence_101 = require(LuaSocialLibrariesDeps.RoduxPresence),
	RoduxGames = require(LuaSocialLibrariesDeps.RoduxGames),
	httpRequest = require(LuaSocialLibrariesDeps.httpRequest),
	NetworkingPresence = require(LuaSocialLibrariesDeps.NetworkingPresence),
	NetworkingAliases = require(LuaSocialLibrariesDeps.NetworkingAliases),
	NetworkingChat = require(LuaSocialLibrariesDeps.NetworkingChat),
	NetworkingFriends = require(LuaSocialLibrariesDeps.NetworkingFriends),
	NetworkingGames = require(LuaSocialLibrariesDeps.NetworkingGames),
	CollisionMatchers = require(LuaSocialLibrariesDeps.CollisionMatchers),
	SocialLibraries = require(LuaSocialLibrariesDeps.SocialLibraries),
	NetworkingUsers = require(LuaSocialLibrariesDeps.NetworkingUsers),
}
