--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["InfiniteScroller-5bd4142d-0.8.0"]["InfiniteScroller"])

return Package
