--[[----------------------------------------------------------------------------------------------------
	<auto-generated>
		This file was generated by: https://github.com/Roblox/IAPExperience/loc/UpdateLocale.py

		See the repository for documentation.
	</auto-generated>
--------------------------------------------------------------------------------------------------------]]
    return{
    ["IAPExperience.Text.Test"] = [[Testo di prova]],
    ["IAPExperience.Text.Test2"] = [[Testo di prova 2]],
    ["IAPExperience.RobuxUpsell.Title.InsufficientFunds"] = [[Fondi insufficienti]],
    ["IAPExperience.RobuxUpsell.Text.BuyRobuxQuestion"] = [[Vuoi acquistare]],
    ["IAPExperience.RobuxUpsell.Text.DisclosurePayment"] = [[Il tuo metodo di pagamento verrà addebitato.]],
    ["IAPExperience.RobuxUpsell.Text.DisclosureTerms"] = [[Si applicano i Termini di utilizzo di Roblox.]],
    ["IAPExperience.RobuxUpsell.Text.RemainingBalance"] = [[I rimanenti {robux} verranno accreditati ai tuoi fondi.]],
    ["IAPExperience.RobuxUpsell.Action.Cancel"] = [[Annulla]],
    ["IAPExperience.PurchasePrompt.Title.BuyItem"] = [[Acquista oggetto]],
    ["IAPExperience.PurchasePrompt.Text.BuyItemQuestion"] = [[Vuoi acquistare "{name}"?]],
    ["IAPExperience.PurchasePrompt.Text.RemainingBalance"] = [[Il tuo saldo dopo questa transazione sarà]],
    ["IAPExperience.PurchasePrompt.Action.Cancel"] = [[Annulla]],
}