--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["Cryo-b39ad756-f7c72476"]["Cryo"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package