PROTO_0:
        0 LOADK                            R0 K0 ["local AnimationClipProvider = game:GetService(\"AnimationClipProvider\")\nlocal ReplicatedStorage = game:GetService(\"ReplicatedStorage\")\nlocal RunService = game:GetService(\"RunService\")\n\nif not RunService:IsRunning() then\n\treturn\nend\n\nlocal character = script.Parent\nlocal humanoid = character:WaitForChild(\"Humanoid\")\nlocal graphNameValue = script:FindFirstChild(\"GraphName\")\nlocal graphName = if graphNameValue then graphNameValue.Value else nil\nlocal characterNameValue = script:FindFirstChild(\"CharacterName\")\nlocal characterName = if characterNameValue then characterNameValue.Value else nil\n\nlocal editorFolder = nil\nlocal graphKey = nil\n\nif RunService:IsStudio() and characterName and graphName then\n\teditorFolder = ReplicatedStorage:WaitForChild(\"AnimationGraphEditor\", 1)\n\tgraphKey = characterName .. \"_\" .. graphName\nend\n\nlocal animator = humanoid:FindFirstChildOfClass(\"Animator\") or humanoid\n\nlocal track = nil\nlocal animation = nil\nlocal lastAnimationId = nil\n\nlocal function stopCurrentAnimation()\n\tif track then\n\t\ttrack:Stop()\n\t\ttrack:Destroy()\n\t\ttrack = nil\n\tend\n\tif animation then\n\t\tanimation:Destroy()\n\t\tanimation = nil\n\tend\n\tlastAnimationId = nil\nend\n\nlocal function registerGraphClone()\n\tif not editorFolder or not graphKey then\n\t\treturn nil\n\tend\n\n\tlocal graphClone = editorFolder:FindFirstChild(graphKey)\n\tif not graphClone then\n\t\treturn nil\n\tend\n\n\treturn AnimationClipProvider:RegisterAnimationClip(graphClone)\nend\n\nlocal function resolveAnimationId()\n\tif not RunService:IsStudio() then\n\t\tlocal graph = character:FindFirstChildWhichIsA(\"AnimationGraphDefinition\", true)\n\t\tif graph then\n\t\t\tlocal sourceAssetId = graph:GetAttribute(\"RBX_SourceAssetId\")\n\t\t\tif sourceAssetId then\n\t\t\t\treturn `rbxassetid://{sourceAssetId}`\n\t\t\tend\n\t\tend\n\t\treturn nil\n\tend\n\n\treturn registerGraphClone()\nend\n\nlocal function updatePlayState()\n\tlocal animationId = resolveAnimationId()\n\n\tif animationId and animationId ~= \"\" then\n\t\tif animationId ~= lastAnimationId then\n\t\t\tstopCurrentAnimation()\n\t\t\tanimation = Instance.new(\"Animation\")\n\t\t\tanimation.AnimationId = animationId\n\t\t\tanimation:AddTag(\"AnimationEditor_GraphAnimation\")\n\t\t\tanimation.Parent = script\n\t\t\ttrack = animator:LoadAnimation(animation)\n\t\t\ttrack:Play()\n\t\t\tlastAnimationId = animationId\n\t\tend\n\telse\n\t\tstopCurrentAnimation()\n\tend\nend\n\nupdatePlayState()\n\nif editorFolder and graphKey then\n\teditorFolder.ChildAdded:Connect(function(child)\n\t\tif child.Name == graphKey then\n\t\t\tupdatePlayState()\n\t\tend\n\tend)\nend\n\n"]
        1 RETURN                           R0 1

MAIN:
        0 PREPVARARGS                      0
        1 NEWTABLE                         R0 1 0
        3 DUPCLOSURE                       R1 K0 [PROTO_0]
        4 SETTABLEKS                       R1 R0 K1 ["template"]
        6 RETURN                           R0 1
