--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["roblox_roact-498a4104-3de41375"]["roact"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package