--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["RoduxFriends-948a3386-02a3ea83"]["RoduxFriends"])

return Package
