--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["RoactRodux-456316a1-d4255300"]["RoactRodux"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package