--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["roblox_developer-tools-0.1.8"]["developer-tools"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package
