return {
	OverflowMenu = require(script.OverflowMenu),
	Chat = require(script.Chat),
	UnibarMenuToggleButton = require(script.UnibarMenuToggleButtonV2),
	CompactUtilityBackButton = require(script.CompactUtilityBackButton),
	TrustAndSafety = require(script.TrustAndSafety),
	DummyWindow = require(script.DummyWindow),
	DummyWindow2 = require(script.DummyWindow2),
	DummyContainer = require(script.DummyContainer),
	ToggleMic = require(script.ToggleMic),
	JoinVoice = require(script.JoinVoice),
	SelfieView = require(script.SelfieView),
	Captures = require(script.CameraUtility.Captures),
	Screenshot = require(script.CameraUtility.Screenshot),
	CameraEntrypoint = require(script.CameraUtility.CameraEntrypoint),
	MusicEntrypoint = require(script.MusicUtility.MusicEntrypoint),
	Songbird = require(script.MusicUtility.Songbird),
	Party = require(script.Party),
}
