--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["JestMatcherUtils"]["JestMatcherUtils"])

export type MatcherHintOptions = Package.MatcherHintOptions


return Package
