--[[
	Package link auto-generated by migrate_to_roact17.py and Rotriever
]]
local FFlagDeveloperStorybookMigrateToRoact17 = game:GetFastFlag("DeveloperStorybookMigrateToRoact17")
local Packages = script:FindFirstAncestor("Packages")
if FFlagDeveloperStorybookMigrateToRoact17 then
    return require(Packages.Roact17)
else
    return require(Packages._Index.Roact.Roact)
end

