-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.BYTES_IN_KB = 1024
var0.BYTES_IN_MB = 1048576
local var1 = {}
local var5 = "Texture"
var1.Texture = {}
local var7 = "Texture"
var1.Decal = {}
local var9 = "TextureID"
var1.MeshPart = {}
local var14 = "RoughnessMap"
var1.SurfaceAppearance = { "ColorMap", "NormalMap", "MetalnessMap" }
local var19 = "RoughnessMap"
var1.MaterialVariant = { "ColorMap", "NormalMap", "MetalnessMap" }
local var21 = "Image"
var1.ImageLabel = {}
local var23 = "Texture"
var1.ParticleEmitter = {}
local var25 = "Texture"
var1.Beam = {}
local var27 = "FallbackImage"
var1.AdGui = {}
local var29 = "CursorIcon"
var1.ClickDetector = {}
local var33 = "Image"
var1.ImageButton = { "HoverImage", "PressedImage" }
local var13 = "SunTextureId"
var1.Sky = { "MoonTextureId", "SkyboxBk", "SkyboxDn", "SkyboxFt", "SkyboxLf", "SkyboxRt", "SkyboxUp" }
local var44 = "Texture"
var1.Trail = {}
local var15 = "RoughnessMap"
var1.TerrainDetail = { "ColorMap", "MetalnessMap", "NormalMap" }
local var51 = "ShirtTemplate"
var1.Shirt = {}
local var53 = "PantsTemplate"
var1.Pants = {}
local var55 = "TextureId"
var1.SpecialMesh = {}
local var19 = "TopImage"
var1.ScrollingFrame = { "BottomImage", "MidImage" }
var0.INSTANCE_PROPERTIES_TO_PARSE = var1
return var0
