--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent

local package = PackageIndex["Promise"].Packages["Promise"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package