-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("AvatarCompatibilityPreviewer")
local var1 = require(var0.Src.Types)
local var2 = require(var0.Src.Util.createUnimplemented)
local var3 = {}
local var33 = {}
var3.equippedItems = var33
var33 = var2
local var35 = var33("addEquippedItem")
var3.addEquippedItem = var35
var35 = var2
local var37 = var35("removeEquippedItem")
var3.removeEquippedItem = var37
var37 = var2
local var39 = var37("removeAllEquippedItems")
var3.removeAllEquippedItems = var39
var39 = var2
local var41 = var39("moveEquippedItemsToIndex")
var3.moveEquippedItemsToIndex = var41
var41 = var2
local var43 = var41("DEPRECATED_swapEquippedItemsByIndex")
var3.DEPRECATED_swapEquippedItemsByIndex = var43
var43 = var2
local var45 = var43("hideEquippedItem")
var3.hideEquippedItem = var45
var45 = var2
local var47 = var45("showEquippedItem")
var3.showEquippedItem = var47
var47 = var2
var3.setHideAllEquippedItems = var47("setHideAllEquippedItems")
local var50 = {}
var50.accessories = {}
var50.animation = nil
var50.clothing = {}
var50.emotion = nil
local var55 = {}
var50.patches = var55
var3.avatarAssets = var50
var55 = var3
return require(var0.Packages.React).createContext(var55)
