-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("AvatarCompatibilityPreviewer")
local var1 = require(var0.Src.Types)
local var2 = require(var0.Src.Util.createUnimplemented)
local var3 = {}
local var22 = {}
var3.equippedItems = var22
var22 = var2
local var24 = var22("addEquippedItem")
var3.addEquippedItem = var24
var24 = var2
local var26 = var24("removeEquippedItem")
var3.removeEquippedItem = var26
var26 = var2
local var28 = var26("removeAllEquippedItems")
var3.removeAllEquippedItems = var28
var28 = var2
local var30 = var28("moveEquippedItemsToIndex")
var3.moveEquippedItemsToIndex = var30
var30 = var2
var3.DEPRECATED_swapEquippedItemsByIndex = var30("DEPRECATED_swapEquippedItemsByIndex")
local var33 = {}
var33.accessories = {}
var33.animation = nil
var33.clothing = {}
var33.emotion = nil
local var38 = {}
var33.patches = var38
var3.avatarAssets = var33
var38 = var3
return require(var0.Packages.React).createContext(var38)
