-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.HISTORY_FRAMES = game:DefineFastInt("CDHistoryLength", 600)
local var6 = {}
var6.LayerData = "LayerData"
var6.Visualization = "Visualization"
var6.History = "History"
var6.RawData = "RawData"
var0.LAYER_TABS = var6
local var11 = {}
var11.CompositorDebugger = "__RobloxCompositorDebugger"
var11.Server = "Server"
var11.Client = "Client"
var11.AdornmentHandles = "AdornmentHandles"
var0.FOLDERS = var11
local var16 = {}
var16.DebugData = "DebugData"
var16.PropertyOverrides = "PropertyOverrides"
var16.LayerAdornments = "LayerAdornments"
var0.EVENTS = var16
local var20 = {}
var20.Clear = "Clear"
var20.History = "History"
var20.NoOp = "NoOp"
var0.LAYERVIEW_ACTIONS = var20
local var5 = {}
var5.LayerFilters = "CD_LayerFilters"
var5.ActiveLayersFilter = "CD_ActiveLayersFilter"
var0.SETTINGS = var5
return var0
