-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
var0.HISTORY_FRAMES = game:DefineFastInt("CDHistoryLength", 600)
local var32 = {}
var32.LayerData = "LayerData"
var32.Visualization = "Visualization"
var32.History = "History"
var32.RawData = "RawData"
var0.LAYER_TABS = var32
local var37 = {}
var37.CompositorDebugger = "__RobloxCompositorDebugger"
var37.Server = "Server"
var37.Client = "Client"
var37.AdornmentHandles = "AdornmentHandles"
var0.FOLDERS = var37
local var42 = {}
var42.DebugData = "DebugData"
var42.PropertyOverrides = "PropertyOverrides"
var42.LayerAdornments = "LayerAdornments"
var0.EVENTS = var42
local var46 = {}
var46.Clear = "Clear"
var46.History = "History"
var46.NoOp = "NoOp"
var0.LAYERVIEW_ACTIONS = var46
local var5 = {}
var5.LayerFilters = "CD_LayerFilters"
var5.ActiveLayersFilter = "CD_ActiveLayersFilter"
var0.SETTINGS = var5
return var0
