-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = {}
local var28 = {}
var28.DebugData = "DebugData"
var28.PropertyOverrides = "PropertyOverrides"
var28.LayerAdornments = "LayerAdornments"
var28.DebugPose = "DebugPose"
var0.EVENTS = var28
local var33 = {}
var33.CompositorDebugger = "__RobloxCompositorDebugger"
var33.Server = "Server"
var33.Client = "Client"
var33.AdornmentHandles = "AdornmentHandles"
var0.FOLDERS = var33
local var38 = {}
var38.LayerData = "LayerData"
var38.Visualization = "Visualization"
var38.History = "History"
var38.RawData = "RawData"
var0.LAYER_TABS = var38
local var43 = {}
var43.Clear = "Clear"
var43.History = "History"
var43.NoOp = "NoOp"
var0.LAYERVIEW_ACTIONS = var43
local var47 = {}
var47.LayerFilters = "CD_LayerFilters"
var47.ActiveLayersFilter = "CD_ActiveLayersFilter"
var47.FrameBufferDuration = "CD_FrameBufferDuration"
var0.SETTINGS = var47
var0.DEFAULT_TIMECONTROLS_INTERVAL = 10
var0.FRAMERATE = 60
local var54 = {}
var54.Minor = 1
var54.Major = 5
local var57 = {}
var57.Minor = 1
var57.Medium = 5
var57.Major = 10
local var8 = {}
var8.Minor = 5
var8.Major = 10
var0.TIMECONTROLS_INVERVALS = {}
return var0
