--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["Rodux"]["Rodux"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package