return {
	-- context bar
	CONTEXT_BAR_HEIGHT = 52,
	CONTEXT_BAR_PADDING_START = 16,
	CONTEXT_BAR_PADDING_END = 16,
	CONTEXT_BAR_ITEMS_SPACING = 24,
	CONTEXT_BAR_ITEM_LABEL_HEIGHT = 26,
	CONTEXT_BAR_ITEM_ICON_LABEL_SPACING = 8,
	-- IconTab
	ICON_TAB_GROUP_HEIGHT = 72,
	ICON_TAB_HEIGHT = 72,
	ICON_TAB_PADDING = 9,
	ICON_TAB_ITEM_PADDING_LEFT = 25,
	ICON_TAB_ITEM_PADDING_RIGHT = 25,
	ICON_TAB_ITEM_SPACING = 11,
	ICON_TAB_ITEM_ICON_TITLE_SPACING = 12,
	ICON_TAB_ITEM_ICON_WIDTH = 44,
	ICON_TAB_ITEM_ICON_HEIGHT = 44,
	ICON_TAB_PRESSED_TRANSPARENCY = 0.5,
	ICON_TAB_SELECTED_TRANSPARENCY = 0.8,
}
