--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent.Parent._Index

local Package = require(PackageIndex["ReactRoblox-15bfef7d-211d7169"]["ReactRoblox"])

export type RootType = Package.RootType


return Package
