-- Generated with Unluau (https://github.com/valencefun/unluau)
local var0 = script:FindFirstAncestor("MaterialGenerator")
local var1 = require(var0.Packages.Promise)
local var2 = require(var0.Src.Enum.GenerationErrorType)
local var3 = require(var0.Src.Types)
return function(arg1, arg2)
   return var1.new(function()
      local var0 = var2:UploadMaterialAsync(arg1.ColorMap)
   end)
end
